In [13]:
%%javascript
/** Below because this notebook is pretty large */
var rto = 180;
console.log('NB: Increase require timeout to ' + rto + ' seconds');
window.requirejs.config({waitSeconds: rto});

<a href="https://clarusway.com/contact-us/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="Open in Clarusway LMS" width="110" height="200" title="This notebook is licensed by Clarusway IT training school. Please contact the authorized persons about the conditions under which you can use or share."></a>

___

<a href="https://lms.clarusway.com/mod/lesson/view.php?id=8511&pageid=8142&startlastseen=no"><img align="left" src="https://i.ibb.co/6Z5pQxD/lmss.png" alt="Open in Clarusway LMS" width="70" height="200" title="Open Clarusway Learning Management Sytem"></a>

<a href=""><img align="right" src="https://i.ibb.co/n3HWyQX/github-logo.png" alt="Open in Clarusway GitHub" width="100" height="150" title="Open and Execute in Clarusway GitHub Repository"></a>

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<img src=https://i.ibb.co/b5xXg11/used-cars1.jpg width="1100" height="100">

[Image Credit](https://myscriptneedshelp.com/2022/auto/buying-used-cars-in-tempe-is-easier-now/)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">The Capstone Project of Data Analytics Module</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:150%; text-align:center; border-radius:10px 10px;">Car Price Prediction EDA</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [IMPORTING LIBRARIES NEEDED IN THIS NOTEBOOK](#0)
* [PART-02 (HANDLING WITH MISSING VALUES)](#1)
* [THE EXAMINATION OF MISSING VALUES IN THE COLUMNS](#2)    
* [THE END OF MISSING VALUES (PART - 02)](#3)

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Importing Libraries Needed in This Notebook</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

If you have NOT installed NumPy & Pandas so far, once you've installed them you can import them as a library and other libraries need in this analysis:

In [14]:
import numpy as np
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt
from scipy import stats
from scipy.stats.mstats import winsorize
import re
from ipywidgets import interact, Dropdown, IntSlider, Output, widgets
from IPython.display import display

import warnings
warnings.filterwarnings("ignore")
warnings.warn("this will not show")

%matplotlib inline
# %matplotlib notebook

plt.rcParams["figure.figsize"] = (10, 6)
# plt.rcParams['figure.dpi'] = 100

sns.set_style("whitegrid")
pd.set_option('display.float_format', lambda x: '%.2f' % x)

pd.options.display.max_rows = 500
# pd.set_option('display.max_rows', None)
pd.options.display.max_columns = 150

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">PART- 02 (Handling with Missing Values)</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [15]:
df0 = pd.read_csv("clean_scout2022.csv")
df = df0.copy()

**[read_excel with dtype=str converts empty cells to the string 'nan'](https://github.com/pandas-dev/pandas/issues/20377)**

Since Pandas version 0.9 (from 2012), you can read your csv with empty cells interpreted as empty strings by simply setting keep_default_na=False:

**keep_default_nabool, default True**

Whether or not to include the default NaN values when parsing the data. Depending on whether na_values is passed in, the behavior is as follows:

- If keep_default_na is True, and na_values are specified, na_values is appended to the default NaN values used for parsing.

- If keep_default_na is True, and na_values are not specified, only the default NaN values are used for parsing.

- If keep_default_na is False, and na_values are specified, only the NaN values specified na_values are used for parsing.

- If keep_default_na is False, and na_values are not specified, no strings will be parsed as NaN.

Note that if na_filter is passed in as False, the keep_default_na and na_values parameters will be ignored.

In [16]:
df.head(3).T

,0,1,2
make_model,Mercedes-Benz A 160,Mercedes-Benz EQE 350,Mercedes-Benz A 45 AMG
short_description,CDi,350+,S 4Matic+ 8G-DCT
make,Mercedes-Benz,Mercedes-Benz,Mercedes-Benz
model,A 160,EQE 350,A 45 AMG
location,"P.I. EL PALMAR C/FORJA 6, 11500 PUERTO DE SAN...","APARTADO DE CORREOS 1032, 26140 LOGROÑO, ES","PORT. TARRACO, MOLL DE LLEVANT, Nº 5, LOC. 6-8..."
price,16950.00,80900.00,69900.00
body_type,Compact,Compact,Compact
type,Used,Pre-registered,Used
doors,5.00,4.00,5.00
warranty,24.00,24.00,12.00
mileage,120200.00,5000.00,18900.00
gearbox,Manual,Automatic,Automatic
fuel_type,Diesel,Electric,Benzine
seller,Dealer,Dealer,Dealer
seats,NaN,5.00,5.00
engine_size,NaN,1.00,1991.00
gears,NaN,9.00,8.00
co_emissions,NaN,0.00,NaN
drivetrain,NaN,NaN,4WD
cylinders,NaN,NaN,4.00
comfort_&_convenience,NaN,NaN,NaN
entertainment_&_media,NaN,NaN,NaN
safety_&_security,NaN,NaN,NaN
extras,NaN,NaN,NaN
empty_weight,NaN,NaN,NaN
full_service_history,No,No,No
upholstery,NaN,NaN,NaN
previous_owner,NaN,NaN,NaN
energy_efficiency_class,NaN,NaN,NaN
age,6.00,0.00,2.00
power_kW,NaN,215.00,310.00
power_hp,NaN,292.00,421.00
cons_avg,NaN,NaN,8.40
cons_city,NaN,NaN,10.90
cons_country,NaN,NaN,5.80

In [17]:
df.shape

(28630, 35)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28630 entries, 0 to 28629
Data columns (total 35 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   make_model               28630 non-null  object
 1   short_description        28417 non-null  object
 2   make                     28630 non-null  object
 3   model                    28354 non-null  object
 4   location                 28630 non-null  object
 5   price                    28630 non-null  float64
 6   body_type                28630 non-null  object
 7   type                     28630 non-null  object
 8   doors                    28271 non-null  float64
 9   warranty                 13465 non-null  float64
 10  mileage                  28629 non-null  float64
 11  gearbox                  28382 non-null  object
 12  fuel_type                26843 non-null  object
 13  seller                   28630 non-null  object
 14  seats                    25505 non-null  float64
 15  engine_size              27227 non-null  float64
 16  gears                    18954 non-null  float64
 17  co_emissions             18594 non-null  float64
 18  drivetrain               16893 non-null  object
 19  cylinders                18852 non-null  float64
 20  comfort_&_convenience    25433 non-null  object
 21  entertainment_&_media    23644 non-null  object
 22  safety_&_security        25415 non-null  object
 23  extras                   23480 non-null  object
 24  empty_weight             17758 non-null  float64
 25  full_service_history     28630 non-null  object
 26  upholstery               18610 non-null  object
 27  previous_owner           14015 non-null  float64
 28  energy_efficiency_class  7804 non-null   object
 29  age                      28628 non-null  float64
 30  power_kW                 28058 non-null  float64
 31  power_hp                 28058 non-null  float64
 32  cons_avg                 23385 non-null  float64
 33  cons_city                20100 non-null  float64
 34  cons_country             20100 non-null  float64
dtypes: float64(17), object(18)
memory usage: 7.6+ MB

In [19]:
class color:
    PURPLE = '\033[95m'
    CYAN = '\033[96m'
    DARKCYAN = '\033[36m'
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
    END = '\033[0m'

def check_obj_columns(df):
    '''
    Returns NO PROBLEM or column/s which has/have mixed object types.
    '''    
    
    tdf = df.select_dtypes(include=['object']).applymap(type)
    for col in tdf:
        if len(set(tdf[col].values)) > 1:
            print("Column" + " " + color.BOLD + color.RED + col + color.END + " " + "has mixed object types." )
    else:
        if len(set(tdf[col].values)) == 1:
            print(color.BOLD + color.GREEN + " " + "NO PROBLEM" + " " + color.END + " " + "with the data types of Columns in the DataFrame.")

check_obj_columns(df)

Column short_description has mixed object types.
Column model has mixed object types.
Column gearbox has mixed object types.
Column fuel_type has mixed object types.
Column drivetrain has mixed object types.
Column comfort_&_convenience has mixed object types.
Column entertainment_&_media has mixed object types.
Column safety_&_security has mixed object types.
Column extras has mixed object types.
Column upholstery has mixed object types.
Column energy_efficiency_class has mixed object types.

### The Examination of Missing Values:

In [20]:
missing_percentage = df.isnull().sum()*100 / df.shape[0]

In [21]:
# miss_val = []

# [miss_val.append(column) for column in df.columns if any(df[column].isnull())]

# print("Columns that have missing values :")
# print("---"*11)

# print(f"{miss_val}\n\n{missing_percentage}")

In [22]:
# Here, the columns with even one missing value are collected in a list by means of the concept of List Comprehension. 
# And then, the percentage of each feature/column is represented in the output.  

miss_val = []
[miss_val.append(column) for column in df.columns if any(df[column].isnull())]

missing_percentage = df[miss_val].isnull().sum()*100 / df[miss_val].shape[0]
missing_percentage = missing_percentage.sort_values(ascending=False)
print("Columns that have missing values :")
print("---"*11)
print(f"{miss_val}\n\n{missing_percentage}")

Columns that have missing values :
---------------------------------
['short_description', 'model', 'doors', 'warranty', 'mileage', 'gearbox', 'fuel_type', 'seats', 'engine_size', 'gears', 'co_emissions', 'drivetrain', 'cylinders', 'comfort_&_convenience', 'entertainment_&_media', 'safety_&_security', 'extras', 'empty_weight', 'upholstery', 'previous_owner', 'energy_efficiency_class', 'age', 'power_kW', 'power_hp', 'cons_avg', 'cons_city', 'cons_country']

energy_efficiency_class   72.74
warranty                  52.97
previous_owner            51.05
drivetrain                41.00
empty_weight              37.97
co_emissions              35.05
upholstery                35.00
cylinders                 34.15
gears                     33.80
cons_country              29.79
cons_city                 29.79
cons_avg                  18.32
extras                    17.99
entertainment_&_media     17.42
safety_&_security         11.23
comfort_&_convenience     11.17
seats                     10.92
fuel_type                  6.24
engine_size                4.90
power_kW                   2.00
power_hp                   2.00
doors                      1.25
model                      0.96
gearbox                    0.87
short_description          0.74
age                        0.01
mileage                    0.00
dtype: float64

In [23]:
def df_nans(df, limit):
    """
    Returns a Pandas Series containing the percentage of missing values in each column of the input DataFrame 'df' that
    exceeds the given 'limit'.

    Parameters:
    -----------
    df : pandas.DataFrame
        The DataFrame to analyze for missing values.
    limit : float
        The threshold (in percentage) above which to consider a column as having too many missing values.

    Returns:
    --------
    pandas.Series
        A Series containing the percentage of missing values in each column of the input DataFrame 'df' that exceeds
        the given 'limit'.
        If no column has missing values that exceed the given limit, returns a string message indicating this.
    """
    missing = df.isnull().sum()*100 / df.shape[0]
    missing = missing.loc[lambda x : x >= limit]
    if missing.empty:
        return "No columns have missing values that exceed the given limit."
    else:
        return missing

def show_missing_values(limit):
    return df_nans(df, limit)

def column_nans(serial):
    # display percentage of NaNs in a Series
    return serial.isnull().sum()*100 / serial.shape[0]

In [24]:
# Let's explore the percentage of missing values in each column that exceeds the given 'limit'.

interact(show_missing_values, limit=(0, 100, 5))

interactive(children=(IntSlider(value=50, description='limit', step=5), Output()), _dom_classes=('widget-inter…

### The Examination of Duplicated Values:

In [25]:
df.duplicated(keep=False).sum()

3861

keep : {'first', 'last', False}, default 'first'
    Determines which duplicates (if any) to mark.

    - ``first`` : Mark duplicates as ``True`` except for the first occurrence.
    - ``last`` : Mark duplicates as ``True`` except for the last occurrence.
    - False : Mark all duplicates as ``True``.

This code will return all the rows of a Pandas DataFrame df that are duplicates based on all columns.

The duplicated() method when called with the argument keep=False returns a boolean Series indicating whether each row is a duplicate or not. If a row has a duplicate, the value is True, otherwise it is False.

By passing this boolean Series as an index to the DataFrame df, we can filter and select only the rows that have True values, which means they are duplicates. Thus, this code returns all the rows of the DataFrame df that have at least one duplicate row.

For example, if df has two identical rows, this code will return both the rows. If there are no duplicates, this code will return an empty DataFrame.

In [26]:
df[df.duplicated(keep=False)]

,make_model,short_description,make,model,location,price,body_type,type,doors,warranty,mileage,gearbox,fuel_type,seller,seats,engine_size,gears,co_emissions,drivetrain,cylinders,comfort_&_convenience,entertainment_&_media,safety_&_security,extras,empty_weight,full_service_history,upholstery,previous_owner,energy_efficiency_class,age,power_kW,power_hp,cons_avg,cons_city,cons_country
142,Mercedes-Benz A 45 AMG,S 4Matic+ 8G-DCT,Mercedes-Benz,A 45 AMG,"RONDA PONENT 62, 8201 SABADELL, ES",72890.00,Compact,Used,5.00,12.00,12900.00,Automatic,Benzine,Dealer,5.00,1991.00,8.00,NaN,4WD,4.00,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,1.00,310.00,421.00,8.40,10.90,5.80
237,Mercedes-Benz CL,200 163ch AMG Line 7G-DCT 9cv,Mercedes-Benz,CL,"--, 77240 Vert St Denis, FR",39990.00,Compact,Used,5.00,NaN,8500.00,Automatic,Benzine,Dealer,5.00,1332.00,NaN,NaN,NaN,NaN,"Air conditioning, Armrest, Automatic climate c...","Digital radio, Hands-free equipment, On-board ...","ABS, Central door lock, Central door lock with...","Alloy wheels, Shift paddles, Sport package, Sp...",NaN,No,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN
253,Mercedes-Benz CL,200 163ch AMG Line 7G-DCT 9cv,Mercedes-Benz,CL,"--, 77240 Vert St Denis, FR",39990.00,Compact,Used,5.00,NaN,8500.00,Automatic,Benzine,Dealer,5.00,1332.00,NaN,NaN,NaN,NaN,"Air conditioning, Armrest, Automatic climate c...","Digital radio, Hands-free equipment, On-board ...","ABS, Central door lock, Central door lock with...","Alloy wheels, Shift paddles, Sport package, Sp...",NaN,No,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN
263,Mercedes-Benz CL,200 163ch AMG Line 7G-DCT 9cv,Mercedes-Benz,CL,"--, 77240 Vert St Denis, FR",39990.00,Compact,Used,5.00,NaN,8500.00,Automatic,Benzine,Dealer,5.00,1332.00,NaN,NaN,NaN,NaN,"Air conditioning, Armrest, Automatic climate c...","Digital radio, Hands-free equipment, On-board ...","ABS, Central door lock, Central door lock with...","Alloy wheels, Shift paddles, Sport package, Sp...",NaN,No,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN
276,Mercedes-Benz A 45 AMG,S 4Matic+ 8G-DCT,Mercedes-Benz,A 45 AMG,"RONDA PONENT 62, 8201 SABADELL, ES",72890.00,Compact,Used,5.00,12.00,12900.00,Automatic,Benzine,Dealer,5.00,1991.00,8.00,NaN,4WD,4.00,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,1.00,310.00,421.00,8.40,10.90,5.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28253,Volvo V60 Cross Country,D4 AWD Geartronic Pro,Volvo,V60 Cross Country,"Via Ca' Baroncello, 32/B, 36061 Bassano Del G...",32500.00,Station wagon,Used,5.00,NaN,142000.00,Automatic,Diesel,Dealer,5.00,1969.00,8.00,143.00,4WD,4.00,"Air conditioning, Armrest, Automatic climate c...","Digital radio, Radio","Adaptive Cruise Control, Blind spot monitor, D...","Alloy wheels, Automatically dimming interior m...",NaN,No,Full leather,NaN,NaN,3.00,140.00,190.00,5.40,6.30,4.90
28556,Volvo S90,D5 AWD R Design SchiebeD LED Nav WinterP 19Z,Volvo,S90,"Von-Drais-Str. 2, 77855 Achern, DE",31488.00,Sedan,Used,4.00,NaN,84000.00,Automatic,Diesel,Dealer,5.00,1969.00,0.00,127.00,4WD,4.00,"Air conditioning, Automatic climate control, A...","On-board computer, Radio, USB","ABS, Adaptive headlights, Central door lock, D...","Alloy wheels, Catalytic Converter, Sport suspe...",1892.00,No,Full leather,NaN,efficient,5.00,173.00,235.00,4.80,5.70,4.30
28557,Volvo S90,D5 AWD R Design SchiebeD LED Nav WinterP 19Z,Volvo,S90,"Von-Drais-Str. 2, 77855 Achern, DE",31488.00,Sedan,Used,4.00,NaN,84000.00,Automatic,Diesel,Dealer,5.00,1969.00,0.00,127.00,4WD,4.00,"Air conditioning, Automatic climate control, A...","On-board computer, Radio, USB","ABS, Adaptive headlights, Central door lock, D...","Alloy wheels, Catalytic Converter, Sport suspe...",1892.00,No,Full leather,NaN,efficient,5.00,173.00,235.00,4.80,5.70,4.30
28593,Volvo V40,D3 150ch R-Design Geartronic,Volvo,V40,"19 rue des Alliés, 57050 Metz, FR",18999.00,Sedan,Used,5.00,12.00,93257.00,Automatic,Diesel,Dealer,5.00,1969.00,NaN,108.00,NaN,NaN,"Armrest, Automatic climate control, 2 zones, A...",NaN,"ABS, Driver-side airbag, Emergency brake assis...",Emergency tyre,NaN,No,NaN,NaN,NaN,4.00,112.00,152.00,NaN,NaN,NaN
28595,Volvo V40,D3 150ch R-Design Geartronic,Volvo,V40,"19 rue des Alliés, 57050 Metz, FR",18999.00,Sedan,Used,5.00,12.00,93257.00,Automatic,Diesel,Dealer,5.00,1969.00,NaN,108.00,NaN,NaN,"Armrest, Automatic climate control, 2 zones, A...",NaN,"ABS, Driver-side airbag, Emergency brake assis...",Emergency tyre,NaN,No,NaN,NaN,NaN,4.00,112.00,152.00,NaN,NaN,NaN

### ⚠️ 🔥 SPECIAL NOTE:

The duplicated values in the DataFrame will be taken care of after some Exploratory Data Analysis processes.

## User Defined Functions (DEFs) to fill the missing values:

### 1) first_looking(col)

In [27]:
def first_looking(*cols):
    """
    Prints basic information about given columns in a Pandas DataFrame.

    Parameters:
    *cols (str): The names of the columns to analyze.

    Returns:
    None.

    Prints:
    - The name of each column.
    - The percentage of null values in each column.
    - The number of null values in each column.
    - The number of unique values in each column.
    - The value counts for each unique value in each column, including null values.
    """
    for col in cols:
        print("COLUMN NAME    : ", col)
        print("--------------------------------")
        print("per_of_nulls   : ", "%", round(df[col].isnull().sum()*100 / df.shape[0], 2))
        print("num_of_nulls   : ", df[col].isnull().sum())
        print("num_of_uniques : ", df[col].nunique())
        print("--------------------------------")
        print(df[col].value_counts(dropna=False))
        print("\n")

This is a Python User Defined Function (DEF) called ``first_looking`` that takes a column name as input (col). The function is designed to provide an initial analysis of a given column in a Pandas DataFrame (df).

The function first prints the column name, followed by a line of dashes for formatting. It then calculates and prints the percentage of null values in the column (per_of_nulls), the number of null values in the column (num_of_nulls), and the number of unique values in the column (num_of_uniques), each on a separate line.

After printing these summary statistics, the function prints another line of dashes for formatting, followed by a Pandas value_counts() method call that prints the frequency of each unique value in the column, including NaN values (if any). This can help identify common values and outliers in the data, as well as any potential issues, such as missing or incorrect data.

Overall, the first_looking function provides a quick and easy way to get a first look at a given column in a Pandas DataFrame, including basic summary statistics and value frequencies.

### 2) fill_most_freq(df, group_col, col_name)

In [28]:
def fill_most_freq(df, group_col, col_name):
    """
    Fills missing values in a column of a Pandas DataFrame `df` with the most frequent value 
    in each group defined by a grouping column.

    Parameters:
    df (pandas.DataFrame): The DataFrame to operate on.
    group_col (str): The name of the grouping column.
    col_name (str): The name of the column to fill missing values in.

    Returns:
    None.

    Prints:
    - The name of the column that was filled.
    - The percentage of null values in the column after filling.
    - The number of null values in the column after filling.
    - The number of unique values in the column after filling.
    - The value counts for each unique value in the column after filling, including null values, sorted by index.
    """    
    for group in list(df[group_col].unique()):
        cond = df[group_col]==group
        mode = list(df[cond][col_name].mode())
        if mode != []:
            df.loc[cond, col_name] = df.loc[cond, col_name].fillna(df[cond][col_name].mode()[0])
        else:
            df.loc[cond, col_name] = df.loc[cond, col_name].fillna(df[col_name].mode()[0])
    
    print("COLUMN NAME    : ", col_name)
    print("--------------------------------")
    print("per_of_nulls   : ", "%", round(df[col_name].isnull().sum()*100 / df.shape[0], 2))
    print("num_of_nulls   : ", df[col_name].isnull().sum())
    print("num_of_uniques : ", df[col_name].nunique())
    print("--------------------------------")
    print(df[col_name].value_counts(dropna = False).sort_index())

This is a Python User Defined Function (DEF) called ``fill_most_freq`` that takes three (3) input parameters: a Pandas DataFrame (df), the name of a column to group by (group_col), and the name of a column to fill missing values in (col_name).

This for loop in the DEF is used to fill missing values in a specific column of a pandas DataFrame df based on the values in another column. Here's what's happening in each line of the loop:

  - ``for group in list(df[group_col].unique())``: - This line iterates over all the unique values in the column specified by group_col. Each unique value is stored in the variable group.

  - ``cond = df[group_col]==group`` - This line creates a boolean Series cond with True values for all rows in df where the value in the column group_col is equal to group.

  - ``mode = list(df[cond][col_name].mode())`` - This line calculates the mode of the column specified by col_name for all rows where the cond Series is True. The mode is stored as a list in the variable mode.

  - ``if mode != []``: - This line checks if mode is not an empty list.

  - ``df.loc[cond, col_name] = df.loc[cond, col_name].fillna(df[cond][col_name].mode()[0])`` - This line fills missing values in the column specified by col_name for all rows where the cond Series is True. The missing values are filled using the mode of the column for rows where the value in the column group_col is equal to group.

  - ``else``: - This line executes if mode is an empty list.

  - ``df.loc[cond, col_name] = df.loc[cond, col_name].fillna(df[col_name].mode()[0])`` - This line fills missing values in the column specified by col_name for all rows where the cond Series is True, but the mode of the column for rows where the value in the column group_col is equal to group is not available. The missing values are filled using the mode of the column for all rows in the DataFrame.

Overall, this User Defined Function (DEF) called ``fill_most_freq`` fills missing values in a specific column of a DataFrame based on the values in another column, with the goal of preserving group-specific information and filling missing values intelligently.

### 3) fill_mode(df, group_col1, group_col2, col_name)

In [29]:
def fill_mode(df, group_col1, group_col2, col_name):
    """
    Fills missing values in a column of a Pandas DataFrame `df` based on the values in two other columns.

    Parameters:
    df (pandas.DataFrame): The DataFrame to operate on.
    group_col1 (str): The name of the first grouping column.
    group_col2 (str): The name of the second grouping column.
    col_name (str): The name of the column to fill missing values in.

    Returns:
    None.

    Prints:
    - The name of the column that was filled.
    - The percentage of null values in the column after filling.
    - The number of null values in the column after filling.
    - The number of unique values in the column after filling.
    - The value counts for each unique value in the column after filling, including null values.
    """    
    for group1 in list(df[group_col1].unique()):
        for group2 in list(df[group_col2].unique()):
            cond1 = df[group_col1]==group1
            cond2 = (df[group_col1]==group1) & (df[group_col2]==group2)
            mode1 = list(df[cond1][col_name].mode())
            mode2 = list(df[cond2][col_name].mode())
            if mode2 != []:
                df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[cond2][col_name].mode()[0])
            elif mode1 != []:
                df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[cond1][col_name].mode()[0])
            else:
                df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[col_name].mode()[0])
    
    print("column name    : ", col_name)
    print("--------------------------------")
    print("per_of_nulls   : ", "%", round(df[col_name].isnull().sum()*100 / df.shape[0], 2))
    print("num_of_nulls   : ", df[col_name].isnull().sum())
    print("num_of_uniques : ", df[col_name].nunique())
    print("--------------------------------")
    print(df[col_name].value_counts(dropna = False))

This is a Python User Defined Function (DEF) called ``fill_mode`` that takes four (4) input parameters: a Pandas DataFrame (df), the name of a column to group by (group_col1), another name of a column to group by (group_col2), and the name of a column to fill missing values in (col_name).

This nested for loop in the DEF is used to fill missing values in a specific column of a pandas DataFrame df based on the values in two other columns. Here's what's happening in each line of the loop:

  - ``for group1 in list(df[group_col1].unique())``: - This line iterates over all the unique values in the column specified by group_col1. Each unique value is stored in the variable group1.

  - ``for group2 in list(df[group_col2].unique())``: - This line iterates over all the unique values in the column specified by group_col2. Each unique value is stored in the variable group2.

  - ``cond1 = df[group_col1]==group1`` - This line creates a boolean Series cond1 with True values for all rows in df where the value in the column group_col1 is equal to group1.

  - ``cond2 = (df[group_col1]==group1) & (df[group_col2]==group2)`` - This line creates a boolean Series cond2 with True values for all rows in df where the value in the column group_col1 is equal to group1 AND the value in the column group_col2 is equal to group2. This ensures that we are only filling missing values for rows that have both group1 and group2.

  - ``mode1 = list(df[cond1][col_name].mode())`` - This line calculates the mode of the column specified by col_name for all rows where the cond1 Series is True. The mode is stored as a list in the variable mode1.

  - ``mode2 = list(df[cond2][col_name].mode())`` - This line calculates the mode of the column specified by col_name for all rows where the cond2 Series is True. The mode is stored as a list in the variable mode2.

  - ``if mode2 != []``: - This line checks if mode2 is not an empty list.

  - ``df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[cond2][col_name].mode()[0])`` - This line fills missing values in the column specified by col_name for all rows where the cond2 Series is True. The missing values are filled using the mode of the column for rows where both group1 and group2 are present.

  - ``elif mode1 != []``: - This line checks if mode1 is not an empty list, and if mode2 is empty.

  - ``df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[cond1][col_name].mode()[0])`` - This line fills missing values in the column specified by col_name for all rows where the cond2 Series is True, but the mode of the column for rows where both group1 and group2 are present is not available. The missing values are filled using the mode of the column for rows where only group1 is present.

  - ``else``: - This line executes if both mode1 and mode2 are empty.

  - ``df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[col_name].mode()[0])`` - This line fills missing values in the column specified by col_name for all rows where the cond2 Series is True, but the mode of the column for rows where both group1 and group2 are present, and the mode of the column for rows where only group1 is present are both not available. The missing values are filled using the mode of the column for all rows in the DataFrame.

Overall, this User Defined Function (DEF) called ``fill_mode`` fills missing values in a specific column of a DataFrame based on the values in two other columns, with the goal of preserving group-specific information and filling missing values intelligently.

### 4) fill_prop(df, group_col, col_name)

In [30]:
def fill_prop(df, group_col, col_name):
    """
    Fills missing values in a column of a Pandas DataFrame `df` using forward and backward fill based on a grouping column.

    Parameters:
    df (pandas.DataFrame): The DataFrame to operate on.
    group_col (str): The name of the grouping column.
    col_name (str): The name of the column to fill missing values in.

    Returns:
    None.

    Prints:
    - The name of the column that was filled.
    - The percentage of null values in the column after filling.
    - The number of null values in the column after filling.
    - The number of unique values in the column after filling.
    - The value counts for each unique value in the column after filling, including null values, sorted by index.
    """    
    for group in list(df[group_col].unique()):
        cond = df[group_col]==group
        df.loc[cond, col_name] = df.loc[cond, col_name].fillna(method="ffill").fillna(method="bfill")
    df[col_name] = df[col_name].fillna(method="ffill").fillna(method="bfill")
    
    print("COLUMN NAME    : ", col_name)
    print("--------------------------------")
    print("per_of_nulls   : ", "%", round(df[col_name].isnull().sum()*100 / df.shape[0], 2))
    print("num_of_nulls   : ", df[col_name].isnull().sum())
    print("num_of_uniques : ", df[col_name].nunique())
    print("--------------------------------")
    print(df[col_name].value_counts(dropna = False).sort_index())

This is a Python User Defined Function (DEF) called ``fill_prop`` that takes three (3) input parameters: a Pandas DataFrame (df), the name of a column to group by (group_col), and the name of a column to fill missing values in (col_name).

This for loop in the DEF is used to fill missing values in a specific column of a pandas DataFrame df based on the values in another column. Here's what's happening in each line of the loop:

  - ``for group in list(df[group_col].unique())``: - This line iterates over all the unique values in the column specified by group_col. Each unique value is stored in the variable group.

  - ``cond = df[group_col]==group`` - This line creates a boolean Series cond with True values for all rows in df where the value in the column group_col is equal to group.

  - ``df.loc[cond, col_name] = df.loc[cond, col_name].fillna(method="ffill").fillna(method="bfill")`` - This line fills missing values in the column specified by col_name for all rows where the cond Series is True. The missing values are first filled using the forward fill method (method="ffill") and then with the backward fill method (method="bfill"). This ensures that any missing values are filled with the nearest non-missing value in the same group.

  - ``df[col_name] = df[col_name].fillna(method="ffill").fillna(method="bfill")`` - This line fills any remaining missing values in the column specified by col_name using the same forward fill and backward fill method. This ensures that any missing values not associated with a specific group are also filled with the nearest non-missing value.

Overall, this User Defined Function (DEF) called ``fill_prop`` fills missing values in a specific column of a DataFrame based on the values in another column, with the goal of preserving group-specific information and filling any remaining missing values.

### 5) fill(df, group_col1, group_col2, col_name, method)

In [31]:
def fill(df, group_col1, group_col2, col_name, method):
    """
    Fills missing values in a column of a Pandas DataFrame `df` based on double-stage grouping and a specified filling method.

    Parameters:
    df (pandas.DataFrame): The DataFrame to operate on.
    group_col1 (str): The name of the first grouping column.
    group_col2 (str): The name of the second grouping column.
    col_name (str): The name of the column to fill missing values in.
    method (str): The filling method to use. Can be "mode", "mean", "median", "ffill", or "bfill".

    Returns:
    None.

    Prints:
    None.
    """
    
    if method == "mode":
        for group1 in list(df[group_col1].unique()):
            for group2 in list(df[group_col2].unique()):
                cond1 = df[group_col1]==group1
                cond2 = (df[group_col1]==group1) & (df[group_col2]==group2)
                mode1 = list(df[cond1][col_name].mode())
                mode2 = list(df[cond2][col_name].mode())
                if mode2 != []:
                    df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[cond2][col_name].mode()[0])
                elif mode1 != []:
                    df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[cond1][col_name].mode()[0])
                else:
                    df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[col_name].mode()[0])

    elif method == "mean":
        df[col_name].fillna(df.groupby([group_col1, group_col2])[col_name].transform("mean"), inplace = True)
        df[col_name].fillna(df.groupby(group_col1)[col_name].transform("mean"), inplace = True)
        df[col_name].fillna(df[col_name].mean(), inplace = True)
        
    elif method == "median":
        df[col_name].fillna(df.groupby([group_col1, group_col2])[col_name].transform("median"), inplace = True)
        df[col_name].fillna(df.groupby(group_col1)[col_name].transform("median"), inplace = True)
        df[col_name].fillna(df[col_name].median(), inplace = True)
        
    elif method == "ffill":           
        for group1 in list(df[group_col1].unique()):
            for group2 in list(df[group_col2].unique()):
                cond2 = (df[group_col1]==group1) & (df[group_col2]==group2)
                df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(method="ffill").fillna(method="bfill")
                
        for group1 in list(df[group_col1].unique()):
            cond1 = df[group_col1]==group1
            df.loc[cond1, col_name] = df.loc[cond1, col_name].fillna(method="ffill").fillna(method="bfill")            
           
        df[col_name] = df[col_name].fillna(method="ffill").fillna(method="bfill")
    
    print("COLUMN NAME    : ", col_name)
    print("--------------------------------")
    print("per_of_nulls   : ", "%", round(df[col_name].isnull().sum()*100 / df.shape[0], 2))
    print("num_of_nulls   : ", df[col_name].isnull().sum())
    print("num_of_uniques : ", df[col_name].nunique())
    print("--------------------------------")
    print(df[col_name].value_counts(dropna = False).sort_index())

This is a Python User Defined Function (DEF) called ``fill`` that takes five (5) input parameters: a Pandas DataFrame (df), the name of a first column to group by (group_col1), the name of a second column to group by (group_col2), the name of a column to fill missing values in (col_name), and a method to use for filling missing values (method). The method parameter can take one of four values: "mode", "mean", "median", or "ffill".

The function first defines a docstring that describes its purpose: to fill missing values in the col_name column using one of several methods, based on double-stage grouping by the group_col1 and group_col2 columns.

The function then checks the value of the method parameter and executes the appropriate code block to fill missing values using the specified method.

If method is "mode", the function defines a nested loop that iterates over the unique values in both the group_col1 and group_col2 columns. For each combination of unique values, the function fills missing values in the col_name column with the mode of that column for the corresponding group.

If method is "mean" or "median", the function uses the fillna method to fill missing values in the col_name column based on the mean or median of the column for each combination of unique values in the group_col1 and group_col2 columns, then for each unique value in the group_col1 column, and finally for the entire column.

If method is "ffill", the function defines two nested loops that iterate over the unique values in both the group_col1 and group_col2 columns, and for each combination of unique values, the function fills missing values in the col_name column with the "forward fill" (ffill) and "backward fill" (bfill) methods. The function then applies the same fill methods to fill any remaining missing values at the beginning or end of the column.

After filling missing values using the specified method, the function prints some summary statistics for the col_name column, including the percentage and number of null values, the number of unique values, and the value counts for each unique value in the column, including NaN values (if any). The sort_index method is used to sort the value counts by index (i.e., in ascending order).

Overall, the fill function provides a flexible and powerful way to fill missing values in a Pandas DataFrame column using several different methods, with the option to group by one or two columns for greater flexibility.

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">The Examination of Missing Values in the Columns</p>

<a id="2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### ⚠️ 🔥 SPECIAL NOTE:

Before we start our analysis and move forward, it is useful to underline one point.<br>
In this analysis, according to the **``Domain Knowledge``** we obtained, the **``make_model``** & **``body_type``** features will be referenced when filling in missing values, since these features are thought to have more or less influence on the formation of other features, either directly or indirectly.

So, at the begining we need to a close look at these features if they have missing values; if so, let us decide how to handle them:

In [32]:
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

In [33]:
df_notnull = df[df.columns[~df.isnull().any()]]
df_notnull.columns

Index(['make_model', 'make', 'location', 'price', 'body_type', 'type',
       'seller', 'full_service_history'],
      dtype='object')

In [34]:
for col in df_notnull.columns:
    print(first_looking(col))
    print()

COLUMN NAME    :  make_model
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  611
--------------------------------
make_model
Renault Megane     863
SEAT Leon          787
Volvo V40          740
Dacia Sandero      730
Hyundai i30        706
                  ...
Toyota GR86          1
Toyota Tacoma        1
Toyota Tundra        1
Toyota 4-Runner      1
Volvo 244            1
Name: count, Length: 611, dtype: int64


None

COLUMN NAME    :  make
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  13
--------------------------------
make
Volvo            3659
Mercedes-Benz    2398
Opel             2385
Peugeot          2360
Renault          2351
Fiat             2338
Ford             2324
Nissan           2064
Toyota           2038
Hyundai          1867
SEAT             1743
Skoda            1566
Dacia            1537
Name: count, dtype: int64


None

COLUMN NAME    :  location
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  8181
--------------------------------
location
Av. Laboral, 10,  28021 MADRID, ES                          306
Luckenwalder Berg 5,  14913 Jüterbog, DE                    170
Ctra. del Mig, 96,,  08097 L'Hospitalet de Llobregat, ES    146
9 boulevard Jules Ferry,  75011 Paris, FR                   142
Neuenhofstr. 77,  52078 Aachen, DE                          135
                                                           ...
2727CT ZOETERMEER, NL                                         1
Rosendaalsestraat 437-439,  6824 CK ARNHEM, NL                1
5751VH DEURNE, NL                                             1
00148 roma, IT                                                1
Sur rendez-vous,  5060 Sambreville, BE                        1
Name: count, Length: 8181, dtype: int64


None

COLUMN NAME    :  price
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  5021
--------------------------------
price
14990.00    222
12990.00    219
16990.00    186
19990.00    166
9990.00     160
           ...
19112.00      1
30465.00      1
18461.00      1
22649.00      1
4440.00       1
Name: count, Length: 5021, dtype: int64


None

COLUMN NAME    :  body_type
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  6
--------------------------------
body_type
Station wagon       5448
Off-Road/Pick-up    5415
Compact             5387
Sedan               5043
Coupe               4009
Convertible         3328
Name: count, dtype: int64


None

COLUMN NAME    :  type
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  4
--------------------------------
type
Used              25251
Demonstration      1433
Pre-registered     1377
Employee's car      569
Name: count, dtype: int64


None

COLUMN NAME    :  seller
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  2
--------------------------------
seller
Dealer            26318
Private seller     2312
Name: count, dtype: int64


None

COLUMN NAME    :  full_service_history
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  2
--------------------------------
full_service_history
No     16065
Yes    12565
Name: count, dtype: int64


None

Among the features above, **``make_model``**,  **``make``**, **``model``** & sometimes **``body_type``** are the critical/crucial ones to impute the missing values. Therefore let's take a close look at them one by one:

## make_model, make, & model

In [35]:
# Let's explore basic information about "make_model", "make", "model"

first_looking("make_model", "make", "model")

COLUMN NAME    :  make_model
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  611
--------------------------------
make_model
Renault Megane     863
SEAT Leon          787
Volvo V40          740
Dacia Sandero      730
Hyundai i30        706
                  ...
Toyota GR86          1
Toyota Tacoma        1
Toyota Tundra        1
Toyota 4-Runner      1
Volvo 244            1
Name: count, Length: 611, dtype: int64


COLUMN NAME    :  make
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  13
--------------------------------
make
Volvo            3659
Mercedes-Benz    2398
Opel             2385
Peugeot          2360
Renault          2351
Fiat             2338
Ford             2324
Nissan           2064
Toyota           2038
Hyundai          1867
SEAT             1743
Skoda            1566
Dacia            1537
Name: count, dtype: int64


COLUMN NAME    :  model
--------------------------------
per_of_nulls   :  % 0.96
num_of_nulls   :  276
num_of_uniques :  593
--------------------------------
model
Megane        863
Leon          787
V40           740
Sandero       730
i30           706
             ...
GLA 35 AMG      1
G 55 AMG        1
Ariya           1
105             1
244             1
Name: count, Length: 594, dtype: int64

In [36]:
df[['make_model', 'make', 'model', "short_description"]].sample(20)

,make_model,make,model,short_description
2410,Opel Corsa,Opel,Corsa,1.4 Advance EcoFlex 90PK RZ85711
22540,Ford Focus,Ford,Focus,Cool&Connect Navi|Sportsitze|PDC|SHZ
27232,Volvo XC60,Volvo,XC60,T8 Momentum Plug-In Hybrid AWD Pano Standhz
9857,Fiat 500,Fiat,500,1.2 Mirror
14055,Skoda Enyaq,Skoda,Enyaq,iV 80 Loft *LED*Navi*Kamera*Pano*20 Zoll* Klima
23583,Hyundai i30,Hyundai,i30,2.0 T-GDI Fastback N Performance
22761,Ford Fiesta,Ford,Fiesta,ST-Line AHK Winter-Paket 1.0 EcoBoost
23271,Hyundai Excel,Hyundai,Excel,1.3i LS 1e Eigenaar! 4x Nieuwe banden NAP APK
7920,Peugeot 307,Peugeot,307,CC 110 Filou
2338,Mercedes-Benz E 220,Mercedes-Benz,E 220,D*Navi*Rückfahrkamera*Sitzheizung*LED*DAB*
8362,Peugeot 3008,Peugeot,3008,300 e-EAT8 Allure Pack
20684,Nissan Qashqai,Nissan,Qashqai,DIG-T 103 kW (140 CV) E6D N-STYLE
16918,Toyota Auris,Toyota,Auris,hybrid 140H Feel! Edition
10359,Fiat 124 Spider,Fiat,124 Spider,1.4 Multiair
6905,Renault Clio,Renault,Clio,ZEN TCe90 X-tronic SITZH/PARKP/EASY-LINK
24805,Hyundai i30,Hyundai,i30,N Performance 8-DCT NaviP KomfortP AssistP
26062,Volvo C70,Volvo,C70,2.5T 220PS Cabriolet T5 Summum 1.Hand Xenon
21851,Ford Mustang,Ford,Mustang,5.0 Ti-VCT V8 Mach I (Fastsb.)
26123,Volvo C70,Volvo,C70,Cabriolet 2.4 T
9457,Peugeot 208,Peugeot,208,1.5 BlueHDi 100ch E6.c Active BVM5 86g 5p

<img src=https://i.ibb.co/VHd4whm/empty-cells.png width="350" height="100">

In [37]:
df['model'].str.contains(r'^\s*$', na=False).value_counts()

# (df['model'] == '').value_counts()

model
False    28630
Name: count, dtype: int64

The regular expression pattern <b><code>r'^\s*$'</code></b> matches a string that consists of zero or more whitespace characters.

  - ``^`` asserts the start of the string.
  - ``\s`` matches any whitespace character, such as space, tab, or newline.
  - ``*`` matches zero or more occurrences of the preceding pattern, in this case, zero or more whitespace characters.
  - ``$`` asserts the end of the string.

So, the pattern <b><code>r'^\s*$'</code></b> will match a string if it contains only whitespace characters or is completely empty, such as "", " ", " ", "\t\t", and/or "\n"

In [38]:
# df[(df["make"] == "Mercedes-Benz")&(~df['model'].isna())][['make_model', 'make', 'model']]

# df[df['model'].str.contains(r'^\s*$', na=False)][['make_model', 'make', 'model']]

In [39]:
df["model"] = df["model"].replace(r'^\s*$', np.nan, regex=True)
df[df["model"].isna()][['make_model', 'make', 'model']]

           make_model           make model
162    Mercedes-Benz   Mercedes-Benz   NaN
184    Mercedes-Benz   Mercedes-Benz   NaN
186    Mercedes-Benz   Mercedes-Benz   NaN
211    Mercedes-Benz   Mercedes-Benz   NaN
213    Mercedes-Benz   Mercedes-Benz   NaN
226    Mercedes-Benz   Mercedes-Benz   NaN
319    Mercedes-Benz   Mercedes-Benz   NaN
427    Mercedes-Benz   Mercedes-Benz   NaN
442    Mercedes-Benz   Mercedes-Benz   NaN
471    Mercedes-Benz   Mercedes-Benz   NaN
474    Mercedes-Benz   Mercedes-Benz   NaN
608    Mercedes-Benz   Mercedes-Benz   NaN
642    Mercedes-Benz   Mercedes-Benz   NaN
643    Mercedes-Benz   Mercedes-Benz   NaN
651    Mercedes-Benz   Mercedes-Benz   NaN
766    Mercedes-Benz   Mercedes-Benz   NaN
856    Mercedes-Benz   Mercedes-Benz   NaN
861    Mercedes-Benz   Mercedes-Benz   NaN
922    Mercedes-Benz   Mercedes-Benz   NaN
1229   Mercedes-Benz   Mercedes-Benz   NaN
1275   Mercedes-Benz   Mercedes-Benz   NaN
1294   Mercedes-Benz   Mercedes-Benz   NaN
1818   Mercedes-Benz   Mercedes-Benz   NaN
1972   Mercedes-Benz   Mercedes-Benz   NaN
2033   Mercedes-Benz   Mercedes-Benz   NaN
2114   Mercedes-Benz   Mercedes-Benz   NaN
2120   Mercedes-Benz   Mercedes-Benz   NaN
2184   Mercedes-Benz   Mercedes-Benz   NaN
2232   Mercedes-Benz   Mercedes-Benz   NaN
2335   Mercedes-Benz   Mercedes-Benz   NaN
2371   Mercedes-Benz   Mercedes-Benz   NaN
2914            Opel            Opel   NaN
2918            Opel            Opel   NaN
2920            Opel            Opel   NaN
2921            Opel            Opel   NaN
2923            Opel            Opel   NaN
2924            Opel            Opel   NaN
2925            Opel            Opel   NaN
2928            Opel            Opel   NaN
2929            Opel            Opel   NaN
2930            Opel            Opel   NaN
2931            Opel            Opel   NaN
2933            Opel            Opel   NaN
2936            Opel            Opel   NaN
2939            Opel            Opel   NaN
2940            Opel            Opel   NaN
2941            Opel            Opel   NaN
2942            Opel            Opel   NaN
2945            Opel            Opel   NaN
2946            Opel            Opel   NaN
2947            Opel            Opel   NaN
2948            Opel            Opel   NaN
2949            Opel            Opel   NaN
2950            Opel            Opel   NaN
2951            Opel            Opel   NaN
2955            Opel            Opel   NaN
2956            Opel            Opel   NaN
2957            Opel            Opel   NaN
2958            Opel            Opel   NaN
2959            Opel            Opel   NaN
2961            Opel            Opel   NaN
2962            Opel            Opel   NaN
2963            Opel            Opel   NaN
2964            Opel            Opel   NaN
2965            Opel            Opel   NaN
2966            Opel            Opel   NaN
2967            Opel            Opel   NaN
2968            Opel            Opel   NaN
2969            Opel            Opel   NaN
2970            Opel            Opel   NaN
2971            Opel            Opel   NaN
2972            Opel            Opel   NaN
2973            Opel            Opel   NaN
2975            Opel            Opel   NaN
2976            Opel            Opel   NaN
2977            Opel            Opel   NaN
2978            Opel            Opel   NaN
2979            Opel            Opel   NaN
2980            Opel            Opel   NaN
2981            Opel            Opel   NaN
2982            Opel            Opel   NaN
2984            Opel            Opel   NaN
2986            Opel            Opel   NaN
2987            Opel            Opel   NaN
2988            Opel            Opel   NaN
2989            Opel            Opel   NaN
2990            Opel            Opel   NaN
2992            Opel            Opel   NaN
2993            Opel            Opel   NaN
2994            Opel            Opel   NaN
2995            Opel            Opel   NaN
2996            Opel            Opel   NaN
2997            Opel            Opel   NaN
2998            Opel            Opel   NaN
2999            Opel            Opel   NaN
3000            Opel            Opel   NaN
3001            Opel            Opel   NaN
3002            Opel            Opel   NaN
3003            Opel            Opel   NaN
3004            Opel            Opel   NaN
3005            Opel            Opel   NaN
3006            Opel            Opel   NaN
3007            Opel            Opel   NaN
3008            Opel            Opel   NaN
3009            Opel            Opel   NaN
3011            Opel            Opel   NaN
3012            Opel            Opel   NaN
3013            Opel            Opel   NaN
3014            Opel            Opel   NaN
3015            Opel            Opel   NaN
3016            Opel            Opel   NaN
3017            Opel            Opel   NaN
3018            Opel            Opel   NaN
3019            Opel            Opel   NaN
3020            Opel            Opel   NaN
3021            Opel            Opel   NaN
3022            Opel            Opel   NaN
3024            Opel            Opel   NaN
3025            Opel            Opel   NaN
3026            Opel            Opel   NaN
3027            Opel            Opel   NaN
3028            Opel            Opel   NaN
3029            Opel            Opel   NaN
3030            Opel            Opel   NaN
3031            Opel            Opel   NaN
3033            Opel            Opel   NaN
3035            Opel            Opel   NaN
3036            Opel            Opel   NaN
3037            Opel            Opel   NaN
3038            Opel            Opel   NaN
3039            Opel            Opel   NaN
3040            Opel            Opel   NaN
3358            Opel            Opel   NaN
3378            Opel            Opel   NaN
5173         Renault         Renault   NaN
5300         Renault         Renault   NaN
5301         Renault         Renault   NaN
5383         Renault         Renault   NaN
5583         Renault         Renault   NaN
5599         Renault         Renault   NaN
5633         Renault         Renault   NaN
5717         Renault         Renault   NaN
6048         Renault         Renault   NaN
6071         Renault         Renault   NaN
6087         Renault         Renault   NaN
6096         Renault         Renault   NaN
6101         Renault         Renault   NaN
6594         Renault         Renault   NaN
6678         Renault         Renault   NaN
6699         Renault         Renault   NaN
7778         Peugeot         Peugeot   NaN
8043         Peugeot         Peugeot   NaN
9114         Peugeot         Peugeot   NaN
9120         Peugeot         Peugeot   NaN
9280         Peugeot         Peugeot   NaN
9672            Fiat            Fiat   NaN
9902            Fiat            Fiat   NaN
10000           Fiat            Fiat   NaN
10009           Fiat            Fiat   NaN
10047           Fiat            Fiat   NaN
10217           Fiat            Fiat   NaN
10327           Fiat            Fiat   NaN
10328           Fiat            Fiat   NaN
10370           Fiat            Fiat   NaN
10371           Fiat            Fiat   NaN
10373           Fiat            Fiat   NaN
10376           Fiat            Fiat   NaN
10384           Fiat            Fiat   NaN
10390           Fiat            Fiat   NaN
10406           Fiat            Fiat   NaN
10421           Fiat            Fiat   NaN
10465           Fiat            Fiat   NaN
10472           Fiat            Fiat   NaN
10493           Fiat            Fiat   NaN
10523           Fiat            Fiat   NaN
10524           Fiat            Fiat   NaN
10549           Fiat            Fiat   NaN
10551           Fiat            Fiat   NaN
10617           Fiat            Fiat   NaN
11097           Fiat            Fiat   NaN
11121           Fiat            Fiat   NaN
11214           Fiat            Fiat   NaN
11569           Fiat            Fiat   NaN
11919           SEAT            SEAT   NaN
12221           SEAT            SEAT   NaN
12233           SEAT            SEAT   NaN
12966           SEAT            SEAT   NaN
14890          Skoda           Skoda   NaN
15169          Dacia           Dacia   NaN
15209          Dacia           Dacia   NaN
15210          Dacia           Dacia   NaN
16235          Dacia           Dacia   NaN
16531          Dacia           Dacia   NaN
17109         Toyota          Toyota   NaN
17120         Toyota          Toyota   NaN
17121         Toyota          Toyota   NaN
17132         Toyota          Toyota   NaN
17160         Toyota          Toyota   NaN
17167         Toyota          Toyota   NaN
17211         Toyota          Toyota   NaN
17475         Toyota          Toyota   NaN
17477         Toyota          Toyota   NaN
17694         Toyota          Toyota   NaN
17873         Toyota          Toyota   NaN
17890         Toyota          Toyota   NaN
17943         Toyota          Toyota   NaN
18111         Toyota          Toyota   NaN
18122         Toyota          Toyota   NaN
18172         Toyota          Toyota   NaN
19127         Nissan          Nissan   NaN
19129         Nissan          Nissan   NaN
19132         Nissan          Nissan   NaN
19285         Nissan          Nissan   NaN
19426         Nissan          Nissan   NaN
19462         Nissan          Nissan   NaN
19468         Nissan          Nissan   NaN
19511         Nissan          Nissan   NaN
19524         Nissan          Nissan   NaN
19528         Nissan          Nissan   NaN
19540         Nissan          Nissan   NaN
19551         Nissan          Nissan   NaN
21312           Ford            Ford   NaN
21317           Ford            Ford   NaN
21333           Ford            Ford   NaN
21335           Ford            Ford   NaN
21338           Ford            Ford   NaN
21349           Ford            Ford   NaN
21350           Ford            Ford   NaN
21365           Ford            Ford   NaN
21372           Ford            Ford   NaN
21378           Ford            Ford   NaN
21385           Ford            Ford   NaN
21386           Ford            Ford   NaN
21393           Ford            Ford   NaN
21454           Ford            Ford   NaN
21461           Ford            Ford   NaN
21670           Ford            Ford   NaN
21927           Ford            Ford   NaN
21952           Ford            Ford   NaN
22176           Ford            Ford   NaN
23127        Hyundai         Hyundai   NaN
24019        Hyundai         Hyundai   NaN
24045        Hyundai         Hyundai   NaN
24046        Hyundai         Hyundai   NaN
24052        Hyundai         Hyundai   NaN
24063        Hyundai         Hyundai   NaN
24095        Hyundai         Hyundai   NaN
24124        Hyundai         Hyundai   NaN
24502        Hyundai         Hyundai   NaN
24503        Hyundai         Hyundai   NaN
24519        Hyundai         Hyundai   NaN
24611        Hyundai         Hyundai   NaN
24612        Hyundai         Hyundai   NaN
24656        Hyundai         Hyundai   NaN
26004          Volvo           Volvo   NaN
26317          Volvo           Volvo   NaN
26378          Volvo           Volvo   NaN
26384          Volvo           Volvo   NaN
26434          Volvo           Volvo   NaN
26439          Volvo           Volvo   NaN
26477          Volvo           Volvo   NaN
26523          Volvo           Volvo   NaN
26538          Volvo           Volvo   NaN
26553          Volvo           Volvo   NaN
26559          Volvo           Volvo   NaN
26609          Volvo           Volvo   NaN
26614          Volvo           Volvo   NaN
26652          Volvo           Volvo   NaN
26698          Volvo           Volvo   NaN
26713          Volvo           Volvo   NaN
26835          Volvo           Volvo   NaN
26851          Volvo           Volvo   NaN
26893          Volvo           Volvo   NaN
27224          Volvo           Volvo   NaN
27240          Volvo           Volvo   NaN
27281          Volvo           Volvo   NaN

In [40]:
# pd.set_option('display.max_colwidth', None)
# pd.reset_option('display.max_colwidth')
df.iloc[162]

make_model                                                    Mercedes-Benz
short_description                                 Classe A 1.9 116ch A 180 d
make                                                           Mercedes-Benz
model                                                                    NaN
location                           9 boulevard Jules Ferry,  75011 Paris, FR
price                                                               30490.00
body_type                                                            Compact
type                                                                    Used
doors                                                                   5.00
warranty                                                                 NaN
mileage                                                             28539.00
gearbox                                                               Manual
fuel_type                                                             Diesel
seller                                                                Dealer
seats                                                                   5.00
engine_size                                                          1900.00
gears                                                                   6.00
co_emissions                                                          134.00
drivetrain                                                             Front
cylinders                                                               4.00
comfort_&_convenience      Air conditioning, Cruise control, Seat heating...
entertainment_&_media      Bluetooth, Digital cockpit, Digital radio, Rad...
safety_&_security          Driver-side airbag, Isofix, LED Daytime Runnin...
extras                                                          Summer tyres
empty_weight                                                         1460.00
full_service_history                                                      No
upholstery                                                               NaN
previous_owner                                                          1.00
energy_efficiency_class                                                  NaN
age                                                                     1.00
power_kW                                                               85.00
power_hp                                                              116.00
cons_avg                                                                0.00
cons_city                                                                NaN
cons_country                                                             NaN
Name: 162, dtype: object

In [41]:
# Let's define models and extract them from "short_description" feature
model_pattern = '(Mitecki)|(BJ40)|(Business)|(1300)|(TURBO)|(bj 42)|(4cv)|(B 220)|(E 63)|(S 580e)|(SL 43)|(EDITION 1)|(A 160)|(GLE 63)|(C 63)|(C 300)|(C 180)|(A 200)|(C 200)|(A 180)|(A 180)|(Clase GLK)|(Clase SL)|(ANDERE)|(220)|(E 500)|(GLA 250)|(4Matic)|(C 43)|(200CDI)|(AMG GT)|(AMG Autom)|(AMG-Night)|(4M)|(2.0 CDTi)|(1.4 Turbo)|(1.4 S/S)|(1.4 T)|(Cabrio 1.4)|(Cabrio 1.6)|(Cabrio 2.0)|(Olympia)|(Astra)|(Adam)|(i30)|(Twizy)|(Alpine)|(Zen)|(Spider)|(Intens)|(COUPE)|(Cabriolet)|(124 Spider)|(Qubo)|(Ultimate AWD)|(1st Edition AWD)|(240 Z)|(Buckel)|(CRDI)|(RS200)|(SPYDER)|(GR Supra)|(2,0 T-Bar)|(1.8)|(Mach E)|(370 Z)|(Zagato)|(Tornado)|(Essential)|(1100D)|(Topolino Lotus)|(850)|(Neuer 500)|(124 Spyder)|(R.S. Line)|(Blue dCi)|(1500)|(Coupè)|(201)|(Berline|(Berlina)|(403)|(600)|(850)|(124)|(128 sport)|(Cupra)|(COMFORT TCe)|(Abarth)|(Coupé)|(X-MODE)|(Family Active)|(LJ70)|(Auris Touring Sports)|(RAV)|(Cabrio)|(T-Bird)|(MUSTANG)|(RAPTOR)|(GALAXIE SUNLINER)|(HOT ROD)|(Spaceback)|(Datsun)|(Skyline)|(Roadster)|(1.0 T-GDI)|(Mild-Hybrid)|(BAYON)|(I30N)|(P 1800 E)|(P1800E)|(P1800)|(2.4 Momentum)|(PV544 Sport)|(444))'

# Let's create a new feature named "extracted_models" using model_pattern
df["extracted_models"] = (df["short_description"].str.extract(model_pattern, flags=re.IGNORECASE)).bfill(axis=1)[0]

# let's explore which "make_model", "make", and "model" have NaN values
df[df["model"].isna()][['make_model', 'make', 'model', "extracted_models", "short_description"]]

,make_model,make,model,extracted_models,short_description
162,Mercedes-Benz,Mercedes-Benz,NaN,A 180,Classe A 1.9 116ch A 180 d
184,Mercedes-Benz,Mercedes-Benz,NaN,A 180,Classe A 1.5 109ch A 180 CDI BlueEfficiency
186,Mercedes-Benz,Mercedes-Benz,NaN,A 180,Classe A 1.5 116ch A 180 d
211,Mercedes-Benz,Mercedes-Benz,NaN,A 160,Classe A 1.5 90ch A 160 CDI / d
213,Mercedes-Benz,Mercedes-Benz,NaN,A 180,Classe A 1.5 116ch A 180 d
226,Mercedes-Benz,Mercedes-Benz,NaN,A 160,Classe A 1.3 109ch A 160
319,Mercedes-Benz,Mercedes-Benz,NaN,Clase GLK,MERCEDES-BENZ Clase GLK Pequeño Automático de 5
427,Mercedes-Benz,Mercedes-Benz,NaN,SL 43,SL 43 DIGITAL LIGHT+BURMESTER+DISTRO+HUD+MEMORY
442,Mercedes-Benz,Mercedes-Benz,NaN,Clase SL,MERCEDES-BENZ Clase SL Descapotable Automático d
471,Mercedes-Benz,Mercedes-Benz,NaN,ANDERE,ANDERE 43 Premium-Navi*360°Ka.*AIRSCARF
474,Mercedes-Benz,Mercedes-Benz,NaN,AMG-Night,AMG-Night MBUX+360°+Distronic+DIG-LED
608,Mercedes-Benz,Mercedes-Benz,NaN,ANDERE,ANDERE AMG Night+AIRSCARF+DISTRONIC+DIGITAL-LIGHT
642,Mercedes-Benz,Mercedes-Benz,NaN,C 180,C 180 Cabrio 9G-TRONIC AMG Line
643,Mercedes-Benz,Mercedes-Benz,NaN,C 200,C 200 Cabrio 9G-TRONIC AMG Line
651,Mercedes-Benz,Mercedes-Benz,NaN,220,220 d AMG Line+Alcantara+MulitBeamLED+Keyless
766,Mercedes-Benz,Mercedes-Benz,NaN,C 63,C 63 S AMG Cabrio *AMG-DRIVERS*PERF-ABGAS*VOLL*
856,Mercedes-Benz,Mercedes-Benz,NaN,E 500,E 500 AMG-Paket Harman Kardon APS Comand
861,Mercedes-Benz,Mercedes-Benz,NaN,AMG GT,AMG GT S E AMG PERFORMANCE grau magno HUD+CARBON
922,Mercedes-Benz,Mercedes-Benz,NaN,GLE 63,GLE 63 4MATIC Coupé LED*Abst-Tempo*360 Grad*No...
1229,Mercedes-Benz,Mercedes-Benz,NaN,ANDERE,ANDERE AMG UNTERBODEN GESTRAHLT KONSERVIERT/SHZ
1275,Mercedes-Benz,Mercedes-Benz,NaN,GLA 250,-Klasse GLA 250 Urban 4Matic Xenon Pano AHK Alu 1
1294,Mercedes-Benz,Mercedes-Benz,NaN,GLE 63,GLE 63 4MATIC Coupé LED*Abst-Tempo*360 Grad*No...
1818,Mercedes-Benz,Mercedes-Benz,NaN,C 43,C -Klasse T-Modell C 43 AMG 4Matic T
1972,Mercedes-Benz,Mercedes-Benz,NaN,C 300,C 300 e T 9G AMG*Pano*Distronic*Digital-Light*...
2033,Mercedes-Benz,Mercedes-Benz,NaN,E 63,E 63 AMG E 63 S AMG 4M+ MBUXHighE+PD+Burm+Mbea...
2114,Mercedes-Benz,Mercedes-Benz,NaN,4M,e 4M L AMG-CHAUFFEUR-PANO-EXKLUSIV PAKET
2120,Mercedes-Benz,Mercedes-Benz,NaN,AMG Autom,AMG Autom. Leder ACC Xenon VOLL
2184,Mercedes-Benz,Mercedes-Benz,NaN,S 580e,S 580e 4M L 9G*AMG*Chauffeur*Pano*Digital-Light*
2232,Mercedes-Benz,Mercedes-Benz,NaN,EDITION 1,+ EDITION 1-HEADUP-PANO-AIRMATIC-360°
2335,Mercedes-Benz,Mercedes-Benz,NaN,B 220,-Klasse B 220 d Progressive Panorama Kamera AHK
2371,Mercedes-Benz,Mercedes-Benz,NaN,4M,4M EDITION ONE AMG-DISTR-PREMIUM-PANO-360°
2914,Opel,Opel,NaN,2.0 CDTi,2.0 CDTi S/S 165 CV Excellence
2918,Opel,Opel,NaN,2.0 CDTi,2.0 CDTi S/S 165 CV Excellence
2920,Opel,Opel,NaN,Cabrio 1.6,Cabrio 1.6T S&S Excellence Aut.
2921,Opel,Opel,NaN,1.4 Turbo,1.4 Turbo Excellence
2923,Opel,Opel,NaN,1.4 T,1.4 T S/S Excellence
2924,Opel,Opel,NaN,1.4 Turbo,1.4 Turbo Excellence
2925,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2928,Opel,Opel,NaN,Cabrio 1.6,Cabrio 1.6T S&S Excellence Aut.
2929,Opel,Opel,NaN,Cabrio 1.6,Cabrio 1.6T S&S Excellence Aut.
2930,Opel,Opel,NaN,1.4 Turbo,1.4 Turbo Excellence
2931,Opel,Opel,NaN,1.4 Turbo,1.4 Turbo Excellence
2933,Opel,Opel,NaN,1.4 T,1.4 T S/S Excellence
2936,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2939,Opel,Opel,NaN,1.4 Turbo,1.4 Turbo Excellence
2940,Opel,Opel,NaN,Cabrio 1.6,Cabrio 1.6T S&S Excellence
2941,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2942,Opel,Opel,NaN,2.0 CDTi,2.0 CDTi S/S 165 CV Excellence
2945,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2946,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2947,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2948,Opel,Opel,NaN,Cabrio 2.0,Cabrio 2.0CDTi S&S Excellence 165
2949,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2950,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2951,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2955,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2956,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2957,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2958,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2959,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2961,Opel,Opel,NaN,1.4 T,1.4 T S/S Excellence
2962,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2963,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2964,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2965,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2966,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2967,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2968,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2969,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2970,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2971,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2972,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2973,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2975,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2976,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2977,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2978,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2979,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2980,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2981,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2982,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2984,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2986,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2987,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2988,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2989,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2990,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2992,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2993,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2994,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2995,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2996,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2997,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2998,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
2999,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3000,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3001,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3002,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3003,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3004,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3005,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3006,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3007,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3008,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3009,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3011,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3012,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3013,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3014,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3015,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3016,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3017,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3018,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3019,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3020,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3021,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3022,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3024,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3025,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3026,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3027,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3028,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3029,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3030,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3031,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3033,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3035,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3036,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3037,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3038,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3039,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3040,Opel,Opel,NaN,Cabrio 1.4,Cabrio 1.4T S&S Excellence
3358,Opel,Opel,NaN,Olympia,Olympia
3378,Opel,Opel,NaN,Astra,Astra H GTC Opc Line
5173,Renault,Renault,NaN,Twizy,Twizy 45 Intens Black Flex
5300,Renault,Renault,NaN,4cv,4cv * DECOUVRABLE
5301,Renault,Renault,NaN,Spider,Spider Sport
5383,Renault,Renault,NaN,Spider,Sport Spider 2.0 Windschutz-Scheibe 1. Hand
5583,Renault,Renault,NaN,Alpine,Alpine A110S *KLIMA*NAVI*PDC*
5599,Renault,Renault,NaN,NaN,III 2.0 16V 265 S&S RS
5633,Renault,Renault,NaN,Alpine,"Alpine A610 Turbo, 83tkm, perfekt gepflegt,Klima"
5717,Renault,Renault,NaN,TURBO,TURBO 1
6048,Renault,Renault,NaN,Zen,Zen 1.3 TCe LED+Navi+Keyless+Rückfahrkam.+PDC...
6071,Renault,Renault,NaN,Intens,Intens 1.3 TCe 140 EDC EU6d Winter-Paket
6087,Renault,Renault,NaN,Intens,Intens 1.3 TCe 140 EDC EU6d Winter-Paket
6096,Renault,Renault,NaN,R.S. Line,R.S. Line TCe 140 *Navi *360°*KLIMA
6101,Renault,Renault,NaN,Zen,Zen 1.3 TCe NAVI PDC BLUETOOTH
6594,Renault,Renault,NaN,Zen,Zen Energy dCi 81kW (110CV)
6678,Renault,Renault,NaN,Blue dCi,Blue dCi 200 EDC Initiale Paris
6699,Renault,Renault,NaN,Blue dCi,Blue dCi 190 EDC Initiale Paris
7778,Peugeot,Peugeot,NaN,NaN,<NULL
8043,Peugeot,Peugeot,NaN,201,201 '30
9114,Peugeot,Peugeot,NaN,403,403 Oldtimer/ Sammler /Rarität/Black Panther/
9120,Peugeot,Peugeot,NaN,Berline,Berline Bj.1956
9280,Peugeot,Peugeot,NaN,403,403 Berlina
9672,Fiat,Fiat,NaN,Neuer 500,Neuer 500 ICON 42kWh MJ22 ICON NAVI SITZHZG. M...
9902,Fiat,Fiat,NaN,124 Spyder,124 Spyder Lusso+LED+Navi+BOSE+Vollleder+Kamera
10000,Fiat,Fiat,NaN,Spider,PININFARINA Spider 2000
10009,Fiat,Fiat,NaN,Cabriolet,522L Cabriolet
10047,Fiat,Fiat,NaN,124 Spider,124 Spider 1.4 MultiAir Turbo Lusso Automatik
10217,Fiat,Fiat,NaN,124 Spider,124 Spider Lusso Leder Klima Rückfahrkamera 1 HA
10327,Fiat,Fiat,NaN,850,850c coupe
10328,Fiat,Fiat,NaN,128,128 A1 Coupe Moretti 1300
10370,Fiat,Fiat,NaN,124,"Fiat 124 BC1 , BJ. 1971"
10371,Fiat,Fiat,NaN,Coupe,2300 S Coupe
10373,Fiat,Fiat,NaN,1300,1300 coupe Raritat
10376,Fiat,Fiat,NaN,COUPÈ,2300 S COUPÈ
10384,Fiat,Fiat,NaN,Coupé,Coupé 20V Turbo Leder Radio CD Brembo 2. Hand...
10390,Fiat,Fiat,NaN,Coupè,Other Coupè 2.0 i.e. turbo 16V Plus
10406,Fiat,Fiat,NaN,Coupè,Coupè
10421,Fiat,Fiat,NaN,850,850 Coupè
10465,Fiat,Fiat,NaN,Coupé,2300 Coupé Ghia
10472,Fiat,Fiat,NaN,Coupè,Other Coupè 1.8 i.e. 16V
10493,Fiat,Fiat,NaN,850,*Fiat 850 Coupe´Serie 1*TÜV+H*
10523,Fiat,Fiat,NaN,1500,1500 VIGNALE 1Â° SERIE
10524,Fiat,Fiat,NaN,COUPE,COUPE
10549,Fiat,Fiat,NaN,COUPE,1100/103 TV COUPE' PININFARINA
10551,Fiat,Fiat,NaN,Abarth,Other 595-Abarth
10617,Fiat,Fiat,NaN,Topolino Lotus,"Action-Topolino Lotus Edition, Modellreihe 2022"
11097,Fiat,Fiat,NaN,Qubo,"Qubo 1,4 73 Dynamic"
11121,Fiat,Fiat,NaN,Qubo,"Qubo 1,3 16V Multijet II 75 Dynamic DPF AHV"
11214,Fiat,Fiat,NaN,1500,Fiat 1500 Familiare OSI
11569,Fiat,Fiat,NaN,1100D,1100D
11919,SEAT,SEAT,NaN,600,Seat 600
12221,SEAT,SEAT,NaN,850,850
12233,SEAT,SEAT,NaN,128,128 sport
12966,SEAT,SEAT,NaN,Cupra,Cupra DSG 4Dr. RfKamera/Fahrassist.-P.
14890,Skoda,Skoda,NaN,Spaceback,Spaceback Monte Carlo 1.0 TSI RFK/PDC/SHZ
15169,Dacia,Dacia,NaN,Business,Electric Business
15209,Dacia,Dacia,NaN,Essential,Essential NAVI+KAMERA+CARPLAY+KLIMA+LED
15210,Dacia,Dacia,NaN,Essential,Essential NAVI+KAMERA+CARPLAY+KLIMA+LED
16235,Dacia,Dacia,NaN,COMFORT TCe,COMFORT TCe 110 KLIMAAUTOMATIK+RADIO+ZV+
16531,Dacia,Dacia,NaN,1300,"1300, Oldtimer, H-Zulassung."
17109,Toyota,Toyota,NaN,LJ70,LJ70 2.4 Turbo D '92
17120,Toyota,Toyota,NaN,1.8,1.8-16v VVT-i
17121,Toyota,Toyota,NaN,Tornado,Tornado
17132,Toyota,Toyota,NaN,BJ40,BJ40 '78
17160,Toyota,Toyota,NaN,NaN,140 VVT-i SMT bva
17167,Toyota,Toyota,NaN,1.8,1.8 16v VVT-i Special edition semiautomaat
17211,Toyota,Toyota,NaN,GR Supra,"GR Supra Dynamic Kamera,Navigation, Sitzhzg."
17475,Toyota,Toyota,NaN,GR Supra,GR Supra 3.0 LEGEND
17477,Toyota,Toyota,NaN,"2,0 T-Bar","2,0 T-Bar GT-i 16V"
17694,Toyota,Toyota,NaN,X-MODE,X-MODE Comfort- und Technik-Paket
17873,Toyota,Toyota,NaN,RAV,RAV4 2.0i 4WD LMV 2 X DAK LPG APK
17890,Toyota,Toyota,NaN,bj 42,bj 42 4 marce asi
17943,Toyota,Toyota,NaN,RAV,"RAV 2.5 Hybrid PlugIn 4x4 Technik-P., Klimaaut..."
18111,Toyota,Toyota,NaN,Auris Touring Sports,Auris Touring Sports 1.6 D-4D Active
18122,Toyota,Toyota,NaN,Auris Touring Sports,Auris Touring Sports 1.8 Hybrid Active
18172,Toyota,Toyota,NaN,Family Active,1.5D 96kW (130CV) Family Active L1
19127,Nissan,Nissan,NaN,Roadster,"Roadster nur 29.990 km, Schaltgetriebe!"
19129,Nissan,Nissan,NaN,ROADSTER,3.7 i V6 24V 328 cv ROADSTER PACK
19132,Nissan,Nissan,NaN,Roadster,Roadster Pack
19285,Nissan,Nissan,NaN,NaN,NaN
19426,Nissan,Nissan,NaN,Skyline,Skyline r34 gtt/gtr umbau
19462,Nissan,Nissan,NaN,240 Z,240 Z
19468,Nissan,Nissan,NaN,370 Z,370 Z Nismo*Schale*BOSE*Kamera*DEUTSCH*SportAGA*
19511,Nissan,Nissan,NaN,Skyline,Skyline gtst
19524,Nissan,Nissan,NaN,Datsun,"Datsun 260 z voll restauriert , wie neu"
19528,Nissan,Nissan,NaN,Datsun,"Datsun 240 z voll restauriert , wie neu"
19540,Nissan,Nissan,NaN,Zagato,Autech Zagato Stelvio AZ1 900 kms d'origine
19551,Nissan,Nissan,NaN,Datsun,Datsun 280Z 2 +2 top Zustand restauriert
21312,Ford,Ford,NaN,SPYDER,INTERMECCANICA SPYDER ITALIA
21317,Ford,Ford,NaN,Roadster,Model A Roadster / Hot Rod
21333,Ford,Ford,NaN,Hot Rod,V8 Hot Rod*Typisiert*
21335,Ford,Ford,NaN,Mitecki,Mitecki Dragster Straßenzul. mit Bremsfallschirm
21338,Ford,Ford,NaN,Coupe,Steel 5-Window Coupe V8
21349,Ford,Ford,NaN,Cabrio,Oldtimer Ford V 8 Cabrio 4 türig
21350,Ford,Ford,NaN,T-Bird,T-Bird
21365,Ford,Ford,NaN,NaN,NaN
21372,Ford,Ford,NaN,ROADSTER,T ROADSTER open tourer *CABRIOLET* *1928*
21378,Ford,Ford,NaN,MUSTANG,MUSTANG V 5.0 V8 412 GT CALIFORNIA SPECIAL
21385,Ford,Ford,NaN,NaN,-
21386,Ford,Ford,NaN,HOT ROD,HOT ROD 5.3 V8 PONTIAC 326CI
21393,Ford,Ford,NaN,GALAXIE SUNLINER,GALAXIE SUNLINER XL 500
21454,Ford,Ford,NaN,Cabrio,Cabrio
21461,Ford,Ford,NaN,Hot rod,Hot rod 1932 V8 d'origine Carte grise française
21670,Ford,Ford,NaN,Coupe,3.8 V6 Coupe AUT AIRCO YOUNGTIMER MOOIE AUTO
21927,Ford,Ford,NaN,RS200,RS200
21952,Ford,Ford,NaN,RAPTOR,RAPTOR F 150 SUPERCREW PANO|LEDER|CAM|PDC
22176,Ford,Ford,NaN,Mach E,Mach E AWD Leder LED Navi Kurvenlicht e-Sitze ACC
23127,Hyundai,Hyundai,NaN,1.0 T-GDI,1.0 T-GDI iMT 48V Intro Plus LED Alu17 DAB
24019,Hyundai,Hyundai,NaN,1.0 T-GDI,1.0 T-GDI 48V Mild-Hybrid Intro Edition 100PS ...
24045,Hyundai,Hyundai,NaN,Mild-Hybrid,Select Mild-Hybrid 2WD 1.0 T-GDI EU6d Fernlich...
24046,Hyundai,Hyundai,NaN,1.0 T-GDI,1.0 T-GDI 48V Select Einparkhilfe/Tempomat/Alu...
24052,Hyundai,Hyundai,NaN,Mild-Hybrid,"Mild-Hybrid 2WD T-GDI EU6d Prime 1.0, Navigati..."
24063,Hyundai,Hyundai,NaN,Mild-Hybrid,"Mild-Hybrid 2WD T-GDI EU6d Prime 1.0, Navigati..."
24095,Hyundai,Hyundai,NaN,Mild-Hybrid,"Mild-Hybrid 2WD T-GDI EU6d Prime 1.0 , Navigat..."
24124,Hyundai,Hyundai,NaN,Mild-Hybrid,Select Mild-Hybrid 1.0 T-GDI Bluetooth - USB -...
24502,Hyundai,Hyundai,NaN,I30,I30 N Performance
24503,Hyundai,Hyundai,NaN,CRDI,CRDI 7 plazas 4x2 35 aniversario
24519,Hyundai,Hyundai,NaN,BAYON,BAYON 1.0 T-GDi Select #Winterpaket*
24611,Hyundai,Hyundai,NaN,I30,"I30N Perf M/T AHK Navip. N-Sportsitze,Leder,LED"
24612,Hyundai,Hyundai,NaN,I30,"I30N Perf M/T Navip. N-Sportsitze,Leder,LED"
24656,Hyundai,Hyundai,NaN,1.0 T-GDi,1.0 T-GDi IntroEdition+Navigation+Rückfahrkame...
26004,Volvo,Volvo,NaN,2.4 Momentum,2.4 Momentum *Youngtimer*
26317,Volvo,Volvo,NaN,2.4 Momentum,2.4 Momentum *Youngtimer*
26378,Volvo,Volvo,NaN,coupe,Amazon coupe
26384,Volvo,Volvo,NaN,P 1800 E,P 1800 E Automatik Restauriert
26434,Volvo,Volvo,NaN,PV544 Sport,PV544 Sport B18 B20 Buckelvolvo
26439,Volvo,Volvo,NaN,444,444 kattenrug
26477,Volvo,Volvo,NaN,P1800,VOLVO P1800 S
26523,Volvo,Volvo,NaN,Buckel,Buckel Volvo
26538,Volvo,Volvo,NaN,P1800E,P1800E
26553,Volvo,Volvo,NaN,coupe,Amazon coupe
26559,Volvo,Volvo,NaN,P 1800 E,P 1800 E Automatik Restauriert
26609,Volvo,Volvo,NaN,PV544 Sport,PV544 Sport B18 B20 Buckelvolvo
26614,Volvo,Volvo,NaN,444,444 kattenrug
26652,Volvo,Volvo,NaN,P1800,VOLVO P1800 S
26698,Volvo,Volvo,NaN,Buckel,Buckel Volvo
26713,Volvo,Volvo,NaN,P1800E,P1800E
26835,Volvo,Volvo,NaN,Ultimate AWD,Ultimate AWD Recharge Pure Electric Twin getön...
26851,Volvo,Volvo,NaN,1st Edition AWD,1st Edition AWD Recharge Pure Electric Twin
26893,Volvo,Volvo,NaN,1st Edition AWD,1st Edition AWD Recharge Pure Electric Twin
27224,Volvo,Volvo,NaN,Ultimate AWD,Ultimate AWD Recharge Pure Electric Twin getön...
27240,Volvo,Volvo,NaN,1st Edition AWD,1st Edition AWD Recharge Pure Electric Twin
27281,Volvo,Volvo,NaN,1st Edition AWD,1st Edition AWD Recharge Pure Electric Twin

In [42]:
df["model"].isna().sum()

# Before filling missing values in "model" feature, we have 276.

276

In [43]:
df['model'].fillna(df['extracted_models']).isnull().sum()

# When filling missing values in "model" feature with defined models we will have still 6 NaN values. We had 276 before.
# We have NOT filled NaN values in "model" feature yet

6

In [44]:
# df[df['make']=="Nissan"]["model"].value_counts()

In [45]:
# df['make_model'] = df['make_model'].str.strip()

In [46]:
df[['make_model', 'make', 'model', "extracted_models", "short_description"]]

,make_model,make,model,extracted_models,short_description
0,Mercedes-Benz A 160,Mercedes-Benz,A 160,NaN,CDi
1,Mercedes-Benz EQE 350,Mercedes-Benz,EQE 350,NaN,350+
2,Mercedes-Benz A 45 AMG,Mercedes-Benz,A 45 AMG,4Matic,S 4Matic+ 8G-DCT
3,Mercedes-Benz A 35 AMG,Mercedes-Benz,A 35 AMG,4Matic,4Matic+ 7G-DCT
4,Mercedes-Benz A 45 AMG,Mercedes-Benz,A 45 AMG,200CDI,200CDI BE Line 4M 7G-DCT
...,...,...,...,...,...
28625,Volvo S90,Volvo,S90,Business,T8 Twin Business Plus AWD Aut.
28626,Volvo S40,Volvo,S40,NaN,2.4i Momentum/ Airco/ NAP/ APK/ Elek. Ramen
28627,Volvo C30,Volvo,C30,NaN,1.6 D DRIVe Start/Stop R-design
28628,Volvo S90,Volvo,S90,BUSINESS,T5 AUT(8) MOMENTUM BUSINESS SCHUIFDAK 360GR CA...
28629,Volvo S80,Volvo,S80,NaN,2.9 Executive G. NETTE AUTO! LEER! NAVI! CRUIS...

In [47]:
# Let's explore the NaN values in both "model" and "extracted_models"

df[(df["model"].isna()) & (df["extracted_models"].isna())][['make_model', 'make', 'model', "extracted_models", "short_description"]]

      make_model     make model extracted_models       short_description
5599    Renault   Renault   NaN              NaN  III 2.0 16V 265 S&S RS
7778    Peugeot   Peugeot   NaN              NaN                   <NULL
17160    Toyota    Toyota   NaN              NaN       140 VVT-i SMT bva
19285    Nissan    Nissan   NaN              NaN                     NaN
21365      Ford      Ford   NaN              NaN                     NaN
21385      Ford      Ford   NaN              NaN                       -

In [48]:
# Let's find the row index number of NaN values in "model" feature
model_index_nan = df[df["model"].isna()][['make_model', 'make', 'model', "extracted_models", "short_description"]].index

model_index_nan

Index([  162,   184,   186,   211,   213,   226,   319,   427,   442,   471,
       ...
       26614, 26652, 26698, 26713, 26835, 26851, 26893, 27224, 27240, 27281],
      dtype='int64', length=276)

In [49]:
df['model'].fillna(df['extracted_models'], inplace=True)

display(df['model'].isnull().sum())
display(df['make_model'].isnull().sum())

6

0

In [50]:
df[df["model"].isna()][['make_model', 'make', 'model', "extracted_models", "short_description"]]

      make_model     make model extracted_models       short_description
5599    Renault   Renault   NaN              NaN  III 2.0 16V 265 S&S RS
7778    Peugeot   Peugeot   NaN              NaN                   <NULL
17160    Toyota    Toyota   NaN              NaN       140 VVT-i SMT bva
19285    Nissan    Nissan   NaN              NaN                     NaN
21365      Ford      Ford   NaN              NaN                     NaN
21385      Ford      Ford   NaN              NaN                       -

In [51]:
display(df.shape)  # Gives the shape of df BEFORE dropping NaN values in 'model'

df.dropna(subset=['model'], inplace=True)

display(df['model'].isnull().sum())  # Gives the total number of NaN values in 'model' AFTER dropping them 

display(df.shape)  # Gives the shape of df AFTER dropping NaN values in 'model'

(28630, 36)

0

(28624, 36)

In [52]:
# Let's combine "make" and "model" to create a new feature named "modified_make_model"

df["modified_make_model"] = df["make"] + " " + df["model"]
modified_make_model = df.pop("modified_make_model")
df.insert(1, 'modified_make_model', modified_make_model)
df["modified_make_model"]

0           Mercedes-Benz A 160
1         Mercedes-Benz EQE 350
2        Mercedes-Benz A 45 AMG
3        Mercedes-Benz A 35 AMG
4        Mercedes-Benz A 45 AMG
                  ...
28625                 Volvo S90
28626                 Volvo S40
28627                 Volvo C30
28628                 Volvo S90
28629                 Volvo S80
Name: modified_make_model, Length: 28624, dtype: object

In [53]:
# Let's compare the values in the columns of "make_model" and "modified_make_model"

df[["make_model", "modified_make_model"]]

                   make_model     modified_make_model
0         Mercedes-Benz A 160     Mercedes-Benz A 160
1       Mercedes-Benz EQE 350   Mercedes-Benz EQE 350
2      Mercedes-Benz A 45 AMG  Mercedes-Benz A 45 AMG
3      Mercedes-Benz A 35 AMG  Mercedes-Benz A 35 AMG
4      Mercedes-Benz A 45 AMG  Mercedes-Benz A 45 AMG
...                       ...                     ...
28625               Volvo S90               Volvo S90
28626               Volvo S40               Volvo S40
28627               Volvo C30               Volvo C30
28628               Volvo S90               Volvo S90
28629               Volvo S80               Volvo S80

[28624 rows x 2 columns]

In [54]:
df['modified_make_model'].fillna(df['make_model'], inplace=True)

display(df['model'].isnull().sum())
display(df['make_model'].isnull().sum())
display(df['modified_make_model'].isnull().sum())

0

0

0

In [55]:
df.iloc[model_index_nan]

,make_model,modified_make_model,short_description,make,model,location,price,body_type,type,doors,warranty,mileage,gearbox,fuel_type,seller,seats,engine_size,gears,co_emissions,drivetrain,cylinders,comfort_&_convenience,entertainment_&_media,safety_&_security,extras,empty_weight,full_service_history,upholstery,previous_owner,energy_efficiency_class,age,power_kW,power_hp,cons_avg,cons_city,cons_country,extracted_models
162,Mercedes-Benz,Mercedes-Benz A 180,Classe A 1.9 116ch A 180 d,Mercedes-Benz,A 180,"9 boulevard Jules Ferry, 75011 Paris, FR",30490.00,Compact,Used,5.00,NaN,28539.00,Manual,Diesel,Dealer,5.00,1900.00,6.00,134.00,Front,4.00,"Air conditioning, Cruise control, Seat heating...","Bluetooth, Digital cockpit, Digital radio, Rad...","Driver-side airbag, Isofix, LED Daytime Runnin...",Summer tyres,1460.00,No,NaN,1.00,NaN,1.00,85.00,116.00,0.00,NaN,NaN,A 180
184,Mercedes-Benz,Mercedes-Benz A 180,Classe A 1.5 109ch A 180 CDI BlueEfficiency,Mercedes-Benz,A 180,"9 boulevard Jules Ferry, 75011 Paris, FR",22790.00,Compact,Used,5.00,NaN,47638.00,Automatic,Diesel,Dealer,5.00,1500.00,7.00,102.00,Front,4.00,"Air conditioning, Cruise control, Start-stop s...","Bluetooth, CD player, MP3, Radio, Sound system","Driver-side airbag, Isofix, LED Daytime Runnin...","Shift paddles, Summer tyres",1395.00,No,NaN,1.00,NaN,5.00,80.00,109.00,3.90,NaN,NaN,A 180
186,Mercedes-Benz,Mercedes-Benz A 180,Classe A 1.5 116ch A 180 d,Mercedes-Benz,A 180,"9 boulevard Jules Ferry, 75011 Paris, FR",28790.00,Compact,Used,5.00,NaN,24045.00,Manual,Diesel,Dealer,5.00,1500.00,6.00,104.00,Front,4.00,"Air conditioning, Cruise control, Start-stop s...","Apple CarPlay, Bluetooth, Digital cockpit, Dig...","Driver-side airbag, Isofix, LED Daytime Runnin...",Summer tyres,1425.00,No,NaN,1.00,NaN,3.00,85.00,116.00,0.00,NaN,NaN,A 180
211,Mercedes-Benz,Mercedes-Benz A 160,Classe A 1.5 90ch A 160 CDI / d,Mercedes-Benz,A 160,"9 boulevard Jules Ferry, 75011 Paris, FR",18390.00,Compact,Used,5.00,NaN,66574.00,Manual,Diesel,Dealer,5.00,1500.00,6.00,102.00,Front,4.00,"Air conditioning, Cruise control, Start-stop s...","Bluetooth, CD player, MP3, Radio, Sound system","Driver-side airbag, Isofix, LED Daytime Runnin...",Winter tyres,1395.00,No,NaN,1.00,NaN,5.00,66.00,90.00,3.90,NaN,NaN,A 160
213,Mercedes-Benz,Mercedes-Benz A 180,Classe A 1.5 116ch A 180 d,Mercedes-Benz,A 180,"9 boulevard Jules Ferry, 75011 Paris, FR",28290.00,Compact,Used,5.00,NaN,22888.00,Manual,Diesel,Dealer,5.00,1500.00,6.00,104.00,Front,4.00,"Air conditioning, Cruise control, Start-stop s...","Bluetooth, Digital cockpit, Digital radio, Rad...","Driver-side airbag, Isofix, LED Daytime Runnin...",Summer tyres,1425.00,No,Full leather,1.00,NaN,3.00,85.00,116.00,0.00,NaN,NaN,A 180
226,Mercedes-Benz,Mercedes-Benz A 160,Classe A 1.3 109ch A 160,Mercedes-Benz,A 160,"9 boulevard Jules Ferry, 75011 Paris, FR",21690.00,Compact,Used,5.00,NaN,59199.00,Manual,Benzine,Dealer,5.00,1300.00,6.00,127.00,Front,4.00,"Air conditioning, Cruise control, Start-stop s...","Apple CarPlay, Bluetooth, Digital cockpit, Sou...","Driver-side airbag, Isofix, LED Daytime Runnin...",Summer tyres,1350.00,No,NaN,1.00,NaN,3.00,80.00,109.00,0.00,NaN,NaN,A 160
319,Mercedes-Benz,Mercedes-Benz Clase GLK,MERCEDES-BENZ Clase GLK Pequeño Automático de 5,Mercedes-Benz,Clase GLK,"ANTONIO MACHADO 34,, 02003 ALBACETE, ES",16500.00,Compact,Used,5.00,NaN,188000.00,Automatic,Diesel,Dealer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,10.00,125.00,170.00,NaN,NaN,NaN,Clase GLK
427,Mercedes-Benz,Mercedes-Benz SL 43,SL 43 DIGITAL LIGHT+BURMESTER+DISTRO+HUD+MEMORY,Mercedes-Benz,SL 43,"St.-Georgener-Straße 1, 79111 Freiburg, DE",159850.00,Convertible,Demonstration,2.00,NaN,2001.00,Automatic,Benzine,Dealer,4.00,1991.00,NaN,212.00,NaN,4.00,"360° camera, Air conditioning, Armrest, Automa...","Android Auto, Apple CarPlay, Bluetooth, Digita...","ABS, Adaptive Cruise Control, Alarm system, Bl...","Alloy wheels (21""), Ambient lighting, Automati...",1810.00,Yes,Full leather,1.00,unefficient,0.00,280.00,381.00,9.40,13.90,8.90,SL 43
442,Mercedes-Benz,Mercedes-Benz Clase SL,MERCEDES-BENZ Clase SL Descapotable Automático d,Mercedes-Benz,Clase SL,"Poligono industrial Zabal, Bj 44, 11300 La Lí...",12900.00,Convertible,Used,2.00,NaN,111258.00,Automatic,Benzine,Dealer,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,29.00,140.00,190.00,NaN,NaN,NaN,Clase SL
471,Mercedes-Benz,Mercedes-Benz ANDERE,ANDERE 43 Premium-Navi*360°Ka.*AIRSCARF,Mercedes-Benz,ANDERE,"Ziegelstraße 8, 01662 Meißen, DE",151099.00,Convertible,Demonstration,2.00,12.00,6000.00,Automatic,Benzine,Dealer,4.00,1991.00,NaN,212.00,NaN,4.00,"360° camera, Air conditioning, Automatic clima...","Android Auto, Apple CarPlay, Bluetooth, Digita...","ABS, Adaptive Cruise Control, Alarm system, Ce...","Ambient lighting, Automatically dimming interi...",1810.00,Yes,Full leather,1.00,unefficient,0.00,280.00,381.00,9.40,9.40,9.40,ANDERE
474,Mercedes-Benz,Mercedes-Benz AMG-Night,AMG-Night MBUX+360°+Distronic+DIG-LED,Mercedes-Benz,AMG-Night,"Schoemperlenstr. 14, 76185 Karlsruhe, DE",132999.00,Convertible,Demonstration,2.00,22.00,10000.00,Automatic,Benzine,Dealer,4.00,1991.00,9.00,NaN,NaN,NaN,"Air conditioning, Armrest, Automatic climate c...","Bluetooth, Digital radio, Hands-free equipment...","ABS, Adaptive Cruise Control, Adaptive headlig...","Alloy wheels (21""), Shift paddles, Sport packa...",NaN,Yes,Full leather,1.00,NaN,0.00,280.00,381.00,NaN,NaN,NaN,AMG-Night
608,Mercedes-Benz,Mercedes-Benz ANDERE,ANDERE AMG Night+AIRSCARF+DISTRONIC+DIGITAL-LIGHT,Mercedes-Benz,ANDERE,"Landshuter Str. 1, 94315 Straubing, DE",132880.00,Convertible,Demonstration,3.00,24.00,5000.00,Automatic,Benzine,Dealer,4.00,1991.00,NaN,NaN,NaN,4.00,"360° camera, Air conditioning, Automatic clima...","Android Auto, Apple CarPlay, Bluetooth, Digita...","ABS, Adaptive Cruise Control, Alarm system, Ce...","Alloy wheels, Ambient lighting, Automatically ...",1810.00,Yes,Full leather,1.00,NaN,0.00,280.00,381.00,NaN,NaN,NaN,ANDERE
642,Mercedes-Benz,Mercedes-Benz C 180,C 180 Cabrio 9G-TRONIC AMG Line,Mercedes-Benz,C 180,"Willi-Eichler-Straße 34, 37079 Göttingen, DE",56980.00,Convertible,Demonstration,2.00,12.00,3001.00,Automatic,Benzine,Dealer,4.00,1497.00,9.00,182.00,NaN,4.00,"Air conditioning, Armrest, Automatic climate c...","Android Auto, Apple CarPlay, Bluetooth, Digita...","ABS, Central door lock, Central door lock with...","Alloy wheels (19""), Ambient lighting, Automati...",1690.00,Yes,Cloth,1.00,unefficient,0.00,115.00,156.00,8.00,11.40,6.80,C 180
643,Mercedes-Benz,Mercedes-Benz C 200,C 200 Cabrio 9G-TRONIC AMG Line,Mercedes-Benz,C 200,"Sandershäuser Straße 110, 34123 Kassel, DE",56930.00,Convertible,Demonstration,2.00,12.00,3001.00,Automatic,Benzine,Dealer,4.00,1497.00,9.00,181.00,NaN,4.00,"Air conditioning, Armrest, Automatic climate c...","Android Auto, Apple CarPlay, Bluetooth, Digita...","ABS, Central door lock, Central door lock with...","Alloy wheels (19""), Ambient lighting, Automati...",1710.00,Yes,Cloth,1.00,efficient,0.00,135.00,184.00,8.00,11.00,6.90,C 200
651,Mercedes-Benz,Mercedes-Benz 220,220 d AMG Line+Alcantara+MulitBeamLED+Keyless,Mercedes-Benz,220,"Am Hornberg 9, 29614 Soltau, DE",44990.00,Convertible,Used,2.00,NaN,23152.00,Automatic,Diesel,Dealer,4.00,1950.00,NaN,126.00,Rear,4.00,"Air conditioning, Armrest, Automatic climate c...","Android Auto, Apple CarPlay, Bluetooth, Hands-...","ABS, Alarm system, Central door lock, Central ...","All season tyres, Alloy wheels (18""), Automati...",1735.00,Yes,Part leather,2.00,efficient,3.00,143.00,194.00,4.80,5.20,4.50,220
766,Mercedes-Benz,Mercedes-Benz C 63,C 63 S AMG Cabrio *AMG-DRIVERS*PERF-ABGAS*VOLL*,Mercedes-Benz,C 63,"Robert-Bosch-Str. 32, 72348 Rosenfeld, DE",76890.00,Convertible,Used,2.00,NaN,45630.00,Automatic,Benzine,Dealer,4.00,3982.00,7.00,208.00,NaN,NaN,"Air conditioning, Armrest, Cruise control, Ele...","Bluetooth, CD player, Hands-free equipment, In...","ABS, Adaptive Cruise Control, Adaptive headlig...","Alloy wheels, Ambient lighting, Automatically ...",1925.00,Yes,Full leather,NaN,unefficient,4.00,375.00,510.00,8.90,12.00,7.20,C 63
856,Mercedes-Benz,Mercedes-Benz E 500,E 500 AMG-Paket Harman Kardon APS Comand,Mercedes-Benz,E 500,"Industriestr. 8, 84337 Schönau, DE",35990.00,Coupe,Used,2.00,NaN,55000.00,Automatic,Benzine,Dealer,4.00,4663.00,7.00,258.00,Rear,8.00,"Air conditioning, Armrest, Automatic climate c...","Bluetooth, CD player, Hands-free equipment, MP...","ABS, Adaptive Cruise Control, Adaptive headlig...","Alloy wheels, Ambient lighting, Automatically ...",1795.00,Yes,Full leather,NaN,unefficient,10.00,300.00,408.00,10.90,16.10,7.80,E 500
861,Mercedes-Benz,Mercedes-Benz AMG GT,AMG GT S E AMG PERFORMANCE grau magno HUD+CARBON,Mercedes-Benz,AMG GT,"Altendorfer Straße 44 C, 45127 Essen, DE",214885.00,Coupe,Demonstration,4.00,24.00,6900.00,Automatic,NaN,Dealer,4.00,3982.00,NaN,180.00,4WD,8.00,"360° camera, Air suspension, Armrest, Automati...","Android Auto, Apple CarPlay, Bluetooth, Digita...","ABS, Adaptive Cruise Control, Adaptive headlig...","Alloy wheels, Ambient lighting, Automatically ...",2380.00,Yes,Full leather,1.00,efficient,0.00,470.00,639.00,7.90,NaN,NaN,AMG GT
922,Mercedes-Benz,Mercedes-Benz GLE 63,GLE 63 4MATIC Coupé LED*Abst-Tempo*360 Grad*No...,Mercedes-Benz,GLE 63,"Hauptstraße 24-25, 13127 Berlin Französisch-B...",60999.00,Coupe,Used,5.00,NaN,75400.00,Automatic,Benzine,Dealer,5.00,5461.00,NaN,278.00,4WD,NaN,"Air suspension, Armrest, Automatic climate con...","Bluetooth, Hands-free equipment, MP3, On-board...","ABS, Adaptive Cruise Control, Blind spot monit...","Alloy wheels, Ambient lighting, Automatically ...",2350.00,Yes,Full leather,4.00,unefficient,6.00,410.00,557.00,11.90,15.80,9.70,GLE 63
1229,Mercedes-Benz,Mercedes-Benz ANDERE,ANDERE AMG UNTERBODEN GESTRAHLT KONSERVIERT/SHZ,Mercedes-Benz,ANDERE,"Alte Bundesstr. 45, 71332 Waiblingen, DE",69500.00,Off-Road/Pick-up,Used,5.00,NaN,146000.00,Automatic,Benzine,Dealer,4.00,3606.00,NaN,0.00,4WD,NaN,"Air conditioning, Cruise control, Electrically...",On-board computer,"Central door lock, Power steering",Steel wheels,NaN,Yes,Full leather,3.00,NaN,25.00,200.00,272.00,0.00,NaN,NaN,ANDERE
1275,Mercedes-Benz,Mercedes-Benz GLA 250,-Klasse GLA 250 Urban 4Matic Xenon Pano AHK Alu 1,Mercedes-Benz,GLA 250,"Hessenstraße 1, 35625 Hüttenberg, DE",24770.00,Off-Road/Pick-up,Used,5.00,12.00,71200.00,Automatic,Benzine,Dealer,NaN,1991.00,7.00,152.00,4WD,NaN,"Air conditioning, Armrest, Automatic climate c...","CD player, On-board computer, Radio","ABS, Adaptive headlights, Bi-Xenon headlights,...","Alloy wheels, Ambient lighting, Automatically ...",1505.00,Yes,Part leather,4.00,unefficient,7.00,155.00,211.00,6.40,8.50,5.20,GLA 250
1294,Mercedes-Benz,Mercedes-Benz GLE 63,GLE 63 4MATIC Coupé LED*Abst-Tempo*360 Grad*No...,Mercedes-Benz,GLE 63,"Hauptstraße 24-25, 13127 Berlin Französisch-B...",60999.00,Off-Road/Pick-up,Used,5.00,NaN,75400.00,Automatic,Benzine,Dealer,5.00,5461.00,NaN,278.00,4WD,NaN,"Air suspension, Armrest, Automatic climate con...","Bluetooth, Hands-free equipment, MP3, On-board...","ABS, Adaptive Cruise Control, Blind spot monit...","Alloy wheels, Ambient lighting, Automatically ...",2350.00,Yes,Full leather,4.00,unefficient,6.00,410.00,557.00,11.90,15.80,9.70,GLE 63
1818,Mercedes-Benz,Mercedes-Benz C 43,C -Klasse T-Modell C 43 AMG 4Matic T,Mercedes-Benz,C 43,"Bahnhofstrasse 33, 27305 Bruchhausen-Vilsen, DE",35490.00,Station wagon,Used,4.00,NaN,84300.00,Automatic,Benzine,Dealer,5.00,2996.00,NaN,181.00,4WD,NaN,"360° camera, Air conditioning, Armrest, Automa...","Bluetooth, Hands-free equipment, On-board comp...","ABS, Adaptive Cruise Control, Alarm system, Ce...","Alloy wheels, Automatically dimming interior m...",NaN,Yes,Full leather,2.00,NaN,6.00,270.00,367.00,7.90,10.70,6.40,C 43
1972,Mercedes-Benz,Mercedes-Benz C 300,C 300 e T 9G AMG*Pano*Distronic*Digital-Light*...,Mercedes-Benz,C 300,"Helsinkistraße 1, 97424 Schweinfurt, DE",67500.00,Station wagon,Demonstration,5.00,12.00,9900.00,Automatic,Benzine,Dealer,5.00,1999.00,9.00,19.00,NaN,4.00,"360° camera, Air conditioning, Automatic clima...","Android Auto, Apple CarPlay, Bluetooth, Digita...","ABS, Adaptive Cruise Control, Adaptive headlig...","Alloy wheels (18""), Ambient lighting, Automati...",2120.00,Yes,Cloth,1.00,efficient,0.00,150.00,204.00,0.80,NaN,NaN,C 300
2033,Mercedes-Benz,Mercedes-Benz E 63,E 63 AMG E 63 S AMG 4M+ MBUXHighE+PD+Burm+Mbea...,Mercedes-Benz,E 63,"Rotthauser Str. 10, 45309 Essen, DE",115985.00,Sedan,Used,4.00,24.00,6511.00,Automatic,Benzine,Dealer,5.00,3982.00,NaN,267.00,4WD,8.00,"360° camera, Air suspension, Armrest, Automati...","Android Auto, Apple CarPlay, Bluetooth, Digita...","ABS, Adaptive Cruise Control, Adaptive headlig...","Alloy wheels, Ambient lighting, Automatically ...",2010.00,Yes,Full leather,2.00,unefficient,1.00,450.00,612.00,11.60,15.70,9.30,E 63
2114,Mercedes-Benz,Mercedes-Benz 4M,e 4M L AMG-CHAUFFEUR-PANO-EXKLUSIV PAKET,Mercedes-Benz,4M,"Gewerbestraße 19, 86707 Westendorf, DE",179995.00,Sedan,Demonstration,5.00,NaN,8000.00,Automatic,Benzine,Dealer,5.00,2999.00,9.00,187.00,4WD,6.00,"360° camera, Air conditioning, Air suspension,...","Android Auto, Apple CarPlay, Bluetooth, Digita...","ABS, Adaptive Cruise Control, Adaptive headlig...","Alloy wheels (20""), Ambient lighting, Automati...",2440.00,Yes,Full leather,1.00,efficient,0.00,380.00,517.00,NaN,NaN,NaN,4M
2120,Mercedes-Benz,Mercedes-Benz AMG Autom,AMG Autom. Leder ACC Xenon VOLL,Mercedes-Benz,AMG Autom,"Langwegerstr. 1, 49393 Lohne, DE",18890.00,Sedan,Used,4.00,NaN,88500.00,Automatic,Benzine,Dealer,5.00,5439.00,5.00,310.00,NaN,8.00,"Armrest, Automatic climate control, 2 zones, C...","CD player, MP3, On-board computer, Radio, Soun...","ABS, Adaptive Cruise Control, Alarm system, Bi...","Alloy wheels (18""), Automatically dimming inte...",1855.00,Yes,Full leather,NaN,NaN,21.00,265.00,360.00,13.00,19.60,9.20,AMG Autom
2184,Mercedes-Benz,Mercedes-Benz S 580e,S 580e 4M L 9G*AMG*Chauffeur*Pano*Digital-Light*,Mercedes-Benz,S 580e,"Randersackerer Strasse 54, 97072 Würzburg, DE",178890.00,Sedan,Demonstration,4.00,12.00,9900.00,Automatic,Benzine,Dealer,5.00,2999.00,9.00,21.00,4WD,6.00,"360° camera, Air conditioning, Air suspension,...","Android Auto, Apple CarPlay, Bluetooth, Digita...","ABS, Adaptive Cruise Control, Adaptive headlig...","Alloy wheels (20""), Ambient lighting, Automati...",2440.00,Yes,Full leather,1.00,efficient,0.00,270.00,367.00,0.90,NaN,NaN,S 580e
2232,Mercedes-Benz,Mercedes-Benz EDITION 1,+ EDITION 1-HEADUP-PANO-AIRMATIC-360°,Mercedes-Benz,EDITION 1,"Gewerbestraße 19, 86707 Westendorf, DE",103580.00,Sedan,Demonstration,5.00,NaN,8000.00,NaN,NaN,Dealer,5.00,NaN,NaN,NaN,Rear,NaN,"360° camera, Air conditioning, Air suspension,...","Android Auto, Apple CarPlay, Bluetooth, Digita...","ABS, Adaptive Cruise Control, Adaptive headlig...","Alloy wheels (21""), Ambient lighting, Automati...",2355.00,Yes,Full leather,1.00,NaN,0.00,215.00,292.00,NaN,NaN,NaN,EDITION 1
2335,Mercedes-Benz,Mercedes-Benz B 220,-Klasse B 220 d Progressive Panorama Kamera AHK,Mercedes-Benz,B 220,"Magistrale 2-4, 16244 Finowfurt, DE",35425.00,Sedan,Used,5.00,12.00,32949.00,Automatic,Diesel,Dealer,5.00,1950.00,NaN,0.00,Front,NaN,"360° camera, Air conditioning, Automatic clima...","Bluetooth, Digital cockpit, Hands-free equipme...","ABS, Alarm system, Blind spot monitor, Daytime...","Automatically dimming interior mirror, Headlig...",1545.00,Yes,Full leather,1.00,NaN,3.00,140.00,190.00,0.00,0.00,0.00,B 220
2371,Mercedes-Benz,Mercedes-Benz 4M,4M EDITION ONE AMG-DISTR-PREMIUM-PANO-360°,Mercedes-Benz,4M,"Gewerbestraße 19, 86707 Westendorf, DE",188008.00,Sedan,Used,5.00,NaN,21000.00,NaN,NaN,Dealer,5.00,NaN,NaN,NaN,4WD,NaN,"360° camera, Air conditioning, Air suspension,...","Android Auto, Apple CarPlay, Bluetooth, Digita...","ABS, Adaptive Cruise Control, Adaptive headlig...","Alloy wheels (21""), Ambient lighting, Automati...",2712.00,Yes,Full leather,NaN,NaN,1.00,385.00,523.00,NaN,NaN,NaN,4M
2914,Opel,Opel 2.0 CDTi,2.0 CDTi S/S 165 CV Excellence,Opel,2.0 CDTi,"Ctra. del Mig, 96,, 08097 L'Hospitalet de Llo...",9990.00,Convertible,Used,2.00,12.00,166345.00,Manual,Diesel,Dealer,NaN,2000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,8.00,121.00,165.00,5.20,6.30,4.60,2.0 CDTi
2918,Opel,Opel 2.0 CDTi,2.0 CDTi S/S 165 CV Excellence,Opel,2.0 CDTi,"Calle Comercio s/n del polígono El Florío, 18...",9990.00,Convertible,Used,2.00,12.00,166345.00,Manual,Diesel,Dealer,NaN,2000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,8.00,121.00,165.00,5.20,6.30,4.60,2.0 CDTi
2920,Opel,Opel Cabrio 1.6,Cabrio 1.6T S&S Excellence Aut.,Opel,Cabrio 1.6,"AVD. ARIAS DE VELASCO Nº 35, 29601 MARBELLA, ES",19900.00,Convertible,Used,2.00,12.00,24945.00,Automatic,Benzine,Dealer,4.00,1598.00,6.00,NaN,Front,4.00,"Air conditioning, Automatic climate control, C...","Bluetooth, CD player, MP3, On-board computer","ABS, Central door lock, Driver-side airbag, El...",NaN,1733.00,No,NaN,NaN,NaN,5.00,125.00,170.00,7.20,9.30,5.90,Cabrio 1.6
2921,Opel,Opel 1.4 Turbo,1.4 Turbo Excellence,Opel,1.4 Turbo,"CARRETERA FUENCARRAL A HORTALEZA 89 D, 28050 ...",15754.00,Convertible,Used,2.00,12.00,44944.00,Manual,Benzine,Dealer,NaN,1400.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,4.00,103.00,140.00,NaN,NaN,NaN,1.4 Turbo
2923,Opel,Opel 1.4 T,1.4 T S/S Excellence,Opel,1.4 T,"Ctra. del Mig, 96,, 08097 L'Hospitalet de Llo...",14990.00,Convertible,Used,2.00,12.00,66700.00,Manual,Benzine,Dealer,NaN,1400.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,6.00,103.00,140.00,6.40,7.90,5.50,1.4 T
2924,Opel,Opel 1.4 Turbo,1.4 Turbo Excellence,Opel,1.4 Turbo,"Plaza de Europa, S/N Centro Comercial Gran Tur...",15754.00,Convertible,Used,2.00,12.00,44944.00,Manual,Benzine,Dealer,NaN,1400.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,4.00,103.00,140.00,NaN,NaN,NaN,1.4 Turbo
2925,Opel,Opel Cabrio 1.4,Cabrio 1.4T S&S Excellence,Opel,Cabrio 1.4,"Rúa do Gandarón, 48, 36214 Vigo, ES",15421.00,Convertible,Used,2.00,12.00,62703.00,Manual,Benzine,Dealer,4.00,1362.00,6.00,NaN,Front,4.00,"Air conditioning, Automatic climate control, C...","Bluetooth, CD player, MP3, On-board computer","ABS, Central door lock, Driver-side airbag, El...",Alloy wheels,1701.00,No,NaN,NaN,NaN,7.00,103.00,140.00,6.30,7.80,5.40,Cabrio 1.4
2928,Opel,Opel Cabrio 1.6,Cabrio 1.6T S&S Excellence Aut.,Opel,Cabrio 1.6,"CALLE ALGUER Nº2, 08830 SANT BOI DE LLOBREGAT...",18550.00,Convertible,Used,2.00,12.00,52345.00,Automatic,Benzine,Dealer,4.00,1598.00,6.00,NaN,Front,4.00,"Air conditioning, Automatic climate control, C...","Bluetooth, CD player, MP3, On-board computer","ABS, Central door lock, Driver-side airbag, El...",NaN,1733.00,No,NaN,NaN,NaN,8.00,125.00,170.00,7.20,9.30,5.90,Cabrio 1.6
2929,Opel,Opel Cabrio 1.6,Cabrio 1.6T S&S Excellence Aut.,Opel,Cabrio 1.6,"C/ VILLA ESTHER Nº18 ALJETE MADRID, 28110 MAD...",18900.00,Convertible,Used,2.00,12.00,52345.00,Automatic,Benzine,Dealer,4.00,1598.00,6.00,NaN,Front,4.00,"Air conditioning, Automatic climate control, C...","Bluetooth, CD player, MP3, On-board computer","ABS, Central door lock, Driver-side airbag, El...",NaN,1733.00,No,NaN,NaN,NaN,8.00,125.00,170.00,7.20,9.30,5.90,Cabrio 1.6
2930,Opel,Opel 1.4 Turbo,1.4 Turbo Excellence,Opel,1.4 Turbo,"AVENIDA GARCÍA MORATO, S/N, 41001 SEVILLA, ES",15754.00,Convertible,Used,2.00,12.00,44944.00,Manual,Benzine,Dealer,NaN,1400.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,4.00,103.00,140.00,NaN,NaN,NaN,1.4 Turbo
2931,Opel,Opel 1.4 Turbo,1.4 Turbo Excellence,Opel,1.4 Turbo,"C. Arroyo Totalán, 36, 29730 Rincón de la Vic...",15754.00,Convertible,Used,2.00,12.00,44944.00,Manual,Benzine,Dealer,NaN,1400.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,4.00,103.00,140.00,NaN,NaN,NaN,1.4 Turbo

In [56]:
df['make_model'] = df['modified_make_model']
df.iloc[162]

make_model                                               Mercedes-Benz A 180
modified_make_model                                      Mercedes-Benz A 180
short_description                                 Classe A 1.9 116ch A 180 d
make                                                           Mercedes-Benz
model                                                                  A 180
location                           9 boulevard Jules Ferry,  75011 Paris, FR
price                                                               30490.00
body_type                                                            Compact
type                                                                    Used
doors                                                                   5.00
warranty                                                                 NaN
mileage                                                             28539.00
gearbox                                                               Manual
fuel_type                                                             Diesel
seller                                                                Dealer
seats                                                                   5.00
engine_size                                                          1900.00
gears                                                                   6.00
co_emissions                                                          134.00
drivetrain                                                             Front
cylinders                                                               4.00
comfort_&_convenience      Air conditioning, Cruise control, Seat heating...
entertainment_&_media      Bluetooth, Digital cockpit, Digital radio, Rad...
safety_&_security          Driver-side airbag, Isofix, LED Daytime Runnin...
extras                                                          Summer tyres
empty_weight                                                         1460.00
full_service_history                                                      No
upholstery                                                               NaN
previous_owner                                                          1.00
energy_efficiency_class                                                  NaN
age                                                                     1.00
power_kW                                                               85.00
power_hp                                                              116.00
cons_avg                                                                0.00
cons_city                                                                NaN
cons_country                                                             NaN
extracted_models                                                       A 180
Name: 162, dtype: object

In [57]:
# # Master, SPYDER, Torino, MUSTANG, Safrane, Modus, Master, Bipper, Espace, iOn, Tacoma, Zafira, Supra, C-Max, Capri, Mach, Night, Clase, COUPÈ, Coupè

# df[df["make_model"].str.contains("Toyota", flags=re.IGNORECASE, regex=True)][["make_model", "age", "mileage", "price", "body_type", "gearbox", "fuel_type", "seller", "seats", "engine_size", "gears", "drivetrain", "short_description"]]

In [58]:
# Let's fix some anomalies in the names of "make_model" 

df["make_model"].replace(["Ford SPYDER", "Ford MUSTANG", "Renault Grand Espace", "Fiat Spider", "Fiat Spider Europa", "Fiat 1300", "Opel Zafira Tourer", "Opel Zafira Life", "Toyota GR Supra", "Ford Grand C-Max", "Volvo P 1800 E", "Volvo P1800E", "Volvo coupe", "Toyota Auris Touring Sports", "Ford Mustang Mach-E\t", "Toyota Prius+", "Toyota 1.8", "Mercedes-Benz AMG-Night", "Mercedes-Benz Clase GLK", "Mercedes-Benz Clase SL", "Ford Hot Rod", "Ford HOT ROD", "Ford Hot rod", "Fiat 124 Coupè", "Fiat COUPÈ", "Fiat Coupè", "Toyota Corolla Verso", "Toyota Verso-S", "Renault Alpine", "Hyundai KONA Elektro", "Hyundai 1.0 T-GDi", "Hyundai H 350", "Hyundai H-1", "Hyundai ACCENT", "Hyundai CRDI", "Renault"],
                         ["Ford Mustang", "Ford Mustang", "Renault Espace", "Fiat 124 Spider", "Fiat 124 Spider", "Fiat 130", "Opel Zafira", "Opel Zafira", "Toyota Supra", "Ford C-Max", "Volvo P1800", "Volvo P1800", "Volvo Coupe", "Toyota Auris", "Ford Mustang Mach-E", "Toyota Prius", "Toyota MR 2", "Mercedes-Benz AMG GT", "Mercedes-Benz Clase", "Mercedes-Benz Clase", "Ford Hot Rod", "Ford Hot Rod", "Ford Hot Rod", "Fiat 124 Coupe", "Fiat 124 Coupe", "Fiat 124 Coupe", "Toyota Verso", "Toyota Verso", "Renault Alpine A110", "Hyundai KONA", "Hyundai 1.0 T-GDI", "Hyundai H", "Hyundai H", "Hyundai Accent", "Hyundai Accent", "Renault Megane"], inplace=True)

In [59]:
# Let's standardize all names in the "make_model", "make", and "model" columns by converting them to title case

df[["make_model", "make", "model"]] = df[["make_model", "make", "model"]].apply(lambda x: x.str.title())

In [60]:
# Let's drop unnecassary columns in the DataFrame

df.drop(["modified_make_model", "short_description", "extracted_models"], axis=1, inplace=True)
df.head()

,make_model,make,model,location,price,body_type,type,doors,warranty,mileage,gearbox,fuel_type,seller,seats,engine_size,gears,co_emissions,drivetrain,cylinders,comfort_&_convenience,entertainment_&_media,safety_&_security,extras,empty_weight,full_service_history,upholstery,previous_owner,energy_efficiency_class,age,power_kW,power_hp,cons_avg,cons_city,cons_country
0,Mercedes-Benz A 160,Mercedes-Benz,A 160,"P.I. EL PALMAR C/FORJA 6, 11500 PUERTO DE SAN...",16950.00,Compact,Used,5.00,24.00,120200.00,Manual,Diesel,Dealer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,6.00,NaN,NaN,NaN,NaN,NaN
1,Mercedes-Benz Eqe 350,Mercedes-Benz,Eqe 350,"APARTADO DE CORREOS 1032, 26140 LOGROÑO, ES",80900.00,Compact,Pre-registered,4.00,24.00,5000.00,Automatic,Electric,Dealer,5.00,1.00,9.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,0.00,215.00,292.00,NaN,NaN,NaN
2,Mercedes-Benz A 45 Amg,Mercedes-Benz,A 45 Amg,"PORT. TARRACO, MOLL DE LLEVANT, Nº 5, LOC. 6-8...",69900.00,Compact,Used,5.00,12.00,18900.00,Automatic,Benzine,Dealer,5.00,1991.00,8.00,NaN,4WD,4.00,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,2.00,310.00,421.00,8.40,10.90,5.80
3,Mercedes-Benz A 35 Amg,Mercedes-Benz,A 35 Amg,"Carrer de Provença, 31 Local, 8029 BARCELONA, ES",46990.00,Compact,Used,5.00,12.00,18995.00,Automatic,Benzine,Dealer,5.00,1991.00,7.00,NaN,4WD,4.00,"Air conditioning, Automatic climate control, P...",USB,"ABS, Central door lock, Driver-side airbag, El...",Sport seats,NaN,No,NaN,NaN,NaN,2.00,225.00,306.00,7.30,9.30,6.10
4,Mercedes-Benz A 45 Amg,Mercedes-Benz,A 45 Amg,"CARRIL ARAGONES 4, 30007 CASILLAS, ES",16800.00,Compact,Used,5.00,12.00,197000.00,Automatic,Diesel,Dealer,5.00,2143.00,7.00,NaN,4WD,4.00,"Air conditioning, Electrical side mirrors, Mul...","Bluetooth, CD player, MP3, USB","ABS, Central door lock, Driver-side airbag, El...",NaN,1545.00,No,NaN,NaN,NaN,7.00,100.00,136.00,4.90,5.70,4.40

In [61]:
first_looking("make_model", "make", "model")

COLUMN NAME    :  make_model
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  664
--------------------------------
make_model
Renault Megane      863
Seat Leon           787
Volvo V40           740
Dacia Sandero       730
Hyundai I30         709
                   ...
Fiat Cinquecento      1
Fiat Doblo            1
Fiat Multipla         1
Fiat 1100D            1
Volvo 244             1
Name: count, Length: 664, dtype: int64


COLUMN NAME    :  make
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  13
--------------------------------
make
Volvo            3659
Mercedes-Benz    2398
Opel             2385
Peugeot          2359
Renault          2350
Fiat             2338
Ford             2322
Nissan           2063
Toyota           2037
Hyundai          1867
Seat             1743
Skoda            1566
Dacia            1537
Name: count, dtype: int64


COLUMN NAME    :  model
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  674
--------------------------------
model
Megane       863
Leon         787
V40          740
Sandero      730
I30          709
            ...
C 320          1
Edition 1      1
S 580E         1
240 Z          1
244            1
Name: count, Length: 674, dtype: int64

## body_type

In [62]:
# Let's explore basic information about "body_type"

first_looking("body_type")

COLUMN NAME    :  body_type
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  6
--------------------------------
body_type
Station wagon       5448
Off-Road/Pick-up    5415
Compact             5387
Sedan               5043
Coupe               4007
Convertible         3324
Name: count, dtype: int64

In [63]:
# Let's standardize all names in the "body_type" column by converting them to title case

df['body_type'] = df['body_type'].str.title()

In [64]:
first_looking("body_type")

COLUMN NAME    :  body_type
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  6
--------------------------------
body_type
Station Wagon       5448
Off-Road/Pick-Up    5415
Compact             5387
Sedan               5043
Coupe               4007
Convertible         3324
Name: count, dtype: int64

<!-- <div style="background-color: #EBA6EC; padding: 10px; font-size: 23px; font-weight: bold;">
    Now it's time to examine and fill the missing values of each column/feature one by one:
</div> -->

## <p style="background-color:#E278E3; font-family:newtimeroman; color:#000000; font-size:121%; text-align:left; border-radius:10px 10px;">Now it's time to examine and fill the missing values of each column/feature one by one:</p>

In [65]:
df_isnull = df[df.columns[df.isnull().any()]]
df_isnull.columns

Index(['doors', 'warranty', 'mileage', 'gearbox', 'fuel_type', 'seats',
       'engine_size', 'gears', 'co_emissions', 'drivetrain', 'cylinders',
       'comfort_&_convenience', 'entertainment_&_media', 'safety_&_security',
       'extras', 'empty_weight', 'upholstery', 'previous_owner',
       'energy_efficiency_class', 'age', 'power_kW', 'power_hp', 'cons_avg',
       'cons_city', 'cons_country'],
      dtype='object')

In [66]:
# Let's explore the percentage of missing values in each column that exceeds the given 'limit'.

interact(show_missing_values, limit=(0, 100, 5))

interactive(children=(IntSlider(value=50, description='limit', step=5), Output()), _dom_classes=('widget-inter…

## engine_size

In [54]:
# Let's explore basic information about "engine_size"

first_looking("engine_size")

COLUMN NAME    :  engine_size
--------------------------------
per_of_nulls   :  % 4.9
num_of_nulls   :  1403
num_of_uniques :  467
--------------------------------
engine_size
1598.00     2099
999.00      2068
1969.00     1929
NaN         1403
1461.00     1110
1998.00      999
998.00       925
1199.00      866
1498.00      782
1997.00      665
1968.00      625
1984.00      580
1332.00      510
1798.00      473
1560.00      472
898.00       405
1499.00      397
1197.00      382
1242.00      373
1995.00      352
1991.00      351
1368.00      348
1248.00      322
2435.00      302
1600.00      252
2143.00      242
1364.00      226
1500.00      210
5038.00      204
3982.00      203
1950.00      202
1591.00      201
1956.00      195
2000.00      191
3498.00      175
1395.00      174
1987.00      159
1149.00      157
1796.00      156
3696.00      153
1200.00      153
1490.00      152
1497.00      149
1198.00      149
2400.00      148
2996.00      145
1999.00      145
1398.00      143
1794.00      137
1496.00      137
1618.00      128
1482.00      127
1582.00      125
2925.00      117
0.00         116
875.00       112
1587.00      110
1595.00      109
1596.00      106
2987.00      105
1400.00      104
2261.00      101
1000.00       99
1333.00       94
1685.00       92
1580.00       91
2521.00       91
1390.00       90
1362.00       90
4951.00       89
2999.00       86
1477.00       85
3799.00       76
1747.00       69
1229.00       63
2755.00       62
1300.00       60
1396.00       59
1870.00       55
1397.00       54
2319.00       53
900.00        53
2998.00       52
2300.00       52
1399.00       52
5461.00       51
1353.00       50
1386.00       48
1800.00       43
2401.00       43
2500.00       42
1597.00       41
2488.00       40
1422.00       39
1084.00       38
2494.00       38
2487.00       37
2198.00       35
1975.00       35
1769.00       34
1599.00       32
4663.00       31
1749.00       31
2199.00       31
1.00          30
1360.00       28
1686.00       28
1896.00       28
1329.00       27
1910.00       27
2946.00       23
2231.00       22
2230.00       21
1721.00       21
5000.00       21
2982.00       21
2960.00       20
1240.00       20
2720.00       20
899.00        20
2184.00       19
1341.00       19
3778.00       19
2800.00       19
1993.00       19
1469.00       19
3000.00       18
4966.00       18
2997.00       17
1330.00       17
3198.00       17
2299.00       16
1086.00       15
2200.00       15
1900.00       14
1700.00       13
2298.00       13
4606.00       13
1389.00       12
2.00          12
6208.00       12
5200.00       12
1299.00       11
2954.00       11
2953.00       10
1108.00       10
4700.00       10
1986.00       10
1124.00       10
2700.00       10
2442.00       10
2179.00       10
2792.00        9
2956.00        9
2656.00        9
4009.00        9
5439.00        9
3700.00        9
3720.00        9
1996.00        9
1468.00        8
2600.00        8
2497.00        8
2664.00        8
1781.00        7
1298.00        7
1762.00        7
1875.00        7
1764.00        7
2295.00        7
2148.00        7
3199.00        7
3731.00        7
2264.00        7
2498.00        7
2922.00        7
4600.00        7
1342.00        7
1388.00        7
3496.00        6
1495.00        6
843.00         6
4973.00        6
1576.00        6
1100.00        5
2478.00        5
3500.00        5
2188.00        5
3956.00        5
1905.00        5
1809.00        5
5513.00        5
1994.00        5
3724.00        4
2294.00        4
1120.00        4
3726.00        4
5162.00        4
5400.00        4
499.00         4
3200.00        4
1586.00        4
4000.00        4
2359.00        4
850.00         4
3800.00        4
2990.00        4
4949.00        4
5980.00        4
1658.00        4
1782.00        4
3606.00        4
767.00         3
2826.00        3
2279.00        3
5.00           3
1797.00        3
4414.00        3
4952.00        3
1990.00        3
2393.00        3
2544.00        3
964.00         3
2746.00        3
2947.00        3
1897.00        3
2799.00        3
1679.00        3
1761.00        3
2458.00        3
2717.00        3
3996.00        3
5600.00        3
2297.00        3
1979.00        3
1294.00        3
2721.00        3
1783.00        3
1948.00        3
2597.00        3
1955.00        3
6300.00        2
1795.00        2
1590.00        2
3600.00        2
3597.00        2
2798.00        2
2598.00        2
4742.00        2
4735.00        2
2171.00        2
5689.00        2
1635.00        2
5409.00        2
1221.00        2
4.00           2
2940.00        2
4942.00        2
1296.00        2
3878.00        2
5800.00        2
5032.00        2
2446.00        2
2784.00        2
1481.00        2
6400.00        2
1488.00        2
2499.00        2
750.00         2
4728.00        2
2995.00        2
2100.00        2
1116.00        2
5987.00        2
3235.00        2
2902.00        2
1301.00        2
2151.00        2
1337.00        2
652.00         2
3950.00        2
2034.00        2
1584.00        2
500.00         2
2992.00        2
1372.00        2
1589.00        2
1414.00        2
1699.00        2
1194.00        2
4200.00        2
2316.00        2
996.00         2
2932.00        2
4996.00        2
1290.00        2
1569.00        2
650.00         2
1709.00        2
903.00         2
1438.00        2
973.00         2
1992.00        1
2180.00        1
2043.00        1
3595.00        1
4948.00        1
3727.00        1
4601.00        1
5666.00        1
5766.00        1
4489.00        1
5812.00        1
5300.00        1
2985.00        1
4885.00        1
6276.00        1
54009.00       1
5768.00        1
2967.00        1
5700.00        1
5786.00        1
2685.00        1
3459.00        1
4605.00        1
2288.00        1
6387.00        1
2290.00        1
2699.00        1
3490.00        1
997.00         1
3793.00        1
1594.00        1
2966.00        1
2962.00        1
2306.00        1
2657.00        1
4800.00        1
5981.00        1
2351.00        1
300.00         1
2035.00        1
1799.00        1
3192.00        1
2461.00        1
2127.00        1
3300.00        1
2748.00        1
1954.00        1
6209.00        1
5083.00        1
3900.00        1
2276.00        1
3998.00        1
6294.00        1
4006.00        1
4886.00        1
5031.00        1
5686.00        1
8660.00        1
3797.00        1
289.00         1
19194.00       1
4736.00        1
6653.00        1
4995.00        1
6000.00        1
2263.00        1
2490.00        1
4660.00        1
3238.00        1
600.00         1
1739.00        1
549.00         1
1891.00        1
1245.00        1
2829.00        1
1616.00        1
2441.00        1
1647.00        1
2324.00        1
1270.00        1
1089.00        1
332.00         1
16597.00       1
1289.00        1
99900.00       1
1565.00        1
2993.00        1
2457.00        1
2975.00        1
16998.00       1
982.00         1
1988.00        1
1489.00        1
3220.00        1
1251.00        1
2155.00        1
2927.00        1
1581.00        1
1280.00        1
698.00         1
498.00         1
1122.00        1
1981.00        1
2518.00        1
2418.00        1
2402.00        1
1465.00        1
1295.00        1
1608.00        1
1756.00        1
1971.00        1
1592.00        1
847.00         1
1983.00        1
1150.00        1
2977.00        1
2384.00        1
4664.00        1
2740.00        1
2573.00        1
2935.00        1
2568.00        1
2484.00        1
2569.00        1
1585.00        1
2496.00        1
2991.00        1
2980.00        1
2464.00        1
2197.00        1
1974.00        1
5950.00        1
1241.00        1
2548.00        1
4146.00        1
4598.00        1
2398.00        1
1196.00        1
2145.00        1
2149.00        1
2565.00        1
988.00         1
1577.00        1
987.00         1
2933.00        1
1158.00        1
839.00         1
2645.00        1
20.00          1
1763.00        1
2959.00        1
1119.00        1
2969.00        1
2172.00        1
4500.00        1
5663.00        1
4164.00        1
3955.00        1
1235.00        1
3059.00        1
1281.00        1
2753.00        1
2495.00        1
200.00         1
3224.00        1
2473.00        1
Name: count, dtype: int64

In [55]:
# All NaN values are converted to dash/hyphen sign "-" to see them in the output of describe() and explore the hidden pattern

df["engine_size"].fillna("-", inplace=True)

**⚠️ Why do we need to convert ``Nan`` values into something else, "-" in our case❓**

**``describe()``** does **NOT** return anything for ``NaN`` values. If you have **``"Nan"``** at the column/feature you are interested in, you should replace these ``nan`` values with something else. In our case, we have replaced the **``"NaN"``** values with **``"-"``** so that we could implement the ``describe()`` method.

In [56]:
# let's explore if there is any pattern among ""make_model", "body_type", and "engine_size" by "price"

df.groupby(["make_model", "body_type","engine_size"]).price.describe()

                                                count     mean     std
make_model        body_type        engine_size
Dacia 1300        Sedan            1289.0        1.00  9999.00     NaN  \
Dacia Break       Station Wagon    -             1.00 20500.00     NaN
Dacia Business    Compact          0.0           1.00 19515.00     NaN
Dacia Comfort Tce Station Wagon    999.0         1.00 21799.00     NaN
Dacia Dokker      Compact          1461.0        1.00 11930.00     NaN
...                                               ...      ...     ...
Volvo Xc90        Off-Road/Pick-Up 2922.0        2.00 16990.00    0.00
                                   -             2.00 55900.00    0.00
                  Sedan            1969.0        2.00 48100.00  565.69
                                   -             1.00 84900.00     NaN
                  Station Wagon    1969.0        4.00 32750.00 3752.78

                                                    min      25%      50%
make_model        body_type        engine_size
Dacia 1300        Sedan            1289.0       9999.00  9999.00  9999.00  \
Dacia Break       Station Wagon    -           20500.00 20500.00 20500.00
Dacia Business    Compact          0.0         19515.00 19515.00 19515.00
Dacia Comfort Tce Station Wagon    999.0       21799.00 21799.00 21799.00
Dacia Dokker      Compact          1461.0      11930.00 11930.00 11930.00
...                                                 ...      ...      ...
Volvo Xc90        Off-Road/Pick-Up 2922.0      16990.00 16990.00 16990.00
                                   -           55900.00 55900.00 55900.00
                  Sedan            1969.0      47700.00 47900.00 48100.00
                                   -           84900.00 84900.00 84900.00
                  Station Wagon    1969.0      29500.00 29500.00 32750.00

                                                    75%      max
make_model        body_type        engine_size
Dacia 1300        Sedan            1289.0       9999.00  9999.00
Dacia Break       Station Wagon    -           20500.00 20500.00
Dacia Business    Compact          0.0         19515.00 19515.00
Dacia Comfort Tce Station Wagon    999.0       21799.00 21799.00
Dacia Dokker      Compact          1461.0      11930.00 11930.00
...                                                 ...      ...
Volvo Xc90        Off-Road/Pick-Up 2922.0      16990.00 16990.00
                                   -           55900.00 55900.00
                  Sedan            1969.0      48300.00 48500.00
                                   -           84900.00 84900.00
                  Station Wagon    1969.0      36000.00 36000.00

[3879 rows x 8 columns]

<div style="background-color: #ffeeba; padding: 10px; font-size: 16px; font-weight: bold;">
    The <code>engine_size</code> of cars changes by their <code>make_models</code> & <code>body_type</code> most of the time. So it is more beneficial to decide to fill missing values with <code>mode value</code> of corresponding group.
</div>

In [57]:
# Let's replace dash/hyphen sign "-" with np.nan

df["engine_size"].replace("-", np.nan, inplace=True)

def fill(df, group_col1, group_col2, col_name, method): # method can be either "mode" or "mean" or "median" or "ffill"
    
    '''Fills the missing values with "mode/mean/median/ffill/bfill method" according to double-stage grouping'''
    
    if method == "mode":
        for group1 in list(df[group_col1].unique()):
            for group2 in list(df[group_col2].unique()):
                cond1 = df[group_col1]==group1
                cond2 = (df[group_col1]==group1) & (df[group_col2]==group2)
                mode1 = list(df[cond1][col_name].mode())
                mode2 = list(df[cond2][col_name].mode())
                if mode2 != []:
                    df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[cond2][col_name].mode()[0])
                elif mode1 != []:
                    df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[cond1][col_name].mode()[0])
                else:
                    df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[col_name].mode()[0])

    elif method == "mean":
        df[col_name].fillna(df.groupby([group_col1, group_col2])[col_name].transform("mean"), inplace = True)
        df[col_name].fillna(df.groupby(group_col1)[col_name].transform("mean"), inplace = True)
        df[col_name].fillna(df[col_name].mean(), inplace = True)
        
    elif method == "median":
        df[col_name].fillna(df.groupby([group_col1, group_col2])[col_name].transform("median"), inplace = True)
        df[col_name].fillna(df.groupby(group_col1)[col_name].transform("median"), inplace = True)
        df[col_name].fillna(df[col_name].median(), inplace = True)
        
    elif method == "ffill":           
        for group1 in list(df[group_col1].unique()):
            for group2 in list(df[group_col2].unique()):
                cond2 = (df[group_col1]==group1) & (df[group_col2]==group2)
                df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(method="ffill").fillna(method="bfill")
                
        for group1 in list(df[group_col1].unique()):
            cond1 = df[group_col1]==group1
            df.loc[cond1, col_name] = df.loc[cond1, col_name].fillna(method="ffill").fillna(method="bfill")            
           
        df[col_name] = df[col_name].fillna(method="ffill").fillna(method="bfill")
    
    print("COLUMN NAME    : ", col_name)
    print("--------------------------------")
    print("per_of_nulls   : ", "%", round(df[col_name].isnull().sum()*100 / df.shape[0], 2))
    print("num_of_nulls   : ", df[col_name].isnull().sum())
    print("num_of_uniques : ", df[col_name].nunique())
    print("--------------------------------")
    print(df[col_name].value_counts(dropna = False).sort_index())

In [58]:
# This DEF will fill the missing values in the "engine_size" with the mode value based on "make_model" and "body_type"

fill(df, "make_model", "body_type", "engine_size", "mode")

COLUMN NAME    :  engine_size
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  467
--------------------------------
engine_size
0.00         328
1.00         111
2.00          12
4.00           2
5.00           3
20.00          1
200.00         1
289.00         1
300.00         1
332.00         1
498.00         1
499.00         5
500.00         2
549.00         1
600.00         1
650.00         2
652.00         2
698.00         1
750.00         2
767.00         6
839.00         2
843.00        10
847.00         1
850.00         4
875.00       113
898.00       432
899.00        20
900.00        53
903.00         4
964.00         3
973.00         2
982.00         1
987.00         2
988.00         1
996.00         2
997.00         1
998.00       953
999.00      2145
1000.00       99
1084.00       38
1086.00       15
1089.00        1
1100.00       13
1108.00       10
1116.00        2
1119.00        1
1120.00        4
1122.00        1
1124.00       10
1149.00      159
1150.00        2
1158.00        4
1194.00        2
1196.00        1
1197.00      384
1198.00      153
1199.00      930
1200.00      162
1221.00        2
1229.00       64
1235.00        1
1240.00       20
1241.00        1
1242.00      421
1245.00        1
1248.00      332
1251.00        1
1270.00        1
1280.00        1
1281.00        1
1289.00        1
1290.00        2
1294.00        3
1295.00        1
1296.00        2
1298.00        7
1299.00       11
1300.00       60
1301.00        2
1329.00       27
1330.00       17
1332.00      530
1333.00      105
1337.00        2
1341.00       19
1342.00        7
1353.00       50
1360.00       30
1362.00       90
1364.00      230
1368.00      359
1372.00        2
1386.00       48
1388.00        7
1389.00       12
1390.00       90
1395.00      176
1396.00       59
1397.00       54
1398.00      147
1399.00       52
1400.00      105
1414.00        2
1422.00       39
1438.00        2
1461.00     1144
1465.00        1
1468.00        8
1469.00       19
1477.00       88
1481.00        2
1482.00      127
1488.00        2
1489.00        1
1490.00      153
1495.00        6
1496.00      138
1497.00      154
1498.00      785
1499.00      413
1500.00      211
1560.00      479
1565.00        1
1569.00        2
1576.00        6
1577.00        1
1580.00      109
1581.00        1
1582.00      128
1584.00        4
1585.00        1
1586.00        4
1587.00      113
1589.00        2
1590.00        2
1591.00      203
1592.00        1
1594.00        1
1595.00      120
1596.00      106
1597.00       42
1598.00     2265
1599.00       33
1600.00      297
1608.00        2
1616.00        1
1618.00      128
1635.00        2
1647.00        1
1658.00        4
1679.00        3
1685.00       92
1686.00       28
1699.00        2
1700.00       16
1709.00        2
1721.00       21
1739.00        1
1747.00       71
1749.00       31
1756.00        1
1761.00        3
1762.00        7
1763.00        1
1764.00        7
1769.00       34
1781.00        7
1782.00        4
1783.00        3
1794.00      139
1795.00        2
1796.00      160
1797.00        3
1798.00      487
1799.00        1
1800.00       49
1809.00        5
1870.00       55
1875.00       12
1891.00        1
1896.00       28
1897.00        3
1900.00       15
1905.00        5
1910.00       27
1948.00        3
1950.00      203
1954.00        1
1955.00        3
1956.00      203
1968.00      631
1969.00     1967
1971.00        2
1974.00        1
1975.00       36
1979.00        3
1981.00        1
1983.00        1
1984.00      584
1986.00       10
1987.00      164
1988.00        1
1990.00        3
1991.00      356
1992.00        1
1993.00       19
1994.00        6
1995.00      357
1996.00        9
1997.00      676
1998.00     1054
1999.00      149
2000.00      211
2034.00        2
2035.00        1
2043.00        2
2100.00        2
2127.00        1
2143.00      251
2145.00        1
2148.00        7
2149.00        1
2151.00        2
2155.00        1
2171.00        2
2172.00        1
2179.00       11
2180.00        1
2184.00       19
2188.00        5
2197.00        1
2198.00       35
2199.00       34
2200.00       16
2230.00       21
2231.00       22
2261.00      101
2263.00        1
2264.00        7
2276.00        1
2279.00        3
2288.00        2
2290.00        1
2294.00        4
2295.00        7
2297.00        3
2298.00       13
2299.00       19
2300.00       52
2306.00        1
2316.00        2
2319.00       53
2324.00        1
2351.00        1
2359.00        4
2384.00        1
2393.00        3
2398.00        1
2400.00      155
2401.00       43
2402.00        1
2418.00        1
2435.00      309
2441.00        1
2442.00       11
2446.00        2
2457.00        1
2458.00        6
2461.00        1
2464.00        1
2473.00        1
2478.00        5
2484.00        1
2487.00       37
2488.00       40
2490.00        1
2494.00       40
2495.00        1
2496.00        2
2497.00        8
2498.00        7
2499.00        2
2500.00       50
2518.00        1
2521.00       91
2544.00        3
2548.00        1
2565.00        1
2568.00        1
2569.00        1
2573.00        1
2597.00        3
2598.00        2
2600.00        8
2645.00        1
2656.00        9
2657.00        1
2664.00       13
2685.00        1
2699.00        1
2700.00       18
2717.00        3
2720.00       25
2721.00        3
2740.00        1
2746.00        3
2748.00        1
2753.00        1
2755.00       75
2784.00        4
2792.00        9
2798.00        2
2799.00        3
2800.00       19
2826.00        3
2829.00        1
2902.00        3
2922.00        7
2925.00      119
2927.00        1
2932.00        2
2933.00        1
2935.00        1
2940.00        2
2946.00       24
2947.00        3
2953.00       10
2954.00       12
2956.00        9
2959.00        1
2960.00       23
2962.00        1
2966.00        1
2967.00        1
2969.00        1
2975.00        1
2977.00        1
2980.00        1
2982.00       21
2985.00        1
2987.00      106
2990.00        4
2991.00        1
2992.00        2
2993.00        1
2995.00        2
2996.00      147
2997.00       17
2998.00       53
2999.00       90
3000.00       18
3059.00        1
3192.00        1
3198.00       17
3199.00        7
3200.00        7
3220.00        1
3224.00        1
3235.00        2
3238.00        1
3300.00        1
3459.00        1
3490.00        1
3496.00        6
3498.00      180
3500.00        5
3595.00        1
3597.00        2
3600.00        2
3606.00        4
3696.00      157
3700.00        9
3720.00        9
3724.00        4
3726.00        4
3727.00        1
3731.00        7
3778.00       19
3793.00        1
3797.00        2
3799.00       77
3800.00        4
3878.00        3
3900.00        1
3950.00        5
3955.00        5
3956.00        5
3982.00      205
3996.00        3
3998.00        1
4000.00        4
4006.00        1
4009.00        9
4146.00        1
4164.00        1
4200.00        2
4414.00        3
4489.00        1
4500.00        1
4598.00        1
4600.00        7
4601.00        1
4605.00        1
4606.00       13
4660.00        1
4663.00       31
4664.00        1
4700.00       10
4728.00        2
4735.00        2
4736.00        1
4742.00        2
4800.00        1
4885.00        1
4886.00        1
4942.00        2
4948.00        1
4949.00       10
4951.00       89
4952.00        3
4966.00       19
4973.00        7
4995.00        1
4996.00        2
5000.00       21
5031.00        1
5032.00        2
5038.00      304
5083.00        1
5162.00        4
5200.00       12
5300.00        2
5400.00        4
5409.00        2
5439.00        9
5461.00       51
5513.00        5
5600.00        4
5663.00        1
5666.00        1
5686.00        1
5689.00        2
5700.00        2
5766.00        1
5768.00        1
5786.00        1
5800.00        2
5812.00        1
5950.00        1
5980.00        4
5981.00        1
5987.00        2
6000.00        1
6208.00       12
6209.00        1
6276.00        1
6294.00        1
6300.00        2
6387.00        1
6400.00        2
6653.00        1
8660.00        1
16597.00       1
16998.00       1
19194.00       1
54009.00       1
99900.00       1
Name: count, dtype: int64

## age

In [59]:
# Let's explore basic information about "age"

first_looking("age")

COLUMN NAME    :  age
--------------------------------
per_of_nulls   :  % 0.01
num_of_nulls   :  2
num_of_uniques :  83
--------------------------------
age
3.00       3667
4.00       3492
0.00       3085
1.00       2870
2.00       2473
5.00       2426
6.00       1486
7.00       1237
8.00        935
9.00        703
10.00       654
11.00       642
12.00       559
15.00       492
14.00       440
13.00       424
16.00       395
17.00       287
18.00       247
19.00       211
21.00       191
20.00       186
22.00       160
23.00       144
24.00        91
25.00        81
28.00        80
27.00        78
26.00        71
31.00        62
30.00        60
29.00        55
32.00        54
56.00        41
55.00        33
34.00        33
57.00        32
49.00        29
50.00        29
54.00        27
35.00        26
44.00        23
36.00        22
33.00        20
52.00        19
51.00        18
37.00        18
53.00        17
43.00        17
39.00        16
47.00        14
45.00        13
58.00        11
46.00        11
40.00        11
38.00        10
41.00         9
59.00         9
48.00         9
60.00         8
61.00         7
42.00         6
67.00         6
68.00         4
64.00         4
65.00         4
62.00         4
90.00         3
85.00         2
63.00         2
122.00        2
69.00         2
92.00         2
NaN           2
70.00         2
-3.00         1
89.00         1
76.00         1
66.00         1
-1.00         1
93.00         1
72.00         1
94.00         1
-180.00       1
Name: count, dtype: int64

In [60]:
# All NaN values are converted to dash/hyphen sign "-" to see them in the output of describe() and explore the hidden pattern

df['age'].fillna('-', inplace=True)

In [61]:
# let's explore if there is any pattern among ""age" by "mileage"

df.groupby("age").mileage.describe()

,count,mean,std,min,25%,50%,75%,max
age,,,,,,,,
-180.0,1.00,20926.00,NaN,20926.00,20926.00,20926.00,20926.00,20926.00
-3.0,1.00,59629.00,NaN,59629.00,59629.00,59629.00,59629.00,59629.00
-1.0,1.00,147985.00,NaN,147985.00,147985.00,147985.00,147985.00,147985.00
0.0,3084.00,3044.32,4698.15,0.00,10.00,406.00,5000.00,46500.00
1.0,2870.00,15009.23,12832.03,0.00,5806.00,12175.00,21493.50,94000.00
2.0,2473.00,30711.26,22596.14,1.00,16100.00,25681.00,39000.00,217000.00
3.0,3667.00,50955.46,39455.40,10.00,27319.50,44000.00,65166.00,1440000.00
4.0,3492.00,70204.33,44890.05,1.00,42000.00,64062.00,91500.00,1199900.00
5.0,2426.00,77484.79,40133.76,0.00,50000.00,72151.50,99699.25,415000.00
6.0,1486.00,83995.42,42973.69,1.00,53777.75,79999.50,108128.00,399000.00
7.0,1237.00,98250.39,45588.55,10.00,68000.00,93850.00,124883.00,523992.00
8.0,935.00,108955.46,56280.33,10.00,69873.00,102100.00,136109.50,546888.00
9.0,703.00,116788.03,53265.30,150.00,82000.00,112000.00,143281.00,383754.00
10.0,654.00,123084.03,55036.82,351.00,85032.50,117079.00,154693.00,406000.00
11.0,642.00,134643.42,62227.25,1021.00,94051.50,129981.50,172884.00,600000.00
12.0,559.00,147977.11,67955.45,6269.00,102635.00,141081.00,184737.50,667128.00
13.0,424.00,149548.22,67977.03,520.00,102750.00,142962.00,191242.00,400332.00
14.0,440.00,159193.55,67212.79,14162.00,116085.50,158438.00,194125.00,448914.00
15.0,492.00,163675.33,70389.44,2700.00,112448.75,160000.00,200000.00,433850.00
16.0,395.00,154184.00,61647.37,10800.00,115000.00,150000.00,199025.00,339000.00
17.0,287.00,160294.97,77156.50,139.00,106286.50,155000.00,203800.00,494457.00
18.0,247.00,174932.94,73793.42,10000.00,120428.50,166512.00,218491.00,461626.00
19.0,211.00,156258.81,66272.56,38270.00,98911.50,150000.00,199579.00,370000.00
20.0,186.00,154883.20,73669.68,4600.00,97907.25,156775.50,208511.50,361000.00
21.0,191.00,166095.01,75262.76,2000.00,115000.00,167363.00,207983.50,372008.00
22.0,160.00,148224.41,74415.08,7000.00,92744.75,144355.50,193150.00,600001.00
23.0,144.00,158723.42,88957.10,5000.00,92750.00,153850.00,211622.75,547000.00
24.0,91.00,130119.14,63423.22,5000.00,93200.00,125000.00,173600.00,256064.00
25.0,81.00,154737.32,82520.04,1.00,101000.00,150000.00,199000.00,350000.00
26.0,71.00,140526.28,68759.45,16000.00,96310.50,134504.00,170000.00,336634.00
27.0,78.00,138833.97,58265.54,12774.00,101912.00,133701.00,173054.25,339000.00
28.0,80.00,145438.04,69963.74,35600.00,93943.50,131754.00,185485.00,398000.00
29.0,55.00,150443.56,71014.32,9723.00,100100.00,151836.00,199500.00,350000.00
30.0,60.00,135084.50,68353.56,10000.00,87750.00,127377.50,182512.50,300000.00
31.0,62.00,150345.13,98111.08,10.00,76712.50,131876.00,203868.25,377733.00
32.0,54.00,146269.59,69476.18,900.00,100875.00,141917.50,186250.00,287064.00
33.0,20.00,104872.60,61901.90,2500.00,47126.00,119900.00,145112.50,208700.00
34.0,33.00,139495.55,79987.65,1.00,76000.00,123000.00,185180.00,302718.00
35.0,26.00,126674.96,54208.70,40000.00,86675.00,115043.00,148336.75,235964.00
36.0,22.00,178897.68,261746.67,1000.00,84511.50,143750.00,199517.75,1300000.00
37.0,18.00,112710.67,104722.54,2000.00,60500.00,94999.50,116482.75,457379.00
38.0,10.00,96806.90,57684.38,6000.00,49025.00,112034.50,144250.00,166000.00
39.0,16.00,94641.88,61222.87,1500.00,68600.00,90508.00,105682.75,262000.00
40.0,11.00,141104.18,127230.98,1.00,49680.00,147000.00,194814.50,431330.00
41.0,9.00,105145.00,60755.24,1.00,63715.00,119000.00,150000.00,196589.00
42.0,6.00,96055.17,15564.19,76072.00,82550.00,101929.50,108964.75,109000.00
43.0,17.00,108403.59,69128.07,300.00,51500.00,123000.00,150000.00,222606.00
44.0,23.00,118440.65,115268.78,10.00,44374.50,104498.00,159000.00,536388.00
45.0,13.00,86378.38,51218.31,596.00,50586.00,76025.00,135000.00,160000.00
46.0,11.00,69099.09,68456.07,1.00,9944.50,50000.00,130000.00,175000.00
47.0,14.00,87400.36,62188.46,1.00,45215.00,76311.00,138750.00,180559.00
48.0,9.00,56524.22,47047.16,1.00,15896.00,72500.00,95500.00,121000.00
49.0,29.00,76488.59,45976.78,2000.00,45000.00,73000.00,102301.00,191900.00
50.0,29.00,98134.97,72946.10,55.00,39500.00,85000.00,107933.00,260000.00
51.0,18.00,89645.17,46746.25,500.00,61533.75,90796.00,140013.50,146212.00
52.0,19.00,77385.79,52568.76,1000.00,38296.50,83400.00,111111.00,174000.00
53.0,17.00,59595.24,34806.01,1000.00,36000.00,49432.00,83500.00,150000.00
54.0,27.00,115241.67,256813.82,202.00,14062.50,45000.00,76500.00,1000000.00
55.0,33.00,73071.42,35229.43,20.00,50000.00,72850.00,94665.00,166221.00
56.0,41.00,85791.76,150315.47,2639.00,45220.00,55770.00,81480.00,999999.00
57.0,32.00,62834.69,39673.63,1.00,41585.00,54675.50,78915.00,163046.00
58.0,11.00,79000.27,28530.36,39000.00,50233.50,100000.00,100000.00,115000.00
59.0,9.00,55120.78,37724.10,10.00,46000.00,47470.00,82600.00,99999.00
60.0,8.00,90936.25,28639.23,59000.00,74675.00,79950.00,115415.00,132470.00
61.0,7.00,109524.29,65387.00,50000.00,57100.00,100000.00,151235.00,200000.00
62.0,4.00,52048.75,33253.27,18620.00,38960.00,45740.00,58828.75,98095.00
63.0,2.00,60603.50,55007.96,21707.00,41155.25,60603.50,80051.75,99500.00
64.0,4.00,46687.25,26288.55,24000.00,32724.75,39184.50,53147.00,84380.00
65.0,4.00,59412.50,52512.04,5650.00,23912.50,54000.00,89500.00,124000.00
66.0,1.00,41170.00,NaN,41170.00,41170.00,41170.00,41170.00,41170.00
67.0,6.00,23864.17,21335.71,1.00,12100.00,18042.00,32246.00,60000.00
68.0,4.00,64414.00,46946.14,1.00,44291.50,79177.50,99300.00,99300.00
69.0,2.00,46000.00,0.00,46000.00,46000.00,46000.00,46000.00,46000.00
70.0,2.00,65000.00,1414.21,64000.00,64500.00,65000.00,65500.00,66000.00
72.0,1.00,52466.00,NaN,52466.00,52466.00,52466.00,52466.00,52466.00
76.0,1.00,180000.00,NaN,180000.00,180000.00,180000.00,180000.00,180000.00
85.0,2.00,28000.00,0.00,28000.00,28000.00,28000.00,28000.00,28000.00
89.0,1.00,999999.00,NaN,999999.00,999999.00,999999.00,999999.00,999999.00
90.0,3.00,14700.00,11053.05,3500.00,9250.00,15000.00,20300.00,25600.00
92.0,2.00,30616.50,41554.54,1233.00,15924.75,30616.50,45308.25,60000.00
93.0,1.00,65515.00,NaN,65515.00,65515.00,65515.00,65515.00,65515.00
94.0,1.00,5000.00,NaN,5000.00,5000.00,5000.00,5000.00,5000.00
122.0,2.00,14985.50,21178.56,10.00,7497.75,14985.50,22473.25,29961.00
-,2.00,3175.00,963.08,2494.00,2834.50,3175.00,3515.50,3856.00

In [62]:
# Let's explore what the age is for dash/hyphen signs "-"

df[df["age"] == "-"]["mileage"].value_counts(dropna=False)

mileage
3856.00    1
2494.00    1
Name: count, dtype: int64

When it's needed, the condition could be improved according to following logic:

cond1 = (df['mileage'] < 10000)
cond2 = ((df['mileage'] >= 10000) & (df['mileage'] < 25000))
cond3 = ((df['mileage'] >= 25000) & (df['mileage'] < 40000))
cond4 = (df['mileage'] >= 40000)
...

df.loc[cond1,'age'] = df.loc[cond1,'age'].replace('-', 0)
df.loc[cond2,'age'] = df.loc[cond2,'age'].replace('-', 1)
df.loc[cond3,'age'] = df.loc[cond3,'age'].replace('-', 2)
df.loc[cond4,'age'] = df.loc[cond4,'age'].replace('-', 3)

**Let us use replace() function to fill missing values at "age" column with proper values.**

In [63]:
cond_age1 = (df['mileage'] < 10000)

df.loc[cond_age1, 'age'] = df.loc[cond_age1, 'age'].replace('-', 0)

In [64]:
df.groupby('age').mileage.mean()

age
-180.00    20926.00
-3.00      59629.00
-1.00     147985.00
0.00        3044.40
1.00       15009.23
2.00       30711.26
3.00       50955.46
4.00       70204.33
5.00       77484.79
6.00       83995.42
7.00       98250.39
8.00      108955.46
9.00      116788.03
10.00     123084.03
11.00     134643.42
12.00     147977.11
13.00     149548.22
14.00     159193.55
15.00     163675.33
16.00     154184.00
17.00     160294.97
18.00     174932.94
19.00     156258.81
20.00     154883.20
21.00     166095.01
22.00     148224.41
23.00     158723.42
24.00     130119.14
25.00     154737.32
26.00     140526.28
27.00     138833.97
28.00     145438.04
29.00     150443.56
30.00     135084.50
31.00     150345.13
32.00     146269.59
33.00     104872.60
34.00     139495.55
35.00     126674.96
36.00     178897.68
37.00     112710.67
38.00      96806.90
39.00      94641.88
40.00     141104.18
41.00     105145.00
42.00      96055.17
43.00     108403.59
44.00     118440.65
45.00      86378.38
46.00      69099.09
47.00      87400.36
48.00      56524.22
49.00      76488.59
50.00      98134.97
51.00      89645.17
52.00      77385.79
53.00      59595.24
54.00     115241.67
55.00      73071.42
56.00      85791.76
57.00      62834.69
58.00      79000.27
59.00      55120.78
60.00      90936.25
61.00     109524.29
62.00      52048.75
63.00      60603.50
64.00      46687.25
65.00      59412.50
66.00      41170.00
67.00      23864.17
68.00      64414.00
69.00      46000.00
70.00      65000.00
72.00      52466.00
76.00     180000.00
85.00      28000.00
89.00     999999.00
90.00      14700.00
92.00      30616.50
93.00      65515.00
94.00       5000.00
122.00     14985.50
Name: mileage, dtype: float64

In [65]:
first_looking("age")

COLUMN NAME    :  age
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  83
--------------------------------
age
3.0       3667
4.0       3492
0.0       3087
1.0       2870
2.0       2473
5.0       2426
6.0       1486
7.0       1237
8.0        935
9.0        703
10.0       654
11.0       642
12.0       559
15.0       492
14.0       440
13.0       424
16.0       395
17.0       287
18.0       247
19.0       211
21.0       191
20.0       186
22.0       160
23.0       144
24.0        91
25.0        81
28.0        80
27.0        78
26.0        71
31.0        62
30.0        60
29.0        55
32.0        54
56.0        41
55.0        33
34.0        33
57.0        32
49.0        29
50.0        29
54.0        27
35.0        26
44.0        23
36.0        22
33.0        20
52.0        19
37.0        18
51.0        18
43.0        17
53.0        17
39.0        16
47.0        14
45.0        13
40.0        11
58.0        11
46.0        11
38.0        10
48.0         9
59.0         9
41.0         9
60.0         8
61.0         7
67.0         6
42.0         6
68.0         4
65.0         4
64.0         4
62.0         4
90.0         3
122.0        2
85.0         2
63.0         2
70.0         2
92.0         2
69.0         2
89.0         1
-3.0         1
76.0         1
-1.0         1
93.0         1
66.0         1
-180.0       1
94.0         1
72.0         1
Name: count, dtype: int64

## mileage

In [66]:
# Let's explore basic information about "mileage"

first_looking("mileage")

COLUMN NAME    :  mileage
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  1
num_of_uniques :  14182
--------------------------------
mileage
10.00        586
1.00         172
50.00        133
100.00       119
5000.00      118
            ...
141589.00      1
59821.00       1
123500.00      1
29781.00       1
230047.00      1
Name: count, Length: 14183, dtype: int64

In [67]:
# Let's explore what the average mileage of the vehicles is by "age" 

df.groupby("age").mileage.mean()

age
-180.00    20926.00
-3.00      59629.00
-1.00     147985.00
0.00        3044.40
1.00       15009.23
2.00       30711.26
3.00       50955.46
4.00       70204.33
5.00       77484.79
6.00       83995.42
7.00       98250.39
8.00      108955.46
9.00      116788.03
10.00     123084.03
11.00     134643.42
12.00     147977.11
13.00     149548.22
14.00     159193.55
15.00     163675.33
16.00     154184.00
17.00     160294.97
18.00     174932.94
19.00     156258.81
20.00     154883.20
21.00     166095.01
22.00     148224.41
23.00     158723.42
24.00     130119.14
25.00     154737.32
26.00     140526.28
27.00     138833.97
28.00     145438.04
29.00     150443.56
30.00     135084.50
31.00     150345.13
32.00     146269.59
33.00     104872.60
34.00     139495.55
35.00     126674.96
36.00     178897.68
37.00     112710.67
38.00      96806.90
39.00      94641.88
40.00     141104.18
41.00     105145.00
42.00      96055.17
43.00     108403.59
44.00     118440.65
45.00      86378.38
46.00      69099.09
47.00      87400.36
48.00      56524.22
49.00      76488.59
50.00      98134.97
51.00      89645.17
52.00      77385.79
53.00      59595.24
54.00     115241.67
55.00      73071.42
56.00      85791.76
57.00      62834.69
58.00      79000.27
59.00      55120.78
60.00      90936.25
61.00     109524.29
62.00      52048.75
63.00      60603.50
64.00      46687.25
65.00      59412.50
66.00      41170.00
67.00      23864.17
68.00      64414.00
69.00      46000.00
70.00      65000.00
72.00      52466.00
76.00     180000.00
85.00      28000.00
89.00     999999.00
90.00      14700.00
92.00      30616.50
93.00      65515.00
94.00       5000.00
122.00     14985.50
Name: mileage, dtype: float64

In [68]:
df[df["mileage"].isna()][["make_model", "age", "mileage"]]

      make_model  age  mileage
10753  Fiat 500X 0.00      NaN

In [69]:
display(df["mileage"].mean())  # the average mileage of all vehicles
display(df[df["make_model"] == "Fiat 500X"]["mileage"].mean())   # the average mileage of all "Fiat 500X"
display(df[(df["make_model"] == "Fiat 500X") & (df["age"] == 0)]["mileage"].mean())   # the average mileage of all "Fiat 500X" at age of 0

72630.04873702966

49154.09333333333

1410.8163265306123

**Let us use transform() function to fill missing values at "mileage" column with "mean".**

In [70]:
df.groupby(["make_model", "age"]).mileage.transform("mean")

0       131346.00
1         7233.55
2        33156.82
3        36861.25
4       122055.50
           ...
28625    45138.56
28626   181000.00
28627   166912.96
28628    91159.74
28629   151462.33
Name: mileage, Length: 28624, dtype: float64

In [71]:
df["mileage"].fillna(df.groupby(["make_model", "age"]).mileage.transform("mean"), inplace=True)

In [72]:
df[df["mileage"].isna()][["age", "mileage"]]

Empty DataFrame
Columns: [age, mileage]
Index: []

In [73]:
df.loc[10753][["make_model", "age", "mileage"]]

make_model    Fiat 500X
age                0.00
mileage         1410.82
Name: 10753, dtype: object

**Using transform() function, we have filled missing values at "mileage" column with the "mean" of the each "age" group.**

In [74]:
first_looking("mileage")

COLUMN NAME    :  mileage
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  14183
--------------------------------
mileage
10.00        586
1.00         172
50.00        133
100.00       119
5000.00      118
            ...
141589.00      1
59821.00       1
123500.00      1
29781.00       1
230047.00      1
Name: count, Length: 14183, dtype: int64

## doors

In [75]:
# Let's explore basic information about "doors"

first_looking("doors")

COLUMN NAME    :  doors
--------------------------------
per_of_nulls   :  % 1.25
num_of_nulls   :  358
num_of_uniques :  6
--------------------------------
doors
5.00    17481
2.00     5520
4.00     3001
3.00     2257
NaN       358
6.00        5
1.00        2
Name: count, dtype: int64

<div style="background-color: #ffeeba; padding: 10px; font-size: 16px; font-weight: bold;">
    The <code>number of doors</code> of cars mostly changes by their <code>make_models</code> and <code>body_types</code>. So it's decided to fill missing values with <code>mode value</code> of corresponding group.
</div>

In [76]:
# This is the nested for loop where it's used in fill_mode(df, group_col1, group_col2, col_name) DEF to be generalized for all data

for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
        cond1 = df["make_model"]==group1
        cond2 = (df["make_model"]==group1) & (df["body_type"]==group2)
        mode1 = list(df[cond1]["doors"].mode())
        mode2 = list(df[cond2]["doors"].mode())
        if mode2 != []:
            df.loc[cond2, "doors"] = df.loc[cond2, "doors"].fillna(df[cond2]["doors"].mode()[0])
        elif mode1 != []:
            df.loc[cond2, "doors"] = df.loc[cond2, "doors"].fillna(df[cond1]["doors"].mode()[0])
        else:
            df.loc[cond2, "doors"] = df.loc[cond2, "doors"].fillna(df["doors"].mode()[0])

In [77]:
# df["doors"].value_counts(dropna=False)

first_looking("doors")

COLUMN NAME    :  doors
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  6
--------------------------------
doors
5.00    17638
2.00     5664
4.00     3012
3.00     2303
6.00        5
1.00        2
Name: count, dtype: int64

def fill_mode(df, group_col1, group_col2, col_name):
    
    for group1 in list(df[group_col1].unique()):
        for group2 in list(df[group_col2].unique()):
            cond1 = df[group_col1]==group1
            cond2 = (df[group_col1]==group1) & (df[group_col2]==group2)
            mode1 = list(df[cond1][col_name].mode())
            mode2 = list(df[cond2][col_name].mode())
            if mode2 != []:
                df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[cond2][col_name].mode()[0])
            elif mode1 != []:
                df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[cond1][col_name].mode()[0])
            else:
                df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[col_name].mode()[0])
    
    print("column name    : ", col_name)
    print("--------------------------------")
    print("per_of_nulls   : ", "%", round(df[col_name].isnull().sum()*100 / df.shape[0], 2))
    print("num_of_nulls   : ", df[col_name].isnull().sum())
    print("num_of_uniques : ", df[col_name].nunique())
    print("--------------------------------")
    print(df[col_name].value_counts(dropna = False))

In [78]:
# In fact there is no need to run this DEF since all NaNs manually were filled above by for nested loop

fill_mode(df, "make_model", "body_type", "doors")

column name    :  doors
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  6
--------------------------------
doors
5.00    17638
2.00     5664
4.00     3012
3.00     2303
6.00        5
1.00        2
Name: count, dtype: int64

# Method-2

# if we want to generalize this script, it may NOT work in every case because of the indexing of mode result
# Sometimes it may give different results comparing with solution of "for loop"

df["doors"].fillna(df.groupby(["make_model", "body_type"])["doors"].transform(lambda x : x.mode()), inplace = True)
df["doors"].fillna(df.groupby("make_model")["doors"].transform(lambda x : x.mode()[0]), inplace = True)
df["doors"].fillna(df["doors"].mode()[0], inplace = True)

df["doors"].value_counts(dropna=False)

5.000    17637
2.000     5669
4.000     3013
3.000     2304
6.000        5
1.000        2
Name: Nr_of_Doors, dtype: int64

## warranty

In [79]:
# Let's explore basic information about "warranty"

first_looking("warranty")

COLUMN NAME    :  warranty
--------------------------------
per_of_nulls   :  % 52.97
num_of_nulls   :  15161
num_of_uniques :  64
--------------------------------
warranty
NaN       15161
12.00      9544
24.00      1515
60.00       968
6.00        398
36.00       257
3.00        184
0.00        133
48.00        78
84.00        47
72.00        40
13.00        22
8.00         19
18.00        15
1.00         15
15.00        13
14.00        13
16.00        13
30.00        12
34.00        11
21.00        11
33.00        11
32.00         9
20.00         9
23.00         9
19.00         9
17.00         9
35.00         8
28.00         8
50.00         6
22.00         6
42.00         5
31.00         4
26.00         4
52.00         4
47.00         4
9.00          4
25.00         3
58.00         3
11.00         3
27.00         3
45.00         2
53.00         2
10.00         2
57.00         2
51.00         2
29.00         2
2.00          2
80.00         2
90.00         2
7.00          2
46.00         1
117.00        1
43.00         1
65.00         1
39.00         1
142.00        1
110.00        1
37.00         1
49.00         1
55.00         1
99.00         1
122.00        1
44.00         1
4.00          1
Name: count, dtype: int64

In [80]:
# All NaN values are converted to dash/hyphen sign "-" to see them in the output of describe() and explore the hidden pattern

df["warranty"].fillna("-", inplace=True)

In [81]:
# let's explore if there is any pattern among ""make_model" and "body_type" by "age"

df.groupby(["make_model", "body_type"])["age"].describe()

                                    count  unique   top  freq
make_model        body_type
Dacia 1300        Sedan              1.00    1.00 47.00  1.00
Dacia Break       Station Wagon      1.00    1.00  0.00  1.00
Dacia Business    Compact            1.00    1.00  1.00  1.00
Dacia Comfort Tce Station Wagon      1.00    1.00  0.00  1.00
Dacia Dokker      Compact            1.00    1.00  4.00  1.00
...                                   ...     ...   ...   ...
Volvo Xc70        Station Wagon     26.00    7.00  6.00  6.00
Volvo Xc90        Coupe              4.00    1.00  5.00  4.00
                  Off-Road/Pick-Up 199.00   15.00  5.00 40.00
                  Sedan              3.00    3.00  4.00  1.00
                  Station Wagon      4.00    1.00  6.00  4.00

[1287 rows x 4 columns]

In [82]:
# Because the dtype of "age" is string it's converted to floating point to examine it in detail 

df["age"] = df["age"].astype(float)

In [83]:
# let's explore if there is any pattern among ""make_model" and "body_type" by "age"

df.groupby(["make_model", "body_type"])["age"].describe()

                                    count  mean  std   min   25%   50%   75%
make_model        body_type
Dacia 1300        Sedan              1.00 47.00  NaN 47.00 47.00 47.00 47.00  \
Dacia Break       Station Wagon      1.00  0.00  NaN  0.00  0.00  0.00  0.00
Dacia Business    Compact            1.00  1.00  NaN  1.00  1.00  1.00  1.00
Dacia Comfort Tce Station Wagon      1.00  0.00  NaN  0.00  0.00  0.00  0.00
Dacia Dokker      Compact            1.00  4.00  NaN  4.00  4.00  4.00  4.00
...                                   ...   ...  ...   ...   ...   ...   ...
Volvo Xc70        Station Wagon     26.00  8.38 2.28  6.00  7.00  8.00  9.00
Volvo Xc90        Coupe              4.00  5.00 0.00  5.00  5.00  5.00  5.00
                  Off-Road/Pick-Up 199.00  4.23 3.44  0.00  2.00  4.00  5.00
                  Sedan              3.00  2.67 1.53  1.00  2.00  3.00  3.50
                  Station Wagon      4.00  6.00 0.00  6.00  6.00  6.00  6.00

                                     max
make_model        body_type
Dacia 1300        Sedan            47.00
Dacia Break       Station Wagon     0.00
Dacia Business    Compact           1.00
Dacia Comfort Tce Station Wagon     0.00
Dacia Dokker      Compact           4.00
...                                  ...
Volvo Xc70        Station Wagon    14.00
Volvo Xc90        Coupe             5.00
                  Off-Road/Pick-Up 18.00
                  Sedan             4.00
                  Station Wagon     6.00

[1287 rows x 8 columns]

**Let us take a close look at the age of cars considering the warranty feature with missing values**

In [84]:
df.loc[df["warranty"] == "-"][["make_model", "body_type", "warranty", "age"]]

                   make_model body_type warranty   age
5         Mercedes-Benz C 160   Compact        - 17.00
8      Mercedes-Benz A 35 Amg   Compact        -  3.00
15        Mercedes-Benz A 180   Compact        - 12.00
16        Mercedes-Benz A 250   Compact        -  1.00
23        Mercedes-Benz A 200   Compact        -  3.00
...                       ...       ...      ...   ...
28615               Volvo 960     Sedan        - 30.00
28620               Volvo S90     Sedan        -  4.00
28623               Volvo V40     Sedan        -  4.00
28626               Volvo S40     Sedan        - 18.00
28629               Volvo S80     Sedan        - 20.00

[15161 rows x 4 columns]

In [85]:
df.loc[df["warranty"] == "-"]["age"].value_counts(dropna=False).sort_index()

age
-180.00       1
-3.00         1
-1.00         1
0.00       1752
1.00       1385
2.00       1060
3.00       1577
4.00       1266
5.00        955
6.00        677
7.00        534
8.00        478
9.00        443
10.00       440
11.00       438
12.00       391
13.00       346
14.00       333
15.00       386
16.00       311
17.00       229
18.00       210
19.00       171
20.00       163
21.00       172
22.00       146
23.00       128
24.00        83
25.00        77
26.00        67
27.00        73
28.00        77
29.00        51
30.00        60
31.00        61
32.00        52
33.00        18
34.00        32
35.00        26
36.00        20
37.00        18
38.00        10
39.00        16
40.00        11
41.00         9
42.00         6
43.00        17
44.00        22
45.00        13
46.00        11
47.00        14
48.00         8
49.00        29
50.00        28
51.00        17
52.00        19
53.00        17
54.00        26
55.00        31
56.00        39
57.00        31
58.00        11
59.00         9
60.00         8
61.00         7
62.00         4
63.00         2
64.00         4
65.00         4
66.00         1
67.00         6
68.00         4
69.00         2
70.00         2
72.00         1
76.00         1
85.00         2
89.00         1
90.00         3
92.00         2
93.00         1
94.00         1
122.00        2
Name: count, dtype: int64

In [86]:
display(df.loc[df["warranty"] == "-"]["age"].mean())

8.950333091484731

**It's assumed that missing values in the warranty feature represent no-warranty.**

In [87]:
def warrantyclassifier(x):
    if "-" in x:
        return "No"
    else:
        return "Yes"

df["warranty"] = df["warranty"].astype(str).apply(warrantyclassifier)

In [88]:
first_looking("warranty")

COLUMN NAME    :  warranty
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  2
--------------------------------
warranty
No     15161
Yes    13463
Name: count, dtype: int64

## gears & gearbox

Since the Domain Knowledge demonstrates that there has been a close association between "gears" and "gearbox", so they will be evaluted together for filling missing values:

### gears

In [89]:
# Let's explore basic information about "gears"

first_looking("gears")

COLUMN NAME    :  gears
--------------------------------
per_of_nulls   :  % 33.79
num_of_nulls   :  9671
num_of_uniques :  11
--------------------------------
gears
NaN      9671
6.00     8411
5.00     5335
7.00     1738
8.00     1690
1.00      712
9.00      642
4.00      256
10.00     112
0.00       31
3.00       24
2.00        2
Name: count, dtype: int64

In [90]:
# df.groupby("fuel_type").gears.value_counts(dropna=False)

In [91]:
# Looking at the gear of electric vehicles is of particular importance.

df[df["fuel_type"]=="Electric"].gears.value_counts(dropna=False)

gears
NaN     100
1.00     77
6.00      4
0.00      3
5.00      2
9.00      1
7.00      1
Name: count, dtype: int64

In [92]:
df["gears"].fillna("-", inplace=True)

In [93]:
# let's explore if there is any pattern among ""make_model", "body_type", "gearbox", and "gears" by "price"

df.groupby(["make_model", "body_type", "gearbox", "gears"]).price.describe()

                                                         count     mean
make_model        body_type        gearbox        gears
Dacia 1300        Sedan            Manual         4.0     1.00  9999.00  \
Dacia Break       Station Wagon    Manual         -       1.00 20500.00
Dacia Business    Compact          Automatic      1.0     1.00 19515.00
Dacia Comfort Tce Station Wagon    Manual         -       1.00 21799.00
Dacia Dokker      Compact          Manual         -       1.00 11930.00
...                                                        ...      ...
Volvo Xc90        Off-Road/Pick-Up Manual         6.0     2.00  6799.00
                                                  -       2.00  7600.00
                  Sedan            Automatic      -       3.00 60366.67
                  Station Wagon    Automatic      8.0     2.00 29500.00
                                   Semi-automatic 8.0     2.00 36000.00

                                                             std      min
make_model        body_type        gearbox        gears
Dacia 1300        Sedan            Manual         4.0        NaN  9999.00  \
Dacia Break       Station Wagon    Manual         -          NaN 20500.00
Dacia Business    Compact          Automatic      1.0        NaN 19515.00
Dacia Comfort Tce Station Wagon    Manual         -          NaN 21799.00
Dacia Dokker      Compact          Manual         -          NaN 11930.00
...                                                          ...      ...
Volvo Xc90        Off-Road/Pick-Up Manual         6.0       0.00  6799.00
                                                  -         0.00  7600.00
                  Sedan            Automatic      -     21250.25 47700.00
                  Station Wagon    Automatic      8.0       0.00 29500.00
                                   Semi-automatic 8.0       0.00 36000.00

                                                             25%      50%
make_model        body_type        gearbox        gears
Dacia 1300        Sedan            Manual         4.0    9999.00  9999.00  \
Dacia Break       Station Wagon    Manual         -     20500.00 20500.00
Dacia Business    Compact          Automatic      1.0   19515.00 19515.00
Dacia Comfort Tce Station Wagon    Manual         -     21799.00 21799.00
Dacia Dokker      Compact          Manual         -     11930.00 11930.00
...                                                          ...      ...
Volvo Xc90        Off-Road/Pick-Up Manual         6.0    6799.00  6799.00
                                                  -      7600.00  7600.00
                  Sedan            Automatic      -     48100.00 48500.00
                  Station Wagon    Automatic      8.0   29500.00 29500.00
                                   Semi-automatic 8.0   36000.00 36000.00

                                                             75%      max
make_model        body_type        gearbox        gears
Dacia 1300        Sedan            Manual         4.0    9999.00  9999.00
Dacia Break       Station Wagon    Manual         -     20500.00 20500.00
Dacia Business    Compact          Automatic      1.0   19515.00 19515.00
Dacia Comfort Tce Station Wagon    Manual         -     21799.00 21799.00
Dacia Dokker      Compact          Manual         -     11930.00 11930.00
...                                                          ...      ...
Volvo Xc90        Off-Road/Pick-Up Manual         6.0    6799.00  6799.00
                                                  -      7600.00  7600.00
                  Sedan            Automatic      -     66700.00 84900.00
                  Station Wagon    Automatic      8.0   29500.00 29500.00
                                   Semi-automatic 8.0   36000.00 36000.00

[3184 rows x 8 columns]

<div style="background-color: #ffeeba; padding: 10px; font-size: 16px; font-weight: bold;">
    The <code>number of gears</code> of cars changes by their <code>make_models</code>, <code>body_types</code>, and <code>gearbox</code> most of the time. So it's decided to fill missing values with <code>mode value</code> of corresponding group.
</div>

In [94]:
# Let's replace dash/hyphen sign "-" with np.nan

df["gears"].replace("-", np.nan, inplace=True)

In [95]:
for group1 in df["make_model"].unique():
    for group2 in df["body_type"].unique():
        for group3 in df["gearbox"].unique():
            cond1 = df["make_model"] == group1
            cond2 = (df["make_model"] == group1) & (df["body_type"] == group2)
            cond3 = (df["make_model"] == group1) & (df["body_type"] == group2) & (df["gearbox"] == group3)
            mode1 = list(df[cond1]["gears"].mode())
            mode2 = list(df[cond2]["gears"].mode())
            mode3 = list(df[cond3]["gears"].mode())
            if mode3 != []:
                df.loc[cond3, "gears"] = df.loc[cond3, "gears"].fillna(df[cond3]["gears"].mode()[0])
            elif mode2 != []:
                df.loc[cond3, "gears"] = df.loc[cond3, "gears"].fillna(df[cond2]["gears"].mode()[0])
            elif mode1 != []:
                df.loc[cond3, "gears"] = df.loc[cond3, "gears"].fillna(df[cond1]["gears"].mode()[0])
            else:
                df.loc[cond3, "gears"] = df.loc[cond3, "gears"].fillna(df["gears"].mode()[0])

In [96]:
first_looking("gears")

COLUMN NAME    :  gears
--------------------------------
per_of_nulls   :  % 0.68
num_of_nulls   :  194
num_of_uniques :  11
--------------------------------
gears
6.00     12225
5.00      7729
8.00      2724
7.00      2609
1.00      1342
9.00      1135
4.00       341
10.00      242
NaN        194
3.00        49
0.00        31
2.00         3
Name: count, dtype: int64

**However, there have still been some (196) missing values for ``gears`` and WHY❓**

In [97]:
df[df["gears"].isna()][["make_model", "body_type", "gearbox"]]

                    make_model         body_type gearbox
175     Mercedes-Benz A 35 Amg           Compact     NaN
210        Mercedes-Benz A 200           Compact     NaN
222        Mercedes-Benz A 220           Compact     NaN
235        Mercedes-Benz A 220           Compact     NaN
239           Mercedes-Benz Cl           Compact     NaN
241        Mercedes-Benz A 200           Compact     NaN
244        Mercedes-Benz A 200           Compact     NaN
246           Mercedes-Benz Cl           Compact     NaN
247     Mercedes-Benz A 35 Amg           Compact     NaN
256        Mercedes-Benz A 180           Compact     NaN
258           Mercedes-Benz Cl           Compact     NaN
259        Mercedes-Benz A 220           Compact     NaN
267        Mercedes-Benz A 220           Compact     NaN
268        Mercedes-Benz A 180           Compact     NaN
931      Mercedes-Benz Cla 250             Coupe     NaN
2232   Mercedes-Benz Edition 1             Sedan     NaN
2371          Mercedes-Benz 4M             Sedan     NaN
3085                   Opel Gt       Convertible     NaN
3240            Opel Commodore             Coupe     NaN
3246                Opel Astra             Coupe     NaN
3286               Opel Kadett             Coupe     NaN
3316                   Opel Gt             Coupe     NaN
3321                Opel Manta             Coupe     NaN
3409                Opel Monza             Coupe     NaN
3422                   Opel Gt             Coupe     NaN
3689          Opel Crossland X  Off-Road/Pick-Up     NaN
3998             Opel Insignia     Station Wagon     NaN
4978            Renault Twingo           Compact     NaN
5004            Renault Megane           Compact     NaN
5072              Renault Clio           Compact     NaN
5095            Renault Megane           Compact     NaN
5108            Renault Megane           Compact     NaN
5126            Renault Megane           Compact     NaN
5133              Renault Clio           Compact     NaN
5152            Renault Megane           Compact     NaN
5170            Renault Megane           Compact     NaN
5239          Renault Talisman       Convertible     NaN
5300               Renault 4Cv       Convertible     NaN
5384            Renault Megane       Convertible     NaN
5434              Renault Wind       Convertible     NaN
5436              Renault Wind       Convertible     NaN
5444            Renault Kangoo       Convertible     NaN
5523              Renault Clio       Convertible     NaN
5664            Renault Arkana             Coupe     NaN
5665            Renault Megane             Coupe     NaN
5681            Renault Megane             Coupe     NaN
5707            Renault Megane             Coupe     NaN
5713         Renault Alpine V6             Coupe     NaN
5739            Renault Laguna             Coupe     NaN
5788            Renault Arkana             Coupe     NaN
5817            Renault Megane             Coupe     NaN
5825              Renault Clio             Coupe     NaN
5839            Renault Arkana             Coupe     NaN
5886            Renault Arkana             Coupe     NaN
5892       Renault Alpine A310             Coupe     NaN
5945              Renault Clio             Coupe     NaN
5963            Renault Arkana             Coupe     NaN
5977            Renault Arkana  Off-Road/Pick-Up     NaN
6190            Renault Kadjar  Off-Road/Pick-Up     NaN
6196            Renault Kadjar  Off-Road/Pick-Up     NaN
6218            Renault Captur  Off-Road/Pick-Up     NaN
6244            Renault Kadjar  Off-Road/Pick-Up     NaN
6248            Renault Captur  Off-Road/Pick-Up     NaN
6529            Renault Megane     Station Wagon     NaN
6530            Renault Megane     Station Wagon     NaN
6821            Renault Megane             Sedan     NaN
7043            Renault Megane             Sedan     NaN
7445               Peugeot 208           Compact     NaN
7547               Peugeot 206       Convertible     NaN
7598               Peugeot 504       Convertible     NaN
7691               Peugeot 206       Convertible     NaN
7702               Peugeot 207       Convertible     NaN
7703               Peugeot 206       Convertible     NaN
7727               Peugeot 205       Convertible     NaN
7734               Peugeot 307       Convertible     NaN
7763               Peugeot 207       Convertible     NaN
7845               Peugeot 206       Convertible     NaN
7872               Peugeot 206       Convertible     NaN
7876               Peugeot 207       Convertible     NaN
8061               Peugeot 205             Coupe     NaN
8356              Peugeot 3008  Off-Road/Pick-Up     NaN
9045               Peugeot 308     Station Wagon     NaN
9065               Peugeot 208     Station Wagon     NaN
9634                 Fiat Tipo           Compact     NaN
9647                  Fiat 500           Compact     NaN
9777                  Fiat 500           Compact     NaN
10329                Fiat Dino             Coupe     NaN
10377                 Fiat 500             Coupe     NaN
10422               Fiat Coupe             Coupe     NaN
10431                 Fiat 850             Coupe     NaN
10482               Fiat Coupe             Coupe     NaN
10488          Fiat 124 Spider             Coupe     NaN
10522                Fiat Dino             Coupe     NaN
10549               Fiat Coupe             Coupe     NaN
10562                 Fiat 500             Coupe     NaN
10569                Fiat Dino             Coupe     NaN
10573                 Fiat 130             Coupe     NaN
10578                 Fiat 128             Coupe     NaN
10595                 Fiat 600             Coupe     NaN
10617      Fiat Topolino Lotus             Coupe     NaN
10662                Fiat 500L             Coupe     NaN
10720                Fiat 500X  Off-Road/Pick-Up     NaN
10736                Fiat 500X  Off-Road/Pick-Up     NaN
10740                Fiat 500X  Off-Road/Pick-Up     NaN
10749                Fiat 500X  Off-Road/Pick-Up     NaN
10775                Fiat 500X  Off-Road/Pick-Up     NaN
10818                Fiat 500X  Off-Road/Pick-Up     NaN
11085                Fiat 500X     Station Wagon     NaN
11086                Fiat 500X     Station Wagon     NaN
11104                Fiat 500X     Station Wagon     NaN
11156                Fiat Tipo     Station Wagon     NaN
11196                Fiat 500X     Station Wagon     NaN
11568                Fiat Tipo             Sedan     NaN
12233                 Seat 128             Coupe     NaN
12259                Seat Leon             Coupe     NaN
12267               Seat Ibiza             Coupe     NaN
12793             Seat Tarraco  Off-Road/Pick-Up     NaN
12803               Seat Arona  Off-Road/Pick-Up     NaN
12972                Seat Leon     Station Wagon     NaN
13959            Skoda Felicia       Convertible     NaN
15526            Dacia Sandero       Convertible     NaN
15527             Dacia Duster       Convertible     NaN
15667             Dacia Spring  Off-Road/Pick-Up     NaN
16253             Dacia Duster     Station Wagon     NaN
16268              Dacia Logan     Station Wagon     NaN
17064              Toyota Fj40       Convertible     NaN
17150            Toyota Celica       Convertible     NaN
17192              Toyota Fj40       Convertible     NaN
17360           Toyota Corolla             Coupe     NaN
17400             Toyota Supra             Coupe     NaN
17415            Toyota Celica             Coupe     NaN
17472           Toyota Corolla             Coupe     NaN
17501           Toyota Corolla             Coupe     NaN
17521            Toyota Celica             Coupe     NaN
17567              Toyota C-Hr             Coupe     NaN
17931        Toyota Fj Cruiser  Off-Road/Pick-Up     NaN
19191            Nissan 100 Nx       Convertible     NaN
19204            Nissan Figaro       Convertible     NaN
19288              Nissan Gt-R             Coupe     NaN
19509           Nissan Skyline             Coupe     NaN
19523              Nissan Gt-R             Coupe     NaN
19550            Nissan Datsun             Coupe     NaN
19630              Nissan Gt-R             Coupe     NaN
20046              Nissan Juke     Station Wagon     NaN
20131            Nissan Murano     Station Wagon     NaN
20134           Nissan Qashqai     Station Wagon     NaN
20141              Nissan Juke     Station Wagon     NaN
20261           Nissan Qashqai     Station Wagon     NaN
20267           Nissan X-Trail     Station Wagon     NaN
20325              Nissan Juke     Station Wagon     NaN
20337           Nissan Qashqai     Station Wagon     NaN
20338              Nissan Juke     Station Wagon     NaN
20376              Nissan Juke     Station Wagon     NaN
20398           Nissan Qashqai     Station Wagon     NaN
20399           Nissan Qashqai     Station Wagon     NaN
20788              Ford Fiesta           Compact     NaN
20813              Ford Ka/Ka+           Compact     NaN
21269             Ford Mustang       Convertible     NaN
21315            Ford Focus Cc       Convertible     NaN
21319             Ford Mustang       Convertible     NaN
21357             Ford Mustang       Convertible     NaN
21380             Ford Mustang       Convertible     NaN
21461             Ford Hot Rod       Convertible     NaN
21463              Ford Escort       Convertible     NaN
21485             Ford Mustang       Convertible     NaN
21756              Ford Sierra             Coupe     NaN
21926             Ford Mustang             Coupe     NaN
21929             Ford Mustang             Coupe     NaN
22823      Ford Mustang Mach-E             Sedan     NaN
23200            Hyundai Ioniq           Compact     NaN
23224              Hyundai I30           Compact     NaN
23274            Hyundai Ioniq           Compact     NaN
23776              Hyundai I30             Coupe     NaN
24257              Hyundai I30     Station Wagon     NaN
24308           Hyundai Tucson     Station Wagon     NaN
24309           Hyundai Tucson     Station Wagon     NaN
25792                Volvo C70       Convertible     NaN
26108                Volvo C70       Convertible     NaN
26387              Volvo P1800             Coupe     NaN
26407                Volvo C70             Coupe     NaN
26424              Volvo P1800             Coupe     NaN
26426                Volvo 262             Coupe     NaN
26428                Volvo 262             Coupe     NaN
26493              Volvo Pv544             Coupe     NaN
26562              Volvo P1800             Coupe     NaN
26582                Volvo C70             Coupe     NaN
26599              Volvo P1800             Coupe     NaN
26601                Volvo 262             Coupe     NaN
26603                Volvo 262             Coupe     NaN
26668              Volvo Pv544             Coupe     NaN
27644                Volvo V90     Station Wagon     NaN
27647  Volvo V90 Cross Country     Station Wagon     NaN
28029                Volvo V90     Station Wagon     NaN
28032  Volvo V90 Cross Country     Station Wagon     NaN

### gearbox

In [98]:
# Let's explore basic information about "gearbox"

first_looking("gearbox")

COLUMN NAME    :  gearbox
--------------------------------
per_of_nulls   :  % 0.86
num_of_nulls   :  246
num_of_uniques :  3
--------------------------------
gearbox
Manual            17021
Automatic         11285
NaN                 246
Semi-automatic       72
Name: count, dtype: int64

In [99]:
# df.groupby("fuel_type").gearbox.value_counts(dropna=False)

In [100]:
# Looking at the gear types of electric vehicles is of particular importance.

df[df["fuel_type"]=="Electric"].gearbox.value_counts(dropna=False)

gearbox
Automatic         181
NaN                 3
Manual              3
Semi-automatic      1
Name: count, dtype: int64

In [101]:
df["gearbox"].fillna("-", inplace=True)

In [102]:
# let's explore if there is any pattern among ""make_model", "body_type", and "gearbox" by "price"

df.groupby(["make_model", "body_type", "gearbox"]).price.describe()

                                                   count     mean      std
make_model        body_type        gearbox
Dacia 1300        Sedan            Manual           1.00  9999.00      NaN  \
Dacia Break       Station Wagon    Manual           1.00 20500.00      NaN
Dacia Business    Compact          Automatic        1.00 19515.00      NaN
Dacia Comfort Tce Station Wagon    Manual           1.00 21799.00      NaN
Dacia Dokker      Compact          Manual           1.00 11930.00      NaN
...                                                  ...      ...      ...
Volvo Xc90        Off-Road/Pick-Up Automatic      195.00 52812.41 19180.00
                                   Manual           4.00  7199.50   462.46
                  Sedan            Automatic        3.00 60366.67 21250.25
                  Station Wagon    Automatic        2.00 29500.00     0.00
                                   Semi-automatic   2.00 36000.00     0.00

                                                       min      25%      50%
make_model        body_type        gearbox
Dacia 1300        Sedan            Manual          9999.00  9999.00  9999.00  \
Dacia Break       Station Wagon    Manual         20500.00 20500.00 20500.00
Dacia Business    Compact          Automatic      19515.00 19515.00 19515.00
Dacia Comfort Tce Station Wagon    Manual         21799.00 21799.00 21799.00
Dacia Dokker      Compact          Manual         11930.00 11930.00 11930.00
...                                                    ...      ...      ...
Volvo Xc90        Off-Road/Pick-Up Automatic       6400.00 41980.00 49900.00
                                   Manual          6799.00  6799.00  7199.50
                  Sedan            Automatic      47700.00 48100.00 48500.00
                  Station Wagon    Automatic      29500.00 29500.00 29500.00
                                   Semi-automatic 36000.00 36000.00 36000.00

                                                       75%      max
make_model        body_type        gearbox
Dacia 1300        Sedan            Manual          9999.00  9999.00
Dacia Break       Station Wagon    Manual         20500.00 20500.00
Dacia Business    Compact          Automatic      19515.00 19515.00
Dacia Comfort Tce Station Wagon    Manual         21799.00 21799.00
Dacia Dokker      Compact          Manual         11930.00 11930.00
...                                                    ...      ...
Volvo Xc90        Off-Road/Pick-Up Automatic      64990.00 97450.00
                                   Manual          7600.00  7600.00
                  Sedan            Automatic      66700.00 84900.00
                  Station Wagon    Automatic      29500.00 29500.00
                                   Semi-automatic 36000.00 36000.00

[1834 rows x 8 columns]

<div style="background-color: #ffeeba; padding: 10px; font-size: 16px; font-weight: bold;">
    The <code>type of gearbox</code> of cars changes by their <code>make_models</code> and <code>body_types</code> most of the time. So it's decided to fill missing values with <code>mode value</code> of corresponding group.
</div>

In [103]:
# Let's replace dash/hyphen sign "-" with np.nan

df["gearbox"] = df["gearbox"].replace('-', np.nan)

In [104]:
fill(df, "make_model", "body_type", "gearbox", "mode")

COLUMN NAME    :  gearbox
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  3
--------------------------------
gearbox
Automatic         11361
Manual            17191
Semi-automatic       72
Name: count, dtype: int64

**Let us take care of ``gears`` again:**

In [105]:
# This is the nested for loop where it's used in fill(df, group_col1, group_col2, col_name, method) DEF to be generalized for all data

for group1 in df["make_model"].unique():
    for group2 in df["body_type"].unique():
        for group3 in df["gearbox"].unique():
            cond1 = df["make_model"] == group1
            cond2 = (df["make_model"] == group1) & (df["body_type"] == group2)
            cond3 = (df["make_model"] == group1) & (df["body_type"] == group2) & (df["gearbox"] == group3)
            mode1 = list(df[cond1]["gears"].mode())
            mode2 = list(df[cond2]["gears"].mode())
            mode3 = list(df[cond3]["gears"].mode())
            if mode3 != []:
                df.loc[cond3, "gears"] = df.loc[cond3, "gears"].fillna(df[cond3]["gears"].mode()[0])
            elif mode2 != []:
                df.loc[cond3, "gears"] = df.loc[cond3, "gears"].fillna(df[cond2]["gears"].mode()[0])
            elif mode1 != []:
                df.loc[cond3, "gears"] = df.loc[cond3, "gears"].fillna(df[cond1]["gears"].mode()[0])
            else:
                df.loc[cond3, "gears"] = df.loc[cond3, "gears"].fillna(df["gears"].mode()[0])

In [106]:
first_looking("gears")

COLUMN NAME    :  gears
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  11
--------------------------------
gears
6.00     12293
5.00      7790
8.00      2735
7.00      2628
1.00      1350
9.00      1136
4.00       358
10.00      244
3.00        56
0.00        31
2.00         3
Name: count, dtype: int64

## fuel_type

With a greater push towards fuel efficiency, low running costs and less carbon emissions, you’ll find that hybrid, diesel and electric cars will hold their value for much longer than petrol counterparts. This isn’t a universal truth, as small petrol cars can do very well, but it is becoming a trend.

In [107]:
# Let's explore basic information about "fuel_type"

first_looking("fuel_type")

COLUMN NAME    :  fuel_type
--------------------------------
per_of_nulls   :  % 6.24
num_of_nulls   :  1787
num_of_uniques :  4
--------------------------------
fuel_type
Benzine               17543
Diesel                 8727
NaN                    1787
Liquid/Natural Gas      379
Electric                188
Name: count, dtype: int64

In [108]:
# All NaN values are converted to dash/hyphen sign "-" to see them in the output of describe() and explore the hidden pattern

df["fuel_type"].fillna("-", inplace=True)

### 📝 Domain Knowledge:

If we use the same transmission in both engines, the power to the wheels would be uneven and disproportionate as per the engine RPM and driving conditions. Hence we cannot couple the same manual transmission with both the engines.

**🧐 [Is there any difference between transmission systems of petrol and diesel engines?](https://www.quora.com/Is-there-any-difference-between-transmission-systems-of-petrol-and-diesel-engines)**

**🧐 [Can I use a diesel engine on a petrol gearbox?](https://www.quora.com/Can-I-use-a-diesel-engine-on-a-petrol-gearbox)**

In [109]:
# let's explore if there is any pattern among ""make_model", "body_type", "gearbox", and "fuel_type" by "price"

df.groupby(["make_model", "body_type", "gearbox", "fuel_type"]).price.describe()

                                                             count     mean
make_model        body_type        gearbox        fuel_type
Dacia 1300        Sedan            Manual         Benzine     1.00  9999.00  \
Dacia Break       Station Wagon    Manual         Benzine     1.00 20500.00
Dacia Business    Compact          Automatic      -           1.00 19515.00
Dacia Comfort Tce Station Wagon    Manual         Benzine     1.00 21799.00
Dacia Dokker      Compact          Manual         Diesel      1.00 11930.00
...                                                            ...      ...
Volvo Xc90        Off-Road/Pick-Up Manual         Diesel      4.00  7199.50
                  Sedan            Automatic      -           1.00 84900.00
                                                  Diesel      2.00 48100.00
                  Station Wagon    Automatic      Diesel      2.00 29500.00
                                   Semi-automatic Diesel      2.00 36000.00

                                                               std      min
make_model        body_type        gearbox        fuel_type
Dacia 1300        Sedan            Manual         Benzine      NaN  9999.00  \
Dacia Break       Station Wagon    Manual         Benzine      NaN 20500.00
Dacia Business    Compact          Automatic      -            NaN 19515.00
Dacia Comfort Tce Station Wagon    Manual         Benzine      NaN 21799.00
Dacia Dokker      Compact          Manual         Diesel       NaN 11930.00
...                                                            ...      ...
Volvo Xc90        Off-Road/Pick-Up Manual         Diesel    462.46  6799.00
                  Sedan            Automatic      -            NaN 84900.00
                                                  Diesel    565.69 47700.00
                  Station Wagon    Automatic      Diesel      0.00 29500.00
                                   Semi-automatic Diesel      0.00 36000.00

                                                                 25%      50%
make_model        body_type        gearbox        fuel_type
Dacia 1300        Sedan            Manual         Benzine    9999.00  9999.00  \
Dacia Break       Station Wagon    Manual         Benzine   20500.00 20500.00
Dacia Business    Compact          Automatic      -         19515.00 19515.00
Dacia Comfort Tce Station Wagon    Manual         Benzine   21799.00 21799.00
Dacia Dokker      Compact          Manual         Diesel    11930.00 11930.00
...                                                              ...      ...
Volvo Xc90        Off-Road/Pick-Up Manual         Diesel     6799.00  7199.50
                  Sedan            Automatic      -         84900.00 84900.00
                                                  Diesel    47900.00 48100.00
                  Station Wagon    Automatic      Diesel    29500.00 29500.00
                                   Semi-automatic Diesel    36000.00 36000.00

                                                                 75%      max
make_model        body_type        gearbox        fuel_type
Dacia 1300        Sedan            Manual         Benzine    9999.00  9999.00
Dacia Break       Station Wagon    Manual         Benzine   20500.00 20500.00
Dacia Business    Compact          Automatic      -         19515.00 19515.00
Dacia Comfort Tce Station Wagon    Manual         Benzine   21799.00 21799.00
Dacia Dokker      Compact          Manual         Diesel    11930.00 11930.00
...                                                              ...      ...
Volvo Xc90        Off-Road/Pick-Up Manual         Diesel     7600.00  7600.00
                  Sedan            Automatic      -         84900.00 84900.00
                                                  Diesel    48300.00 48500.00
                  Station Wagon    Automatic      Diesel    29500.00 29500.00
                                   Semi-automatic Diesel    36000.00 36000.00

[2477 rows x 8 columns]

In [110]:
df["fuel_type"] = df["fuel_type"].replace('-', np.nan)

<div style="background-color: #ffeeba; padding: 10px; font-size: 16px; font-weight: bold;">
    Domain Knowledge demonstrates that the <code>fuel type</code> of cars might change by their <code>make_models</code> and <code>gear_box</code> most of the time. So it's decided to fill missing values with <code>mode value</code> of corresponding group.
</div>

In [111]:
# This DEF will fill the missing values in the "fuel_type" with the mode value based on "make_model" and "body_type"

fill(df, "make_model", "gearbox", "fuel_type", "mode")

COLUMN NAME    :  fuel_type
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  4
--------------------------------
fuel_type
Benzine               18698
Diesel                 9102
Electric                440
Liquid/Natural Gas      384
Name: count, dtype: int64

## seats

In [112]:
# Let's explore basic information about "seats"

first_looking("seats")

COLUMN NAME    :  seats
--------------------------------
per_of_nulls   :  % 10.91
num_of_nulls   :  3124
num_of_uniques :  11
--------------------------------
seats
5.00     18307
4.00      5389
NaN       3124
2.00      1183
7.00       488
8.00        43
9.00        35
3.00        25
6.00        12
0.00         9
1.00         7
17.00        2
Name: count, dtype: int64

<div style="background-color: #ffeeba; padding: 10px; font-size: 16px; font-weight: bold;">
    Domain Knowledge demonstrates that the <code>number of seats</code> of cars might change by their <code>make_models</code> and <code>body_types</code> most of the time. So it's decided to fill missing values with <code>mode value</code> of corresponding group.
</div>

In [113]:
# This DEF will fill the missing values in the "seats" with the mode value based on "make_model" and "body_type"

fill(df, "make_model", "body_type", "seats", "mode")

COLUMN NAME    :  seats
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  11
--------------------------------
seats
0.00         9
1.00         7
2.00      1258
3.00        26
4.00      5964
5.00     20722
6.00        12
7.00       545
8.00        44
9.00        35
17.00        2
Name: count, dtype: int64

## co_emissions

In [114]:
# Let's explore basic information about "co_emissions"

first_looking("co_emissions")

COLUMN NAME    :  co_emissions
--------------------------------
per_of_nulls   :  % 35.05
num_of_nulls   :  10034
num_of_uniques :  326
--------------------------------
co_emissions
NaN       10034
0.00       1040
119.00      393
124.00      340
129.00      319
114.00      313
99.00       312
115.00      304
139.00      299
109.00      265
108.00      262
125.00      255
149.00      255
130.00      230
123.00      230
138.00      230
120.00      218
117.00      214
110.00      213
127.00      211
126.00      204
111.00      204
104.00      197
112.00      186
95.00       184
107.00      179
135.00      178
116.00      175
154.00      173
134.00      171
145.00      170
122.00      170
133.00      165
178.00      164
113.00      161
128.00      159
106.00      158
121.00      157
103.00      157
131.00      153
93.00       147
98.00       144
105.00      142
156.00      141
118.00      139
140.00      139
148.00      139
155.00      137
159.00      136
88.00       136
136.00      135
144.00      135
102.00      134
96.00       133
147.00      127
158.00      127
161.00      125
94.00       118
92.00       117
142.00      117
167.00      114
132.00      114
137.00      112
143.00      109
166.00      107
169.00      106
146.00      103
164.00      102
101.00      100
152.00       97
85.00        92
174.00       91
97.00        91
151.00       88
153.00       87
171.00       86
150.00       84
89.00        82
191.00       81
170.00       77
165.00       76
162.00       73
168.00       72
175.00       71
180.00       70
196.00       70
194.00       68
157.00       68
90.00        67
177.00       67
141.00       66
273.00       65
185.00       65
218.00       64
230.00       62
160.00       62
179.00       61
193.00       60
163.00       60
184.00       57
190.00       57
181.00       56
82.00        56
195.00       56
173.00       56
229.00       55
176.00       50
199.00       50
100.00       48
219.00       47
212.00       46
34.00        45
42.00        44
200.00       43
209.00       42
261.00       41
225.00       41
183.00       40
41.00        39
197.00       38
226.00       38
192.00       38
26.00        37
248.00       37
187.00       35
189.00       35
234.00       34
182.00       33
49.00        33
76.00        33
275.00       33
289.00       32
210.00       32
263.00       32
253.00       31
215.00       30
186.00       30
64.00        30
284.00       30
38.00        30
268.00       30
188.00       29
84.00        29
242.00       28
220.00       28
172.00       28
47.00        27
40.00        27
214.00       26
39.00        25
86.00        25
280.00       25
87.00        25
211.00       24
79.00        24
279.00       24
91.00        23
245.00       22
254.00       22
288.00       22
75.00        22
36.00        21
217.00       21
35.00        21
205.00       21
236.00       20
270.00       20
216.00       19
208.00       19
202.00       19
31.00        18
232.00       18
48.00        18
1.00         18
201.00       17
262.00       16
299.00       16
235.00       16
32.00        16
204.00       16
252.00       16
198.00       16
259.00       15
203.00       15
246.00       15
278.00       15
46.00        15
223.00       14
54.00        14
213.00       14
250.00       14
83.00        14
50.00        14
25.00        13
207.00       13
221.00       13
238.00       13
206.00       13
244.00       12
247.00       12
285.00       12
258.00       11
44.00        11
256.00       11
281.00       11
231.00       10
51.00        10
240.00       10
222.00       10
78.00        10
224.00       10
277.00       10
298.00       10
295.00       10
37.00         9
311.00        9
260.00        9
33.00         9
249.00        9
228.00        9
237.00        8
287.00        8
251.00        8
267.00        8
29.00         8
292.00        8
282.00        8
52.00         8
239.00        8
28.00         8
59.00         8
255.00        8
265.00        7
55.00         6
330.00        6
312.00        6
257.00        6
306.00        6
296.00        6
14.00         5
22.00         5
30.00         5
66.00         5
327.00        5
269.00        5
68.00         5
227.00        5
43.00         5
283.00        5
303.00        4
320.00        4
81.00         4
27.00         4
243.00        4
24.00         4
276.00        4
274.00        4
241.00        4
322.00        4
271.00        4
18.00         3
15.00         3
300.00        3
319.00        3
310.00        3
324.00        3
17.00         3
8.00          2
414.00        2
290.00        2
336.00        2
16.00         2
340.00        2
45.00         2
23.00         2
233.00        2
293.00        2
264.00        2
400.00        2
56.00         2
10.00         2
65.00         2
272.00        1
9.00          1
71.00         1
307.00        1
326.00        1
313.00        1
399.00        1
940.00        1
294.00        1
420.00        1
328.00        1
304.00        1
314.00        1
350.00        1
339.00        1
394.00        1
910.00        1
343.00        1
316.00        1
341.00        1
21.00         1
317.00        1
335.00        1
20.00         1
19.00         1
345.00        1
13.00         1
348.00        1
266.00        1
373.00        1
344.00        1
80.00         1
398.00        1
7.00          1
377.00        1
5.00          1
3.00          1
308.00        1
321.00        1
73.00         1
332.00        1
70.00         1
338.00        1
342.00        1
53.00         1
Name: count, dtype: int64

In [115]:
# All NaN values are converted to dash/hyphen sign "-" to see them in the output of describe() and explore the hidden pattern

df["co_emissions"].fillna("-", inplace=True)

In [116]:
# let's explore if there is any pattern among ""make_model", "body_type", "fuel_type", and "co_emissions" by "price"

df.groupby(["make_model", "body_type", "fuel_type", "co_emissions"]).price.describe()

                                                           count     mean
make_model        body_type        fuel_type co_emissions
Dacia 1300        Sedan            Benzine   -              1.00  9999.00  \
Dacia Break       Station Wagon    Benzine   -              1.00 20500.00
Dacia Business    Compact          Benzine   -              1.00 19515.00
Dacia Comfort Tce Station Wagon    Benzine   130.0          1.00 21799.00
Dacia Dokker      Compact          Diesel    -              1.00 11930.00
...                                                          ...      ...
Volvo Xc90        Off-Road/Pick-Up Electric  0.0            4.00 64400.00
                  Sedan            Diesel    47.0           1.00 84900.00
                                             -              2.00 48100.00
                  Station Wagon    Diesel    149.0          2.00 29500.00
                                             152.0          2.00 36000.00

                                                              std      min
make_model        body_type        fuel_type co_emissions
Dacia 1300        Sedan            Benzine   -                NaN  9999.00  \
Dacia Break       Station Wagon    Benzine   -                NaN 20500.00
Dacia Business    Compact          Benzine   -                NaN 19515.00
Dacia Comfort Tce Station Wagon    Benzine   130.0            NaN 21799.00
Dacia Dokker      Compact          Diesel    -                NaN 11930.00
...                                                           ...      ...
Volvo Xc90        Off-Road/Pick-Up Electric  0.0          9814.95 55900.00
                  Sedan            Diesel    47.0             NaN 84900.00
                                             -             565.69 47700.00
                  Station Wagon    Diesel    149.0           0.00 29500.00
                                             152.0           0.00 36000.00

                                                               25%      50%
make_model        body_type        fuel_type co_emissions
Dacia 1300        Sedan            Benzine   -             9999.00  9999.00  \
Dacia Break       Station Wagon    Benzine   -            20500.00 20500.00
Dacia Business    Compact          Benzine   -            19515.00 19515.00
Dacia Comfort Tce Station Wagon    Benzine   130.0        21799.00 21799.00
Dacia Dokker      Compact          Diesel    -            11930.00 11930.00
...                                                            ...      ...
Volvo Xc90        Off-Road/Pick-Up Electric  0.0          55900.00 64400.00
                  Sedan            Diesel    47.0         84900.00 84900.00
                                             -            47900.00 48100.00
                  Station Wagon    Diesel    149.0        29500.00 29500.00
                                             152.0        36000.00 36000.00

                                                               75%      max
make_model        body_type        fuel_type co_emissions
Dacia 1300        Sedan            Benzine   -             9999.00  9999.00
Dacia Break       Station Wagon    Benzine   -            20500.00 20500.00
Dacia Business    Compact          Benzine   -            19515.00 19515.00
Dacia Comfort Tce Station Wagon    Benzine   130.0        21799.00 21799.00
Dacia Dokker      Compact          Diesel    -            11930.00 11930.00
...                                                            ...      ...
Volvo Xc90        Off-Road/Pick-Up Electric  0.0          72900.00 72900.00
                  Sedan            Diesel    47.0         84900.00 84900.00
                                             -            48300.00 48500.00
                  Station Wagon    Diesel    149.0        29500.00 29500.00
                                             152.0        36000.00 36000.00

[8238 rows x 8 columns]

**Let's first examine how co_emission values for Electric cars differ from others.**

In [117]:
df.groupby(["fuel_type", "make_model", "body_type", "co_emissions"]).price.describe().loc["Electric"]

                                                     count      mean      std
make_model            body_type        co_emissions
Dacia Spring          Compact          -             27.00  22753.67   912.02  \
                      Off-Road/Pick-Up 0.0            2.00  17494.50  1407.85
                                       -              1.00  22980.00      NaN
                      Sedan            0.0            1.00  18400.00      NaN
                                       -              8.00  21581.75  2571.87
Fiat 500              Compact          0.0            8.00  26186.25  6390.54
                      Convertible      0.0            6.00  30148.33  2373.10
                      Coupe            0.0            3.00  31333.33  5918.05
                      Sedan            0.0            2.00  27400.00  2262.74
Fiat 500E             Compact          0.0            4.00  22824.50  5984.56
                                       -             11.00  31006.36  3225.38
                      Convertible      0.0            4.00  29550.00  2150.19
                                       -              5.00  34025.80  1069.97
                      Coupe            0.0            2.00  26470.00   678.82
                                       -              1.00  26599.00      NaN
                      Sedan            0.0           15.00  27516.53  3733.04
                                       -              7.00  29791.29  2614.82
Fiat Topolino Lotus   Coupe            0.0            1.00  27900.00      NaN
Ford Kuga             Off-Road/Pick-Up 0.0            3.00  37400.00  3905.12
Ford Mustang          Off-Road/Pick-Up 0.0            1.00  71250.00      NaN
Ford Mustang Mach-E   Coupe            -              1.00  64500.00      NaN
                      Off-Road/Pick-Up 0.0            2.00  66400.00  4949.75
                                       -             14.00  69253.93  9204.23
                      Sedan            0.0            1.00  64400.00      NaN
                                       -              2.00  59977.50  7074.60
Hyundai Ioniq         Compact          0.0            1.00  33900.00      NaN
                      Sedan            0.0            2.00  38450.00 16263.46
Hyundai Kona          Off-Road/Pick-Up 0.0            9.00  31973.33  4224.54
Mercedes-Benz Eqa     Off-Road/Pick-Up 0.0            2.00  58050.00  1202.08
                                       -              1.00  54850.00      NaN
                      Sedan            -              1.00  61485.00      NaN
Mercedes-Benz Eqb 350 Off-Road/Pick-Up 0.0            1.00  64900.00      NaN
                                       -              5.00  67148.00  2814.12
Mercedes-Benz Eqc 400 Off-Road/Pick-Up 0.0            4.00  76449.25 10466.31
                                       -             12.00  75537.75  4864.80
Mercedes-Benz Eqe 350 Compact          0.0            1.00  80900.00      NaN
                      Sedan            0.0            2.00  85000.00  6929.65
                                       -              7.00  97532.00 10038.27
                      Station Wagon    -              1.00  87879.00      NaN
Mercedes-Benz Eqs     Compact          -              3.00 136148.00 28080.66
                      Sedan            0.0            3.00 133773.00 21400.12
                                       -             20.00 128365.50 23153.38
                      Station Wagon    -              3.00 126085.67 44873.47
Nissan Leaf           Compact          0.0           17.00  23733.35  5519.33
                                       -             17.00  21521.94  6980.65
                      Sedan            0.0           12.00  22683.33  5809.86
                                       1.0            1.00  20990.00      NaN
                                       -             13.00  25984.08  6481.87
                      Station Wagon    0.0            1.00  11000.00      NaN
Opel Corsa            Compact          0.0            1.00  28000.00      NaN
Opel Mokka            Off-Road/Pick-Up 0.0            1.00  25500.00      NaN
Peugeot 2008          Off-Road/Pick-Up 0.0            1.00  29999.00      NaN
                      Station Wagon    0.0            2.00  34435.00   629.33
Peugeot 208           Compact          0.0            3.00  30318.33   280.42
                      Sedan            0.0            8.00  28263.88  4494.75
Peugeot 308           Sedan            0.0            1.00  33355.00      NaN
Peugeot 508           Sedan            0.0            1.00  34173.00      NaN
Peugeot E-2008        Off-Road/Pick-Up -              1.00  35989.00      NaN
                      Station Wagon    0.0            6.00  37365.67   520.26
Peugeot E-208         Compact          0.0            2.00  26999.00  4242.64
                                       -              3.00  31130.00  1014.85
Peugeot Ion           Compact          0.0            1.00   9990.00      NaN
Peugeot Partner       Station Wagon    0.0            2.00  16370.00   537.40
                                       1.0            1.00  14990.00      NaN
Renault Arkana        Coupe            132.0          1.00  27500.00      NaN
Renault R 11          Sedan            0.0            1.00  10490.00      NaN
Renault R 9           Sedan            0.0            3.00  10923.33   404.15
Renault Twingo        Compact          0.0            2.00  16910.00  2729.43
Renault Twizy         Compact          0.0            2.00   8440.00  2757.72
                                       -              3.00  10160.00  4364.25
                      Convertible      -              1.00   5900.00      NaN
                      Coupe            0.0            2.00   5747.50   350.02
                                       -              3.00   8166.00  4010.44
                      Off-Road/Pick-Up -              2.00   7697.50   357.09
Renault Zoe           Compact          0.0            8.00  19100.12  6901.42
                                       -             40.00  20607.80  8255.64
                      Convertible      0.0            1.00  21999.00      NaN
                      Sedan            0.0           14.00  15664.93  4999.31
                                       -             24.00  19912.17  5970.15
Skoda Enyaq           Off-Road/Pick-Up 0.0            2.00  60900.00  5656.85
                                       -             14.00  58745.71  6566.63
                      Sedan            -              1.00  61930.00      NaN
Toyota Proace         Station Wagon    0.0            1.00  40999.00      NaN
Toyota Rav 4          Off-Road/Pick-Up 0.0            4.00  46750.00     0.00
Volvo S90             Sedan            0.0            2.00  51900.00     0.00
Volvo Xc90            Off-Road/Pick-Up 0.0            4.00  64400.00  9814.95

                                                          min       25%
make_model            body_type        co_emissions
Dacia Spring          Compact          -             19269.00  22985.00  \
                      Off-Road/Pick-Up 0.0           16499.00  16996.75
                                       -             22980.00  22980.00
                      Sedan            0.0           18400.00  18400.00
                                       -             18099.00  21074.25
Fiat 500              Compact          0.0           17000.00  22925.00
                      Convertible      0.0           27000.00  29067.50
                      Coupe            0.0           25700.00  28250.00
                      Sedan            0.0           25800.00  26600.00
Fiat 500E             Compact          0.0           14900.00  20974.25
                                       -             23700.00  29290.00
                      Convertible      0.0           26900.00  28400.00
                                       -             32400.00  33750.00
                      Coupe            0.0           25990.00  26230.00
                                       -             26599.00  26599.00
                      Sedan            0.0           22900.00  24950.00
                                       -             27450.00  28445.00
Fiat Topolino Lotus   Coupe            0.0           27900.00  27900.00
Ford Kuga             Off-Road/Pick-Up 0.0           32900.00  36150.00
Ford Mustang          Off-Road/Pick-Up 0.0           71250.00  71250.00
Ford Mustang Mach-E   Coupe            -             64500.00  64500.00
                      Off-Road/Pick-Up 0.0           62900.00  64650.00
                                       -             55975.00  64622.50
                      Sedan            0.0           64400.00  64400.00
                                       -             54975.00  57476.25
Hyundai Ioniq         Compact          0.0           33900.00  33900.00
                      Sedan            0.0           26950.00  32700.00
Hyundai Kona          Off-Road/Pick-Up 0.0           25990.00  27990.00
Mercedes-Benz Eqa     Off-Road/Pick-Up 0.0           57200.00  57625.00
                                       -             54850.00  54850.00
                      Sedan            -             61485.00  61485.00
Mercedes-Benz Eqb 350 Off-Road/Pick-Up 0.0           64900.00  64900.00
                                       -             62900.00  65950.00
Mercedes-Benz Eqc 400 Off-Road/Pick-Up 0.0           64900.00  70972.75
                                       -             69580.00  71453.75
Mercedes-Benz Eqe 350 Compact          0.0           80900.00  80900.00
                      Sedan            0.0           80100.00  82550.00
                                       -             86370.00  92895.00
                      Station Wagon    -             87879.00  87879.00
Mercedes-Benz Eqs     Compact          -            117500.00 120000.00
                      Sedan            0.0          109950.00 124975.00
                                       -             99290.00 110890.00
                      Station Wagon    -             98879.00 100189.00
Nissan Leaf           Compact          0.0           12999.00  21500.00
                                       -             10450.00  14850.00
                      Sedan            0.0           13200.00  20650.00
                                       1.0           20990.00  20990.00
                                       -             13290.00  21980.00
                      Station Wagon    0.0           11000.00  11000.00
Opel Corsa            Compact          0.0           28000.00  28000.00
Opel Mokka            Off-Road/Pick-Up 0.0           25500.00  25500.00
Peugeot 2008          Off-Road/Pick-Up 0.0           29999.00  29999.00
                      Station Wagon    0.0           33990.00  34212.50
Peugeot 208           Compact          0.0           29995.00  30230.00
                      Sedan            0.0           22980.00  24869.25
Peugeot 308           Sedan            0.0           33355.00  33355.00
Peugeot 508           Sedan            0.0           34173.00  34173.00
Peugeot E-2008        Off-Road/Pick-Up -             35989.00  35989.00
                      Station Wagon    0.0           36799.00  37024.00
Peugeot E-208         Compact          0.0           23999.00  25499.00
                                       -             29995.00  30720.00
Peugeot Ion           Compact          0.0            9990.00   9990.00
Peugeot Partner       Station Wagon    0.0           15990.00  16180.00
                                       1.0           14990.00  14990.00
Renault Arkana        Coupe            132.0         27500.00  27500.00
Renault R 11          Sedan            0.0           10490.00  10490.00
Renault R 9           Sedan            0.0           10490.00  10740.00
Renault Twingo        Compact          0.0           14980.00  15945.00
Renault Twizy         Compact          0.0            6490.00   7465.00
                                       -              6500.00   7745.00
                      Convertible      -              5900.00   5900.00
                      Coupe            0.0            5500.00   5623.75
                                       -              3999.00   6249.50
                      Off-Road/Pick-Up -              7445.00   7571.25
Renault Zoe           Compact          0.0           12500.00  15250.00
                                       -              9945.00  11950.00
                      Convertible      0.0           21999.00  21999.00
                      Sedan            0.0            8500.00  12950.00
                                       -             13990.00  16290.00
Skoda Enyaq           Off-Road/Pick-Up 0.0           56900.00  58900.00
                                       -             48995.00  54995.00
                      Sedan            -             61930.00  61930.00
Toyota Proace         Station Wagon    0.0           40999.00  40999.00
Toyota Rav 4          Off-Road/Pick-Up 0.0           46750.00  46750.00
Volvo S90             Sedan            0.0           51900.00  51900.00
Volvo Xc90            Off-Road/Pick-Up 0.0           55900.00  55900.00

                                                          50%       75%
make_model            body_type        co_emissions
Dacia Spring          Compact          -             22985.00  22985.00  \
                      Off-Road/Pick-Up 0.0           17494.50  17992.25
                                       -             22980.00  22980.00
                      Sedan            0.0           18400.00  18400.00
                                       -             21599.00  21607.00
Fiat 500              Compact          0.0           26850.00  31922.50
                      Convertible      0.0           29700.00  31225.00
                      Coupe            0.0           30800.00  34150.00
                      Sedan            0.0           27400.00  28200.00
Fiat 500E             Compact          0.0           23499.00  25349.25
                                       -             32950.00  32990.00
                      Convertible      0.0           29700.00  30850.00
                                       -             33999.00  34990.00
                      Coupe            0.0           26470.00  26710.00
                                       -             26599.00  26599.00
                      Sedan            0.0           26699.00  29270.00
                                       -             28700.00  30249.50
Fiat Topolino Lotus   Coupe            0.0           27900.00  27900.00
Ford Kuga             Off-Road/Pick-Up 0.0           39400.00  39650.00
Ford Mustang          Off-Road/Pick-Up 0.0           71250.00  71250.00
Ford Mustang Mach-E   Coupe            -             64500.00  64500.00
                      Off-Road/Pick-Up 0.0           66400.00  68150.00
                                       -             68470.00  69990.00
                      Sedan            0.0           64400.00  64400.00
                                       -             59977.50  62478.75
Hyundai Ioniq         Compact          0.0           33900.00  33900.00
                      Sedan            0.0           38450.00  44200.00
Hyundai Kona          Off-Road/Pick-Up 0.0           32900.00  33800.00
Mercedes-Benz Eqa     Off-Road/Pick-Up 0.0           58050.00  58475.00
                                       -             54850.00  54850.00
                      Sedan            -             61485.00  61485.00
Mercedes-Benz Eqb 350 Off-Road/Pick-Up 0.0           64900.00  64900.00
                                       -             67790.00  69200.00
Mercedes-Benz Eqc 400 Off-Road/Pick-Up 0.0           75498.50  80975.00
                                       -             75389.50  79224.25
Mercedes-Benz Eqe 350 Compact          0.0           80900.00  80900.00
                      Sedan            0.0           85000.00  87450.00
                                       -             95999.00  98337.50
                      Station Wagon    -             87879.00  87879.00
Mercedes-Benz Eqs     Compact          -            122500.00 145472.00
                      Sedan            0.0          140000.00 145684.50
                                       -            122470.00 143165.00
                      Station Wagon    -            101499.00 139689.00
Nissan Leaf           Compact          0.0           24900.00  28490.00
                                       -             24390.00  26900.00
                      Sedan            0.0           21740.00  23747.50
                                       1.0           20990.00  20990.00
                                       -             25900.00  32000.00
                      Station Wagon    0.0           11000.00  11000.00
Opel Corsa            Compact          0.0           28000.00  28000.00
Opel Mokka            Off-Road/Pick-Up 0.0           25500.00  25500.00
Peugeot 2008          Off-Road/Pick-Up 0.0           29999.00  29999.00
                      Station Wagon    0.0           34435.00  34657.50
Peugeot 208           Compact          0.0           30465.00  30480.00
                      Sedan            0.0           27889.50  29609.75
Peugeot 308           Sedan            0.0           33355.00  33355.00
Peugeot 508           Sedan            0.0           34173.00  34173.00
Peugeot E-2008        Off-Road/Pick-Up -             35989.00  35989.00
                      Station Wagon    0.0           37199.00  37749.00
Peugeot E-208         Compact          0.0           26999.00  28499.00
                                       -             31445.00  31697.50
Peugeot Ion           Compact          0.0            9990.00   9990.00
Peugeot Partner       Station Wagon    0.0           16370.00  16560.00
                                       1.0           14990.00  14990.00
Renault Arkana        Coupe            132.0         27500.00  27500.00
Renault R 11          Sedan            0.0           10490.00  10490.00
Renault R 9           Sedan            0.0           10990.00  11140.00
Renault Twingo        Compact          0.0           16910.00  17875.00
Renault Twizy         Compact          0.0            8440.00   9415.00
                                       -              8990.00  11990.00
                      Convertible      -              5900.00   5900.00
                      Coupe            0.0            5747.50   5871.25
                                       -              8500.00  10249.50
                      Off-Road/Pick-Up -              7697.50   7823.75
Renault Zoe           Compact          0.0           17995.00  19924.75
                                       -             20950.00  24412.50
                      Convertible      0.0           21999.00  21999.00
                      Sedan            0.0           14990.00  18422.50
                                       -             17240.00  22142.50
Skoda Enyaq           Off-Road/Pick-Up 0.0           60900.00  62900.00
                                       -             57492.00  62649.75
                      Sedan            -             61930.00  61930.00
Toyota Proace         Station Wagon    0.0           40999.00  40999.00
Toyota Rav 4          Off-Road/Pick-Up 0.0           46750.00  46750.00
Volvo S90             Sedan            0.0           51900.00  51900.00
Volvo Xc90            Off-Road/Pick-Up 0.0           64400.00  72900.00

                                                          max
make_model            body_type        co_emissions
Dacia Spring          Compact          -             23090.00
                      Off-Road/Pick-Up 0.0           18490.00
                                       -             22980.00
                      Sedan            0.0           18400.00
                                       -             27044.00
Fiat 500              Compact          0.0           33000.00

**It seems more sensible/rational to impute missing values in two stages:**

- With the ``Mode`` value of Electric feature for ``Electric cars``.

- With the ``Median`` values of related make_model, body_type and fuel_type features for the ``others``.

In [118]:
# Let's replace dash/hyphen sign "-" with np.nan

df["co_emissions"].replace("-", np.nan, inplace=True)

In [119]:
# Let's explore CO Emission values of Electric Vehicles

df.loc[df["fuel_type"] == "Electric", "co_emissions"]

1         0.00
93         NaN
94         NaN
108        NaN
1213      0.00
1226      0.00
1271      0.00
1273       NaN
1281       NaN
1283       NaN
1303       NaN
1304       NaN
1307      0.00
1326       NaN
1331       NaN
1341       NaN
1350       NaN
1361       NaN
1364       NaN
1369       NaN
1400       NaN
1416       NaN
1425       NaN
1427       NaN
1436      0.00
1447      0.00
1458      0.00
1513       NaN
1575       NaN
1628       NaN
1641       NaN
1777       NaN
1798       NaN
1998      0.00
2000       NaN
2004       NaN
2015      0.00
2045       NaN
2082       NaN
2084       NaN
2086       NaN
2099       NaN
2130       NaN
2144       NaN
2156       NaN
2161       NaN
2166      0.00
2182       NaN
2192       NaN
2199       NaN
2230       NaN
2246      0.00
2255       NaN
2272       NaN
2276       NaN
2278       NaN
2301      0.00
2312       NaN
2317       NaN
2322       NaN
2328       NaN
2331       NaN
2355       NaN
2356       NaN
2360       NaN
2372       NaN
2713      0.00
3663      0.00
4810       NaN
4819       NaN
4823      0.00
4826       NaN
4838       NaN
4840      0.00
4873       NaN
4886      0.00
4914      0.00
4923       NaN
4929       NaN
4939       NaN
4943      0.00
4952       NaN
4957       NaN
4963       NaN
4972       NaN
4973      0.00
4985       NaN
4986       NaN
4989       NaN
4998       NaN
5002       NaN
5026       NaN
5028       NaN
5040      0.00
5045       NaN
5046       NaN
5047       NaN
5051      0.00
5054       NaN
5067       NaN
5071       NaN
5074       NaN
5075       NaN
5080       NaN
5087       NaN
5093       NaN
5097       NaN
5100       NaN
5102       NaN
5116       NaN
5117       NaN
5120      0.00
5122       NaN
5129       NaN
5134      0.00
5140       NaN
5143       NaN
5148      0.00
5149      0.00
5163       NaN
5166       NaN
5167       NaN
5173       NaN
5199      0.00
5430       NaN
5748      0.00
5786       NaN
5816       NaN
5831    132.00
5919      0.00
5936       NaN
6166       NaN
6205       NaN
6795       NaN
6803      0.00
6810      0.00
6811       NaN
6824       NaN
6830       NaN
6835       NaN
6837       NaN
6839       NaN
6847       NaN
6849       NaN
6852       NaN
6854       NaN
6860       NaN
6869       NaN
6870       NaN
6874       NaN
6876       NaN
6878       NaN
6879      0.00
6882       NaN
6896       NaN
6907      0.00
6909       NaN
6912       NaN
6916      0.00
6918       NaN
6943       NaN
6951      0.00
6952       NaN
6958      0.00
6982      0.00
7060      0.00
7071      0.00
7102      0.00
7103      0.00
7113      0.00
7114      0.00
7116      0.00
7124      0.00
7127      0.00
7132      0.00
7156      0.00
7232      0.00
7316       NaN
7335      0.00
7397       NaN
7408       NaN
7461      0.00
7480      0.00
7525      0.00
8400       NaN
8670      0.00
8876      0.00
8899      0.00
9005      0.00
9070      0.00
9079      0.00
9082      0.00
9087      0.00
9088      0.00
9089      0.00
9091      0.00
9102      1.00
9152      0.00
9154      0.00
9366      0.00
9426      0.00
9428      0.00
9448      0.00
9455      0.00
9473      0.00
9481      0.00
9487      0.00
9501      0.00
9514       NaN
9515      0.00
9522       NaN
9524      0.00
9527       NaN
9532       NaN
9538       NaN
9539       NaN
9540       NaN
9544      0.00
9545      0.00
9603      0.00
9608       NaN
9620       NaN
9654      0.00
9692      0.00
9699      0.00
9706       NaN
9716      0.00
9720       NaN
9795      0.00
9859      0.00
9889      0.00
9894       NaN
9918       NaN
9984      0.00
10023      NaN
10033     0.00
10039      NaN
10069     0.00
10074     0.00
10098      NaN
10104     0.00
10183     0.00
10215     0.00
10246     0.00
10258     0.00
10467     0.00
10566      NaN
10617     0.00
10625     0.00
10630     0.00
10631     0.00
10668     0.00
11467      NaN
11479      NaN
11544     0.00
11558     0.00
11572     0.00
11577     0.00
11578     0.00
11595     0.00
11619     0.00
11620     0.00
11632     0.00
11640     0.00
11641      NaN
11648      NaN
11653     0.00
11655     0.00
11665     0.00
11672      NaN
11673     0.00
11676      NaN
11690      NaN
11730     0.00
11776     0.00
11801     0.00
13978     0.00
13995      NaN
14055      NaN
14057     0.00
14066      NaN
14118      NaN
14188      NaN
14196      NaN
14212      NaN
14235      NaN
14248      NaN
14277      NaN
14284      NaN
14300      NaN
14316      NaN
14317      NaN
14952      NaN
15141      NaN
15143      NaN
15144      NaN
15145      NaN
15146      NaN
15147      NaN
15148      NaN
15149      NaN
15150      NaN
15151      NaN
15152      NaN
15153      NaN
15155      NaN
15156      NaN
15157      NaN
15158      NaN
15159      NaN
15161      NaN
15166      NaN
15181      NaN
15182      NaN
15183      NaN
15184      NaN
15185      NaN
15186      NaN
15187      NaN
15214      NaN
15648     0.00
15667     0.00
15903      NaN
16296      NaN
16312      NaN
16315      NaN
16319      NaN
16344      NaN
16351      NaN
16405      NaN
16416      NaN
16471     0.00
17699     0.00
17701     0.00
17718     0.00
17720     0.00
18114     0.00
18716     0.00
18725     0.00
18726     0.00
18730     0.00
18733     0.00
18742     0.00
18752      NaN
18759      NaN
18774      NaN
18779      NaN
18782      NaN
18784      NaN
18785      NaN
18786      NaN
18787     0.00
18789      NaN
18794      NaN
18795      NaN
18796     0.00
18807      NaN
18812      NaN
18816      NaN
18817      NaN
18819     0.00
18822     0.00
18836     0.00
18861     0.00
18866      NaN
18880     0.00
18917     0.00
18964     0.00
18990      NaN
19025     0.00
19080     0.00
20076     0.00
20414      NaN
20464      NaN
20480      NaN
20484      NaN
20487      NaN
20507     0.00
20516     0.00
20523     0.00
20533     0.00
20534      NaN
20535      NaN
20536      NaN
20537     0.00
20539     0.00
20540     0.00
20546      NaN
20551      NaN
20552      NaN
20557     0.00
20562     0.00
20563     0.00
20571      NaN
20582     1.00
20599      NaN
20600     0.00
20602     0.00
21623      NaN
21937      NaN
21948     0.00
21955     0.00
21957     0.00
21958     0.00
21960      NaN
21963      NaN
21966      NaN
21979      NaN
21986      NaN
21990      NaN
21994      NaN
22004      NaN
22008      NaN
22028      NaN
22029      NaN
22047      NaN
22048     0.00
22185      NaN
22247     0.00
22775      NaN
22783     0.00
22823      NaN
23379     0.00
23809     0.00
23870     0.00
23951     0.00
24051     0.00
24092     0.00
24099     0.00
24123     0.00
24170     0.00
24173     0.00
24832     0.00
24851     0.00
26952     0.00
26985     0.00
27338     0.00
27367     0.00
28340     0.00
28528     0.00
Name: co_emissions, dtype: float64

In [120]:
# Let's see the occurances of unique CO Emission values for Electric Vehicles

df[df["fuel_type"] == "Electric"]["co_emissions"].value_counts(dropna=False)

co_emissions
NaN       252
0.00      185
1.00        2
132.00      1
Name: count, dtype: int64

In [121]:
# Let's explore CO Emission values of Vehicles which run with Benzine

df[df["fuel_type"] == "Benzine"]["co_emissions"].value_counts(dropna=False)

co_emissions
NaN       6017
0.00       673
124.00     241
119.00     235
114.00     217
115.00     199
99.00      199
139.00     187
125.00     179
108.00     179
149.00     172
123.00     165
138.00     164
129.00     157
178.00     154
109.00     151
110.00     148
130.00     146
145.00     146
126.00     139
112.00     132
134.00     131
117.00     130
120.00     125
113.00     121
127.00     121
88.00      120
128.00     119
107.00     115
116.00     114
111.00     114
155.00     112
93.00      111
133.00     111
121.00     109
154.00     107
140.00     106
104.00     106
148.00     102
122.00     100
103.00      98
105.00      95
136.00      92
166.00      91
159.00      89
142.00      88
156.00      87
144.00      85
118.00      85
135.00      84
92.00       83
106.00      83
164.00      83
102.00      80
147.00      79
171.00      79
161.00      78
158.00      78
152.00      77
137.00      77
132.00      73
174.00      72
191.00      72
96.00       71
95.00       71
131.00      70
167.00      69
143.00      66
153.00      65
273.00      65
169.00      65
218.00      63
175.00      63
170.00      62
97.00       60
177.00      58
230.00      58
165.00      57
185.00      56
146.00      53
101.00      52
229.00      52
141.00      52
179.00      52
98.00       51
157.00      51
173.00      50
196.00      50
168.00      49
150.00      49
184.00      49
194.00      48
180.00      48
181.00      47
160.00      47
162.00      46
176.00      45
190.00      45
212.00      42
195.00      42
34.00       41
219.00      41
200.00      41
163.00      40
85.00       39
261.00      38
209.00      38
26.00       36
151.00      36
41.00       36
197.00      36
225.00      35
94.00       34
275.00      33
76.00       33
192.00      32
289.00      32
263.00      32
234.00      32
248.00      31
199.00      31
284.00      30
268.00      30
64.00       30
84.00       29
253.00      28
215.00      27
187.00      26
42.00       26
182.00      26
280.00      25
189.00      25
38.00       24
220.00      24
279.00      24
226.00      23
242.00      23
89.00       23
100.00      23
186.00      23
75.00       22
214.00      22
245.00      22
183.00      22
211.00      22
288.00      22
188.00      21
40.00       21
217.00      21
270.00      20
39.00       20
254.00      20
202.00      19
216.00      19
205.00      19
236.00      18
86.00       18
193.00      18
31.00       18
201.00      17
49.00       17
91.00       17
210.00      17
79.00       17
299.00      16
35.00       16
208.00      16
246.00      15
278.00      15
204.00      15
262.00      15
235.00      15
252.00      15
87.00       14
259.00      14
198.00      14
90.00       14
250.00      13
232.00      13
203.00      13
221.00      13
244.00      12
172.00      12
47.00       12
238.00      12
25.00       12
83.00       12
213.00      12
247.00      12
285.00      12
206.00      11
54.00       11
256.00      11
258.00      11
277.00      10
78.00       10
1.00        10
298.00      10
32.00        9
249.00       9
311.00       9
281.00       9
287.00       8
44.00        8
46.00        8
267.00       8
237.00       8
251.00       8
223.00       8
240.00       8
260.00       8
282.00       8
255.00       8
224.00       8
207.00       8
82.00        7
295.00       7
239.00       7
292.00       7
265.00       7
306.00       6
29.00        6
228.00       6
51.00        6
330.00       6
312.00       6
296.00       6
22.00        5
14.00        5
28.00        5
269.00       5
37.00        5
283.00       5
66.00        5
222.00       5
52.00        5
68.00        5
33.00        5
257.00       5
241.00       4
243.00       4
271.00       4
55.00        4
81.00        4
50.00        4
274.00       4
320.00       4
276.00       4
327.00       4
322.00       4
303.00       4
27.00        3
300.00       3
227.00       3
43.00        3
36.00        3
319.00       3
324.00       3
310.00       3
15.00        3
17.00        3
30.00        3
231.00       3
233.00       2
8.00         2
400.00       2
336.00       2
10.00        2
24.00        2
293.00       2
290.00       2
45.00        2
65.00        2
340.00       2
56.00        2
48.00        2
16.00        2
9.00         1
316.00       1
910.00       1
71.00        1
307.00       1
314.00       1
420.00       1
313.00       1
339.00       1
294.00       1
342.00       1
394.00       1
350.00       1
399.00       1
398.00       1
345.00       1
308.00       1
377.00       1
19.00        1
13.00        1
20.00        1
335.00       1
317.00       1
21.00        1
348.00       1
18.00        1
373.00       1
344.00       1
341.00       1
59.00        1
23.00        1
70.00        1
321.00       1
338.00       1
266.00       1
326.00       1
304.00       1
328.00       1
5.00         1
3.00         1
272.00       1
332.00       1
343.00       1
73.00        1
53.00        1
Name: count, dtype: int64

In [122]:
# Let's fill the missing values for Electric Vehicles with mode

df.loc[df["fuel_type"] == "Electric", "co_emissions"] = df.loc[df["fuel_type"] == "Electric", "co_emissions"].fillna(df.loc[df["fuel_type"] == "Electric", "co_emissions"].mode()[0])
df.loc[df["fuel_type"] == "Electric", "co_emissions"]

1         0.00
93        0.00
94        0.00
108       0.00
1213      0.00
1226      0.00
1271      0.00
1273      0.00
1281      0.00
1283      0.00
1303      0.00
1304      0.00
1307      0.00
1326      0.00
1331      0.00
1341      0.00
1350      0.00
1361      0.00
1364      0.00
1369      0.00
1400      0.00
1416      0.00
1425      0.00
1427      0.00
1436      0.00
1447      0.00
1458      0.00
1513      0.00
1575      0.00
1628      0.00
1641      0.00
1777      0.00
1798      0.00
1998      0.00
2000      0.00
2004      0.00
2015      0.00
2045      0.00
2082      0.00
2084      0.00
2086      0.00
2099      0.00
2130      0.00
2144      0.00
2156      0.00
2161      0.00
2166      0.00
2182      0.00
2192      0.00
2199      0.00
2230      0.00
2246      0.00
2255      0.00
2272      0.00
2276      0.00
2278      0.00
2301      0.00
2312      0.00
2317      0.00
2322      0.00
2328      0.00
2331      0.00
2355      0.00
2356      0.00
2360      0.00
2372      0.00
2713      0.00
3663      0.00
4810      0.00
4819      0.00
4823      0.00
4826      0.00
4838      0.00
4840      0.00
4873      0.00
4886      0.00
4914      0.00
4923      0.00
4929      0.00
4939      0.00
4943      0.00
4952      0.00
4957      0.00
4963      0.00
4972      0.00
4973      0.00
4985      0.00
4986      0.00
4989      0.00
4998      0.00
5002      0.00
5026      0.00
5028      0.00
5040      0.00
5045      0.00
5046      0.00
5047      0.00
5051      0.00
5054      0.00
5067      0.00
5071      0.00
5074      0.00
5075      0.00
5080      0.00
5087      0.00
5093      0.00
5097      0.00
5100      0.00
5102      0.00
5116      0.00
5117      0.00
5120      0.00
5122      0.00
5129      0.00
5134      0.00
5140      0.00
5143      0.00
5148      0.00
5149      0.00
5163      0.00
5166      0.00
5167      0.00
5173      0.00
5199      0.00
5430      0.00
5748      0.00
5786      0.00
5816      0.00
5831    132.00
5919      0.00
5936      0.00
6166      0.00
6205      0.00
6795      0.00
6803      0.00
6810      0.00
6811      0.00
6824      0.00
6830      0.00
6835      0.00
6837      0.00
6839      0.00
6847      0.00
6849      0.00
6852      0.00
6854      0.00
6860      0.00
6869      0.00
6870      0.00
6874      0.00
6876      0.00
6878      0.00
6879      0.00
6882      0.00
6896      0.00
6907      0.00
6909      0.00
6912      0.00
6916      0.00
6918      0.00
6943      0.00
6951      0.00
6952      0.00
6958      0.00
6982      0.00
7060      0.00
7071      0.00
7102      0.00
7103      0.00
7113      0.00
7114      0.00
7116      0.00
7124      0.00
7127      0.00
7132      0.00
7156      0.00
7232      0.00
7316      0.00
7335      0.00
7397      0.00
7408      0.00
7461      0.00
7480      0.00
7525      0.00
8400      0.00
8670      0.00
8876      0.00
8899      0.00
9005      0.00
9070      0.00
9079      0.00
9082      0.00
9087      0.00
9088      0.00
9089      0.00
9091      0.00
9102      1.00
9152      0.00
9154      0.00
9366      0.00
9426      0.00
9428      0.00
9448      0.00
9455      0.00
9473      0.00
9481      0.00
9487      0.00
9501      0.00
9514      0.00
9515      0.00
9522      0.00
9524      0.00
9527      0.00
9532      0.00
9538      0.00
9539      0.00
9540      0.00
9544      0.00
9545      0.00
9603      0.00
9608      0.00
9620      0.00
9654      0.00
9692      0.00
9699      0.00
9706      0.00
9716      0.00
9720      0.00
9795      0.00
9859      0.00
9889      0.00
9894      0.00
9918      0.00
9984      0.00
10023     0.00
10033     0.00
10039     0.00
10069     0.00
10074     0.00
10098     0.00
10104     0.00
10183     0.00
10215     0.00
10246     0.00
10258     0.00
10467     0.00
10566     0.00
10617     0.00
10625     0.00
10630     0.00
10631     0.00
10668     0.00
11467     0.00
11479     0.00
11544     0.00
11558     0.00
11572     0.00
11577     0.00
11578     0.00
11595     0.00
11619     0.00
11620     0.00
11632     0.00
11640     0.00
11641     0.00
11648     0.00
11653     0.00
11655     0.00
11665     0.00
11672     0.00
11673     0.00
11676     0.00
11690     0.00
11730     0.00
11776     0.00
11801     0.00
13978     0.00
13995     0.00
14055     0.00
14057     0.00
14066     0.00
14118     0.00
14188     0.00
14196     0.00
14212     0.00
14235     0.00
14248     0.00
14277     0.00
14284     0.00
14300     0.00
14316     0.00
14317     0.00
14952     0.00
15141     0.00
15143     0.00
15144     0.00
15145     0.00
15146     0.00
15147     0.00
15148     0.00
15149     0.00
15150     0.00
15151     0.00
15152     0.00
15153     0.00
15155     0.00
15156     0.00
15157     0.00
15158     0.00
15159     0.00
15161     0.00
15166     0.00
15181     0.00
15182     0.00
15183     0.00
15184     0.00
15185     0.00
15186     0.00
15187     0.00
15214     0.00
15648     0.00
15667     0.00
15903     0.00
16296     0.00
16312     0.00
16315     0.00
16319     0.00
16344     0.00
16351     0.00
16405     0.00
16416     0.00
16471     0.00
17699     0.00
17701     0.00
17718     0.00
17720     0.00
18114     0.00
18716     0.00
18725     0.00
18726     0.00
18730     0.00
18733     0.00
18742     0.00
18752     0.00
18759     0.00
18774     0.00
18779     0.00
18782     0.00
18784     0.00
18785     0.00
18786     0.00
18787     0.00
18789     0.00
18794     0.00
18795     0.00
18796     0.00
18807     0.00
18812     0.00
18816     0.00
18817     0.00
18819     0.00
18822     0.00
18836     0.00
18861     0.00
18866     0.00
18880     0.00
18917     0.00
18964     0.00
18990     0.00
19025     0.00
19080     0.00
20076     0.00
20414     0.00
20464     0.00
20480     0.00
20484     0.00
20487     0.00
20507     0.00
20516     0.00
20523     0.00
20533     0.00
20534     0.00
20535     0.00
20536     0.00
20537     0.00
20539     0.00
20540     0.00
20546     0.00
20551     0.00
20552     0.00
20557     0.00
20562     0.00
20563     0.00
20571     0.00
20582     1.00
20599     0.00
20600     0.00
20602     0.00
21623     0.00
21937     0.00
21948     0.00
21955     0.00
21957     0.00
21958     0.00
21960     0.00
21963     0.00
21966     0.00
21979     0.00
21986     0.00
21990     0.00
21994     0.00
22004     0.00
22008     0.00
22028     0.00
22029     0.00
22047     0.00
22048     0.00
22185     0.00
22247     0.00
22775     0.00
22783     0.00
22823     0.00
23379     0.00
23809     0.00
23870     0.00
23951     0.00
24051     0.00
24092     0.00
24099     0.00
24123     0.00
24170     0.00
24173     0.00
24832     0.00
24851     0.00
26952     0.00
26985     0.00
27338     0.00
27367     0.00
28340     0.00
28528     0.00
Name: co_emissions, dtype: float64

In [123]:
# There have some anomalies in CO Emission values for some Electric Cars

df.loc[(df["fuel_type"] == "Electric") & (df["co_emissions"] != 0)][["fuel_type", "co_emissions"]]

      fuel_type  co_emissions
5831   Electric        132.00
9102   Electric          1.00
20582  Electric          1.00

In [124]:
df.iloc[5831]

make_model                                                  Renault Avantime
make                                                                 Renault
model                                                               Avantime
location                              Oostendestraat, 258,  8820 Torhout, BE
price                                                                4900.00
body_type                                                              Coupe
type                                                                    Used
doors                                                                   3.00
warranty                                                                 Yes
mileage                                                            152835.00
gearbox                                                               Manual
fuel_type                                                             Diesel
seller                                                                Dealer
seats                                                                   5.00
engine_size                                                          2188.00
gears                                                                   6.00
co_emissions                                                          193.00
drivetrain                                                               NaN
cylinders                                                               4.00
comfort_&_convenience      Air conditioning, Armrest, Automatic climate c...
entertainment_&_media                               On-board computer, Radio
safety_&_security          ABS, Central door lock, Driver-side airbag, Pa...
extras                                            Alloy wheels, Summer tyres
empty_weight                                                         1753.00
full_service_history                                                      No
upholstery                                                      Part leather
previous_owner                                                           NaN
energy_efficiency_class                                                  NaN
age                                                                    20.00
power_kW                                                              110.00
power_hp                                                              150.00
cons_avg                                                                7.30
cons_city                                                                NaN
cons_country                                                             NaN
Name: 5832, dtype: object

In [125]:
# let's explore "Renault Arkana" by "co_emissions"

df.loc[df["make_model"] == "Renault Arkana"][["gearbox", "fuel_type", "gears", "co_emissions"]]

        gearbox fuel_type  gears  co_emissions
5612  Automatic   Benzine   7.00           NaN
5615  Automatic   Benzine   7.00           NaN
5618  Automatic   Benzine   7.00           NaN
5622  Automatic   Benzine   7.00           NaN
5623  Automatic   Benzine   7.00           NaN
5624  Automatic   Benzine   7.00           NaN
5625  Automatic   Benzine   6.00           NaN
5626  Automatic   Benzine   7.00           NaN
5627  Automatic   Benzine   7.00        133.00
5637  Automatic   Benzine   7.00        132.00
5646  Automatic   Benzine   6.00           NaN
5664  Automatic   Benzine   7.00           NaN
5788  Automatic   Benzine   7.00        133.00
5831  Automatic  Electric   7.00        132.00
5839  Automatic   Benzine   7.00           NaN
5862  Automatic   Benzine   7.00           NaN
5886  Automatic   Benzine   7.00        135.00
5905  Automatic   Benzine   7.00           NaN
5943  Automatic   Benzine   7.00        132.00
5958  Automatic   Benzine   7.00        132.00
5963  Automatic   Benzine   7.00        131.00
5977  Automatic   Benzine   7.00        124.00
5994  Automatic   Benzine   7.00        124.00
5995  Automatic   Benzine   4.00           NaN
5996  Automatic   Benzine   7.00         96.00
5999  Automatic   Benzine   7.00        124.00
6003  Automatic   Benzine   7.00        100.00
6010  Automatic   Benzine   7.00        124.00
6022  Automatic   Benzine   7.00           NaN
6034  Automatic   Benzine   7.00         96.00
6053  Automatic   Benzine   7.00           NaN
6061  Automatic   Benzine   7.00        122.00
6062  Automatic   Benzine   7.00        124.00
6066  Automatic   Benzine   7.00           NaN
6081  Automatic   Benzine   7.00        124.00
6106  Automatic   Benzine   7.00        134.00
6116  Automatic   Benzine   7.00         96.00
6161  Automatic   Benzine   7.00         97.00
6172  Automatic   Benzine   7.00           NaN
6175  Automatic   Benzine   7.00        121.00
6182  Automatic   Benzine   7.00           NaN
6183  Automatic   Benzine   7.00           NaN
6192  Automatic   Benzine   7.00          0.00
6194  Automatic   Benzine   1.00         96.00
6198  Automatic   Benzine   7.00        124.00
6209  Automatic   Benzine   7.00        124.00
6210  Automatic   Benzine   7.00        124.00
6220  Automatic   Benzine   7.00          0.00
6226  Automatic   Benzine   7.00        122.00
6228  Automatic   Benzine   7.00        124.00
6231  Automatic   Benzine   7.00        124.00
6239  Automatic   Benzine   7.00           NaN
6255  Automatic   Benzine   7.00          0.00
6264  Automatic   Benzine   7.00        122.00
6266  Automatic   Benzine   7.00           NaN
6267  Automatic   Benzine   7.00        124.00
6273  Automatic   Benzine   7.00         96.00
6299  Automatic   Benzine   7.00          0.00
6317  Automatic   Benzine   7.00           NaN
6321  Automatic   Benzine   7.00           NaN
6788  Automatic   Benzine   7.00        124.00
6797  Automatic   Benzine   7.00        124.00
6838  Automatic   Benzine   7.00        124.00
7074  Automatic   Benzine   7.00        121.00

In [126]:
# According to the examination above, it's assumed that fuel type of that observation might be "Benzine"

# df.at[5831, "fuel_type"] = "Benzine" 
# df.loc[index, "fuel_type"] = "Benzine" 

df.iloc[5831, df.columns.get_loc("fuel_type")] = "Benzine"

In [127]:
df.loc[5831]["fuel_type"]

'Electric'

# Step-1

df['co_emissions'].fillna(df["co_emissions"].median(), inplace = True)

# Step-2

df['co_emissions'].fillna(df.groupby("make_model")["co_emissions"].transform("median"), inplace=True)

# Step-3

df['co_emissions'].fillna(df.groupby(["make_model", "body_type"])["co_emissions"].transform("median"), inplace=True)

# Step-3

df['co_emissions'].fillna(df.groupby(["make_model", "body_type", "fuel_type"])["co_emissions"].transform("median"), inplace=True)

In [128]:
# Let's remember and apply one of our DEFs for imputing missing values in "co_emissions"

def fill_median(df, group_col1, group_col2, group_col3, col_name):
    
    df[col_name].fillna(df.groupby([group_col1, group_col2, group_col3])[col_name].transform("median"), inplace = True)
    df[col_name].fillna(df.groupby([group_col1, group_col2])[col_name].transform("median"), inplace = True)
    df[col_name].fillna(df.groupby(group_col1)[col_name].transform("median"), inplace = True)
    df[col_name].fillna(df[col_name].median(), inplace = True)

    print("column name    : ", col_name)
    print("--------------------------------")
    print("per_of_nulls   : ", "%", round(df[col_name].isnull().sum()*100 / df.shape[0], 2))
    print("num_of_nulls   : ", df[col_name].isnull().sum())
    print("num_of_uniques : ", df[col_name].nunique())
    print("--------------------------------")
    print(df[col_name].value_counts(dropna = False))

In [129]:
# This DEF will fill the missing values in the "co_emissions" with the median value based on "make_model", "body_type", and "fuel_type"

fill_median(df, "make_model", "body_type", "fuel_type", "co_emissions")

column name    :  co_emissions
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  387
--------------------------------
co_emissions
0.00      1404
124.00    1149
115.00     704
99.00      588
119.00     567
89.00      549
129.00     527
117.00     498
139.00     467
109.00     456
108.00     453
114.00     410
113.00     386
110.00     379
123.00     374
104.00     363
116.00     358
130.00     351
120.00     335
138.00     331
149.00     327
127.00     310
125.00     307
112.00     288
105.00     272
107.00     257
111.00     250
93.00      250
273.00     236
178.00     235
128.00     233
98.00      233
126.00     230
145.00     229
102.00     224
118.00     217
96.00      216
135.00     215
121.00     213
137.00     210
276.00     208
142.00     206
95.00      204
148.00     200
85.00      199
155.00     197
133.00     196
131.00     194
122.00     193
143.00     191
106.00     190
167.00     189
154.00     184
134.00     182
169.00     175
147.00     173
144.00     170
185.00     168
232.00     166
156.00     166
166.00     162
88.00      161
103.00     160
159.00     159
132.00     155
136.00     155
140.00     148
158.00     145
162.00     144
92.00      143
94.00      142
196.00     140
161.00     137
101.00     135
97.00      133
230.00     124
170.00     124
146.00     117
150.00     117
194.00     109
151.00     109
153.00     107
164.00     105
87.00      102
152.00     101
174.00     100
248.00      94
173.00      92
141.00      91
180.00      91
165.00      90
171.00      88
184.00      85
193.00      84
90.00       84
191.00      83
168.00      76
175.00      76
160.00      76
84.00       75
177.00      74
218.00      73
79.00       72
100.00      71
157.00      70
195.00      63
179.00      63
219.00      62
163.00      60
275.00      58
181.00      58
226.00      57
190.00      57
101.50      56
82.00       56
229.00      55
106.50      53
189.00      53
234.00      52
176.00      51
199.00      50
107.50      49
212.00      47
34.00       46
209.00      46
250.00      46
192.00      45
42.00       44
91.00       44
200.00      43
217.00      43
225.00      42
183.00      41
261.00      41
257.00      40
197.00      40
182.00      39
49.00       39
41.00       39
125.50      38
26.00       38
187.00      36
210.00      36
186.00      35
289.00      33
76.00       33
172.00      32
263.00      32
220.00      32
253.00      32
214.00      32
280.00      31
211.00      31
268.00      31
188.00      31
88.50       30
86.00       30
112.50      30
64.00       30
284.00      30
38.00       30
215.00      30
47.00       29
242.00      29
238.00      28
94.50       28
131.50      28
87.50       28
40.00       27
116.50      27
198.00      26
216.00      26
202.00      25
39.00       25
279.00      24
3.00        24
254.00      24
247.00      24
205.00      22
22.00       22
75.00       22
245.00      22
288.00      22
121.50      21
36.00       21
35.00       21
236.00      20
270.00      20
201.00      19
276.50      19
222.50      19
208.00      19
252.00      18
1.00        18
31.00       18
48.00       18
54.00       18
223.00      18
262.00      17
246.00      17
203.00      16
299.00      16
235.00      16
260.00      16
32.00       16
204.00      16
278.00      15
213.00      15
46.00       15
259.00      15
330.00      14
83.00       14
50.00       14
224.00      14
206.00      14
295.00      14
138.50      14
244.00      14
133.50      14
186.50      14
221.00      13
146.50      13
25.00       13
207.00      13
285.00      12
44.00       11
141.50      11
281.00      11
126.50      11
256.00      11
258.00      11
222.00      10
51.00       10
228.00      10
277.00      10
78.00       10
152.50      10
282.00      10
240.00      10
298.00      10
249.00      10
231.00      10
336.00       9
239.00       9
37.00        9
227.00       9
311.00       9
33.00        9
171.50       9
103.50       9
178.50       9
28.00        8
29.00        8
287.00       8
66.00        8
52.00        8
237.00       8
255.00       8
350.00       8
59.00        8
10.00        8
267.00       8
110.50       8
292.00       8
251.00       8
265.00       7
293.00       7
306.00       6
104.50       6
312.00       6
296.00       6
55.00        6
14.00        5
310.00       5
43.00        5
327.00       5
283.00       5
68.00        5
149.50       5
30.00        5
269.00       5
27.00        4
243.00       4
322.00       4
271.00       4
199.50       4
170.50       4
274.00       4
24.00        4
320.00       4
241.00       4
203.50       4
303.00       4
156.50       4
261.50       4
142.50       4
81.00        4
139.50       3
18.00        3
300.00       3
113.50       3
17.00        3
0.50         3
324.00       3
15.00        3
319.00       3
136.50       3
188.50       3
99.50        3
45.00        2
120.50       2
55.50        2
8.00         2
56.00        2
227.50       2
75.50        2
179.50       2
414.00       2
23.00        2
190.50       2
63.50        2
290.00       2
264.00       2
65.00        2
400.00       2
233.00       2
16.00        2
56.50        2
332.00       2
7.00         2
308.00       2
340.00       2
394.00       1
294.00       1
157.50       1
339.00       1
313.00       1
321.00       1
399.00       1
377.00       1
169.50       1
314.00       1
71.00        1
420.00       1
940.00       1
307.00       1
9.00         1
338.00       1
167.50       1
326.00       1
304.00       1
328.00       1
272.00       1
63.00        1
341.00       1
123.50       1
910.00       1
343.00       1
95.50        1
5.00         1
80.00        1
127.50       1
111.50       1
197.50       1
108.50       1
266.00       1
118.50       1
37.50        1
216.50       1
21.00        1
317.00       1
335.00       1
128.50       1
73.00        1
20.00        1
19.00        1
70.00        1
345.00       1
13.00        1
348.00       1
373.00       1
342.00       1
398.00       1
316.00       1
344.00       1
146.75       1
53.00        1
Name: count, dtype: int64

## cylinders

In [130]:
# Let's explore basic information about "cylinders"

first_looking("cylinders")

COLUMN NAME    :  cylinders
--------------------------------
per_of_nulls   :  % 34.14
num_of_nulls   :  9773
num_of_uniques :  12
--------------------------------
cylinders
4.00     13068
NaN       9773
3.00      3258
6.00      1012
5.00       799
8.00       539
2.00       103
0.00        35
1.00        21
12.00        8
7.00         6
26.00        1
16.00        1
Name: count, dtype: int64

In [131]:
# All NaN values are converted to dash/hyphen sign "-" to see them in the output of describe() and explore the hidden pattern

df["cylinders"].fillna("-", inplace=True)

In [132]:
# let's explore if there is any pattern among "make_model", "body_type", "age", and "cylinders" by "price"

df.groupby(["make_model", "body_type", "age", "cylinders"]).price.describe()

                                                    count     mean     std
make_model        body_type        age   cylinders
Dacia 1300        Sedan            47.00 4.0         1.00  9999.00     NaN  \
Dacia Break       Station Wagon    0.00  -           1.00 20500.00     NaN
Dacia Business    Compact          1.00  -           1.00 19515.00     NaN
Dacia Comfort Tce Station Wagon    0.00  -           1.00 21799.00     NaN
Dacia Dokker      Compact          4.00  -           1.00 11930.00     NaN
...                                                   ...      ...     ...
Volvo Xc90        Off-Road/Pick-Up 18.00 5.0         2.00  6799.00    0.00
                  Sedan            1.00  -           1.00 84900.00     NaN
                                   3.00  -           1.00 48500.00     NaN
                                   4.00  -           1.00 47700.00     NaN
                  Station Wagon    6.00  4.0         4.00 32750.00 3752.78

                                                        min      25%      50%
make_model        body_type        age   cylinders
Dacia 1300        Sedan            47.00 4.0        9999.00  9999.00  9999.00  \
Dacia Break       Station Wagon    0.00  -         20500.00 20500.00 20500.00
Dacia Business    Compact          1.00  -         19515.00 19515.00 19515.00
Dacia Comfort Tce Station Wagon    0.00  -         21799.00 21799.00 21799.00
Dacia Dokker      Compact          4.00  -         11930.00 11930.00 11930.00
...                                                     ...      ...      ...
Volvo Xc90        Off-Road/Pick-Up 18.00 5.0        6799.00  6799.00  6799.00
                  Sedan            1.00  -         84900.00 84900.00 84900.00
                                   3.00  -         48500.00 48500.00 48500.00
                                   4.00  -         47700.00 47700.00 47700.00
                  Station Wagon    6.00  4.0       29500.00 29500.00 32750.00

                                                        75%      max
make_model        body_type        age   cylinders
Dacia 1300        Sedan            47.00 4.0        9999.00  9999.00
Dacia Break       Station Wagon    0.00  -         20500.00 20500.00
Dacia Business    Compact          1.00  -         19515.00 19515.00
Dacia Comfort Tce Station Wagon    0.00  -         21799.00 21799.00
Dacia Dokker      Compact          4.00  -         11930.00 11930.00
...                                                     ...      ...
Volvo Xc90        Off-Road/Pick-Up 18.00 5.0        6799.00  6799.00
                  Sedan            1.00  -         84900.00 84900.00
                                   3.00  -         48500.00 48500.00
                                   4.00  -         47700.00 47700.00
                  Station Wagon    6.00  4.0       36000.00 36000.00

[7474 rows x 8 columns]

In [133]:
# Let's replace dash/hyphen sign "-" with np.nan

df["cylinders"].replace("-", np.nan, inplace=True)

In [134]:
# This DEF will fill the missing values in the "cylinders" with the mode value based on "make_model" and "body_type"

fill(df, "make_model", "body_type", "cylinders", "mode")

COLUMN NAME    :  cylinders
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  12
--------------------------------
cylinders
0.00       187
1.00       137
2.00       107
3.00      5152
4.00     19804
5.00       970
6.00      1311
7.00         6
8.00       937
12.00       11
16.00        1
26.00        1
Name: count, dtype: int64

<div style="background-color: #FFB6C1; padding: 10px; font-size: 16px; font-weight: bold;">
    However, it is preferred to drop the <code>cylinders</code> feature in this analysis since there have been some other features, such as <code>hp</code>, <code>engine_size</code>, and <code>empty_weight</code>, having fewer missing values and giving similar insight. So it's assumed to continue without the <code>cylinders</code> feature in this analysis.
</div>

In [135]:
df.shape

(28624, 34)

In [136]:
df.drop("cylinders", axis=1, inplace=True)

In [137]:
df.shape

(28624, 33)

## power_kW

In [138]:
# Let's explore basic information about "power_kW"

first_looking("power_kW")

COLUMN NAME    :  power_kW
--------------------------------
per_of_nulls   :  % 1.99
num_of_nulls   :  571
num_of_uniques :  351
--------------------------------
power_kW
110.00    1992
96.00     1356
88.00     1182
81.00     1166
66.00     1110
103.00    1033
85.00     1002
74.00      892
140.00     787
51.00      701
70.00      685
100.00     681
NaN        571
55.00      514
92.00      477
147.00     458
125.00     422
120.00     418
80.00      349
132.00     339
90.00      318
135.00     296
173.00     249
118.00     247
115.00     246
130.00     241
84.00      240
77.00      236
221.00     234
150.00     232
206.00     224
67.00      213
82.00      204
63.00      200
145.00     199
97.00      185
53.00      176
104.00     162
288.00     155
59.00      149
143.00     143
73.00      139
184.00     138
121.00     134
44.00      133
60.00      133
180.00     130
165.00     130
75.00      128
68.00      127
202.00     126
107.00     124
54.00      120
190.00     119
331.00     118
241.00     116
162.00     115
52.00      112
99.00      111
228.00     105
225.00     104
169.00     103
87.00      102
133.00     100
310.00      99
105.00      99
50.00       99
112.00      98
65.00       97
117.00      92
114.00      89
270.00      86
49.00       84
62.00       83
250.00      81
213.00      81
108.00      80
243.00      79
155.00      79
245.00      76
142.00      70
287.00      64
64.00       63
116.00      63
160.00      63
223.00      60
195.00      60
136.00      59
113.00      56
320.00      55
194.00      53
350.00      51
375.00      51
98.00       50
72.00       50
300.00      50
154.00      49
176.00      49
79.00       48
336.00      47
43.00       45
338.00      45
93.00       44
224.00      43
233.00      43
430.00      43
192.00      42
33.00       42
200.00      41
101.00      40
71.00       39
86.00       39
330.00      39
102.00      38
251.00      37
215.00      36
265.00      36
177.00      36
91.00       36
185.00      35
210.00      34
419.00      34
134.00      34
48.00       33
78.00       32
138.00      32
280.00      32
129.00      31
450.00      30
191.00      30
137.00      29
231.00      28
170.00      27
128.00      26
152.00      26
157.00      26
186.00      25
83.00       25
175.00      25
76.00       24
95.00       24
61.00       24
410.00      24
285.00      24
232.00      24
57.00       23
40.00       22
253.00      22
163.00      21
141.00      21
235.00      20
199.00      20
119.00      20
205.00      20
220.00      19
151.00      19
335.00      19
158.00      19
257.00      18
298.00      17
122.00      16
56.00       15
227.00      15
123.00      14
404.00      14
187.00      14
153.00      14
308.00      14
166.00      13
156.00      13
201.00      13
208.00      13
168.00      13
47.00       12
178.00      12
294.00      12
109.00      11
139.00      11
386.00      11
69.00       11
172.00      11
258.00      11
127.00      10
13.00       10
239.00      10
390.00      10
182.00      10
94.00       10
212.00      10
405.00       9
559.00       9
198.00       9
343.00       9
188.00       9
35.00        9
149.00       9
207.00       8
124.00       8
385.00       8
324.00       8
131.00       8
470.00       7
18.00        7
380.00       7
299.00       7
370.00       7
345.00       7
146.00       6
271.00       6
174.00       6
111.00       6
295.00       6
203.00       6
148.00       6
37.00        6
32.00        6
392.00       6
368.00       6
240.00       6
353.00       6
307.00       6
360.00       5
1.00         5
357.00       5
126.00       5
167.00       5
248.00       5
286.00       5
230.00       5
17.00        5
193.00       5
279.00       4
214.00       4
340.00       4
441.00       4
400.00       4
246.00       4
420.00       4
196.00       4
45.00        4
309.00       4
339.00       4
106.00       4
487.00       4
313.00       4
25.00        3
387.00       3
58.00        3
38.00        3
8.00         3
588.00       3
216.00       3
89.00        3
229.00       3
218.00       3
293.00       3
567.00       3
36.00        3
484.00       3
29.00        3
266.00       3
46.00        3
463.00       2
412.00       2
244.00       2
552.00       2
363.00       2
292.00       2
312.00       2
31.00        2
209.00       2
316.00       2
9.00         2
7.00         2
274.00       2
4.00         2
222.00       2
12.00        2
290.00       2
23.00        2
19.00        2
189.00       2
161.00       2
14.00        2
346.00       2
34.00        2
311.00       2
267.00       2
662.00       2
358.00       2
354.00       2
485.00       1
328.00       1
238.00       1
39.00        1
342.00       1
303.00       1
6.00         1
530.00       1
551.00       1
493.00       1
234.00       1
332.00       1
372.00       1
499.00       1
144.00       1
365.00       1
341.00       1
255.00       1
3.00         1
403.00       1
325.00       1
527.00       1
237.00       1
254.00       1
217.00       1
20.00        1
30.00        1
10.00        1
42.00        1
22.00        1
27.00        1
16.00        1
24.00        1
384.00       1
15.00        1
41.00        1
409.00       1
537.00       1
373.00       1
378.00       1
242.00       1
924.00       1
236.00       1
810.00       1
21.00        1
183.00       1
496.00       1
664.00       1
600.00       1
327.00       1
478.00       1
665.00       1
284.00       1
883.00       1
296.00       1
164.00       1
746.00       1
570.00       1
471.00       1
179.00       1
26.00        1
Name: count, dtype: int64

In [139]:
# All NaN values are converted to dash/hyphen sign "-" to see them in the output of describe() and explore the hidden pattern

df["power_kW"].fillna("-", inplace=True)

In [140]:
# let's explore if there is any pattern among "make_model", "body_type", and "power_kW" by "price"

df.groupby(["make_model", "body_type", "power_kW"]).price.describe()

                                             count     mean     std      min
make_model        body_type        power_kW
Dacia 1300        Sedan            40.0       1.00  9999.00     NaN  9999.00  \
Dacia Break       Station Wagon    -          1.00 20500.00     NaN 20500.00
Dacia Business    Compact          33.0       1.00 19515.00     NaN 19515.00
Dacia Comfort Tce Station Wagon    81.0       1.00 21799.00     NaN 21799.00
Dacia Dokker      Compact          66.0       1.00 11930.00     NaN 11930.00
...                                            ...      ...     ...      ...
Volvo Xc90        Off-Road/Pick-Up 294.0      6.00 50793.33 6277.64 42790.00
                                   300.0      2.00 44200.00    0.00 44200.00
                  Sedan            173.0      2.00 48100.00  565.69 47700.00
                                   223.0      1.00 84900.00     NaN 84900.00
                  Station Wagon    165.0      4.00 32750.00 3752.78 29500.00

                                                 25%      50%      75%
make_model        body_type        power_kW
Dacia 1300        Sedan            40.0      9999.00  9999.00  9999.00  \
Dacia Break       Station Wagon    -        20500.00 20500.00 20500.00
Dacia Business    Compact          33.0     19515.00 19515.00 19515.00
Dacia Comfort Tce Station Wagon    81.0     21799.00 21799.00 21799.00
Dacia Dokker      Compact          66.0     11930.00 11930.00 11930.00
...                                              ...      ...      ...
Volvo Xc90        Off-Road/Pick-Up 294.0    45515.00 53690.00 55347.50
                                   300.0    44200.00 44200.00 44200.00
                  Sedan            173.0    47900.00 48100.00 48300.00
                                   223.0    84900.00 84900.00 84900.00
                  Station Wagon    165.0    29500.00 32750.00 36000.00

                                                 max
make_model        body_type        power_kW
Dacia 1300        Sedan            40.0      9999.00
Dacia Break       Station Wagon    -        20500.00
Dacia Business    Compact          33.0     19515.00
Dacia Comfort Tce Station Wagon    81.0     21799.00
Dacia Dokker      Compact          66.0     11930.00
...                                              ...
Volvo Xc90        Off-Road/Pick-Up 294.0    55900.00
                                   300.0    44200.00
                  Sedan            173.0    48500.00
                                   223.0    84900.00
                  Station Wagon    165.0    36000.00

[5014 rows x 8 columns]

In [141]:
df.loc[df["power_kW"] == "-"][["make_model", "body_type", "power_kW", "power_hp", "engine_size", "fuel_type"]]

,make_model,body_type,power_kW,power_hp,engine_size,fuel_type
0,Mercedes-Benz A 160,Compact,-,NaN,1595.00,Diesel
6,Mercedes-Benz Cla 180,Compact,-,NaN,1595.00,Diesel
94,Mercedes-Benz Eqs,Compact,-,NaN,0.00,Electric
100,Mercedes-Benz A 200,Compact,-,NaN,1337.00,Benzine
114,Mercedes-Benz A 200,Compact,-,NaN,1337.00,Benzine
...,...,...,...,...,...,...
26831,Volvo Xc60,Off-Road/Pick-Up,-,NaN,1969.00,Diesel
27220,Volvo Xc60,Off-Road/Pick-Up,-,NaN,1969.00,Diesel
27804,Volvo 240,Station Wagon,-,NaN,2316.00,Benzine
28184,Volvo 240,Station Wagon,-,NaN,2316.00,Benzine
28608,Volvo Xc60,Sedan,-,NaN,1969.00,Benzine

<div style="background-color: #ffeeba; padding: 10px; font-size: 16px; font-weight: bold;">
    Domain Knowledge demonstrates that the <code>kW</code> of cars might change by their <code>make_models</code> and <code>body_types</code> most of the time. So it's decided to fill missing values with <code>mode value</code> of corresponding group.
</div>

In [142]:
# Let's replace dash/hyphen sign "-" with np.nan

df["power_kW"].replace(["-"], np.nan, inplace=True)

In [143]:
# This DEF will fill the missing values in the "power_kW" with the mode value based on "make_model" and "body_type"

fill(df, "make_model", "body_type", "power_kW", "mode")

COLUMN NAME    :  power_kW
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  351
--------------------------------
power_kW
1.00         5
3.00         1
4.00         5
6.00         1
7.00         2
8.00         3
9.00         2
10.00        1
12.00        2
13.00       10
14.00        2
15.00        1
16.00        1
17.00        5
18.00        7
19.00        2
20.00        1
21.00        2
22.00        1
23.00        2
24.00        1
25.00        4
26.00        1
27.00        1
29.00        3
30.00        1
31.00        2
32.00        6
33.00       42
34.00        2
35.00        9
36.00        3
37.00        6
38.00        3
39.00        1
40.00       22
41.00        1
42.00        1
43.00       54
44.00      135
45.00        4
46.00        3
47.00       13
48.00       33
49.00       84
50.00      100
51.00      707
52.00      112
53.00      184
54.00      120
55.00      522
56.00       15
57.00       23
58.00        3
59.00      149
60.00      133
61.00       24
62.00       85
63.00      200
64.00       66
65.00       99
66.00     1151
67.00      213
68.00      132
69.00       11
70.00      696
71.00       39
72.00       51
73.00      139
74.00      915
75.00      130
76.00       24
77.00      238
78.00       32
79.00       48
80.00      356
81.00     1186
82.00      216
83.00       25
84.00      240
85.00     1052
86.00       39
87.00      127
88.00     1202
89.00        3
90.00      324
91.00       36
92.00      477
93.00       44
94.00       10
95.00       24
96.00     1426
97.00      187
98.00       50
99.00      111
100.00     700
101.00      40
102.00      38
103.00    1055
104.00     170
105.00      99
106.00       4
107.00     124
108.00      81
109.00      11
110.00    2019
111.00       6
112.00      98
113.00      56
114.00      89
115.00     248
116.00      79
117.00      92
118.00     258
119.00      20
120.00     422
121.00     134
122.00      16
123.00      15
124.00       8
125.00     424
126.00       5
127.00      10
128.00      26
129.00      31
130.00     252
131.00       8
132.00     344
133.00     100
134.00      34
135.00     315
136.00      59
137.00      29
138.00      32
139.00      11
140.00     790
141.00      21
142.00      70
143.00     143
144.00       1
145.00     205
146.00       6
147.00     460
148.00       6
149.00       9
150.00     234
151.00      19
152.00      26
153.00      14
154.00      49
155.00      79
156.00      13
157.00      26
158.00      19
160.00      65
161.00       2
162.00     116
163.00      21
164.00       1
165.00     130
166.00      13
167.00       5
168.00      13
169.00     103
170.00      27
172.00      11
173.00     249
174.00       6
175.00      25
176.00      49
177.00      36
178.00      15
179.00       1
180.00     130
182.00      11
183.00       1
184.00     138
185.00      35
186.00      25
187.00      14
188.00       9
189.00       2
190.00     119
191.00      30
192.00      42
193.00       5
194.00      53
195.00      60
196.00       4
198.00       9
199.00      20
200.00      41
201.00      13
202.00     129
203.00       6
205.00      20
206.00     224
207.00       8
208.00      13
209.00       2
210.00      34
212.00      10
213.00      81
214.00       4
215.00      37
216.00       3
217.00       1
218.00       3
220.00      19
221.00     234
222.00       2
223.00      60
224.00      43
225.00     104
227.00      15
228.00     105
229.00       3
230.00       5
231.00      28
232.00      24
233.00      43
234.00       1
235.00      20
236.00       1
237.00       1
238.00       1
239.00      10
240.00       7
241.00     116
242.00       1
243.00      79
244.00       2
245.00      76
246.00       4
248.00       5
250.00      81
251.00      37
253.00      22
254.00       1
255.00       1
257.00      18
258.00      11
265.00      36
266.00       3
267.00       2
270.00      86
271.00       6
274.00       2
279.00       4
280.00      32
284.00       1
285.00      24
286.00       5
287.00      64
288.00     155
290.00       2
292.00       2
293.00       3
294.00      12
295.00       6
296.00       1
298.00      17
299.00       7
300.00      50
303.00       1
307.00       6
308.00      14
309.00       4
310.00      99
311.00       2
312.00       2
313.00       4
316.00       2
320.00      55
324.00       8
325.00       1
327.00       1
328.00       1
330.00      39
331.00     170
332.00       1
335.00      19
336.00      47
338.00      45
339.00       4
340.00       4
341.00       1
342.00       1
343.00       9
345.00       7
346.00       2
350.00      51
353.00       6
354.00       2
357.00       5
358.00       2
360.00       5
363.00       2
365.00       1
368.00       6
370.00       7
372.00       1
373.00       1
375.00      51
378.00       1
380.00       7
384.00       1
385.00       8
386.00      11
387.00       3
390.00      10
392.00       6
400.00       4
403.00       1
404.00      14
405.00      11
409.00       1
410.00      24
412.00       2
419.00      34
420.00       4
430.00      43
441.00       4
450.00      30
463.00       2
470.00       7
471.00       1
478.00       1
484.00       3
485.00       1
487.00       4
493.00       1
496.00       1
499.00       1
527.00       1
530.00       1
537.00       1
551.00       1
552.00       2
559.00       9
567.00       3
570.00       1
588.00       3
600.00       1
662.00       2
664.00       1
665.00       1
746.00       1
810.00       1
883.00       1
924.00       1
Name: count, dtype: int64

## power_hp

In [144]:
# Let's explore basic information about "power_hp"

first_looking("power_hp")

COLUMN NAME    :  power_hp
--------------------------------
per_of_nulls   :  % 1.99
num_of_nulls   :  571
num_of_uniques :  347
--------------------------------
power_hp
150.00    1992
131.00    1356
120.00    1182
110.00    1166
90.00     1110
140.00    1033
116.00    1002
101.00     892
190.00     787
69.00      701
95.00      685
136.00     681
NaN        571
75.00      514
125.00     477
200.00     458
170.00     422
163.00     418
109.00     349
179.00     339
122.00     318
184.00     296
235.00     249
160.00     247
156.00     246
177.00     241
114.00     240
105.00     236
300.00     234
204.00     232
280.00     224
91.00      213
111.00     204
86.00      200
197.00     199
132.00     185
72.00      176
141.00     162
392.00     155
80.00      149
194.00     143
99.00      139
250.00     138
165.00     134
60.00      133
82.00      133
224.00     130
245.00     130
102.00     128
92.00      127
275.00     126
145.00     124
73.00      120
258.00     119
450.00     118
328.00     116
220.00     115
71.00      112
135.00     111
310.00     105
306.00     104
230.00     103
118.00     102
181.00     100
143.00      99
421.00      99
68.00       99
152.00      98
88.00       97
159.00      92
155.00      89
367.00      86
67.00       84
84.00       83
290.00      81
340.00      81
147.00      80
211.00      79
330.00      79
333.00      76
193.00      70
390.00      64
218.00      63
87.00       63
158.00      63
303.00      60
265.00      60
185.00      59
154.00      56
435.00      55
264.00      53
510.00      51
476.00      51
408.00      50
133.00      50
98.00       50
239.00      49
209.00      49
107.00      48
457.00      47
460.00      45
58.00       45
126.00      44
317.00      43
305.00      43
585.00      43
45.00       42
261.00      42
272.00      41
137.00      40
97.00       39
449.00      39
117.00      39
139.00      38
341.00      37
292.00      36
241.00      36
124.00      36
360.00      36
252.00      35
182.00      34
286.00      34
570.00      34
65.00       33
381.00      32
106.00      32
188.00      32
175.00      31
612.00      30
260.00      30
186.00      29
314.00      28
231.00      27
207.00      26
174.00      26
213.00      26
238.00      25
253.00      25
113.00      25
387.00      24
557.00      24
129.00      24
315.00      24
103.00      24
83.00       24
77.00       23
54.00       22
344.00      22
222.00      21
192.00      21
271.00      20
279.00      20
162.00      20
320.00      20
299.00      19
205.00      19
215.00      19
455.00      19
349.00      18
405.00      17
166.00      16
309.00      15
76.00       15
254.00      14
167.00      14
549.00      14
419.00      14
208.00      14
228.00      13
212.00      13
226.00      13
273.00      13
283.00      13
64.00       12
242.00      12
400.00      12
189.00      11
351.00      11
148.00      11
234.00      11
94.00       11
525.00      11
530.00      10
128.00      10
247.00      10
288.00      10
18.00       10
173.00      10
325.00      10
760.00       9
48.00        9
269.00       9
466.00       9
551.00       9
256.00       9
1.00         9
203.00       9
441.00       8
523.00       8
178.00       8
169.00       8
281.00       8
639.00       7
24.00        7
517.00       7
469.00       7
503.00       7
407.00       7
151.00       6
50.00        6
368.00       6
417.00       6
480.00       6
533.00       6
44.00        6
237.00       6
199.00       6
201.00       6
500.00       6
276.00       6
326.00       6
401.00       6
489.00       5
171.00       5
227.00       5
485.00       5
389.00       5
313.00       5
23.00        5
337.00       5
262.00       5
291.00       4
461.00       4
379.00       4
334.00       4
600.00       4
144.00       4
462.00       4
420.00       4
662.00       4
61.00        4
571.00       4
266.00       4
544.00       4
426.00       4
39.00        3
79.00        3
658.00       3
398.00       3
294.00       3
63.00        3
11.00        3
49.00        3
362.00       3
121.00       3
52.00        3
526.00       3
771.00       3
799.00       3
34.00        3
296.00       3
311.00       3
423.00       2
424.00       2
397.00       2
430.00       2
494.00       2
373.00       2
751.00       2
394.00       2
363.00       2
470.00       2
487.00       2
481.00       2
630.00       2
560.00       2
332.00       2
19.00        2
26.00        2
257.00       2
302.00       2
12.00        2
5.00         2
31.00        2
284.00       2
42.00        2
219.00       2
900.00       2
10.00        2
46.00        2
16.00        2
324.00       1
464.00       1
775.00       1
22.00        1
37.00        1
30.00        1
57.00        1
14.00        1
41.00        1
721.00       1
507.00       1
20.00        1
446.00       1
749.00       1
496.00       1
659.00       1
318.00       1
442.00       1
4.00         1
347.00       1
8.00         1
53.00        1
640.00       1
514.00       1
35.00        1
451.00       1
196.00       1
249.00       1
243.00       1
386.00       1
321.00       1
223.00       1
556.00       1
402.00       1
904.00       1
650.00       1
445.00       1
816.00       1
903.00       1
674.00       1
329.00       1
345.00       1
678.00       1
522.00       1
56.00        1
730.00       1
29.00        1
295.00       1
322.00       1
27.00        1
717.00       1
548.00       1
465.00       1
412.00       1
670.00       1
506.00       1
33.00        1
Name: count, dtype: int64

In [145]:
# All NaN values are converted to dash/hyphen sign "-" to see them in the output of describe() and explore the hidden pattern

df["power_hp"].fillna("-", inplace=True)

In [146]:
# let's explore if there is any pattern among "make_model", "body_type", and "power_hp" by "price"

df.groupby(["make_model", "body_type", "power_hp"]).price.describe()

                                             count     mean     std      min
make_model        body_type        power_hp
Dacia 1300        Sedan            54.0       1.00  9999.00     NaN  9999.00  \
Dacia Break       Station Wagon    -          1.00 20500.00     NaN 20500.00
Dacia Business    Compact          45.0       1.00 19515.00     NaN 19515.00
Dacia Comfort Tce Station Wagon    110.0      1.00 21799.00     NaN 21799.00
Dacia Dokker      Compact          90.0       1.00 11930.00     NaN 11930.00
...                                            ...      ...     ...      ...
Volvo Xc90        Off-Road/Pick-Up 400.0      6.00 50793.33 6277.64 42790.00
                                   408.0      2.00 44200.00    0.00 44200.00
                  Sedan            235.0      2.00 48100.00  565.69 47700.00
                                   303.0      1.00 84900.00     NaN 84900.00
                  Station Wagon    224.0      4.00 32750.00 3752.78 29500.00

                                                 25%      50%      75%
make_model        body_type        power_hp
Dacia 1300        Sedan            54.0      9999.00  9999.00  9999.00  \
Dacia Break       Station Wagon    -        20500.00 20500.00 20500.00
Dacia Business    Compact          45.0     19515.00 19515.00 19515.00
Dacia Comfort Tce Station Wagon    110.0    21799.00 21799.00 21799.00
Dacia Dokker      Compact          90.0     11930.00 11930.00 11930.00
...                                              ...      ...      ...
Volvo Xc90        Off-Road/Pick-Up 400.0    45515.00 53690.00 55347.50
                                   408.0    44200.00 44200.00 44200.00
                  Sedan            235.0    47900.00 48100.00 48300.00
                                   303.0    84900.00 84900.00 84900.00
                  Station Wagon    224.0    29500.00 32750.00 36000.00

                                                 max
make_model        body_type        power_hp
Dacia 1300        Sedan            54.0      9999.00
Dacia Break       Station Wagon    -        20500.00
Dacia Business    Compact          45.0     19515.00
Dacia Comfort Tce Station Wagon    110.0    21799.00
Dacia Dokker      Compact          90.0     11930.00
...                                              ...
Volvo Xc90        Off-Road/Pick-Up 400.0    55900.00
                                   408.0    44200.00
                  Sedan            235.0    48500.00
                                   303.0    84900.00
                  Station Wagon    224.0    36000.00

[5012 rows x 8 columns]

<div style="background-color: #ffeeba; padding: 10px; font-size: 16px; font-weight: bold;">
    Domain Knowledge demonstrates that the <code>hp</code> of cars changes by their <code>make_models</code> and <code>body_types</code> most of the time. So it's decided to fill missing values with <code>mode value</code> of corresponding group.
</div>

In [147]:
# Let's replace dash/hyphen sign "-" with np.nan

df["power_hp"].replace(["-"], np.nan, inplace=True)

In [148]:
# This DEF will fill the missing values in the "power_kW" with the mode value based on "make_model" and "body_type"

fill(df, "make_model", "body_type", "power_hp", "mode")

COLUMN NAME    :  power_hp
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  347
--------------------------------
power_hp
1.00         9
4.00         1
5.00         5
8.00         1
10.00        2
11.00        3
12.00        2
14.00        1
16.00        2
18.00       10
19.00        2
20.00        1
22.00        1
23.00        5
24.00        7
26.00        2
27.00        1
29.00        2
30.00        1
31.00        2
33.00        1
34.00        4
35.00        1
37.00        1
39.00        3
41.00        1
42.00        2
44.00        6
45.00       42
46.00        2
48.00        9
49.00        3
50.00        6
52.00        3
53.00        1
54.00       22
56.00        1
57.00        1
58.00       54
60.00      135
61.00        4
63.00        3
64.00       13
65.00       33
67.00       84
68.00      100
69.00      707
71.00      112
72.00      184
73.00      120
75.00      522
76.00       15
77.00       23
79.00        3
80.00      149
82.00      133
83.00       24
84.00       85
86.00      200
87.00       66
88.00       99
90.00     1151
91.00      213
92.00      132
94.00       11
95.00      696
97.00       39
98.00       51
99.00      139
101.00     915
102.00     130
103.00      24
105.00     238
106.00      32
107.00      48
109.00     356
110.00    1186
111.00     216
113.00      25
114.00     240
116.00    1052
117.00      39
118.00     127
120.00    1202
121.00       3
122.00     324
124.00      36
125.00     477
126.00      44
128.00      10
129.00      24
131.00    1426
132.00     187
133.00      50
135.00     111
136.00     700
137.00      40
139.00      38
140.00    1055
141.00     170
143.00      99
144.00       4
145.00     124
147.00      81
148.00      11
150.00    2019
151.00       6
152.00      98
154.00      56
155.00      89
156.00     248
158.00      79
159.00      92
160.00     258
162.00      20
163.00     422
165.00     134
166.00      16
167.00      15
169.00       8
170.00     424
171.00       5
173.00      10
174.00      26
175.00      31
177.00     252
178.00       8
179.00     344
181.00     100
182.00      34
184.00     315
185.00      59
186.00      29
188.00      32
189.00      11
190.00     790
192.00      21
193.00      70
194.00     143
196.00       1
197.00     205
199.00       6
200.00     460
201.00       6
203.00       9
204.00     234
205.00      19
207.00      26
208.00      14
209.00      49
211.00      79
212.00      13
213.00      26
215.00      19
218.00      65
219.00       2
220.00     116
222.00      21
223.00       1
224.00     130
226.00      13
227.00       5
228.00      13
230.00     103
231.00      27
234.00      11
235.00     249
237.00       6
238.00      25
239.00      49
241.00      36
242.00      15
243.00       1
245.00     130
247.00      11
249.00       1
250.00     138
252.00      35
253.00      25
254.00      14
256.00       9
257.00       2
258.00     119
260.00      30
261.00      42
262.00       5
264.00      53
265.00      60
266.00       4
269.00       9
271.00      20
272.00      41
273.00      13
275.00     129
276.00       6
279.00      20
280.00     224
281.00       8
283.00      13
284.00       2
286.00      34
288.00      10
290.00      81
291.00       4
292.00      37
294.00       3
295.00       1
296.00       3
299.00      19
300.00     234
302.00       2
303.00      60
305.00      43
306.00     104
309.00      15
310.00     105
311.00       3
313.00       5
314.00      28
315.00      24
317.00      43
318.00       1
320.00      20
321.00       1
322.00       1
324.00       1
325.00      10
326.00       7
328.00     116
329.00       1
330.00      79
332.00       2
333.00      76
334.00       4
337.00       5
340.00      81
341.00      37
344.00      22
345.00       1
347.00       1
349.00      18
351.00      11
360.00      36
362.00       3
363.00       2
367.00      86
368.00       6
373.00       2
379.00       4
381.00      32
386.00       1
387.00      24
389.00       5
390.00      64
392.00     155
394.00       2
397.00       2
398.00       3
400.00      12
401.00       6
402.00       1
405.00      17
407.00       7
408.00      50
412.00       1
417.00       6
419.00      14
420.00       4
421.00      99
423.00       2
424.00       2
426.00       4
430.00       2
435.00      55
441.00       8
442.00       1
445.00       1
446.00       1
449.00      39
450.00     170
451.00       1
455.00      19
457.00      47
460.00      45
461.00       4
462.00       4
464.00       1
465.00       1
466.00       9
469.00       7
470.00       2
476.00      51
480.00       6
481.00       2
485.00       5
487.00       2
489.00       5
494.00       2
496.00       1
500.00       6
503.00       7
506.00       1
507.00       1
510.00      51
514.00       1
517.00       7
522.00       1
523.00       8
525.00      11
526.00       3
530.00      10
533.00       6
544.00       4
548.00       1
549.00      14
551.00      11
556.00       1
557.00      24
560.00       2
570.00      34
571.00       4
585.00      43
600.00       4
612.00      30
630.00       2
639.00       7
640.00       1
650.00       1
658.00       3
659.00       1
662.00       4
670.00       1
674.00       1
678.00       1
717.00       1
721.00       1
730.00       1
749.00       1
751.00       2
760.00       9
771.00       3
775.00       1
799.00       3
816.00       1
900.00       2
903.00       1
904.00       1
Name: count, dtype: int64

<div style="background-color: #FFB6C1; padding: 10px; font-size: 16px; font-weight: bold;">
    The <code>hp</code> feature is dropped from the analysis and <code>kW</code> will be used for further steps since <code>kW</code> is used as the indicator of comsumption for electric vehicles as well.
</div>

In [149]:
df.shape

(28624, 33)

In [150]:
df.drop("power_hp", axis=1, inplace=True)

In [151]:
df.shape

(28624, 32)

## cons_avg

**📢 Problem!!!**

We are all used to the fact that the fuel consumption of a petrol or diesel car is expressed in litres per hundred kilometres (l/100 km)...An electric car does NOT use fuel but gets its energy from a battery. The maximum amount of energy the battery can store (capacity) is expressed in kWh (kilowatt-hour). Instead of the amount of fuel needed to cover hundred kilometres, the energy consumption of an electric car is (usually) expressed in the number of kilowatt-hours needed to drive a hundred kilometres (kWh/100 km).

**🤔 How do we deal with this issue?**

**🧐 [What is the equivalent fuel consumption of an electric car?](https://news.mgmotor.eu/what-is-the-equivalent-fuel-consumption-of-an-electric-car/)**

**🧐 [Energy consumption of full electric vehicles](https://ev-database.org/cheatsheet/energy-consumption-electric-car)**

**🧐 [HOW DO YOU CALCULATE KWH VS. KW?](https://www.directenergyregulatedservices.com/blog/kw-vs-kwh-whats-difference#:~:text=Divide%20the%20wattage%20by%201%2C000,days%20%3D%2090%20kWh%20per%20month)**

In [152]:
# Let's explore basic information about "cons_avg"

first_looking("cons_avg")

COLUMN NAME    :  cons_avg
--------------------------------
per_of_nulls   :  % 18.32
num_of_nulls   :  5244
num_of_uniques :  161
--------------------------------
cons_avg
NaN      5244
5.00      831
4.90      812
4.50      690
0.00      650
5.10      647
4.70      618
5.40      609
4.80      609
5.60      594
4.30      564
5.30      558
5.20      552
4.60      550
4.20      539
4.10      518
3.80      516
5.70      504
5.50      503
5.90      498
4.00      484
4.40      442
6.40      438
6.00      430
6.30      414
5.80      399
3.70      360
3.90      353
3.60      327
7.00      312
3.40      296
6.50      292
6.10      282
6.20      278
6.60      274
6.90      270
7.40      265
7.10      253
6.70      251
6.80      226
7.30      220
7.20      202
8.40      194
8.00      194
7.60      181
3.50      180
8.20      166
7.70      165
7.80      165
7.50      155
12.00     110
3.30      109
9.00      107
9.20      103
12.50     102
8.60       95
9.80       93
8.90       92
8.30       88
3.00       84
7.90       83
9.60       79
8.70       79
1.70       77
9.50       77
1.50       73
9.40       72
9.70       69
8.80       69
8.50       67
10.10      66
1.80       66
10.60      66
3.20       64
8.10       64
11.80      62
11.40      62
9.10       61
9.90       55
10.90      52
12.10      51
2.10       49
1.90       47
10.00      46
1.40       44
10.50      43
12.40      41
9.30       40
1.20       40
11.00      39
12.80      37
10.30      36
10.40      35
12.20      34
2.80       33
1.60       30
11.20      28
2.00       27
1.10       26
10.80      25
12.30      23
11.70      23
13.60      22
11.50      22
11.90      22
10.20      21
3.10       19
13.50      19
2.40       16
1.30       15
11.60      14
12.60      14
2.20       13
11.10      13
11.30      13
10.70      12
1.00       11
2.50       11
14.00      10
2.30       10
13.80       9
0.80        8
2.90        7
13.00       7
12.90       7
13.10       7
2.60        6
12.70       6
0.60        5
13.40       5
13.90       5
13.20       5
0.70        5
99.90       4
14.30       3
0.90        3
16.70       3
14.40       3
14.10       3
2.70        2
16.50       2
14.90       2
53.00       2
15.60       2
93.00       2
14.20       1
14.70       1
15.00       1
16.80       1
18.30       1
23.00       1
16.40       1
15.50       1
15.10       1
15.90       1
56.00       1
0.50        1
16.00       1
57.00       1
61.00       1
14.50       1
44.00       1
Name: count, dtype: int64

**let us first examine how electric vehicles look like?**

In [153]:
df.loc[df["fuel_type"] == "Electric"][["cons_avg"]]

       cons_avg
1           NaN
93          NaN
94          NaN
108         NaN
1213        NaN
1226        NaN
1271        NaN
1273        NaN
1281        NaN
1283        NaN
1303        NaN
1304        NaN
1307        NaN
1326        NaN
1331        NaN
1341        NaN
1350        NaN
1361        NaN
1364        NaN
1369        NaN
1400        NaN
1416        NaN
1425        NaN
1427        NaN
1436        NaN
1447        NaN
1458        NaN
1513        NaN
1575        NaN
1628        NaN
1641        NaN
1777        NaN
1798        NaN
1998        NaN
2000        NaN
2004        NaN
2015        NaN
2045        NaN
2082        NaN
2084        NaN
2086        NaN
2099        NaN
2130        NaN
2144        NaN
2156        NaN
2161        NaN
2166        NaN
2182        NaN
2192        NaN
2199        NaN
2230        NaN
2246        NaN
2255        NaN
2272        NaN
2276        NaN
2278        NaN
2301        NaN
2312        NaN
2317        NaN
2322        NaN
2328        NaN
2331        NaN
2355        NaN
2356        NaN
2360        NaN
2372        NaN
2713        NaN
3663        NaN
4810        NaN
4819        NaN
4823        NaN
4826        NaN
4838        NaN
4840        NaN
4873        NaN
4886        NaN
4914        NaN
4923        NaN
4929        NaN
4939        NaN
4943        NaN
4952        NaN
4957        NaN
4963        NaN
4972        NaN
4973        NaN
4985        NaN
4986        NaN
4989        NaN
4998        NaN
5002        NaN
5026        NaN
5028        NaN
5040        NaN
5045        NaN
5046        NaN
5047        NaN
5051        NaN
5054        NaN
5067        NaN
5071        NaN
5074        NaN
5075        NaN
5080        NaN
5087        NaN
5093        NaN
5097        NaN
5100        NaN
5102        NaN
5116        NaN
5117        NaN
5120        NaN
5122        NaN
5129        NaN
5134        NaN
5140        NaN
5143        NaN
5148        NaN
5149        NaN
5163        NaN
5166        NaN
5167        NaN
5173        NaN
5199        NaN
5430        NaN
5748        NaN
5786        NaN
5816        NaN
5831        NaN
5919        NaN
5936        NaN
6166        NaN
6205        NaN
6795        NaN
6803        NaN
6810        NaN
6811        NaN
6824        NaN
6830        NaN
6835        NaN
6837        NaN
6839        NaN
6847        NaN
6849        NaN
6852        NaN
6854        NaN
6860        NaN
6869        NaN
6870        NaN
6874        NaN
6876        NaN
6878        NaN
6879        NaN
6882        NaN
6896        NaN
6907        NaN
6909        NaN
6912        NaN
6916        NaN
6918        NaN
6943        NaN
6951        NaN
6952        NaN
6958        NaN
6982        NaN
7060        NaN
7071        NaN
7102        NaN
7103        NaN
7113        NaN
7114        NaN
7116        NaN
7124        NaN
7127        NaN
7132        NaN
7156        NaN
7232        NaN
7316        NaN
7335        NaN
7397        NaN
7408        NaN
7461        NaN
7480        NaN
7525        NaN
8400        NaN
8670        NaN
8876        NaN
8899        NaN
9005        NaN
9070        NaN
9079        NaN
9082        NaN
9087        NaN
9088        NaN
9089        NaN
9091        NaN
9102        NaN
9152        NaN
9154        NaN
9366        NaN
9426        NaN
9428        NaN
9448        NaN
9455        NaN
9473        NaN
9481        NaN
9487        NaN
9501        NaN
9514        NaN
9515        NaN
9522        NaN
9524        NaN
9527        NaN
9532        NaN
9538        NaN
9539        NaN
9540        NaN
9544        NaN
9545        NaN
9603        NaN
9608        NaN
9620        NaN
9654        NaN
9692        NaN
9699        NaN
9706        NaN
9716        NaN
9720        NaN
9795        NaN
9859        NaN
9889        NaN
9894        NaN
9918        NaN
9984        NaN
10023       NaN
10033       NaN
10039       NaN
10069       NaN
10074       NaN
10098       NaN
10104       NaN
10183       NaN
10215       NaN
10246       NaN
10258       NaN
10467       NaN
10566       NaN
10617       NaN
10625       NaN
10630       NaN
10631       NaN
10668       NaN
11467       NaN
11479       NaN
11544       NaN
11558       NaN
11572       NaN
11577       NaN
11578       NaN
11595       NaN
11619       NaN
11620       NaN
11632       NaN
11640       NaN
11641       NaN
11648       NaN
11653       NaN
11655       NaN
11665       NaN
11672       NaN
11673       NaN
11676       NaN
11690       NaN
11730       NaN
11776       NaN
11801       NaN
13978       NaN
13995       NaN
14055       NaN
14057       NaN
14066       NaN
14118       NaN
14188       NaN
14196       NaN
14212       NaN
14235       NaN
14248       NaN
14277       NaN
14284       NaN
14300       NaN
14316       NaN
14317       NaN
14952       NaN
15141       NaN
15143       NaN
15144       NaN
15145       NaN
15146       NaN
15147       NaN
15148       NaN
15149       NaN
15150       NaN
15151       NaN
15152       NaN
15153       NaN
15155       NaN
15156       NaN
15157       NaN
15158       NaN
15159       NaN
15161       NaN
15166       NaN
15181       NaN
15182       NaN
15183       NaN
15184       NaN
15185       NaN
15186       NaN
15187       NaN
15214       NaN
15648       NaN
15667       NaN
15903       NaN
16296       NaN
16312       NaN
16315       NaN
16319       NaN
16344       NaN
16351       NaN
16405       NaN
16416       NaN
16471       NaN
17699       NaN
17701       NaN
17718       NaN
17720       NaN
18114       NaN
18716       NaN
18725       NaN
18726       NaN
18730       NaN
18733       NaN
18742       NaN
18752       NaN
18759       NaN
18774       NaN
18779       NaN
18782       NaN
18784       NaN
18785       NaN
18786       NaN
18787       NaN
18789       NaN
18794       NaN
18795       NaN
18796       NaN
18807       NaN
18812       NaN
18816       NaN
18817       NaN
18819       NaN
18822       NaN
18836       NaN
18861       NaN
18866       NaN
18880       NaN
18917       NaN
18964       NaN
18990       NaN
19025       NaN
19080       NaN
20076       NaN
20414       NaN
20464       NaN
20480       NaN
20484       NaN
20487       NaN
20507       NaN
20516       NaN
20523       NaN
20533       NaN
20534       NaN
20535       NaN
20536       NaN
20537       NaN
20539       NaN
20540       NaN
20546       NaN
20551       NaN
20552       NaN
20557       NaN
20562       NaN
20563       NaN
20571       NaN
20582       NaN
20599       NaN
20600       NaN
20602       NaN
21623       NaN
21937       NaN
21948       NaN
21955       NaN
21957       NaN
21958       NaN
21960       NaN
21963       NaN
21966       NaN
21979       NaN
21986       NaN
21990       NaN
21994       NaN
22004       NaN
22008       NaN
22028       NaN
22029       NaN
22047       NaN
22048       NaN
22185       NaN
22247       NaN
22775       NaN
22783       NaN
22823       NaN
23379       NaN
23809       NaN
23870       NaN
23951       NaN
24051       NaN
24092       NaN
24099       NaN
24123       NaN
24170       NaN
24173       NaN
24832       NaN
24851       NaN
26952       NaN
26985       NaN
27338       NaN
27367       NaN
28340       NaN
28528       NaN

In [154]:
df.groupby("fuel_type")[["cons_avg"]].describe()

                   cons_avg
                      count mean  std  min  25%  50%  75%   max
fuel_type
Benzine            15365.00 6.19 2.96 0.00 4.90 5.80 7.30 99.90
Diesel              7679.00 4.70 2.32 0.00 3.90 4.50 5.30 99.90
Electric               0.00  NaN  NaN  NaN  NaN  NaN  NaN   NaN
Liquid/Natural Gas   336.00 5.81 2.16 0.00 5.00 5.70 7.00 13.80

<div style="background-color: #ffeeba; padding: 10px; font-size: 16px; font-weight: bold;">
    No values seem to be entered for electric vehicles.
</div>

### 📝 Domain Knowledge About Energy Consumption of Electric Cars

**According to the following cheatsheet as a quick reference which shows all-electric vehicles sorted by energy consumption, the average consumption of electric vehicles is ``201 Wh/km`` (20100 Wh/100km) - ``0.210 kWh/km`` (21 kWh/100km) (1 watt hour = 0.001 kilowatt hours). Data is based on real-world values. The average is corrected for multiple versions of the same model.**

Let’s take the ``MG5 Electric Long Range`` as an example, the world’s first all-electric station wagon. The battery offers a capacity of ``61.1 kWh``. With a fully charged battery, you can drive a distance up to ``400 km`` according to the European protocol for the measurement of energy consumption (WLTP). This means the average energy consumption of the MG5 Electric Long Range is ``15.3 kWh/100 km``.

Since electric driving is still unknown territory for many, the energy consumption of an electric car doesn’t mean much to most motorists. But to give you an idea, we can calculate the ‘equivalent fuel consumption’ of an electric car.

How? Well, we know a ``litre of petrol`` contains about ``8.9 kWh`` of energy. If we convert this and compare it with the energy consumption of the MG5 Electric Long Range (15.3 kWh/100 km divided by 8.9 kWh/litre), you have an equivalent fuel consumption of just ``1.7 l/100 km``. In other words, the MG5 Electric is considerably more energy efficient than any car with an internal Combustion Engine (ICE).

So, in our case, if the average consumption of electric vehicles, in general, is accepted as **``21 kWh/100km``**, then 21/8.9 is equal to **``2.359 l/100 km``**, which can be used to fill missing values for electric vehicles. 

**🧐 [Energy consumption of full electric vehicles](https://ev-database.org/cheatsheet/energy-consumption-electric-car)**

<br><div style="background-color: #ffeeba; padding: 10px; font-size: 16px; font-weight: bold;">
    It seems more sensible/rational to fill missing values in two stages:
</div>

- With the accepted ``Average`` consumption value of ``electric vehicles``.
- If it's posibble, with the a calculated ``Average`` value; otherwise, with the ``Median`` values of related make_model, body_type and fuel_type features for the ``others``.

### Stage 1:

In [155]:
df.loc[df["fuel_type"] == "Electric", "cons_avg"] = 2.359  # According to Domain Knowledge above
df.loc[df["fuel_type"] == "Electric"][["cons_avg"]]

       cons_avg
1          2.36
93         2.36
94         2.36
108        2.36
1213       2.36
1226       2.36
1271       2.36
1273       2.36
1281       2.36
1283       2.36
1303       2.36
1304       2.36
1307       2.36
1326       2.36
1331       2.36
1341       2.36
1350       2.36
1361       2.36
1364       2.36
1369       2.36
1400       2.36
1416       2.36
1425       2.36
1427       2.36
1436       2.36
1447       2.36
1458       2.36
1513       2.36
1575       2.36
1628       2.36
1641       2.36
1777       2.36
1798       2.36
1998       2.36
2000       2.36
2004       2.36
2015       2.36
2045       2.36
2082       2.36
2084       2.36
2086       2.36
2099       2.36
2130       2.36
2144       2.36
2156       2.36
2161       2.36
2166       2.36
2182       2.36
2192       2.36
2199       2.36
2230       2.36
2246       2.36
2255       2.36
2272       2.36
2276       2.36
2278       2.36
2301       2.36
2312       2.36
2317       2.36
2322       2.36
2328       2.36
2331       2.36
2355       2.36
2356       2.36
2360       2.36
2372       2.36
2713       2.36
3663       2.36
4810       2.36
4819       2.36
4823       2.36
4826       2.36
4838       2.36
4840       2.36
4873       2.36
4886       2.36
4914       2.36
4923       2.36
4929       2.36
4939       2.36
4943       2.36
4952       2.36
4957       2.36
4963       2.36
4972       2.36
4973       2.36
4985       2.36
4986       2.36
4989       2.36
4998       2.36
5002       2.36
5026       2.36
5028       2.36
5040       2.36
5045       2.36
5046       2.36
5047       2.36
5051       2.36
5054       2.36
5067       2.36
5071       2.36
5074       2.36
5075       2.36
5080       2.36
5087       2.36
5093       2.36
5097       2.36
5100       2.36
5102       2.36
5116       2.36
5117       2.36
5120       2.36
5122       2.36
5129       2.36
5134       2.36
5140       2.36
5143       2.36
5148       2.36
5149       2.36
5163       2.36
5166       2.36
5167       2.36
5173       2.36
5199       2.36
5430       2.36
5748       2.36
5786       2.36
5816       2.36
5831       2.36
5919       2.36
5936       2.36
6166       2.36
6205       2.36
6795       2.36
6803       2.36
6810       2.36
6811       2.36
6824       2.36
6830       2.36
6835       2.36
6837       2.36
6839       2.36
6847       2.36
6849       2.36
6852       2.36
6854       2.36
6860       2.36
6869       2.36
6870       2.36
6874       2.36
6876       2.36
6878       2.36
6879       2.36
6882       2.36
6896       2.36
6907       2.36
6909       2.36
6912       2.36
6916       2.36
6918       2.36
6943       2.36
6951       2.36
6952       2.36
6958       2.36
6982       2.36
7060       2.36
7071       2.36
7102       2.36
7103       2.36
7113       2.36
7114       2.36
7116       2.36
7124       2.36
7127       2.36
7132       2.36
7156       2.36
7232       2.36
7316       2.36
7335       2.36
7397       2.36
7408       2.36
7461       2.36
7480       2.36
7525       2.36
8400       2.36
8670       2.36
8876       2.36
8899       2.36
9005       2.36
9070       2.36
9079       2.36
9082       2.36
9087       2.36
9088       2.36
9089       2.36
9091       2.36
9102       2.36
9152       2.36
9154       2.36
9366       2.36
9426       2.36
9428       2.36
9448       2.36
9455       2.36
9473       2.36
9481       2.36
9487       2.36
9501       2.36
9514       2.36
9515       2.36
9522       2.36
9524       2.36
9527       2.36
9532       2.36
9538       2.36
9539       2.36
9540       2.36
9544       2.36
9545       2.36
9603       2.36
9608       2.36
9620       2.36
9654       2.36
9692       2.36
9699       2.36
9706       2.36
9716       2.36
9720       2.36
9795       2.36
9859       2.36
9889       2.36
9894       2.36
9918       2.36
9984       2.36
10023      2.36
10033      2.36
10039      2.36
10069      2.36
10074      2.36
10098      2.36
10104      2.36
10183      2.36
10215      2.36
10246      2.36
10258      2.36
10467      2.36
10566      2.36
10617      2.36
10625      2.36
10630      2.36
10631      2.36
10668      2.36
11467      2.36
11479      2.36
11544      2.36
11558      2.36
11572      2.36
11577      2.36
11578      2.36
11595      2.36
11619      2.36
11620      2.36
11632      2.36
11640      2.36
11641      2.36
11648      2.36
11653      2.36
11655      2.36
11665      2.36
11672      2.36
11673      2.36
11676      2.36
11690      2.36
11730      2.36
11776      2.36
11801      2.36
13978      2.36
13995      2.36
14055      2.36
14057      2.36
14066      2.36
14118      2.36
14188      2.36
14196      2.36
14212      2.36
14235      2.36
14248      2.36
14277      2.36
14284      2.36
14300      2.36
14316      2.36
14317      2.36
14952      2.36
15141      2.36
15143      2.36
15144      2.36
15145      2.36
15146      2.36
15147      2.36
15148      2.36
15149      2.36
15150      2.36
15151      2.36
15152      2.36
15153      2.36
15155      2.36
15156      2.36
15157      2.36
15158      2.36
15159      2.36
15161      2.36
15166      2.36
15181      2.36
15182      2.36
15183      2.36
15184      2.36
15185      2.36
15186      2.36
15187      2.36
15214      2.36
15648      2.36
15667      2.36
15903      2.36
16296      2.36
16312      2.36
16315      2.36
16319      2.36
16344      2.36
16351      2.36
16405      2.36
16416      2.36
16471      2.36
17699      2.36
17701      2.36
17718      2.36
17720      2.36
18114      2.36
18716      2.36
18725      2.36
18726      2.36
18730      2.36
18733      2.36
18742      2.36
18752      2.36
18759      2.36
18774      2.36
18779      2.36
18782      2.36
18784      2.36
18785      2.36
18786      2.36
18787      2.36
18789      2.36
18794      2.36
18795      2.36
18796      2.36
18807      2.36
18812      2.36
18816      2.36
18817      2.36
18819      2.36
18822      2.36
18836      2.36
18861      2.36
18866      2.36
18880      2.36
18917      2.36
18964      2.36
18990      2.36
19025      2.36
19080      2.36
20076      2.36
20414      2.36
20464      2.36
20480      2.36
20484      2.36
20487      2.36
20507      2.36
20516      2.36
20523      2.36
20533      2.36
20534      2.36
20535      2.36
20536      2.36
20537      2.36
20539      2.36
20540      2.36
20546      2.36
20551      2.36
20552      2.36
20557      2.36
20562      2.36
20563      2.36
20571      2.36
20582      2.36
20599      2.36
20600      2.36
20602      2.36
21623      2.36
21937      2.36
21948      2.36
21955      2.36
21957      2.36
21958      2.36
21960      2.36
21963      2.36
21966      2.36
21979      2.36
21986      2.36
21990      2.36
21994      2.36
22004      2.36
22008      2.36
22028      2.36
22029      2.36
22047      2.36
22048      2.36
22185      2.36
22247      2.36
22775      2.36
22783      2.36
22823      2.36
23379      2.36
23809      2.36
23870      2.36
23951      2.36
24051      2.36
24092      2.36
24099      2.36
24123      2.36
24170      2.36
24173      2.36
24832      2.36
24851      2.36
26952      2.36
26985      2.36
27338      2.36
27367      2.36
28340      2.36
28528      2.36

In [156]:
# Let's explore basic information about "cons_avg" again

first_looking("cons_avg")

COLUMN NAME    :  cons_avg
--------------------------------
per_of_nulls   :  % 16.78
num_of_nulls   :  4804
num_of_uniques :  162
--------------------------------
cons_avg
NaN      4804
5.00      831
4.90      812
4.50      690
0.00      650
5.10      647
4.70      618
5.40      609
4.80      609
5.60      594
4.30      564
5.30      558
5.20      552
4.60      550
4.20      539
4.10      518
3.80      516
5.70      504
5.50      503
5.90      498
4.00      484
4.40      442
2.36      440
6.40      438
6.00      430
6.30      414
5.80      399
3.70      360
3.90      353
3.60      327
7.00      312
3.40      296
6.50      292
6.10      282
6.20      278
6.60      274
6.90      270
7.40      265
7.10      253
6.70      251
6.80      226
7.30      220
7.20      202
8.00      194
8.40      194
7.60      181
3.50      180
8.20      166
7.80      165
7.70      165
7.50      155
12.00     110
3.30      109
9.00      107
9.20      103
12.50     102
8.60       95
9.80       93
8.90       92
8.30       88
3.00       84
7.90       83
8.70       79
9.60       79
9.50       77
1.70       77
1.50       73
9.40       72
9.70       69
8.80       69
8.50       67
10.10      66
1.80       66
10.60      66
8.10       64
3.20       64
11.80      62
11.40      62
9.10       61
9.90       55
10.90      52
12.10      51
2.10       49
1.90       47
10.00      46
1.40       44
10.50      43
12.40      41
1.20       40
9.30       40
11.00      39
12.80      37
10.30      36
10.40      35
12.20      34
2.80       33
1.60       30
11.20      28
2.00       27
1.10       26
10.80      25
12.30      23
11.70      23
11.90      22
11.50      22
13.60      22
10.20      21
3.10       19
13.50      19
2.40       16
1.30       15
11.60      14
12.60      14
2.20       13
11.10      13
11.30      13
10.70      12
2.50       11
1.00       11
2.30       10
14.00      10
13.80       9
0.80        8
2.90        7
12.90       7
13.00       7
13.10       7
12.70       6
2.60        6
0.60        5
13.20       5
13.40       5
13.90       5
0.70        5
99.90       4
14.10       3
14.40       3
0.90        3
16.70       3
14.30       3
2.70        2
16.50       2
14.90       2
53.00       2
15.60       2
93.00       2
23.00       1
15.10       1
14.70       1
15.00       1
16.80       1
18.30       1
14.50       1
14.20       1
15.50       1
61.00       1
16.40       1
56.00       1
0.50        1
16.00       1
57.00       1
15.90       1
44.00       1
Name: count, dtype: int64

### Stage 2:

**Let us calculate the average fuel consumption for vehicles according to values at hand:**

In [157]:
# Let's first explore id there has been some values in "cons_city" and "cons_country" columns to fill missing values in "cons_avg"

df[(df["cons_avg"].isnull()) & (df["cons_city"].notnull()) & (df["cons_country"].notnull())]

Empty DataFrame
Columns: [make_model, make, model, location, price, body_type, type, doors, warranty, mileage, gearbox, fuel_type, seller, seats, engine_size, gears, co_emissions, drivetrain, comfort_&_convenience, entertainment_&_media, safety_&_security, extras, empty_weight, full_service_history, upholstery, previous_owner, energy_efficiency_class, age, power_kW, cons_avg, cons_city, cons_country]
Index: []

In [158]:
# Then, let's calculate an average fuel consumption value based on the values in "cons_city" and "cons_country" columns

cons_avg2 = (df["cons_country"] + df["cons_city"])/2
cons_avg2.value_counts(dropna=False)

NaN      8527
0.00      378
5.10      335
5.65      331
5.15      317
4.50      295
5.35      287
5.00      280
4.75      264
4.90      261
5.50      261
4.35      251
6.25      247
5.25      244
5.20      236
5.60      233
5.40      229
6.00      227
7.00      225
6.35      223
3.45      218
4.60      215
5.75      213
5.05      212
4.40      210
4.65      206
5.85      205
4.85      196
4.80      192
8.00      187
4.25      186
5.90      183
6.40      177
5.70      177
6.60      175
4.70      170
4.55      170
4.15      161
6.10      160
4.30      160
6.15      157
5.30      157
3.90      151
7.50      147
5.20      146
3.85      143
6.55      142
4.00      141
3.75      141
4.95      139
6.65      138
6.80      136
3.80      133
3.95      132
5.55      130
5.45      120
7.90      120
5.45      117
4.20      116
6.85      112
6.50      109
4.95      109
5.95      107
8.35      106
5.05      106
4.45      103
5.95       99
7.70       99
7.65       97
7.40       93
5.80       92
6.30       92
5.30       91
3.55       91
4.10       90
6.05       90
7.15       88
7.25       87
7.10       87
3.90       85
4.45       85
3.70       82
7.60       81
5.70       81
7.35       81
8.85       80
3.85       80
7.05       78
6.75       78
3.50       78
6.90       73
6.70       72
8.65       71
4.80       70
9.95       69
5.80       69
10.45      69
6.20       68
10.00      68
8.15       67
9.75       65
13.55      65
7.75       64
7.20       64
3.30       62
4.70       62
6.90       61
3.70       61
11.00      61
6.30       61
6.70       59
8.40       59
9.10       59
8.30       58
10.40      58
6.05       58
7.05       56
8.50       56
8.45       55
9.05       55
10.35      55
7.80       53
8.05       53
4.20       52
4.05       50
8.25       50
6.20       49
6.45       49
7.85       48
11.55      48
12.00      46
12.40      46
9.35       45
8.90       45
6.95       44
8.10       44
6.55       43
6.95       43
9.80       43
7.70       43
10.85      43
3.65       43
8.20       43
8.70       43
13.30      42
8.95       42
9.00       42
4.30       41
13.05      40
7.40       40
8.15       39
9.50       39
3.60       39
12.90      38
6.45       38
6.85       37
8.55       37
4.55       37
7.45       37
7.30       36
13.60      36
9.70       36
8.80       35
9.15       35
8.75       34
12.05      34
14.05      34
3.95       34
3.00       33
7.85       33
6.80       33
9.20       32
9.25       30
10.90      30
7.35       30
7.60       30
10.70      29
14.30      29
11.65      28
9.55       28
7.55       28
9.30       28
5.55       27
8.60       27
7.30       26
7.95       25
7.15       24
13.20      24
7.20       24
9.60       23
10.30      23
7.45       23
9.45       22
11.10      22
3.60       21
10.20      21
11.95      21
11.60      20
10.75      20
3.80       20
9.65       20
10.65      19
7.80       19
10.50      18
12.50      18
7.55       18
12.25      18
3.20       18
11.25      17
10.10      17
3.35       16
7.95       16
3.40       16
9.90       15
12.70      15
9.85       15
14.50      15
14.00      14
10.80      14
14.80      13
12.55      13
11.45      12
11.15      12
13.40      12
12.30      12
4.05       12
6.65       12
10.15      12
7.90       11
11.20      11
14.10      11
13.75      11
3.25       11
13.35      11
13.80      11
8.85       10
6.60       10
12.80      10
9.15       10
13.70      10
12.65      10
12.95       9
9.35        9
11.85       9
10.60       9
11.30       9
8.10        9
11.70       8
35.35       8
12.85       8
12.20       8
11.80       8
10.25       8
14.95       8
7.65        8
9.40        7
9.90        7
12.65       7
9.40        7
11.40       7
11.05       7
13.15       7
8.40        6
15.00       6
11.90       6
13.00       6
8.60        5
8.65        5
11.40       5
13.60       5
12.75       5
8.35        5
14.95       5
10.05       5
13.35       5
9.60        5
13.80       5
12.70       5
12.10       4
0.75        4
10.90       4
10.15       4
3.65        4
9.65        4
10.55       4
8.90        4
11.85       4
7.10        4
12.20       4
11.60       4
13.10       4
12.35       3
14.15       3
14.85       3
12.15       3
1.00        3
10.85       3
11.15       3
9.10        3
9.85        3
2.70        3
13.25       3
11.50       2
3.15        2
12.45       2
13.10       2
17.15       2
2.75        2
15.70       2
3.35        2
1.10        2
11.65       2
12.35       2
10.40       2
16.70       2
1.85        2
14.60       2
15.40       2
18.15       2
13.50       2
13.90       2
0.85        2
13.45       2
34.35       2
10.65       2
17.75       2
3.40        2
13.85       2
15.05       2
14.40       2
15.55       2
1.80        2
15.85       2
6.10        1
0.80        1
12.45       1
15.35       1
16.00       1
15.45       1
14.65       1
2.15        1
14.30       1
6.40        1
10.95       1
16.65       1
12.60       1
4.90        1
11.75       1
15.95       1
14.55       1
10.10       1
14.10       1
16.25       1
17.05       1
11.35       1
13.20       1
12.60       1
15.35       1
14.70       1
14.75       1
16.40       1
10.60       1
11.95       1
15.65       1
1.75        1
14.65       1
1.20        1
98.95       1
64.00       1
25.65       1
25.90       1
49.00       1
2.90        1
14.90       1
40.50       1
Name: count, dtype: int64

In [159]:
# Let's fill fill missing values in "cons_avg" based on average fuel consumption calculation above

df["cons_avg"] = df["cons_avg"].fillna(cons_avg2)

In [160]:
# Let's explore basic information about "cons_avg" again

first_looking("cons_avg")

COLUMN NAME    :  cons_avg
--------------------------------
per_of_nulls   :  % 16.78
num_of_nulls   :  4804
num_of_uniques :  162
--------------------------------
cons_avg
NaN      4804
5.00      831
4.90      812
4.50      690
0.00      650
5.10      647
4.70      618
5.40      609
4.80      609
5.60      594
4.30      564
5.30      558
5.20      552
4.60      550
4.20      539
4.10      518
3.80      516
5.70      504
5.50      503
5.90      498
4.00      484
4.40      442
2.36      440
6.40      438
6.00      430
6.30      414
5.80      399
3.70      360
3.90      353
3.60      327
7.00      312
3.40      296
6.50      292
6.10      282
6.20      278
6.60      274
6.90      270
7.40      265
7.10      253
6.70      251
6.80      226
7.30      220
7.20      202
8.00      194
8.40      194
7.60      181
3.50      180
8.20      166
7.80      165
7.70      165
7.50      155
12.00     110
3.30      109
9.00      107
9.20      103
12.50     102
8.60       95
9.80       93
8.90       92
8.30       88
3.00       84
7.90       83
8.70       79
9.60       79
9.50       77
1.70       77
1.50       73
9.40       72
9.70       69
8.80       69
8.50       67
10.10      66
1.80       66
10.60      66
8.10       64
3.20       64
11.80      62
11.40      62
9.10       61
9.90       55
10.90      52
12.10      51
2.10       49
1.90       47
10.00      46
1.40       44
10.50      43
12.40      41
1.20       40
9.30       40
11.00      39
12.80      37
10.30      36
10.40      35
12.20      34
2.80       33
1.60       30
11.20      28
2.00       27
1.10       26
10.80      25
12.30      23
11.70      23
11.90      22
11.50      22
13.60      22
10.20      21
3.10       19
13.50      19
2.40       16
1.30       15
11.60      14
12.60      14
2.20       13
11.10      13
11.30      13
10.70      12
2.50       11
1.00       11
2.30       10
14.00      10
13.80       9
0.80        8
2.90        7
12.90       7
13.00       7
13.10       7
12.70       6
2.60        6
0.60        5
13.20       5
13.40       5
13.90       5
0.70        5
99.90       4
14.10       3
14.40       3
0.90        3
16.70       3
14.30       3
2.70        2
16.50       2
14.90       2
53.00       2
15.60       2
93.00       2
23.00       1
15.10       1
14.70       1
15.00       1
16.80       1
18.30       1
14.50       1
14.20       1
15.50       1
61.00       1
16.40       1
56.00       1
0.50        1
16.00       1
57.00       1
15.90       1
44.00       1
Name: count, dtype: int64

**However, this approach could NOT work and impact on decreasing the number of missing values in ``cons_avg``**

In [161]:
# All NaN values are converted to dash/hyphen sign "-" to see them in the output of describe() and explore the hidden pattern

df["cons_avg"].fillna("-", inplace=True)

In [162]:
# let's explore if there is any pattern among "make_model", "body_type", "fuel_type", and "cons_avg" by "price"

df.groupby(["make_model", "body_type", "fuel_type", "cons_avg"]).price.describe()

                                                       count     mean     std
make_model        body_type        fuel_type cons_avg
Dacia 1300        Sedan            Benzine   -          1.00  9999.00     NaN  \
Dacia Break       Station Wagon    Benzine   -          1.00 20500.00     NaN
Dacia Business    Compact          Benzine   -          1.00 19515.00     NaN
Dacia Comfort Tce Station Wagon    Benzine   5.6        1.00 21799.00     NaN
Dacia Dokker      Compact          Diesel    4.2        1.00 11930.00     NaN
...                                                      ...      ...     ...
Volvo Xc90        Off-Road/Pick-Up Electric  2.359      4.00 64400.00 9814.95
                  Sedan            Diesel    6.7        2.00 48100.00  565.69
                                             -          1.00 84900.00     NaN
                  Station Wagon    Diesel    5.7        2.00 29500.00    0.00
                                             5.8        2.00 36000.00    0.00

                                                           min      25%
make_model        body_type        fuel_type cons_avg
Dacia 1300        Sedan            Benzine   -         9999.00  9999.00  \
Dacia Break       Station Wagon    Benzine   -        20500.00 20500.00
Dacia Business    Compact          Benzine   -        19515.00 19515.00
Dacia Comfort Tce Station Wagon    Benzine   5.6      21799.00 21799.00
Dacia Dokker      Compact          Diesel    4.2      11930.00 11930.00
...                                                        ...      ...
Volvo Xc90        Off-Road/Pick-Up Electric  2.359    55900.00 55900.00
                  Sedan            Diesel    6.7      47700.00 47900.00
                                             -        84900.00 84900.00
                  Station Wagon    Diesel    5.7      29500.00 29500.00
                                             5.8      36000.00 36000.00

                                                           50%      75%
make_model        body_type        fuel_type cons_avg
Dacia 1300        Sedan            Benzine   -         9999.00  9999.00  \
Dacia Break       Station Wagon    Benzine   -        20500.00 20500.00
Dacia Business    Compact          Benzine   -        19515.00 19515.00
Dacia Comfort Tce Station Wagon    Benzine   5.6      21799.00 21799.00
Dacia Dokker      Compact          Diesel    4.2      11930.00 11930.00
...                                                        ...      ...
Volvo Xc90        Off-Road/Pick-Up Electric  2.359    64400.00 72900.00
                  Sedan            Diesel    6.7      48100.00 48300.00
                                             -        84900.00 84900.00
                  Station Wagon    Diesel    5.7      29500.00 29500.00
                                             5.8      36000.00 36000.00

                                                           max
make_model        body_type        fuel_type cons_avg
Dacia 1300        Sedan            Benzine   -         9999.00
Dacia Break       Station Wagon    Benzine   -        20500.00
Dacia Business    Compact          Benzine   -        19515.00
Dacia Comfort Tce Station Wagon    Benzine   5.6      21799.00
Dacia Dokker      Compact          Diesel    4.2      11930.00
...                                                        ...
Volvo Xc90        Off-Road/Pick-Up Electric  2.359    72900.00
                  Sedan            Diesel    6.7      48500.00
                                             -        84900.00
                  Station Wagon    Diesel    5.7      29500.00
                                             5.8      36000.00

[7390 rows x 8 columns]

In [163]:
# Let's replace dash/hyphen sign "-" with np.nan

df["cons_avg"].replace("-", np.nan, inplace=True)

In [164]:
# This DEF will fill the missing values in the "cons_avg" with the meddian value based on "make_model", "body_type", and "fuel_type"

fill_median(df, "make_model", "body_type", "fuel_type", "cons_avg")

column name    :  cons_avg
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  217
--------------------------------
cons_avg
4.90     1043
5.00      966
5.30      938
4.50      889
5.10      886
0.00      712
4.70      710
5.40      706
4.60      683
5.60      674
4.80      673
4.30      641
5.20      615
3.80      612
5.90      611
4.10      606
4.20      605
5.70      593
5.50      566
4.00      552
4.40      523
6.30      507
6.00      500
3.70      475
5.80      466
6.40      456
2.36      445
3.60      394
3.90      391
6.50      345
6.90      336
7.00      333
7.40      331
6.10      306
3.40      302
6.20      301
6.60      301
6.70      269
7.10      265
6.80      248
7.30      246
12.00     245
8.40      229
7.20      227
7.70      219
7.60      208
8.00      203
7.50      202
3.50      194
12.10     192
7.80      184
8.20      170
9.80      141
8.30      128
3.30      116
9.20      115
9.00      111
9.60      105
12.50     103
8.60       96
8.90       96
3.00       91
8.50       89
10.10      86
8.70       84
9.50       83
7.90       83
9.40       83
10.00      81
9.70       80
1.70       77
1.50       74
8.80       73
3.20       72
10.30      68
10.60      67
1.80       66
8.10       65
11.40      65
9.10       64
11.80      62
4.15       62
9.90       59
10.90      58
2.10       54
1.40       52
9.30       49
1.90       47
12.40      46
10.50      43
10.40      42
11.00      40
1.20       40
11.20      39
12.80      37
11.90      36
4.05       35
5.65       35
12.20      34
6.15       33
2.80       33
1.60       30
7.70       30
4.30       29
4.65       29
10.80      29
2.00       27
11.70      26
1.10       26
8.25       25
12.30      25
11.50      22
13.60      22
10.20      21
3.10       20
7.15       20
11.60      19
13.50      19
3.95       19
4.95       17
14.00      17
2.40       16
10.70      15
1.30       15
13.00      14
11.30      14
2.30       14
12.60      14
2.20       14
2.50       14
6.70       13
11.10      13
4.35       13
13.80      11
1.00       11
13.90      10
0.80       10
5.05        9
2.90        8
16.20       8
5.25        8
4.85        8
3.85        8
5.85        8
12.90       7
4.75        7
11.85       7
14.80       7
5.15        7
3.75        7
5.35        7
13.10       7
2.60        6
13.20       6
12.70       6
0.60        5
10.75       5
13.40       5
6.25        5
0.70        5
5.80        4
99.90       4
5.45        4
7.35        4
0.90        3
16.70       3
14.30       3
6.45        3
14.40       3
14.10       3
5.30        2
16.50       2
15.60       2
6.65        2
53.00       2
5.95        2
4.55        2
2.70        2
7.30        2
14.90       2
93.00       2
5.75        2
14.70       1
15.00       1
3.95        1
7.80        1
16.80       1
0.85        1
3.90        1
10.35       1
18.30       1
23.00       1
6.35        1
15.10       1
61.00       1
0.65        1
7.05        1
0.50        1
9.15        1
16.40       1
14.20       1
57.00       1
6.85        1
16.00       1
6.05        1
8.55        1
8.65        1
3.15        1
6.20        1
14.50       1
4.25        1
5.55        1
9.25        1
56.00       1
44.00       1
15.50       1
15.90       1
Name: count, dtype: int64

## cons_city

In [165]:
# Let's explore basic information about "cons_city"

first_looking("cons_city")

COLUMN NAME    :  cons_city
--------------------------------
per_of_nulls   :  % 29.79
num_of_nulls   :  8527
num_of_uniques :  195
--------------------------------
cons_city
NaN      8527
5.80      494
6.40      485
5.30      479
5.70      464
6.30      433
6.50      424
6.20      423
5.90      420
5.50      412
6.00      405
6.10      401
0.00      389
5.60      382
6.60      374
5.20      373
5.00      345
4.40      327
5.40      321
6.70      320
4.20      311
6.80      307
7.00      298
7.80      293
7.60      278
4.30      276
5.10      272
7.90      260
3.70      259
4.70      245
8.50      242
7.50      235
4.60      232
4.90      230
7.10      228
7.20      207
7.30      207
9.30      206
4.80      205
4.50      205
8.20      205
6.90      204
8.90      189
10.10     187
7.40      186
8.00      186
8.60      180
8.10      180
9.10      177
8.70      175
7.70      171
8.80      171
4.10      167
9.00      166
8.40      146
3.80      129
11.50     127
10.40     126
9.60      126
8.30      121
4.00      120
9.50      119
10.20     117
10.00     115
11.20     112
10.90     106
9.80      101
10.30      98
9.70       96
9.40       88
10.60      87
9.20       81
13.50      79
10.80      77
11.00      75
11.90      75
13.00      73
17.00      72
12.90      71
18.30      68
14.00      67
12.80      66
13.80      66
11.60      64
3.00       62
17.80      60
11.40      60
9.90       59
10.70      58
12.00      56
14.40      53
10.50      51
16.10      49
12.50      48
15.60      47
11.30      47
16.00      44
3.90       44
15.30      42
13.10      42
3.50       38
18.60      37
19.00      36
14.70      36
14.10      36
12.40      34
15.00      34
19.60      34
12.20      32
14.20      32
13.70      32
19.90      31
11.80      30
13.60      29
16.80      27
14.50      27
15.70      26
15.40      26
12.60      25
11.10      25
15.80      24
12.30      24
13.40      23
12.70      22
14.30      21
12.10      21
16.20      20
16.60      20
3.60       19
15.20      18
20.00      15
11.70      14
15.50      14
15.10      13
13.20      13
16.70      13
3.30       12
19.10      12
18.90      11
20.10      11
3.40       11
13.30      11
14.80      11
17.20      11
14.60      10
14.90       9
15.90       8
13.90       8
66.00       8
17.30       8
3.20        7
16.50       7
18.00       7
19.30       7
18.10       6
17.10       6
20.30       6
18.20       5
17.90       5
17.50       5
21.30       4
1.00        4
17.70       4
0.70        4
21.70       4
18.80       4
20.20       3
18.70       3
18.50       3
0.80        3
2.20        3
64.00       2
20.90       2
16.30       2
24.10       2
1.20        2
21.80       2
17.60       2
21.40       2
0.40        2
99.90       1
2.00        1
17.40       1
19.40       1
23.20       1
22.60       1
19.70       1
21.10       1
0.50        1
22.80       1
46.00       1
21.50       1
50.00       1
3.10        1
79.00       1
76.10       1
Name: count, dtype: int64

In [166]:
df.shape

(28624, 32)

In [167]:
# Let's drop "cons_city" since we have a calculate "cons_avg" feature

df.drop("cons_city", axis=1, inplace=True)

In [168]:
df.shape

(28624, 31)

## cons_country

In [169]:
# Let's explore basic information about "cons_country"

first_looking("cons_country")

COLUMN NAME    :  cons_country
--------------------------------
per_of_nulls   :  % 29.79
num_of_nulls   :  8527
num_of_uniques :  114
--------------------------------
cons_country
NaN      8527
4.30      884
4.00      804
4.20      750
4.70      730
5.00      725
3.60      679
4.60      668
4.90      663
3.80      660
4.50      659
3.90      640
4.10      632
5.10      598
4.40      587
3.70      520
5.70      474
4.80      460
5.40      445
5.20      443
5.30      413
5.60      394
5.50      383
0.00      378
5.80      376
3.40      341
3.20      334
3.30      327
3.50      304
5.90      301
6.50      289
6.20      261
6.00      242
6.70      239
6.10      229
7.00      205
6.40      202
6.30      199
3.00      163
6.90      150
6.80      139
3.10      136
7.40      113
8.70      108
6.60      108
7.80      104
8.10       98
7.60       98
7.10       98
7.70       94
9.10       84
7.30       78
8.30       77
7.20       77
8.00       77
8.50       75
8.20       69
8.80       65
2.90       62
7.90       62
9.30       53
9.60       44
7.50       42
8.90       36
9.00       34
8.40       33
9.80       25
8.60       22
9.20       22
9.50       20
11.00      15
10.50      13
10.90      12
9.40       12
10.00      12
2.80       12
11.20      11
10.30      10
9.70        9
10.40       8
2.70        6
1.00        5
0.80        5
11.80       5
10.20       5
11.10       5
12.00       5
13.70       4
9.90        4
12.90       4
2.60        2
0.90        2
12.20       2
11.90       2
10.60       2
13.40       2
2.40        1
12.10       1
0.60        1
14.70       1
11.40       1
48.00       1
12.40       1
10.10       1
13.00       1
44.90       1
49.00       1
98.00       1
1.90        1
14.00       1
18.00       1
11.70       1
14.40       1
11.50       1
12.70       1
Name: count, dtype: int64

In [170]:
df.shape

(28624, 31)

In [171]:
# Let's drop "cons_country" since we have a calculate "cons_avg" feature

df.drop("cons_country", axis=1, inplace=True)

In [172]:
df.shape

(28624, 30)

## drivetrain

In [173]:
# Let's explore basic information about "drivetrain"

first_looking("drivetrain")

COLUMN NAME    :  drivetrain
--------------------------------
per_of_nulls   :  % 40.99
num_of_nulls   :  11733
num_of_uniques :  3
--------------------------------
drivetrain
Front    12066
NaN      11733
4WD       3252
Rear      1573
Name: count, dtype: int64

In [174]:
# All NaN values are converted to dash/hyphen sign "-" to see them in the output of describe() and explore the hidden pattern

df["drivetrain"].fillna("-", inplace=True)

In [175]:
# let's explore if there is any pattern among "make_model", "body_type", and "drivetrain" by "price"

df.groupby(["make_model", "body_type", "drivetrain"]).price.describe()

                                               count     mean      std
make_model        body_type        drivetrain
Dacia 1300        Sedan            -            1.00  9999.00      NaN  \
Dacia Break       Station Wagon    -            1.00 20500.00      NaN
Dacia Business    Compact          Front        1.00 19515.00      NaN
Dacia Comfort Tce Station Wagon    -            1.00 21799.00      NaN
Dacia Dokker      Compact          -            1.00 11930.00      NaN
...                                              ...      ...      ...
Volvo Xc90        Off-Road/Pick-Up -           24.00 51277.08 18230.80
                                   4WD        167.00 52999.94 20131.83
                                   Front        8.00 30697.25 10639.35
                  Sedan            -            3.00 60366.67 21250.25
                  Station Wagon    4WD          4.00 32750.00  3752.78

                                                   min      25%      50%
make_model        body_type        drivetrain
Dacia 1300        Sedan            -           9999.00  9999.00  9999.00  \
Dacia Break       Station Wagon    -          20500.00 20500.00 20500.00
Dacia Business    Compact          Front      19515.00 19515.00 19515.00
Dacia Comfort Tce Station Wagon    -          21799.00 21799.00 21799.00
Dacia Dokker      Compact          -          11930.00 11930.00 11930.00
...                                                ...      ...      ...
Volvo Xc90        Off-Road/Pick-Up -          19975.00 38118.75 49842.50
                                   4WD         6400.00 42500.00 49980.00
                                   Front      13900.00 28967.50 34494.50
                  Sedan            -          47700.00 48100.00 48500.00
                  Station Wagon    4WD        29500.00 29500.00 32750.00

                                                   75%      max
make_model        body_type        drivetrain
Dacia 1300        Sedan            -           9999.00  9999.00
Dacia Break       Station Wagon    -          20500.00 20500.00
Dacia Business    Compact          Front      19515.00 19515.00
Dacia Comfort Tce Station Wagon    -          21799.00 21799.00
Dacia Dokker      Compact          -          11930.00 11930.00
...                                                ...      ...
Volvo Xc90        Off-Road/Pick-Up -          63750.00 83900.00
                                   4WD        65145.00 97450.00
                                   Front      36224.25 39900.00
                  Sedan            -          66700.00 84900.00
                  Station Wagon    4WD        36000.00 36000.00

[2127 rows x 8 columns]

<div style="background-color: #ffeeba; padding: 10px; font-size: 16px; font-weight: bold;">
    Domain Knowledge demonstrates that the <code>drivetrain</code> of cars changes by their <code>make_models</code> and <code>body_types</code> most of the time. So it's decided to fill missing values with <code>mode value</code> of corresponding group.
</div>

In [176]:
df[df["body_type"] == "Off-Road/Pick-up"][["make_model", "body_type", "fuel_type", "drivetrain"]].value_counts()

Series([], Name: count, dtype: int64)

### 📝 Domain Knowledge About Drivetrain of Some Electric Cars

The **``Škoda Enyaq iV``** is a battery electric compact crossover SUV manufactured by Škoda Auto. It was introduced in September 2020 in Prague, while mass production commenced in November 2020...The Enyaq iV will be available either as **``rear-wheel drive``** or **``all-wheel drive``**, with three different battery capacities and five performance versions...

The **``Hyundai Kona``** is a subcompact crossover SUV (B-segment) produced by the South Korean manufacturer Hyundai. The Kona debuted in June 2017 and the production version was revealed later that year...While it is developed as an urban-oriented crossover SUV, the Kona is available in **``front-wheel-drive``** and **``all-wheel-drive``** variants...

The **``Ford Mustang Mach-E``** is a battery electric compact crossover SUV produced by Ford. The vehicle was introduced on November 17, 2019, and went on sale in December 2020 as a 2021 model...Its Layout is either **``Rear-motor``** with **``rear-wheel drive``** or **``Dual-motor``** with **``all-wheel-drive``**...

This Domain Knowledge demonstrates that the newest car technology breaks through some major trends impacting automotive manufacturing, particularly for electric vehicles. Eventually, this comes up with a new terminology. Therefore, there is a conceptual confusion in the automative sector, since the technology used in the production of electric batteries is different and there is **no standardization** in terms of concepts yet.

In [177]:
# Let's replace dash/hyphen sign "-" with np.nan

df["drivetrain"] = df["drivetrain"].replace('-', np.nan)

In [178]:
# This DEF will fill the missing values in the "drivetrain" with the median value based on "make_model" and "body_type"

fill(df, "make_model", "body_type", "drivetrain", "mode")

COLUMN NAME    :  drivetrain
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  3
--------------------------------
drivetrain
4WD       4318
Front    21512
Rear      2794
Name: count, dtype: int64

## empty_weight

In [179]:
# Let's explore basic information about "empty_weight"

first_looking("empty_weight")

COLUMN NAME    :  empty_weight
--------------------------------
per_of_nulls   :  % 37.97
num_of_nulls   :  10868
num_of_uniques :  1218
--------------------------------
empty_weight
NaN        10868
1395.00      233
1055.00      224
1423.00      216
1165.00      200
           ...
1877.00        1
1011.00        1
1069.00        1
983.00         1
1391.00        1
Name: count, Length: 1219, dtype: int64

In [180]:
# All NaN values are converted to dash/hyphen sign "-" to see them in the output of describe() and explore the hidden pattern

df["empty_weight"].fillna("-", inplace=True)

In [181]:
# let's explore if there is any pattern among "make_model", "body_type", and "empty_weight" by "price"

df.groupby(["make_model", "body_type", "empty_weight"]).price.describe()

                                                 count     mean      std
make_model        body_type        empty_weight
Dacia 1300        Sedan            935.0          1.00  9999.00      NaN  \
Dacia Break       Station Wagon    -              1.00 20500.00      NaN
Dacia Business    Compact          1045.0         1.00 19515.00      NaN
Dacia Comfort Tce Station Wagon    -              1.00 21799.00      NaN
Dacia Dokker      Compact          -              1.00 11930.00      NaN
...                                                ...      ...      ...
Volvo Xc90        Off-Road/Pick-Up 2395.0         2.00 76930.00     0.00
                                   -             72.00 49016.86 19176.64
                  Sedan            -              3.00 60366.67 21250.25
                  Station Wagon    1931.0         2.00 29500.00     0.00
                                   2028.0         2.00 36000.00     0.00

                                                     min      25%      50%
make_model        body_type        empty_weight
Dacia 1300        Sedan            935.0         9999.00  9999.00  9999.00  \
Dacia Break       Station Wagon    -            20500.00 20500.00 20500.00
Dacia Business    Compact          1045.0       19515.00 19515.00 19515.00
Dacia Comfort Tce Station Wagon    -            21799.00 21799.00 21799.00
Dacia Dokker      Compact          -            11930.00 11930.00 11930.00
...                                                  ...      ...      ...
Volvo Xc90        Off-Road/Pick-Up 2395.0       76930.00 76930.00 76930.00
                                   -             7500.00 38865.00 48150.00
                  Sedan            -            47700.00 48100.00 48500.00
                  Station Wagon    1931.0       29500.00 29500.00 29500.00
                                   2028.0       36000.00 36000.00 36000.00

                                                     75%      max
make_model        body_type        empty_weight
Dacia 1300        Sedan            935.0         9999.00  9999.00
Dacia Break       Station Wagon    -            20500.00 20500.00
Dacia Business    Compact          1045.0       19515.00 19515.00
Dacia Comfort Tce Station Wagon    -            21799.00 21799.00
Dacia Dokker      Compact          -            11930.00 11930.00
...                                                  ...      ...
Volvo Xc90        Off-Road/Pick-Up 2395.0       76930.00 76930.00
                                   -            60367.50 83900.00
                  Sedan            -            66700.00 84900.00
                  Station Wagon    1931.0       29500.00 29500.00
                                   2028.0       36000.00 36000.00

[7398 rows x 8 columns]

<div style="background-color: #ffeeba; padding: 10px; font-size: 16px; font-weight: bold;">
    Domain Knowledge demonstrates that the <code>empty weight</code> of cars changes by their <code>make_models</code> and <code>body_types</code> most of the time. So it's decided to fill missing values with <code>mode value</code> of corresponding group.
</div>

In [182]:
# Let's replace dash/hyphen sign "-" with np.nan

df["empty_weight"].replace("-", np.nan, inplace=True)

In [183]:
# This DEF will fill the missing values in the "drivetrain" with the mode value based on "make_model", "body_type", and "empty_weight"

fill(df, "make_model", "body_type", "empty_weight", "mode")

COLUMN NAME    :  empty_weight
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  1218
--------------------------------
empty_weight
75.00       1
347.00      1
375.00      1
473.00      5
474.00      1
           ..
2750.00     1
2900.00     1
3150.00     1
11246.00    1
15590.00    1
Name: count, Length: 1218, dtype: int64

## previous_owner

In [184]:
# Let's explore basic information about "previous_owner"

first_looking("previous_owner")

COLUMN NAME    :  previous_owner
--------------------------------
per_of_nulls   :  % 51.04
num_of_nulls   :  14610
num_of_uniques :  13
--------------------------------
previous_owner
NaN      14610
1.00      9746
2.00      3220
3.00       699
4.00       184
5.00        69
6.00        37
7.00        22
8.00        16
9.00        14
12.00        3
10.00        2
14.00        1
13.00        1
Name: count, dtype: int64

In [185]:
# All NaN values are converted to dash/hyphen sign "-" to see them in the output of describe() and explore the hidden pattern

df["previous_owner"].fillna("-", inplace = True)

In [186]:
# let's explore if there is any pattern among "make_model", "body_type", 'age', and "previous_owner" by "price"

df.groupby(['make_model', 'body_type', 'age', 'previous_owner']).price.describe()

                                                         count     mean
make_model        body_type        age   previous_owner
Dacia 1300        Sedan            47.00 -                1.00  9999.00  \
Dacia Break       Station Wagon    0.00  -                1.00 20500.00
Dacia Business    Compact          1.00  1.0              1.00 19515.00
Dacia Comfort Tce Station Wagon    0.00  1.0              1.00 21799.00
Dacia Dokker      Compact          4.00  -                1.00 11930.00
...                                                        ...      ...
Volvo Xc90        Off-Road/Pick-Up 18.00 -                2.00  6799.00
                  Sedan            1.00  -                1.00 84900.00
                                   3.00  -                1.00 48500.00
                                   4.00  -                1.00 47700.00
                  Station Wagon    6.00  1.0              4.00 32750.00

                                                            std      min
make_model        body_type        age   previous_owner
Dacia 1300        Sedan            47.00 -                  NaN  9999.00  \
Dacia Break       Station Wagon    0.00  -                  NaN 20500.00
Dacia Business    Compact          1.00  1.0                NaN 19515.00
Dacia Comfort Tce Station Wagon    0.00  1.0                NaN 21799.00
Dacia Dokker      Compact          4.00  -                  NaN 11930.00
...                                                         ...      ...
Volvo Xc90        Off-Road/Pick-Up 18.00 -                 0.00  6799.00
                  Sedan            1.00  -                  NaN 84900.00
                                   3.00  -                  NaN 48500.00
                                   4.00  -                  NaN 47700.00
                  Station Wagon    6.00  1.0            3752.78 29500.00

                                                             25%      50%
make_model        body_type        age   previous_owner
Dacia 1300        Sedan            47.00 -               9999.00  9999.00  \
Dacia Break       Station Wagon    0.00  -              20500.00 20500.00
Dacia Business    Compact          1.00  1.0            19515.00 19515.00
Dacia Comfort Tce Station Wagon    0.00  1.0            21799.00 21799.00
Dacia Dokker      Compact          4.00  -              11930.00 11930.00
...                                                          ...      ...
Volvo Xc90        Off-Road/Pick-Up 18.00 -               6799.00  6799.00
                  Sedan            1.00  -              84900.00 84900.00
                                   3.00  -              48500.00 48500.00
                                   4.00  -              47700.00 47700.00
                  Station Wagon    6.00  1.0            29500.00 32750.00

                                                             75%      max
make_model        body_type        age   previous_owner
Dacia 1300        Sedan            47.00 -               9999.00  9999.00
Dacia Break       Station Wagon    0.00  -              20500.00 20500.00
Dacia Business    Compact          1.00  1.0            19515.00 19515.00
Dacia Comfort Tce Station Wagon    0.00  1.0            21799.00 21799.00
Dacia Dokker      Compact          4.00  -              11930.00 11930.00
...                                                          ...      ...
Volvo Xc90        Off-Road/Pick-Up 18.00 -               6799.00  6799.00
                  Sedan            1.00  -              84900.00 84900.00
                                   3.00  -              48500.00 48500.00
                                   4.00  -              47700.00 47700.00
                  Station Wagon    6.00  1.0            36000.00 36000.00

[8477 rows x 8 columns]

In [187]:
# let's explore if there is any pattern among "make_model", "body_type", 'age', and "previous_owner" by "mileage"

df.groupby(['make_model', 'body_type', 'age', 'previous_owner']).mileage.describe()

                                                         count      mean
make_model        body_type        age   previous_owner
Dacia 1300        Sedan            47.00 -                1.00  59098.00  \
Dacia Break       Station Wagon    0.00  -                1.00    999.00
Dacia Business    Compact          1.00  1.0              1.00   2376.00
Dacia Comfort Tce Station Wagon    0.00  1.0              1.00   2000.00
Dacia Dokker      Compact          4.00  -                1.00 141100.00
...                                                        ...       ...
Volvo Xc90        Off-Road/Pick-Up 18.00 -                2.00 237102.00
                  Sedan            1.00  -                1.00  20635.00
                                   3.00  -                1.00  68940.00
                                   4.00  -                1.00  86709.00
                  Station Wagon    6.00  1.0              4.00 146775.00

                                                            std       min
make_model        body_type        age   previous_owner
Dacia 1300        Sedan            47.00 -                  NaN  59098.00  \
Dacia Break       Station Wagon    0.00  -                  NaN    999.00
Dacia Business    Compact          1.00  1.0                NaN   2376.00
Dacia Comfort Tce Station Wagon    0.00  1.0                NaN   2000.00
Dacia Dokker      Compact          4.00  -                  NaN 141100.00
...                                                         ...       ...
Volvo Xc90        Off-Road/Pick-Up 18.00 -                 0.00 237102.00
                  Sedan            1.00  -                  NaN  20635.00
                                   3.00  -                  NaN  68940.00
                                   4.00  -                  NaN  86709.00
                  Station Wagon    6.00  1.0            3723.91 143550.00

                                                              25%       50%
make_model        body_type        age   previous_owner
Dacia 1300        Sedan            47.00 -               59098.00  59098.00  \
Dacia Break       Station Wagon    0.00  -                 999.00    999.00
Dacia Business    Compact          1.00  1.0              2376.00   2376.00
Dacia Comfort Tce Station Wagon    0.00  1.0              2000.00   2000.00
Dacia Dokker      Compact          4.00  -              141100.00 141100.00
...                                                           ...       ...
Volvo Xc90        Off-Road/Pick-Up 18.00 -              237102.00 237102.00
                  Sedan            1.00  -               20635.00  20635.00
                                   3.00  -               68940.00  68940.00
                                   4.00  -               86709.00  86709.00
                  Station Wagon    6.00  1.0            143550.00 146775.00

                                                              75%       max
make_model        body_type        age   previous_owner
Dacia 1300        Sedan            47.00 -               59098.00  59098.00
Dacia Break       Station Wagon    0.00  -                 999.00    999.00
Dacia Business    Compact          1.00  1.0              2376.00   2376.00
Dacia Comfort Tce Station Wagon    0.00  1.0              2000.00   2000.00
Dacia Dokker      Compact          4.00  -              141100.00 141100.00
...                                                           ...       ...
Volvo Xc90        Off-Road/Pick-Up 18.00 -              237102.00 237102.00
                  Sedan            1.00  -               20635.00  20635.00
                                   3.00  -               68940.00  68940.00
                                   4.00  -               86709.00  86709.00
                  Station Wagon    6.00  1.0            150000.00 150000.00

[8477 rows x 8 columns]

In [188]:
# Let's replace dash/hyphen sign "-" with np.nan

df["previous_owner"].replace("-", np.nan, inplace=True)

In [189]:
def fill_prop(df, group_col, col_name):
    '''Fills the missing values with "ffill and bfill method" according to single-stage grouping'''
    
    for group in df[group_col].unique():
        cond = df[group_col] == group
        df.loc[cond, col_name] = df.loc[cond, col_name].fillna(method="ffill").fillna(method="bfill")
    
    df[col_name] = df[col_name].fillna(method="ffill").fillna(method="bfill")
    
    print("column name    : ", col_name)
    print("--------------------------------")
    print("per_of_nulls   : ", "%", round(df[col_name].isnull().sum()*100 / df.shape[0], 2))
    print("num_of_nulls   : ", df[col_name].isnull().sum())
    print("num_of_uniques : ", df[col_name].nunique())
    print("--------------------------------")
    print(df[col_name].value_counts(dropna = False))

In [190]:
# This DEF fills missing values in "previous_owner" using forward and backward fill based on "age"

fill_prop(df, "age", "previous_owner")

column name    :  previous_owner
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  13
--------------------------------
previous_owner
1.00     18700
2.00      7199
3.00      1756
4.00       500
5.00       206
6.00       100
8.00        71
7.00        57
9.00        25
12.00        6
10.00        2
14.00        1
13.00        1
Name: count, dtype: int64

## energy_efficiency_class

In [191]:
# Let's explore basic information about "energy_efficiency_class"

first_looking("energy_efficiency_class")

COLUMN NAME    :  energy_efficiency_class
--------------------------------
per_of_nulls   :  % 72.74
num_of_nulls   :  20820
num_of_uniques :  2
--------------------------------
energy_efficiency_class
NaN            20820
efficient       5308
unefficient     2496
Name: count, dtype: int64

In [192]:
# All NaN values are converted to dash/hyphen sign "-" to see them in the output of describe() and explore the hidden pattern

df["energy_efficiency_class"].fillna("-", inplace = True)

In [193]:
# let's explore if there is any pattern among 'energy_efficiency_class', "make_model", "body_type", and "age" by "mileage"

df.groupby(['energy_efficiency_class', 'make_model', 'body_type', 'age']).mileage.describe()

                                                             count      mean
energy_efficiency_class make_model   body_type        age
-                       Dacia 1300   Sedan            47.00   1.00  59098.00  \
                        Dacia Break  Station Wagon    0.00    1.00    999.00
                        Dacia Dokker Compact          4.00    1.00 141100.00
                                     Off-Road/Pick-Up 4.00    2.00 100000.00
                                     Sedan            5.00    1.00 149000.00
...                                                            ...       ...
unefficient             Volvo Xc70   Station Wagon    14.00   2.00 353453.00
                        Volvo Xc90   Off-Road/Pick-Up 1.00    2.00   1494.00
                                                      2.00    4.00  33315.50
                                                      3.00    6.00  47009.33
                                                      14.00   4.00 271343.50

                                                                 std
energy_efficiency_class make_model   body_type        age
-                       Dacia 1300   Sedan            47.00      NaN  \
                        Dacia Break  Station Wagon    0.00       NaN
                        Dacia Dokker Compact          4.00       NaN
                                     Off-Road/Pick-Up 4.00      0.00
                                     Sedan            5.00       NaN
...                                                              ...
unefficient             Volvo Xc70   Station Wagon    14.00     0.00
                        Volvo Xc90   Off-Road/Pick-Up 1.00      0.00
                                                      2.00  10404.43
                                                      3.00  13221.93
                                                      14.00 21542.67

                                                                  min
energy_efficiency_class make_model   body_type        age
-                       Dacia 1300   Sedan            47.00  59098.00  \
                        Dacia Break  Station Wagon    0.00     999.00
                        Dacia Dokker Compact          4.00  141100.00
                                     Off-Road/Pick-Up 4.00  100000.00
                                     Sedan            5.00  149000.00
...                                                               ...
unefficient             Volvo Xc70   Station Wagon    14.00 353453.00
                        Volvo Xc90   Off-Road/Pick-Up 1.00    1494.00
                                                      2.00   24305.00
                                                      3.00   30028.00
                                                      14.00 252687.00

                                                                  25%
energy_efficiency_class make_model   body_type        age
-                       Dacia 1300   Sedan            47.00  59098.00  \
                        Dacia Break  Station Wagon    0.00     999.00
                        Dacia Dokker Compact          4.00  141100.00
                                     Off-Road/Pick-Up 4.00  100000.00
                                     Sedan            5.00  149000.00
...                                                               ...
unefficient             Volvo Xc70   Station Wagon    14.00 353453.00
                        Volvo Xc90   Off-Road/Pick-Up 1.00    1494.00
                                                      2.00   24305.00
                                                      3.00   36021.00
                                                      14.00 252687.00

                                                                  50%
energy_efficiency_class make_model   body_type        age
-                       Dacia 1300   Sedan            47.00  59098.00  \
                        Dacia Break  Station Wagon    0.00     999.00
                        Dacia Dokker Compact          4.00  141100.00
                                     Off-Road/Pick-Up 4.00  100000.00
                                     Sedan            5.00  149000.00
...                                                               ...
unefficient             Volvo Xc70   Station Wagon    14.00 353453.00
                        Volvo Xc90   Off-Road/Pick-Up 1.00    1494.00
                                                      2.00   33315.50
                                                      3.00   54000.00
                                                      14.00 271343.50

                                                                  75%
energy_efficiency_class make_model   body_type        age
-                       Dacia 1300   Sedan            47.00  59098.00  \
                        Dacia Break  Station Wagon    0.00     999.00
                        Dacia Dokker Compact          4.00  141100.00
                                     Off-Road/Pick-Up 4.00  100000.00
                                     Sedan            5.00  149000.00
...                                                               ...
unefficient             Volvo Xc70   Station Wagon    14.00 353453.00
                        Volvo Xc90   Off-Road/Pick-Up 1.00    1494.00
                                                      2.00   42326.00
                                                      3.00   56250.00
                                                      14.00 290000.00

                                                                  max
energy_efficiency_class make_model   body_type        age
-                       Dacia 1300   Sedan            47.00  59098.00
                        Dacia Break  Station Wagon    0.00     999.00
                        Dacia Dokker Compact          4.00  141100.00
                                     Off-Road/Pick-Up 4.00  100000.00
                                     Sedan            5.00  149000.00
...                                                               ...
unefficient             Volvo Xc70   Station Wagon    14.00 353453.00
                        Volvo Xc90   Off-Road/Pick-Up 1.00    1494.00
                                                      2.00   42326.00
                                                      3.00   57000.00
                                                      14.00 290000.00

[6820 rows x 8 columns]

In [194]:
# Let's focus on discovering what NaN values in "energy_efficiency_class" tell

# df.loc[(df.energy_efficiency_class == "-") & (df.fuel_type == "Electric")][["make_model", "age", "body_type", "gearbox", "drivetrain", "gears", "engine_size", "fuel_type", "co_emissions", "cons_avg"]]

df.loc[(df.energy_efficiency_class == "-")][["make_model", "age", "body_type", "gearbox", "drivetrain", "gears", "engine_size", "fuel_type", "co_emissions", "cons_avg"]]

,make_model,age,body_type,gearbox,drivetrain,gears,engine_size,fuel_type,co_emissions,cons_avg
0,Mercedes-Benz A 160,6.00,Compact,Manual,Front,6.00,1595.00,Diesel,98.00,3.80
1,Mercedes-Benz Eqe 350,0.00,Compact,Automatic,4WD,9.00,1.00,Electric,0.00,2.36
2,Mercedes-Benz A 45 Amg,2.00,Compact,Automatic,4WD,8.00,1991.00,Benzine,162.00,8.40
3,Mercedes-Benz A 35 Amg,2.00,Compact,Automatic,4WD,7.00,1991.00,Benzine,169.00,7.30
4,Mercedes-Benz A 45 Amg,7.00,Compact,Automatic,4WD,7.00,2143.00,Diesel,162.00,4.90
...,...,...,...,...,...,...,...,...,...,...
28625,Volvo S90,3.00,Sedan,Automatic,4WD,8.00,1969.00,Diesel,127.00,2.00
28626,Volvo S40,18.00,Sedan,Automatic,Front,5.00,2435.00,Benzine,217.00,9.10
28627,Volvo C30,11.00,Sedan,Manual,Front,6.00,1560.00,Diesel,99.00,3.80
28628,Volvo S90,5.00,Sedan,Automatic,4WD,8.00,1969.00,Benzine,149.00,6.50
28629,Volvo S80,20.00,Sedan,Automatic,Front,6.00,2922.00,Benzine,251.00,10.40

In [195]:
df.loc[(df.energy_efficiency_class == "-")]["age"].value_counts()

age
4.00       2669
3.00       2332
5.00       1999
2.00       1492
1.00       1447
6.00       1248
7.00       1084
0.00       1081
8.00        822
9.00        630
11.00       603
10.00       593
12.00       525
15.00       484
14.00       414
13.00       407
16.00       389
17.00       277
18.00       244
19.00       208
21.00       189
20.00       182
22.00       159
23.00       140
24.00        89
28.00        79
25.00        79
27.00        78
26.00        69
31.00        62
30.00        59
32.00        54
29.00        54
56.00        40
55.00        33
57.00        32
34.00        32
49.00        29
50.00        28
54.00        27
35.00        26
44.00        23
36.00        22
33.00        20
52.00        19
51.00        18
37.00        18
53.00        17
43.00        17
39.00        16
47.00        14
45.00        13
58.00        11
46.00        11
40.00        11
38.00        10
48.00         9
41.00         9
59.00         9
60.00         8
61.00         7
67.00         6
42.00         6
68.00         4
64.00         4
65.00         4
62.00         4
90.00         3
63.00         2
85.00         2
69.00         2
92.00         2
70.00         2
-3.00         1
89.00         1
76.00         1
66.00         1
-1.00         1
93.00         1
72.00         1
94.00         1
-180.00       1
Name: count, dtype: int64

In [196]:
# Let's replace dash/hyphen sign "-" with np.nan

df["energy_efficiency_class"].replace("-", np.nan, inplace=True)

In [197]:
fill(df, "make_model", "age", "energy_efficiency_class", "mode")

COLUMN NAME    :  energy_efficiency_class
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  2
--------------------------------
energy_efficiency_class
efficient      18612
unefficient    10012
Name: count, dtype: int64

## upholstery

In [198]:
# Let's explore basic information about "upholstery"

first_looking("upholstery")

COLUMN NAME    :  upholstery
--------------------------------
per_of_nulls   :  % 35.0
num_of_nulls   :  10017
num_of_uniques :  6
--------------------------------
upholstery
NaN             10017
Cloth            8736
Full leather     5438
Part leather     2834
alcantara         764
Other             627
Velour            208
Name: count, dtype: int64

### 📝 Domain Knowledge About Velour & Alcantara

**``Velour``** is a traditional fabric cloth previously used on OE automotive seating. It features a durable construction and is finished with a 3.5mm foam and denier backing for ease of fabrication. Velour insert cloth is versatile and can be used on other general purpose upholstery applications.

**``Alcantara``** is an Italian-made synthetic fabric that is durable and feels like suede. Alcantara has a soft, suede-like microfiber pile and is renowned for its unmatched durability. Alcantara is commonly used in car interiors such as Alcantara car seats or Alcantara steering wheel covers.

In [199]:
# Let's redesign "upholstery" feature based on Domain Knowledge About Velour & Alcantara above

df["upholstery"].replace(["Velour", "alcantara", "Part leather", "Full leather"],
                         ["Cloth", "Part/Full Leather", "Part/Full Leather", "Part/Full Leather"], inplace=True)

df["upholstery"].replace("Other", np.nan, inplace=True)

df["upholstery"].value_counts(dropna=False)

upholstery
NaN                  10644
Part/Full Leather     9036
Cloth                 8944
Name: count, dtype: int64

In [200]:
# All NaN values are converted to dash/hyphen sign "-" to see them in the output of describe() and explore the hidden pattern

df["upholstery"].fillna("-", inplace=True)

In [201]:
# let's explore if there is any pattern among "make_model", "body_type", "age", and "upholstery"by "price"

df.groupby(["make_model", "body_type", "age", "upholstery"]).price.describe()

                                                            count     mean
make_model        body_type        age   upholstery
Dacia 1300        Sedan            47.00 Cloth               1.00  9999.00  \
Dacia Break       Station Wagon    0.00  -                   1.00 20500.00
Dacia Business    Compact          1.00  Part/Full Leather   1.00 19515.00
Dacia Comfort Tce Station Wagon    0.00  Cloth               1.00 21799.00
Dacia Dokker      Compact          4.00  -                   1.00 11930.00
...                                                           ...      ...
Volvo Xc90        Off-Road/Pick-Up 18.00 -                   2.00  6799.00
                  Sedan            1.00  Part/Full Leather   1.00 84900.00
                                   3.00  -                   1.00 48500.00
                                   4.00  -                   1.00 47700.00
                  Station Wagon    6.00  Part/Full Leather   4.00 32750.00

                                                               std      min
make_model        body_type        age   upholstery
Dacia 1300        Sedan            47.00 Cloth                 NaN  9999.00  \
Dacia Break       Station Wagon    0.00  -                     NaN 20500.00
Dacia Business    Compact          1.00  Part/Full Leather     NaN 19515.00
Dacia Comfort Tce Station Wagon    0.00  Cloth                 NaN 21799.00
Dacia Dokker      Compact          4.00  -                     NaN 11930.00
...                                                            ...      ...
Volvo Xc90        Off-Road/Pick-Up 18.00 -                    0.00  6799.00
                  Sedan            1.00  Part/Full Leather     NaN 84900.00
                                   3.00  -                     NaN 48500.00
                                   4.00  -                     NaN 47700.00
                  Station Wagon    6.00  Part/Full Leather 3752.78 29500.00

                                                                25%      50%
make_model        body_type        age   upholstery
Dacia 1300        Sedan            47.00 Cloth              9999.00  9999.00  \
Dacia Break       Station Wagon    0.00  -                 20500.00 20500.00
Dacia Business    Compact          1.00  Part/Full Leather 19515.00 19515.00
Dacia Comfort Tce Station Wagon    0.00  Cloth             21799.00 21799.00
Dacia Dokker      Compact          4.00  -                 11930.00 11930.00
...                                                             ...      ...
Volvo Xc90        Off-Road/Pick-Up 18.00 -                  6799.00  6799.00
                  Sedan            1.00  Part/Full Leather 84900.00 84900.00
                                   3.00  -                 48500.00 48500.00
                                   4.00  -                 47700.00 47700.00
                  Station Wagon    6.00  Part/Full Leather 29500.00 32750.00

                                                                75%      max
make_model        body_type        age   upholstery
Dacia 1300        Sedan            47.00 Cloth              9999.00  9999.00
Dacia Break       Station Wagon    0.00  -                 20500.00 20500.00
Dacia Business    Compact          1.00  Part/Full Leather 19515.00 19515.00
Dacia Comfort Tce Station Wagon    0.00  Cloth             21799.00 21799.00
Dacia Dokker      Compact          4.00  -                 11930.00 11930.00
...                                                             ...      ...
Volvo Xc90        Off-Road/Pick-Up 18.00 -                  6799.00  6799.00
                  Sedan            1.00  Part/Full Leather 84900.00 84900.00
                                   3.00  -                 48500.00 48500.00
                                   4.00  -                 47700.00 47700.00
                  Station Wagon    6.00  Part/Full Leather 36000.00 36000.00

[8054 rows x 8 columns]

<div style="background-color: #ffeeba; padding: 10px; font-size: 16px; font-weight: bold;">
    Since it was <u>NOT</u> detected a <u>clear relationship</u> among features ffill/bfill methods to fill missing values would be prefered to maintain the current proportionality.
</div>

In [202]:
# Let's replace dash/hyphen sign "-" with np.nan

df["upholstery"].replace("-", np.nan, inplace=True)

In [203]:
# This DEF fills missing values in "upholstery" using forward fill based on "make_model" and "body_type"

fill(df, "make_model", "body_type", "upholstery", "ffill")

COLUMN NAME    :  upholstery
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  2
--------------------------------
upholstery
Cloth                15032
Part/Full Leather    13592
Name: count, dtype: int64

## comfort_&_convenience

In [204]:
# Let's explore basic information about "comfort_&_convenience"

first_looking("comfort_&_convenience")

COLUMN NAME    :  comfort_&_convenience
--------------------------------
per_of_nulls   :  % 11.16
num_of_nulls   :  3194
num_of_uniques :  14435
--------------------------------
comfort_&_convenience
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                3194
Air conditioning, Automatic climate control, Electrical side mirrors, Multi-function steering wheel, Power windows                                                                                                                                                                                                                                                                                                                                                                                                                                                  244
Air conditioning, Automatic climate control, Cruise control                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         171
Air conditioning, Automatic climate control, Cruise control, Electrical side mirrors, Multi-function steering wheel, Power windows                                                                                                                                                                                                                                                                                                                                                                                                                                  168
Air conditioning                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    157
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ...
Air conditioning, Armrest, Automatic climate control, 2 zones, Cruise control, Electric tailgate, Electrical side mirrors, Electrically adjustable seats, Hill Holder, Leather steering wheel, Light sensor, Lumbar support, Massage seats, Multi-function steering wheel, Navigation system, Panorama roof, Parking assist system camera, Parking assist system self-steering, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Split rear seats, Start-stop system, Sunroof, Tinted windows       1
Armrest, Automatic climate control, 2 zones, Cruise control, Fold flat passenger seat, Hill Holder, Leather steering wheel, Light sensor, Lumbar support, Multi-function steering wheel, Navigation system, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Split rear seats, Start-stop system                                                                                                                                                                                                                                         1
Air conditioning, Armrest, Automatic climate control, Cruise control, Electric tailgate, Electrical side mirrors, Hill Holder, Keyless central door lock, Leather steering wheel, Light sensor, Multi-function steering wheel, Navigation system, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating                                                                                                                                                                                                   1
Armrest, Automatic climate control, 2 zones, Cruise control, Electrical side mirrors, Fold flat passenger seat, Hill Holder, Leather steering wheel, Light sensor, Lumbar support, Multi-function steering wheel, Navigation system, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Split rear seats, Start-stop system, Tinted windows                                                                                                                                                           1
Air conditioning, Armrest, Cruise control, Electrical side mirrors, Leather steering wheel, Lumbar support, Multi-function steering wheel, Navigation system, Power windows, Seat heating, Tinted windows                                                                                                                                                                                                                                                                                                                                                             1
Name: count, Length: 14436, dtype: int64

In [205]:
# This DEF will fill the missing values in the "comfort_&_convenience" with the mode value based on "make_model" and "body_type"

fill(df, "make_model", "body_type", "comfort_&_convenience", "mode")

COLUMN NAME    :  comfort_&_convenience
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  14435
--------------------------------
comfort_&_convenience
360° camera                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    3
360° camera, Air conditioning, Air suspension, Armrest, Automatic climate control, 2 zones, Auxiliary heating, Cruise control, Electric tailgate, Electrical side mirrors, Electrically adjustable seats, Heads-up display, Heated steering wheel, Hill Holder, Keyless central door lock, Leather steering wheel, Light sensor, Lumbar support, Multi-function steering wheel, Navigation system, Panorama roof, Parking assist system camera, Parking assist system self-steering, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Start-stop system, Sunroof                                             1
360° camera, Air conditioning, Air suspension, Armrest, Automatic climate control, 2 zones, Auxiliary heating, Cruise control, Electric tailgate, Electrical side mirrors, Electrically adjustable seats, Heads-up display, Heated steering wheel, Hill Holder, Leather steering wheel, Light sensor, Lumbar support, Massage seats, Multi-function steering wheel, Navigation system, Panorama roof, Parking assist system camera, Parking assist system self-steering, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Seat ventilation, Split rear seats, Start-stop system, Sunroof, Tinted windows     3
360° camera, Air conditioning, Air suspension, Armrest, Automatic climate control, 2 zones, Auxiliary heating, Cruise control, Electric tailgate, Electrical side mirrors, Electrically adjustable seats, Heads-up display, Hill Holder, Keyless central door lock, Leather steering wheel, Light sensor, Multi-function steering wheel, Navigation system, Panorama roof, Parking assist system camera, Parking assist system self-steering, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Seat ventilation, Start-stop system, Sunroof                                                                  1
360° camera, Air conditioning, Air suspension, Armrest, Automatic climate control, 2 zones, Auxiliary heating, Cruise control, Electric tailgate, Electrical side mirrors, Electrically adjustable seats, Hill Holder, Keyless central door lock, Leather steering wheel, Light sensor, Lumbar support, Multi-function steering wheel, Navigation system, Panorama roof, Parking assist system camera, Parking assist system self-steering, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Seat ventilation, Split rear seats, Start-stop system, Sunroof, Tinted windows                                  1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ..
Sunroof                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       21
Sunroof, Tinted windows                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
Sunroof, Wind deflector                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
Tinted windows                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                59
Wind deflector                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
Name: count, Length: 14435, dtype: int64

In [206]:
# df['comfort_&_convenience'].str.split(',', expand=True).stack().str.strip().explode().unique()

In [207]:
# If you want to see more, full string for each row/observation, use the following
# pd.set_option('display.max_colwidth', -1)

# df['comfort_&_convenience']

### 📝 Some Remarks on Comfort & Conveniance Features of Cars:

**Let us define ``"Comfort & Conveniance Packages"`` for vehicles based on Domain Knowledge:**

Here are general definitions of standard, premium, and premium comfort & convenience packages for vehicles:

  - **``Standard Package``**: The Standard Package is the base configuration for a vehicle model, and typically includes basic features and equipment. This may include things like air conditioning, power windows and locks, and a basic audio system.

  - **``Premium Package``**: The Premium Package is an upgrade to the standard package and usually includes additional or enhanced features and equipment. This may include features like leather seats, a premium audio system, a sunroof/moonroof, and advanced driver assistance systems (ADAS) such as blind spot monitoring or lane departure warning.

  - **``Premium Plus Package``**: The Premium Plus Package is another upgrade to the premium package and typically includes additional luxury features that enhance the driving experience. This may include features like heated and ventilated seats, a power-adjustable steering wheel, a larger infotainment display, and a premium sound system.

Keep in mind that the specific features and equipment included in each package can vary depending on the vehicle make and model. Additionally, some features may be available as standalone options or bundled with other packages. It's always a good idea to review the specific details of each package to determine which one best fits your needs and budget.

In [208]:
# display all unique values in "comfort_&_convenience"
# pd.set_option('display.max_rows', None)

df['comfort_&_convenience'].unique()

array(['Air conditioning, Cruise control, Start-stop system',
       'Air conditioning, Air suspension, Armrest, Automatic climate control, Auxiliary heating, Cruise control, Electrical side mirrors, Electrically adjustable seats, Electrically heated windshield, Heads-up display, Heated steering wheel, Hill Holder, Keyless central door lock, Leather steering wheel, Light sensor, Lumbar support, Multi-function steering wheel, Navigation system, Panorama roof, Parking assist system camera, Parking assist system self-steering, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Sunroof',
       'Air conditioning, Electrical side mirrors, Multi-function steering wheel, Power windows, Split rear seats',
       ...,
       'Air conditioning, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Multi-function steering wheel, Parking assist system sensors rear, Power windows, Rain sensor, Tinted windows',
       'Air conditioning, Armrest, Automatic climate control, Cruise control, Electric tailgate, Electrical side mirrors, Keyless central door lock, Leather steering wheel, Multi-function steering wheel, Navigation system, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Sunroof',
       'Air conditioning, Armrest, Cruise control, Electrical side mirrors, Leather steering wheel, Lumbar support, Multi-function steering wheel, Navigation system, Power windows, Seat heating, Tinted windows'],
      dtype=object)

In [209]:
# reset the 'max_rows' option to its default value
# pd.reset_option('display.max_rows')

In [210]:
premium = ["Electrical side mirrors", "Parking assist", "Air conditioning", "Hill Holder", "Power windows"]
premium_plus = ["Multi-function", "Navigation ", "Keyless central door lock", "Heads-up", "Massage seats", "heating", "Automatic climate control", "Heated"]

comfort_package = df['comfort_&_convenience'].apply(lambda sentence: "Premium Plus" if all(word in sentence for word in premium_plus) else ("Premium" if all(word in sentence for word in premium) else "Standard"))
comfort_package.value_counts()

comfort_&_convenience
Standard        19722
Premium          8808
Premium Plus       94
Name: count, dtype: int64

**Let us assign each car to related ``"Comfort & Conveniance Packages"`` defined above:**

In [211]:
# # To see maximum column width
# pd.set_option('display.max_colwidth', None)

# # To reset maximum column width OR all options
# pd.reset_option('display.max_colwidth', silent=True)
# pd.reset_option('^display.', silent=True)
# reset_option('all')

premium = ["Electrical side mirrors", "Parking assist", "Air conditioning", "Hill Holder", "Power windows"]
premium_plus = ["Multi-function", "Navigation ", "Keyless central door lock", "Heads-up", "Massage seats", "heating", "Automatic climate control", "Heated"]

df['comfort_&_convenience_Package'] = df['comfort_&_convenience'].apply(lambda sentence: "Premium Plus" if all(word in sentence for word in premium_plus) else ("Premium" if all(word in sentence for word in premium) else "Standard"))
df

,make_model,make,model,location,price,body_type,type,doors,warranty,mileage,gearbox,fuel_type,seller,seats,engine_size,gears,co_emissions,drivetrain,comfort_&_convenience,entertainment_&_media,safety_&_security,extras,empty_weight,full_service_history,upholstery,previous_owner,energy_efficiency_class,age,power_kW,cons_avg,comfort_&_convenience_Package
0,Mercedes-Benz A 160,Mercedes-Benz,A 160,"P.I. EL PALMAR C/FORJA 6, 11500 PUERTO DE SAN...",16950.00,Compact,Used,5.00,Yes,120200.00,Manual,Diesel,Dealer,5.00,1595.00,6.00,98.00,Front,"Air conditioning, Cruise control, Start-stop s...",NaN,NaN,NaN,1270.00,No,Cloth,2.00,efficient,6.00,75.00,3.80,Standard
1,Mercedes-Benz Eqe 350,Mercedes-Benz,Eqe 350,"APARTADO DE CORREOS 1032, 26140 LOGROÑO, ES",80900.00,Compact,Pre-registered,4.00,Yes,5000.00,Automatic,Electric,Dealer,5.00,1.00,9.00,0.00,4WD,"Air conditioning, Air suspension, Armrest, Aut...",NaN,NaN,NaN,2355.00,No,Part/Full Leather,1.00,efficient,0.00,215.00,2.36,Premium
2,Mercedes-Benz A 45 Amg,Mercedes-Benz,A 45 Amg,"PORT. TARRACO, MOLL DE LLEVANT, Nº 5, LOC. 6-8...",69900.00,Compact,Used,5.00,Yes,18900.00,Automatic,Benzine,Dealer,5.00,1991.00,8.00,162.00,4WD,"Air conditioning, Electrical side mirrors, Mul...",NaN,NaN,NaN,1555.00,No,Part/Full Leather,2.00,unefficient,2.00,310.00,8.40,Standard
3,Mercedes-Benz A 35 Amg,Mercedes-Benz,A 35 Amg,"Carrer de Provença, 31 Local, 8029 BARCELONA, ES",46990.00,Compact,Used,5.00,Yes,18995.00,Automatic,Benzine,Dealer,5.00,1991.00,7.00,169.00,4WD,"Air conditioning, Automatic climate control, P...",USB,"ABS, Central door lock, Driver-side airbag, El...",Sport seats,1455.00,No,Part/Full Leather,2.00,unefficient,2.00,225.00,7.30,Standard
4,Mercedes-Benz A 45 Amg,Mercedes-Benz,A 45 Amg,"CARRIL ARAGONES 4, 30007 CASILLAS, ES",16800.00,Compact,Used,5.00,Yes,197000.00,Automatic,Diesel,Dealer,5.00,2143.00,7.00,162.00,4WD,"Air conditioning, Electrical side mirrors, Mul...","Bluetooth, CD player, MP3, USB","ABS, Central door lock, Driver-side airbag, El...",NaN,1545.00,No,Part/Full Leather,2.00,unefficient,7.00,100.00,4.90,Standard
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28625,Volvo S90,Volvo,S90,"HERMANOS LUMIERE Nº16, 29004 MALAGA, ES",37600.00,Sedan,Used,4.00,Yes,40345.00,Automatic,Diesel,Dealer,4.00,1969.00,8.00,127.00,4WD,"Air conditioning, Automatic climate control, M...","Bluetooth, USB","ABS, Central door lock, Driver-side airbag, El...",Alloy wheels,2077.00,No,Part/Full Leather,2.00,efficient,3.00,288.00,2.00,Standard
28626,Volvo S40,Volvo,S40,"Stobbeweg 6, 2461 EX TER AAR, NL",5499.00,Sedan,Used,4.00,No,145000.00,Automatic,Benzine,Dealer,5.00,2435.00,5.00,217.00,Front,"Air conditioning, Armrest, Automatic climate c...","On-board computer, Radio","ABS, Central door lock, Central door lock with...","Alloy wheels (16""), Trailer hitch",1357.00,Yes,Cloth,3.00,efficient,18.00,125.00,9.10,Standard
28627,Volvo C30,Volvo,C30,"Sur rendez-vous, 5060 Sambreville, BE",7300.00,Sedan,Used,3.00,Yes,96000.00,Manual,Diesel,Dealer,4.00,1560.00,6.00,99.00,Front,"Air conditioning, Armrest, Automatic climate c...","Bluetooth, CD player, Hands-free equipment, MP...","ABS, Alarm system, Central door lock with remo...","Alloy wheels, Automatically dimming interior m...",1356.00,Yes,Cloth,1.00,unefficient,11.00,84.00,3.80,Standard
28628,Volvo S90,Volvo,S90,"Bergambachterstraat 5, 2871 JB SCHOONHOVEN, NL",29900.00,Sedan,Used,4.00,Yes,94343.00,Automatic,Benzine,Dealer,5.00,1969.00,8.00,149.00,4WD,"Air conditioning, Armrest, Automatic climate c...","Android Auto, Apple CarPlay, Bluetooth, Hands-...","Adaptive Cruise Control, Adaptive headlights, ...","Alloy wheels (18""), Automatically dimming inte...",1617.00,Yes,Part/Full Leather,1.00,efficient,5.00,187.00,6.50,Standard
28629,Volvo S80,Volvo,S80,"Lage Ham 106, 5102 AE DONGEN, NL",4440.00,Sedan,Used,4.00,No,230047.00,Automatic,Benzine,Dealer,5.00,2922.00,6.00,251.00,Front,"Air conditioning, Armrest, Cruise control, Ele...",On-board computer,"ABS, Alarm system, Central door lock, Central ...","Alloy wheels, Automatically dimming interior m...",1573.00,No,Part/Full Leather,5.00,unefficient,20.00,147.00,10.40,Standard

In [212]:
df['comfort_&_convenience_Package'].value_counts(dropna=False)

comfort_&_convenience_Package
Standard        19722
Premium          8808
Premium Plus       94
Name: count, dtype: int64

In [213]:
df.shape

(28624, 31)

In [214]:
# There is no need for old 'comfort_&_convenience' since a new feature of 'comfort_&_convenience_Package' is created

df.drop("comfort_&_convenience", axis=1, inplace=True)

In [215]:
df.shape

(28624, 30)

## entertainment_&_media

In [216]:
# Let's explore basic information about "entertainment_&_media"

first_looking("entertainment_&_media")

COLUMN NAME    :  entertainment_&_media
--------------------------------
per_of_nulls   :  % 17.41
num_of_nulls   :  4984
num_of_uniques :  1944
--------------------------------
entertainment_&_media
NaN                                                                                                                                                                        4984
Bluetooth, USB                                                                                                                                                              753
Bluetooth                                                                                                                                                                   665
On-board computer                                                                                                                                                           662
CD player, On-board computer, Radio                                                                                                                                         644
                                                                                                                                                                           ...
Android Auto, Apple CarPlay, Bluetooth, Digital cockpit, Digital radio, Induction charging for smartphones, On-board computer, Radio, Sound system, WLAN / WiFi hotspot       1
Bluetooth, CD player, Digital cockpit, Digital radio, Hands-free equipment, Integrated music streaming, On-board computer, Sound system, USB, WLAN / WiFi hotspot             1
Digital cockpit, Digital radio, On-board computer, Radio                                                                                                                      1
Android Auto, Apple CarPlay, Digital radio, On-board computer, Radio, Sound system, USB, WLAN / WiFi hotspot                                                                  1
Hands-free equipment, Integrated music streaming, On-board computer, Radio, USB                                                                                               1
Name: count, Length: 1945, dtype: int64

In [217]:
# This DEF will fill the missing values in the "entertainment_&_media" with the mode value based on "make_model" and "body_type"

fill(df, "make_model", "body_type", "entertainment_&_media", "mode")

COLUMN NAME    :  entertainment_&_media
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  1944
--------------------------------
entertainment_&_media
Android Auto                                                                                                                                                                                                                                                    3
Android Auto, Apple CarPlay                                                                                                                                                                                                                                     9
Android Auto, Apple CarPlay, Bluetooth                                                                                                                                                                                                                          1
Android Auto, Apple CarPlay, Bluetooth, CD player, Digital cockpit, Digital radio, Hands-free equipment, Induction charging for smartphones, Integrated music streaming, MP3, On-board computer, Radio, Sound system, Television, USB                           1
Android Auto, Apple CarPlay, Bluetooth, CD player, Digital cockpit, Digital radio, Hands-free equipment, Induction charging for smartphones, Integrated music streaming, MP3, On-board computer, Radio, Sound system, Television, USB, WLAN / WiFi hotspot      4
                                                                                                                                                                                                                                                             ...
Sound system                                                                                                                                                                                                                                                   61
Sound system, USB                                                                                                                                                                                                                                               3
Sound system, WLAN / WiFi hotspot                                                                                                                                                                                                                               3
USB                                                                                                                                                                                                                                                           206
WLAN / WiFi hotspot                                                                                                                                                                                                                                             4
Name: count, Length: 1944, dtype: int64

### 📝 Some Remarks on Comfort & Conveniance Features of Cars:

**Let us define car ``"Entertainment & Media Packages"``:**

Here are some general definitions of standard and plus Entertainment & Media Packages for vehicles:

  - **``Standard Entertainment & Media Package``**: The standard Entertainment & Media Package is a basic configuration for a vehicle's infotainment system. This package typically includes features such as an AM/FM radio, Bluetooth connectivity, and a basic audio system. It may also include a small touchscreen display for accessing media and vehicle settings.

  - **``Premium/Plus Entertainment & Media Package``**: The Premium/Plus Entertainment & Media Package is an upgrade to the standard package, and typically includes additional features and capabilities. This may include a larger touchscreen display with higher resolution, support for satellite radio, a premium audio system, and additional connectivity options such as Apple CarPlay and Android Auto. It may also include additional safety features such as a backup camera or parking sensors.

It's worth noting that the specific features and equipment included in each package can vary depending on the vehicle make and model. Additionally, some features may be available as standalone options or bundled with other packages. It's always a good idea to review the specific details of each package to determine which one best fits your needs and budget.

In [218]:
# display all unique values in "entertainment_&_media"
# pd.set_option('display.max_rows', None)

df['entertainment_&_media'].unique()

array(['Bluetooth, CD player, Radio',
       'Android Auto, Apple CarPlay, Bluetooth, Digital cockpit, Digital radio, Hands-free equipment, Induction charging for smartphones, Integrated music streaming, On-board computer, Radio, Sound system, USB, WLAN / WiFi hotspot',
       'Bluetooth, CD player, MP3, USB', ...,
       'Hands-free equipment, MP3, Radio, USB',
       'Android Auto, Bluetooth, CD player, Digital cockpit, Digital radio, Hands-free equipment, MP3, On-board computer, Radio, Sound system, Television, USB',
       'Hands-free equipment, Integrated music streaming, On-board computer, Radio, USB'],
      dtype=object)

In [219]:
# reset the 'max_rows' option to its default value
# pd.reset_option('display.max_rows')

In [220]:
# df[df['entertainment_&_media'].str.contains("Apple")]

### Option 1:

In [221]:
media_plus = ["Digital", "Television"]

# media_plus = ["Digital radio", "Hands-free", "Television"]

entertainment_media_package = df['entertainment_&_media'].apply(lambda sentence: "Premium Media" if any(word in sentence for word in media_plus) else "Standard Media")
entertainment_media_package.value_counts()

entertainment_&_media
Standard Media    17759
Premium Media     10865
Name: count, dtype: int64

### Option 2:

In [222]:
# media_plus = ["Digital", "Television"]

media_plus = ["Digital radio", "Hands-free", "Television", "Induction charging for smartphones", "Apple"]

entertainment_media_package = df['entertainment_&_media'].apply(lambda sentence: "Premium Media" if any(word in sentence for word in media_plus) else "Standard Media")
entertainment_media_package.value_counts()

entertainment_&_media
Premium Media     16787
Standard Media    11837
Name: count, dtype: int64

**Let us assign each car to related ``"Entertainment & Media Packages"`` defined above:**

In [223]:
media_plus = ["Digital", "Television"]

df['entertainment_&_media_Package'] = df['entertainment_&_media'].apply(lambda sentence: "Premium Media" if any(word in sentence for word in media_plus) else "Standard Media")
df

,make_model,make,model,location,price,body_type,type,doors,warranty,mileage,gearbox,fuel_type,seller,seats,engine_size,gears,co_emissions,drivetrain,entertainment_&_media,safety_&_security,extras,empty_weight,full_service_history,upholstery,previous_owner,energy_efficiency_class,age,power_kW,cons_avg,comfort_&_convenience_Package,entertainment_&_media_Package
0,Mercedes-Benz A 160,Mercedes-Benz,A 160,"P.I. EL PALMAR C/FORJA 6, 11500 PUERTO DE SAN...",16950.00,Compact,Used,5.00,Yes,120200.00,Manual,Diesel,Dealer,5.00,1595.00,6.00,98.00,Front,"Bluetooth, CD player, Radio",NaN,NaN,1270.00,No,Cloth,2.00,efficient,6.00,75.00,3.80,Standard,Standard Media
1,Mercedes-Benz Eqe 350,Mercedes-Benz,Eqe 350,"APARTADO DE CORREOS 1032, 26140 LOGROÑO, ES",80900.00,Compact,Pre-registered,4.00,Yes,5000.00,Automatic,Electric,Dealer,5.00,1.00,9.00,0.00,4WD,"Android Auto, Apple CarPlay, Bluetooth, Digita...",NaN,NaN,2355.00,No,Part/Full Leather,1.00,efficient,0.00,215.00,2.36,Premium,Premium Media
2,Mercedes-Benz A 45 Amg,Mercedes-Benz,A 45 Amg,"PORT. TARRACO, MOLL DE LLEVANT, Nº 5, LOC. 6-8...",69900.00,Compact,Used,5.00,Yes,18900.00,Automatic,Benzine,Dealer,5.00,1991.00,8.00,162.00,4WD,"Bluetooth, CD player, MP3, USB",NaN,NaN,1555.00,No,Part/Full Leather,2.00,unefficient,2.00,310.00,8.40,Standard,Standard Media
3,Mercedes-Benz A 35 Amg,Mercedes-Benz,A 35 Amg,"Carrer de Provença, 31 Local, 8029 BARCELONA, ES",46990.00,Compact,Used,5.00,Yes,18995.00,Automatic,Benzine,Dealer,5.00,1991.00,7.00,169.00,4WD,USB,"ABS, Central door lock, Driver-side airbag, El...",Sport seats,1455.00,No,Part/Full Leather,2.00,unefficient,2.00,225.00,7.30,Standard,Standard Media
4,Mercedes-Benz A 45 Amg,Mercedes-Benz,A 45 Amg,"CARRIL ARAGONES 4, 30007 CASILLAS, ES",16800.00,Compact,Used,5.00,Yes,197000.00,Automatic,Diesel,Dealer,5.00,2143.00,7.00,162.00,4WD,"Bluetooth, CD player, MP3, USB","ABS, Central door lock, Driver-side airbag, El...",NaN,1545.00,No,Part/Full Leather,2.00,unefficient,7.00,100.00,4.90,Standard,Standard Media
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28625,Volvo S90,Volvo,S90,"HERMANOS LUMIERE Nº16, 29004 MALAGA, ES",37600.00,Sedan,Used,4.00,Yes,40345.00,Automatic,Diesel,Dealer,4.00,1969.00,8.00,127.00,4WD,"Bluetooth, USB","ABS, Central door lock, Driver-side airbag, El...",Alloy wheels,2077.00,No,Part/Full Leather,2.00,efficient,3.00,288.00,2.00,Standard,Standard Media
28626,Volvo S40,Volvo,S40,"Stobbeweg 6, 2461 EX TER AAR, NL",5499.00,Sedan,Used,4.00,No,145000.00,Automatic,Benzine,Dealer,5.00,2435.00,5.00,217.00,Front,"On-board computer, Radio","ABS, Central door lock, Central door lock with...","Alloy wheels (16""), Trailer hitch",1357.00,Yes,Cloth,3.00,efficient,18.00,125.00,9.10,Standard,Standard Media
28627,Volvo C30,Volvo,C30,"Sur rendez-vous, 5060 Sambreville, BE",7300.00,Sedan,Used,3.00,Yes,96000.00,Manual,Diesel,Dealer,4.00,1560.00,6.00,99.00,Front,"Bluetooth, CD player, Hands-free equipment, MP...","ABS, Alarm system, Central door lock with remo...","Alloy wheels, Automatically dimming interior m...",1356.00,Yes,Cloth,1.00,unefficient,11.00,84.00,3.80,Standard,Standard Media
28628,Volvo S90,Volvo,S90,"Bergambachterstraat 5, 2871 JB SCHOONHOVEN, NL",29900.00,Sedan,Used,4.00,Yes,94343.00,Automatic,Benzine,Dealer,5.00,1969.00,8.00,149.00,4WD,"Android Auto, Apple CarPlay, Bluetooth, Hands-...","Adaptive Cruise Control, Adaptive headlights, ...","Alloy wheels (18""), Automatically dimming inte...",1617.00,Yes,Part/Full Leather,1.00,efficient,5.00,187.00,6.50,Standard,Standard Media
28629,Volvo S80,Volvo,S80,"Lage Ham 106, 5102 AE DONGEN, NL",4440.00,Sedan,Used,4.00,No,230047.00,Automatic,Benzine,Dealer,5.00,2922.00,6.00,251.00,Front,On-board computer,"ABS, Alarm system, Central door lock, Central ...","Alloy wheels, Automatically dimming interior m...",1573.00,No,Part/Full Leather,5.00,unefficient,20.00,147.00,10.40,Standard,Standard Media

In [224]:
df['entertainment_&_media_Package'].value_counts(dropna=False)

entertainment_&_media_Package
Standard Media    17759
Premium Media     10865
Name: count, dtype: int64

In [225]:
df.shape

(28624, 31)

In [226]:
# There is no need for old 'entertainment_&_media' since a new feature of 'entertainment_&_media_Package' is created

df.drop("entertainment_&_media", axis=1, inplace=True)

In [227]:
df.shape

(28624, 30)

## extras

In [228]:
# Let's explore basic information about "extras"

first_looking("extras")

COLUMN NAME    :  extras
--------------------------------
per_of_nulls   :  % 17.98
num_of_nulls   :  5148
num_of_uniques :  9359
--------------------------------
extras
NaN                                                                                                                                                                                                                                                                 5148
Alloy wheels                                                                                                                                                                                                                                                        3407
Alloy wheels, Roof rack                                                                                                                                                                                                                                              380
Alloy wheels, Sport seats                                                                                                                                                                                                                                            372
Alloy wheels, Touch screen                                                                                                                                                                                                                                           231
                                                                                                                                                                                                                                                                    ...
All season tyres, Alloy wheels, Automatically dimming interior mirror, Catalytic Converter, Headlight washer system, Ski bag, Sport seats, Trailer hitch, Winter tyres                                                                                                 1
Alloy wheels, Automatically dimming interior mirror, Headlight washer system, Sport package, Sport seats, Summer tyres                                                                                                                                                 1
Alloy wheels (19"), Ambient lighting, Automatically dimming interior mirror, Catalytic Converter, E10-enabled, Emergency tyre repair kit, Headlight washer system, Spoiler, Sport package, Sport seats, Sport suspension, Summer tyres, Tuned car, Voice Control       1
Alloy wheels (17"), Automatically dimming interior mirror, Cargo barrier, Spoiler, Sport seats, Summer tyres, Voice Control                                                                                                                                            1
Alloy wheels, Automatically dimming interior mirror, Ski bag, Trailer hitch                                                                                                                                                                                            1
Name: count, Length: 9360, dtype: int64

In [229]:
# This DEF will fill the missing values in the "extras" with the mode value based on "make_model" and "body_type"

fill(df, "make_model", "body_type", "extras", "mode")

COLUMN NAME    :  extras
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  9359
--------------------------------
extras
All season tyres                                                           40
All season tyres, Alloy wheels                                             35
All season tyres, Alloy wheels (13"), Catalytic Converter, Touch screen     1
All season tyres, Alloy wheels (14")                                        1
All season tyres, Alloy wheels (14"), Emergency tyre, Smoker's package      2
                                                                           ..
Voice Control, Winter package                                               1
Voice Control, Winter tyres                                                 1
Winter package                                                              1
Winter package, Winter tyres                                                1
Winter tyres                                                               16
Name: count, Length: 9359, dtype: int64

## safety_&_security

In [230]:
# Let's explore basic information about "safety_&_security"

first_looking("safety_&_security")

COLUMN NAME    :  safety_&_security
--------------------------------
per_of_nulls   :  % 11.22
num_of_nulls   :  3213
num_of_uniques :  12545
--------------------------------
safety_&_security
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              3213
Isofix                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            380
ABS, Central door lock, Driver-side airbag, Electronic stability control, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag                                                                                                                                                                                                                                                                                                                                                                 328
ABS, Central door lock, Driver-side airbag, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Traction control                                                                                                                                                                                                                                                                                                                                                                             125
ABS, Central door lock, Driver-side airbag, Electronic stability control, Fog lights, Isofix, Power steering, Side airbag                                                                                                                                                                                                                                                                                                                                                                                         121
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ...
ABS, Alarm system, Central door lock, Central door lock with remote control, Daytime running lights, Driver-side airbag, Electronic stability control, Head airbag, Immobilizer, Isofix, LED Daytime Running Lights, Passenger-side airbag, Side airbag, Tire pressure monitoring system, Traction control                                                                                                                                                                                                          1
ABS, Central door lock, Emergency system, Fog lights, Isofix, Power steering, Speed limit control system, Tire pressure monitoring system, Traction control                                                                                                                                                                                                                                                                                                                                                         1
ABS, Adaptive Cruise Control, Alarm system, Bi-Xenon headlights, Blind spot monitor, Central door lock, Daytime running lights, Distance warning system, Driver drowsiness detection, Driver-side airbag, Electronic stability control, Emergency brake assistant, Emergency system, Isofix, LED Daytime Running Lights, LED Headlights, Lane departure warning system, Night view assist, Passenger-side airbag, Power steering, Tire pressure monitoring system, Traffic sign recognition, Xenon headlights       1
ABS, Central door lock, Driver-side airbag, Electronic stability control, Fog lights, Isofix, Passenger-side airbag, Power steering, Rear airbag, Side airbag                                                                                                                                                                                                                                                                                                                                                       1
ABS, Alarm system, Central door lock, Central door lock with remote control, Driver-side airbag, Electronic stability control, Fog lights, Head airbag, Immobilizer, Power steering, Side airbag, Traction control                                                                                                                                                                                                                                                                                                  1
Name: count, Length: 12546, dtype: int64

In [231]:
# This DEF will fill the missing values in the "safety_&_security" with the mode value based on "make_model" and "body_type"

fill(df, "make_model", "body_type", "safety_&_security", "mode")

COLUMN NAME    :  safety_&_security
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  12545
--------------------------------
safety_&_security
ABS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  17
ABS, Adaptive Cruise Control, Adaptive headlights, Alarm system, Bi-Xenon headlights, Blind spot monitor, Central door lock with remote control, Distance warning system, Driver-side airbag, Electronic stability control, Emergency brake assistant, Fog lights, Head airbag, High beam assist, Immobilizer, LED Daytime Running Lights, Lane departure warning system, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control                                                                                                                                                                                                                                                                                                       1
ABS, Adaptive Cruise Control, Adaptive headlights, Alarm system, Bi-Xenon headlights, Blind spot monitor, Central door lock with remote control, Distance warning system, Driver-side airbag, Electronic stability control, Emergency system, Head airbag, High beam assist, Immobilizer, Isofix, LED Daytime Running Lights, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control                                                                                                                                                                                                                                                                                                                                                   1
ABS, Adaptive Cruise Control, Adaptive headlights, Alarm system, Bi-Xenon headlights, Blind spot monitor, Central door lock, Central door lock with remote control, Daytime running lights, Distance warning system, Driver drowsiness detection, Driver-side airbag, Electronic stability control, Emergency brake assistant, Emergency system, Fog lights, Full-LED headlights, Glare-free high beam headlights, Head airbag, High beam assist, Immobilizer, Isofix, LED Daytime Running Lights, LED Headlights, Lane departure warning system, Laser headlights, Night view assist, Passenger-side airbag, Power steering, Rear airbag, Side airbag, Speed limit control system, Tire pressure monitoring system, Traction control, Traffic sign recognition, Xenon headlights     1
ABS, Adaptive Cruise Control, Adaptive headlights, Alarm system, Bi-Xenon headlights, Blind spot monitor, Central door lock, Central door lock with remote control, Daytime running lights, Distance warning system, Driver drowsiness detection, Driver-side airbag, Electronic stability control, Emergency brake assistant, Emergency system, Fog lights, Full-LED headlights, Glare-free high beam headlights, Head airbag, High beam assist, Immobilizer, Isofix, LED Daytime Running Lights, LED Headlights, Lane departure warning system, Laser headlights, Passenger-side airbag, Power steering, Rear airbag, Side airbag, Speed limit control system, Tire pressure monitoring system, Traction control, Traffic sign recognition, Xenon headlights                        2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ..
Side airbag                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           3
Speed limit control system                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            8
Tire pressure monitoring system                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       2
Traction control                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     18
Xenon headlights                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      2
Name: count, Length: 12545, dtype: int64

### 📝 Some Remarks on Safety & Security Features of Cars:

**Let us define car ``"Safety & Security Packages"``:**

Here are some general definitions of standard, premium, and premium plus Safety & Security Packages for vehicles:

  - **``Standard Safety & Security Package``**: The standard Safety & Security Package is the base configuration for a vehicle's safety features and equipment. This package typically includes basic safety features such as anti-lock brakes, traction control, and stability control. It may also include some passive safety features such as airbags and a backup camera.

  - **``Premium Safety & Security Package``**: The Premium Safety & Security Package is an upgrade to the standard package, and typically includes additional safety features and capabilities. This may include advanced driver assistance systems (ADAS) such as blind spot monitoring, lane departure warning, and forward collision warning with automatic emergency braking. It may also include additional passive safety features such as more airbags, automatic high beams, and adaptive headlights.

  - **``Premium Plus Safety & Security Package``**: The Premium Plus Safety & Security Package is another upgrade to the Premium package, and typically includes the most advanced and comprehensive safety features and capabilities. This may include features such as a 360-degree camera system, adaptive cruise control, and lane keeping assist. It may also include additional passive safety features such as a reinforced body structure, improved crash protection, and advanced tire pressure monitoring.
  
It's important to note that the specific features and equipment included in each package can vary depending on the vehicle make and model. Additionally, some features may be available as standalone options or bundled with other packages. It's always a good idea to review the specific details of each package to determine which one best fits your needs and budget.

In [232]:
# display all unique values in "safety_&_security"
# pd.set_option('display.max_rows', None)

df['safety_&_security'].unique()

array(['ABS, Adaptive Cruise Control, Alarm system, Driver-side airbag, Electronic stability control, Emergency brake assistant, Emergency system, Full-LED headlights, Head airbag, Immobilizer, LED Daytime Running Lights, LED Headlights, Passenger-side airbag, Power steering, Rear airbag, Side airbag, Speed limit control system, Traction control',
       'ABS, Adaptive Cruise Control, Adaptive headlights, Alarm system, Blind spot monitor, Central door lock with remote control, Daytime running lights, Driver drowsiness detection, Driver-side airbag, Electronic stability control, Emergency brake assistant, Emergency system, Fog lights, Immobilizer, Isofix, LED Daytime Running Lights, LED Headlights, Lane departure warning system, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control, Traffic sign recognition',
       'ABS, Central door lock, Driver-side airbag, Electronic stability control, Isofix, Xenon headlights',
       ...,
       'ABS, Alarm system, Central door lock with remote control, Daytime running lights, Driver-side airbag, Electronic stability control, Fog lights, Head airbag, Immobilizer, Isofix, Passenger-side airbag, Power steering, Rear airbag, Side airbag, Traction control',
       'Adaptive Cruise Control, Adaptive headlights, Daytime running lights, Emergency system, LED Daytime Running Lights, LED Headlights, Lane departure warning system, Speed limit control system, Tire pressure monitoring system',
       'ABS, Alarm system, Central door lock, Central door lock with remote control, Driver-side airbag, Electronic stability control, Fog lights, Head airbag, Immobilizer, Power steering, Side airbag, Traction control'],
      dtype=object)

In [233]:
# reset the 'max_rows' option to its default value
# pd.reset_option('display.max_rows')

In [234]:
# df[df['safety_&_security'].str.contains("Adaptive")]

In [235]:
premium = ["Tire pressure", "Daytime running lights", "LED Headlight", "Lane departure warning system"]
premium_plus = ["Traction control", "Emergency brake assistant", "Electronic stability control", "Adaptive"]

safety_security_package = df['safety_&_security'].apply(lambda sentence: "Safety Premium Package" if all(word in sentence for word in premium) else ("Safety Premium Plus Package" if all(word in sentence for word in premium_plus) else "Safety Standard Package"))
safety_security_package.value_counts()

safety_&_security
Safety Standard Package        21746
Safety Premium Package          5285
Safety Premium Plus Package     1593
Name: count, dtype: int64

In [236]:
premium = ["Tire pressure", "Daytime running lights", "LED Headlight"]
premium_plus = ["Traction control", "Emergency brake assistant", "Electronic stability control"]

df['safety_&_security_Package'] = df['safety_&_security'].apply(lambda sentence: "Safety Premium Package" if all(word in sentence for word in premium) else ("Safety Premium Plus Package" if all(word in sentence for word in premium_plus) else "Safety Standard Package"))
df

,make_model,make,model,location,price,body_type,type,doors,warranty,mileage,gearbox,fuel_type,seller,seats,engine_size,gears,co_emissions,drivetrain,safety_&_security,extras,empty_weight,full_service_history,upholstery,previous_owner,energy_efficiency_class,age,power_kW,cons_avg,comfort_&_convenience_Package,entertainment_&_media_Package,safety_&_security_Package
0,Mercedes-Benz A 160,Mercedes-Benz,A 160,"P.I. EL PALMAR C/FORJA 6, 11500 PUERTO DE SAN...",16950.00,Compact,Used,5.00,Yes,120200.00,Manual,Diesel,Dealer,5.00,1595.00,6.00,98.00,Front,"ABS, Adaptive Cruise Control, Alarm system, Dr...",Alloy wheels,1270.00,No,Cloth,2.00,efficient,6.00,75.00,3.80,Standard,Standard Media,Safety Premium Plus Package
1,Mercedes-Benz Eqe 350,Mercedes-Benz,Eqe 350,"APARTADO DE CORREOS 1032, 26140 LOGROÑO, ES",80900.00,Compact,Pre-registered,4.00,Yes,5000.00,Automatic,Electric,Dealer,5.00,1.00,9.00,0.00,4WD,"ABS, Adaptive Cruise Control, Adaptive headlig...","Alloy wheels (21""), Shift paddles, Sport packa...",2355.00,No,Part/Full Leather,1.00,efficient,0.00,215.00,2.36,Premium,Premium Media,Safety Premium Package
2,Mercedes-Benz A 45 Amg,Mercedes-Benz,A 45 Amg,"PORT. TARRACO, MOLL DE LLEVANT, Nº 5, LOC. 6-8...",69900.00,Compact,Used,5.00,Yes,18900.00,Automatic,Benzine,Dealer,5.00,1991.00,8.00,162.00,4WD,"ABS, Central door lock, Driver-side airbag, El...",Alloy wheels,1555.00,No,Part/Full Leather,2.00,unefficient,2.00,310.00,8.40,Standard,Standard Media,Safety Standard Package
3,Mercedes-Benz A 35 Amg,Mercedes-Benz,A 35 Amg,"Carrer de Provença, 31 Local, 8029 BARCELONA, ES",46990.00,Compact,Used,5.00,Yes,18995.00,Automatic,Benzine,Dealer,5.00,1991.00,7.00,169.00,4WD,"ABS, Central door lock, Driver-side airbag, El...",Sport seats,1455.00,No,Part/Full Leather,2.00,unefficient,2.00,225.00,7.30,Standard,Standard Media,Safety Standard Package
4,Mercedes-Benz A 45 Amg,Mercedes-Benz,A 45 Amg,"CARRIL ARAGONES 4, 30007 CASILLAS, ES",16800.00,Compact,Used,5.00,Yes,197000.00,Automatic,Diesel,Dealer,5.00,2143.00,7.00,162.00,4WD,"ABS, Central door lock, Driver-side airbag, El...",Alloy wheels,1545.00,No,Part/Full Leather,2.00,unefficient,7.00,100.00,4.90,Standard,Standard Media,Safety Standard Package
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28625,Volvo S90,Volvo,S90,"HERMANOS LUMIERE Nº16, 29004 MALAGA, ES",37600.00,Sedan,Used,4.00,Yes,40345.00,Automatic,Diesel,Dealer,4.00,1969.00,8.00,127.00,4WD,"ABS, Central door lock, Driver-side airbag, El...",Alloy wheels,2077.00,No,Part/Full Leather,2.00,efficient,3.00,288.00,2.00,Standard,Standard Media,Safety Standard Package
28626,Volvo S40,Volvo,S40,"Stobbeweg 6, 2461 EX TER AAR, NL",5499.00,Sedan,Used,4.00,No,145000.00,Automatic,Benzine,Dealer,5.00,2435.00,5.00,217.00,Front,"ABS, Central door lock, Central door lock with...","Alloy wheels (16""), Trailer hitch",1357.00,Yes,Cloth,3.00,efficient,18.00,125.00,9.10,Standard,Standard Media,Safety Standard Package
28627,Volvo C30,Volvo,C30,"Sur rendez-vous, 5060 Sambreville, BE",7300.00,Sedan,Used,3.00,Yes,96000.00,Manual,Diesel,Dealer,4.00,1560.00,6.00,99.00,Front,"ABS, Alarm system, Central door lock with remo...","Alloy wheels, Automatically dimming interior m...",1356.00,Yes,Cloth,1.00,unefficient,11.00,84.00,3.80,Standard,Standard Media,Safety Standard Package
28628,Volvo S90,Volvo,S90,"Bergambachterstraat 5, 2871 JB SCHOONHOVEN, NL",29900.00,Sedan,Used,4.00,Yes,94343.00,Automatic,Benzine,Dealer,5.00,1969.00,8.00,149.00,4WD,"Adaptive Cruise Control, Adaptive headlights, ...","Alloy wheels (18""), Automatically dimming inte...",1617.00,Yes,Part/Full Leather,1.00,efficient,5.00,187.00,6.50,Standard,Standard Media,Safety Premium Package
28629,Volvo S80,Volvo,S80,"Lage Ham 106, 5102 AE DONGEN, NL",4440.00,Sedan,Used,4.00,No,230047.00,Automatic,Benzine,Dealer,5.00,2922.00,6.00,251.00,Front,"ABS, Alarm system, Central door lock, Central ...","Alloy wheels, Automatically dimming interior m...",1573.00,No,Part/Full Leather,5.00,unefficient,20.00,147.00,10.40,Standard,Standard Media,Safety Standard Package

In [237]:
df['safety_&_security_Package'].value_counts(dropna=False)

safety_&_security_Package
Safety Standard Package        18170
Safety Premium Package          6692
Safety Premium Plus Package     3762
Name: count, dtype: int64

**Let us assign each car to related ``"Safety & Security Packages"`` defined above:**

In [238]:
df.shape

(28624, 31)

In [239]:
df.drop("safety_&_security", axis=1, inplace=True)

In [240]:
df.shape

(28624, 30)

## End of this phase

In [241]:
df.head()

,make_model,make,model,location,price,body_type,type,doors,warranty,mileage,gearbox,fuel_type,seller,seats,engine_size,gears,co_emissions,drivetrain,extras,empty_weight,full_service_history,upholstery,previous_owner,energy_efficiency_class,age,power_kW,cons_avg,comfort_&_convenience_Package,entertainment_&_media_Package,safety_&_security_Package
0,Mercedes-Benz A 160,Mercedes-Benz,A 160,"P.I. EL PALMAR C/FORJA 6, 11500 PUERTO DE SAN...",16950.00,Compact,Used,5.00,Yes,120200.00,Manual,Diesel,Dealer,5.00,1595.00,6.00,98.00,Front,Alloy wheels,1270.00,No,Cloth,2.00,efficient,6.00,75.00,3.80,Standard,Standard Media,Safety Premium Plus Package
1,Mercedes-Benz Eqe 350,Mercedes-Benz,Eqe 350,"APARTADO DE CORREOS 1032, 26140 LOGROÑO, ES",80900.00,Compact,Pre-registered,4.00,Yes,5000.00,Automatic,Electric,Dealer,5.00,1.00,9.00,0.00,4WD,"Alloy wheels (21""), Shift paddles, Sport packa...",2355.00,No,Part/Full Leather,1.00,efficient,0.00,215.00,2.36,Premium,Premium Media,Safety Premium Package
2,Mercedes-Benz A 45 Amg,Mercedes-Benz,A 45 Amg,"PORT. TARRACO, MOLL DE LLEVANT, Nº 5, LOC. 6-8...",69900.00,Compact,Used,5.00,Yes,18900.00,Automatic,Benzine,Dealer,5.00,1991.00,8.00,162.00,4WD,Alloy wheels,1555.00,No,Part/Full Leather,2.00,unefficient,2.00,310.00,8.40,Standard,Standard Media,Safety Standard Package
3,Mercedes-Benz A 35 Amg,Mercedes-Benz,A 35 Amg,"Carrer de Provença, 31 Local, 8029 BARCELONA, ES",46990.00,Compact,Used,5.00,Yes,18995.00,Automatic,Benzine,Dealer,5.00,1991.00,7.00,169.00,4WD,Sport seats,1455.00,No,Part/Full Leather,2.00,unefficient,2.00,225.00,7.30,Standard,Standard Media,Safety Standard Package
4,Mercedes-Benz A 45 Amg,Mercedes-Benz,A 45 Amg,"CARRIL ARAGONES 4, 30007 CASILLAS, ES",16800.00,Compact,Used,5.00,Yes,197000.00,Automatic,Diesel,Dealer,5.00,2143.00,7.00,162.00,4WD,Alloy wheels,1545.00,No,Part/Full Leather,2.00,unefficient,7.00,100.00,4.90,Standard,Standard Media,Safety Standard Package

In [242]:
df.shape

(28624, 30)

In [243]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28624 entries, 0 to 28629
Data columns (total 30 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   make_model                     28624 non-null  object
 1   make                           28624 non-null  object
 2   model                          28624 non-null  object
 3   location                       28624 non-null  object
 4   price                          28624 non-null  float64
 5   body_type                      28624 non-null  object
 6   type                           28624 non-null  object
 7   doors                          28624 non-null  float64
 8   warranty                       28624 non-null  object
 9   mileage                        28624 non-null  float64
 10  gearbox                        28624 non-null  object
 11  fuel_type                      28624 non-null  object
 12  seller                         28624 non-null  object
 13  seats                          28624 non-null  float64
 14  engine_size                    28624 non-null  float64
 15  gears                          28624 non-null  float64
 16  co_emissions                   28624 non-null  float64
 17  drivetrain                     28624 non-null  object
 18  extras                         28624 non-null  object
 19  empty_weight                   28624 non-null  float64
 20  full_service_history           28624 non-null  object
 21  upholstery                     28624 non-null  object
 22  previous_owner                 28624 non-null  float64
 23  energy_efficiency_class        28624 non-null  object
 24  age                            28624 non-null  float64
 25  power_kW                       28624 non-null  float64
 26  cons_avg                       28624 non-null  float64
 27  comfort_&_convenience_Package  28624 non-null  object
 28  entertainment_&_media_Package  28624 non-null  object
 29  safety_&_security_Package      28624 non-null  object
dtypes: float64(12), object(18)
memory usage: 7.8+ MB

In [244]:
class color:
    PURPLE = '\033[95m'
    CYAN = '\033[96m'
    DARKCYAN = '\033[36m'
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
    END = '\033[0m'

def check_obj_columns(df):
    '''
    Returns NO PROBLEM or column/s which has/have mixed object types.
    '''    
    
    tdf = df.select_dtypes(include=['object']).applymap(type)
    for col in tdf:
        if len(set(tdf[col].values)) > 1:
            print("Column" + " " + color.BOLD + color.RED + col + color.END + " " + "has mixed object types." )
    else:
        if len(set(tdf[col].values)) == 1:
            print(color.BOLD + color.GREEN + " " + "NO PROBLEM" + " " + color.END + " " + "with the data types of Columns in the DataFrame.")

check_obj_columns(df)

 NO PROBLEM  with the data types of Columns in the DataFrame.

In [245]:
df.isnull().sum()*100 / df.shape[0]

make_model                      0.00
make                            0.00
model                           0.00
location                        0.00
price                           0.00
body_type                       0.00
type                            0.00
doors                           0.00
warranty                        0.00
mileage                         0.00
gearbox                         0.00
fuel_type                       0.00
seller                          0.00
seats                           0.00
engine_size                     0.00
gears                           0.00
co_emissions                    0.00
drivetrain                      0.00
extras                          0.00
empty_weight                    0.00
full_service_history            0.00
upholstery                      0.00
previous_owner                  0.00
energy_efficiency_class         0.00
age                             0.00
power_kW                        0.00
cons_avg                        0.00
comfort_&_convenience_Package   0.00
entertainment_&_media_Package   0.00
safety_&_security_Package       0.00
dtype: float64

In [246]:
df.duplicated(keep=False).sum()

3803

In [247]:
df[df.duplicated(keep=False)]

,make_model,make,model,location,price,body_type,type,doors,warranty,mileage,gearbox,fuel_type,seller,seats,engine_size,gears,co_emissions,drivetrain,extras,empty_weight,full_service_history,upholstery,previous_owner,energy_efficiency_class,age,power_kW,cons_avg,comfort_&_convenience_Package,entertainment_&_media_Package,safety_&_security_Package
142,Mercedes-Benz A 45 Amg,Mercedes-Benz,A 45 Amg,"RONDA PONENT 62, 8201 SABADELL, ES",72890.00,Compact,Used,5.00,Yes,12900.00,Automatic,Benzine,Dealer,5.00,1991.00,8.00,162.00,4WD,Alloy wheels,1555.00,No,Part/Full Leather,1.00,unefficient,1.00,310.00,8.40,Standard,Standard Media,Safety Standard Package
237,Mercedes-Benz Cl,Mercedes-Benz,Cl,"--, 77240 Vert St Denis, FR",39990.00,Compact,Used,5.00,No,8500.00,Automatic,Benzine,Dealer,5.00,1332.00,8.00,118.00,4WD,"Alloy wheels, Shift paddles, Sport package, Sp...",1705.00,No,Part/Full Leather,1.00,unefficient,0.00,87.00,8.40,Premium,Premium Media,Safety Premium Plus Package
253,Mercedes-Benz Cl,Mercedes-Benz,Cl,"--, 77240 Vert St Denis, FR",39990.00,Compact,Used,5.00,No,8500.00,Automatic,Benzine,Dealer,5.00,1332.00,8.00,118.00,4WD,"Alloy wheels, Shift paddles, Sport package, Sp...",1705.00,No,Part/Full Leather,1.00,unefficient,0.00,87.00,8.40,Premium,Premium Media,Safety Premium Plus Package
263,Mercedes-Benz Cl,Mercedes-Benz,Cl,"--, 77240 Vert St Denis, FR",39990.00,Compact,Used,5.00,No,8500.00,Automatic,Benzine,Dealer,5.00,1332.00,8.00,118.00,4WD,"Alloy wheels, Shift paddles, Sport package, Sp...",1705.00,No,Part/Full Leather,1.00,unefficient,0.00,87.00,8.40,Premium,Premium Media,Safety Premium Plus Package
276,Mercedes-Benz A 45 Amg,Mercedes-Benz,A 45 Amg,"RONDA PONENT 62, 8201 SABADELL, ES",72890.00,Compact,Used,5.00,Yes,12900.00,Automatic,Benzine,Dealer,5.00,1991.00,8.00,162.00,4WD,Alloy wheels,1555.00,No,Part/Full Leather,1.00,unefficient,1.00,310.00,8.40,Standard,Standard Media,Safety Standard Package
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28386,Volvo S90,Volvo,S90,"Donnerwenge 2, 57439 Attendorn, DE",55470.00,Sedan,Employee's car,4.00,Yes,10000.00,Automatic,Diesel,Dealer,5.00,1969.00,8.00,127.00,4WD,"Alloy wheels, Touch screen, Trailer hitch, Voi...",1892.00,Yes,Part/Full Leather,1.00,efficient,1.00,173.00,4.80,Premium,Premium Media,Safety Premium Package
28556,Volvo S90,Volvo,S90,"Von-Drais-Str. 2, 77855 Achern, DE",31488.00,Sedan,Used,4.00,No,84000.00,Automatic,Diesel,Dealer,5.00,1969.00,0.00,127.00,4WD,"Alloy wheels, Catalytic Converter, Sport suspe...",1892.00,No,Part/Full Leather,1.00,efficient,5.00,173.00,4.80,Standard,Standard Media,Safety Premium Package
28557,Volvo S90,Volvo,S90,"Von-Drais-Str. 2, 77855 Achern, DE",31488.00,Sedan,Used,4.00,No,84000.00,Automatic,Diesel,Dealer,5.00,1969.00,0.00,127.00,4WD,"Alloy wheels, Catalytic Converter, Sport suspe...",1892.00,No,Part/Full Leather,1.00,efficient,5.00,173.00,4.80,Standard,Standard Media,Safety Premium Package
28593,Volvo V40,Volvo,V40,"19 rue des Alliés, 57050 Metz, FR",18999.00,Sedan,Used,5.00,Yes,93257.00,Automatic,Diesel,Dealer,5.00,1969.00,6.00,108.00,Front,Emergency tyre,1546.00,No,Cloth,1.00,efficient,4.00,112.00,3.95,Standard,Standard Media,Safety Standard Package
28595,Volvo V40,Volvo,V40,"19 rue des Alliés, 57050 Metz, FR",18999.00,Sedan,Used,5.00,Yes,93257.00,Automatic,Diesel,Dealer,5.00,1969.00,6.00,108.00,Front,Emergency tyre,1546.00,No,Cloth,1.00,efficient,4.00,112.00,3.95,Standard,Standard Media,Safety Standard Package

**Let us save our dataset with a csv extension for further analysis (Handling Outliers) in the following notebook:**

In [248]:
df.to_csv("filled_scout2022.csv", index=False)

<a id="10"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:150%; text-align:center; border-radius:10px 10px;">The End of Handling with Missing Values (Part - 02)</p>


<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY"></p>

<a href="https://clarusway.com/"><img align="center" src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" alt="CLRSWY" title="Way to Reinvent Yourself"></a><br/>


## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:120%; text-align:center; border-radius:10px 10px;">Way to Reinvent Yourself</p>
___

<a href="https://clarusway.com/contact-us/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="Open in Clarusway LMS" width="110" height="200" title="This notebook is licensed by Clarusway IT training school. Please contact the authorized persons about the conditions under which you can use or share."></a>